### ISSUE TITLE
[BUG] hash_aggregate_test.py test FAILED:  Type conversion is not allowed from Table {...}

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#10324]
**Describe the bug**

hash_aggregate_test.py test FAILED:  Type conversion is not allowed from Table {...}, these failures are first observed on `Databricks` nightly build/test, let's keep an eye to check if these failures can be repro on other shims build.

 =========================== short test summary info ============================
 FAILED ../../src/main/python/::test_hash_multiple_filters[{'spark.rapids.sql.variableFloatAgg.enabled': 'true', ...
 FAILED ../../src/main/python/::test_hash_multiple_filters[{'spark.rapids.sql.variableFloatAgg.enabled': 'true', ...
 
 
 FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_grpby_pivot[{'spark.rapids.sql.variableFloatAgg.enabled': ...
 FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_grpby_pivot[{'spark.rapids.sql.variableFloatAgg.enabled': ...
 FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_grpby_pivot[{'spark.rapids.sql.variableFloatAgg.enabled': ...
 = 36 failed, 20647 passed, 1702 skipped, 958 xfailed, 2549 xpassed, 12893 warnings in 9272.83s (2:34:32) =

```
----------------------------- Captured stdout call -----------------------------
 ### CPU RUN ###
 ### GPU RUN ###
 _ test_hash_grpby_pivot[{'spark.rapids.sql.variableFloatAgg.enabled': 'true', 'spark.rapids.sql.castStringToFloat.enabled': sql.batchSizeBytes': '250'}-[('a', RepeatSeq(Short)), ('b', Decimal(36,-5)), ('c', Decimal(36,-5))]] _
 [gw1] linux -- Python 3.8.10 /usr/bin/python
 
 data_gen = [('a', RepeatSeq(Short)), ('b', Decimal(36,-5)), ('c', Decimal(36,-5))]
 conf = {'spark.rapids.sql.batchSizeBytes': '250', 'spark.rapids.sql.castStringToFloat.enabled': 'true', ableFloatAgg.enabled': 'true'}
 
     @approximate_float
     @ignore_order(local=True)
     @incompat
     @pytest.mark.parametrize('data_gen', _pivot_gens_with_decimals, ids=idfn)
     @pytest.mark.parametrize('conf', get_params(_confs, params_markers_for_confs), ids=idfn)
     def test_hash_grpby_pivot(data_gen, conf):
 >       assert_gpu_and_cpu_are_equal_collect(
             lambda spark: gen_df(spark, data_gen, length=100)
                 .groupby('a')
                 .pivot('b')
                 .agg(f.sum('c')),
             conf = conf)
 
 ../../src/main/python/hash_aggregate_test.py:475: 
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 ../../src/main/python/asserts.py:595: in assert_gpu_and_cpu_are_equal_collect
     _assert_gpu_and_cpu_are_equal(func, 'COLLECT', conf=conf, is_cpu_first=is_cpu_first, nc_before_compare=result_canonicalize_func_before_compare)
 ../../src/main/python/asserts.py:503: in _assert_gpu_and_cpu_are_equal
     from_gpu = run_on_gpu()
 ../../src/main/python/asserts.py:496: in run_on_gpu
     from_gpu = with_gpu_session(bring_back, conf=conf)
 ../../src/main/python/spark_session.py:164: in with_gpu_session
     return with_spark_session(func, conf=copy)
 /usr/lib/python3.8/contextlib.py:75: in inner
     return func(*args, **kwds)
 ../../src/main/python/spark_session.py:131: in with_spark_session
     ret = func(_spark)
 ../../src/main/python/asserts.py:205: in <lambda>
     bring_back = lambda spark: limit_func(spark).collect()
 /databricks/spark/python/pyspark/instrumentation_utils.py:48: in wrapper
     res = func(*args, **kwargs)
 /databricks/spark/python/pyspark/sql/dataframe.py:1252: in collect
     sock_info = self._jdf.collectToPython()
 /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321: in __call__
     return_value = get_return_value(
 /databricks/spark/python/pyspark/errors/exceptions.py:228: in deco
     return f(*a, **kw)
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 
 answer = 'xro451183'
 gateway_client = <py4j.clientserver.JavaClient object at 0x7f788ed49730>
 target_id = 'o451180', name = 'collectToPython'
 
     def get_return_value(answer, gateway_client, target_id=None, name=None):
         """Converts an answer received from the Java gateway into a Python object.
     
         For example, string representation of integers are converted to Python
         integer, string representation of objects are converted to JavaObject
         instances, etc.
     
         :param answer: the string returned by the Java gateway
         :param gateway_client: the gateway client used to communicate with the Java
             Gateway. Only necessary if the answer is a reference (e.g., object,
             list, map)
         :param target_id: the name of the object from which the answer comes from
             (e.g., *object1* in `object1.hello()`). Optional.
         :param name: the name of the member from which the answer comes from
             (e.g., *hello* in `object1.hello()`). Optional.
         """
         if is_error(answer)[0]:
             if len(answer) > 1:
                 type = answer[1]
                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                 if answer[1] == REFERENCE_TYPE:
 >                   raise Py4JJavaError(
                         "An error occurred while calling {0}{1}{2}.\n".
                         format(target_id, ".", name), value)
 E                   py4j.protocol.Py4JJavaError: An error occurred while calling o451180.collectToPython.
 E                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 10877.0 failed 1 lure: Lost task 1.0 in stage 10877.0 (TID 37314) (ip-10-59-239-21.us-west-2.compute.internal executor driver): or: Type conversion is not allowed from Table{columns=[ColumnVector{rows=8, type=INT16, nullCount=Optional.empty, f451c496330)}, ColumnVector{rows=8, type=DECIMAL128 scale:5, nullCount=Optional.empty, offHeap=(ID: 4434616 7f451c6b5860)}, ype=INT64, nullCount=Optional.empty, offHeap=(ID: 4434617 7f451c5cdc60)}, ColumnVector{rows=8, type=INT64, ty, offHeap=(ID: 4434618 7f451c4e8930)}, ColumnVector{rows=8, type=INT64, nullCount=Optional.empty, offHeap=(ID: 4434619 Vector{rows=8, type=INT64, nullCount=Optional.empty, offHeap=(ID: 4434620 7f451c5d81d0)}, ColumnVector{rows=8, type=BOOL8, ty, offHeap=(ID: 4434621 7f451c4e3e40)}], cudfTable=139934806418560, rows=8} to [ShortType, DecimalType(36,-5), puUnsignedLongType, GpuUnsignedLongType, LongType, BooleanType] columns 0 to 7
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:674)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:555)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$performGroupByAggregation$4(GpuAggregateExec.scala:394)
 E                   	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$performGroupByAggregation$2(GpuAggregateExec.scala:393)
 
 ......
 
 E                   
 E                   Driver stacktrace:
 E                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3396)
 E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3327)
 E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3316)
 
 ......
 
  E                   Caused by: java.lang.AssertionError: Type conversion is not allowed from ector{rows=8, type=INT16, nullCount=Optional.empty, offHeap=(ID: 4434615 7f451c496330)}, ColumnVector{rows=8, type=DECIMAL128 ional.empty, offHeap=(ID: 4434616 7f451c6b5860)}, ColumnVector{rows=8, type=INT64, nullCount=Optional.empty, offHeap=(ID: , ColumnVector{rows=8, type=INT64, nullCount=Optional.empty, offHeap=(ID: 4434618 7f451c4e8930)}, ColumnVector{rows=8, Optional.empty, offHeap=(ID: 4434619 7f451c485d00)}, ColumnVector{rows=8, type=INT64, nullCount=Optional.empty, offHeap=(ID: , ColumnVector{rows=8, type=BOOL8, nullCount=Optional.empty, offHeap=(ID: 4434621 7f451c4e3e40)}], cudfTable=139934806418560,  DecimalType(36,-5), GpuUnsignedLongType, GpuUnsignedLongType, GpuUnsignedLongType, LongType, BooleanType] columns 0 to 7
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:674)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:555)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$performGroupByAggregation$4(GpuAggregateExec.scala:394)
 
......
 
 /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326: Py4JJavaError
```
**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by revans2** [comment]
We need to revert https://github.com/NVIDIA/spark-rapids/commit/3bb2f6c11faae17cf8c869d97a60841e7d5762ff which was added to fix an issue before related to a CUDF change, that caused a performance regression and was reverted.
