### ISSUE TITLE
[BUG] Unit test FAILED against : SPARK-24957: average with decimal followed by aggregation returning wrong result 

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#10327]
**Describe the bug**

Unit test FAILED:  SPARK-24957: average with decimal followed by aggregation returning wrong result, details:

```
 SPARK-24957: average with decimal followed by aggregation returning wrong result *** FAILED ***
 org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent age 3.0 (TID 3) (nightly-work1-jenkins-rapids-scala213-nightly-pre-release-vqjl3 executor driver): pe conversion is not allowed from Table{columns=[ColumnVector{rows=1, type=STRING, nullCount=Optional.empty, ebf0)}, ColumnVector{rows=1, type=INT64, nullCount=Optional.empty, offHeap=(ID: 777021 7fb66003cbd0)}, T64, nullCount=Optional.empty, offHeap=(ID: 777022 7fb66003d3a0)}, ColumnVector{rows=1, type=INT64, fHeap=(ID: 777023 7fb66003d690)}, ColumnVector{rows=1, type=INT64, nullCount=Optional.empty, offHeap=(ID: 777024 {rows=1, type=INT64, nullCount=Optional.empty, offHeap=(ID: 777025 7fb66003dd80)}], cudfTable=140421271470672, rows=1} ongType, GpuUnsignedLongType, GpuUnsignedLongType, LongType, LongType] columns 0 to 6
	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:674)
	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:555)
	at com.nvidia.spark.rapids.AggHelper.$anonfun$performGroupByAggregation$4(GpuAggregateExec.scala:394)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.AggHelper.$anonfun$performGroupByAggregation$2(GpuAggregateExec.scala:393)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.AggHelper.$anonfun$performGroupByAggregation$1(GpuAggregateExec.scala:378)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.AggHelper.performGroupByAggregation(GpuAggregateExec.scala:377)
	at com.nvidia.spark.rapids.AggHelper.aggregate(GpuAggregateExec.scala:292)
	at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$4(GpuAggregateExec.scala:311)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$3(GpuAggregateExec.scala:309)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$2(GpuAggregateExec.scala:308)
	at apidsRetryIterator$AutoCloseableAttemptSpliterator.next(RmmRapidsRetryIterator.scala:477)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:613)
	at apidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:517)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:61
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.aggregateInputBatches(GpuAggregateExec.scala:795)
	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.$anonfun$next$2(GpuAggregateExec.scala:752)
	at scala.Option.getOrElse(Option.scala:201)
	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:749)
	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:711)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
```

**Comment by mattahrens** [comment]
Fixed by https://github.com/NVIDIA/spark-rapids/pull/10331
