### ISSUE TITLE
[BUG] hash_aggregate_test failed : IllegalArgumentException: ArrayType(DecimalType(20,2),true) is not supported for GPU processing yet.

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#10390]
**Describe the bug**

Failed build `rapids_it-UCX-egx06-standalone/968` : hash_aggregate_test failed : IllegalArgumentException: ArrayType(DecimalType(20,2),true) is not supported for GPU processing yet.

I could **NOT** repro with `24.02.0-SNAPSHOT` jar using `-k hash_aggregate_test` locally or with the CI job.

Keep monitoring the pre-release nightly integration test jobs to see if it can be repro.

```
 ----------------------------- Captured stdout call -----------------------------
 ### CPU RUN ###
 ### GPU RUN ###
 _ test_hash_reduction_collect_set_on_nested_array_type[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Array(Array(Decimal(20,2)))))]] _
 
 data_gen = [('a', RepeatSeq(Long)), ('b', RepeatSeq(Array(Array(Decimal(20,2)))))]
 
     @ignore_order(local=True, arrays=["collect_set"])
     @allow_non_gpu("ProjectExec", *non_utc_allow)
     @pytest.mark.parametrize('data_gen', _gen_data_for_collect_set_op_nested, ids=idfn)
     def test_hash_reduction_collect_set_on_nested_array_type(data_gen):
         conf = copy_and_update(_float_conf, {
             "spark.rapids.sql.castFloatToString.enabled": "true",
         })
     
         def do_it(spark):
             return gen_df(spark, data_gen, length=100)\
                 .agg(f.collect_set('b').alias("collect_set"))
     
 >       assert_gpu_and_cpu_are_equal_collect(do_it, conf=conf)
 
 ../../src/main/python/hash_aggregate_test.py:734: 
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 ../../src/main/python/asserts.py:595: in assert_gpu_and_cpu_are_equal_collect
     _assert_gpu_and_cpu_are_equal(func, 'COLLECT', conf=conf, is_cpu_first=is_cpu_first, result_canonicalize_func_before_compare=result_canonicalize_func_before_compare)
 ../../src/main/python/asserts.py:503: in _assert_gpu_and_cpu_are_equal
     from_gpu = run_on_gpu()
 ../../src/main/python/asserts.py:496: in run_on_gpu
     from_gpu = with_gpu_session(bring_back, conf=conf)
 ../../src/main/python/spark_session.py:164: in with_gpu_session
     return with_spark_session(func, conf=copy)
 /opt/miniconda3/lib/python3.8/contextlib.py:75: in inner
     return func(*args, **kwds)
 ../../src/main/python/spark_session.py:131: in with_spark_session
     ret = func(_spark)
 ../../src/main/python/asserts.py:205: in <lambda>
     bring_back = lambda spark: limit_func(spark).collect()
 /var/lib/jenkins/spark/spark-3.3.0-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/dataframe.py:817: in collect
     sock_info = self._jdf.collectToPython()
 /var/lib/jenkins/spark/spark-3.3.0-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321: in __call__
     return_value = get_return_value(
 /var/lib/jenkins/spark/spark-3.3.0-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/utils.py:190: in deco
     return f(*a, **kw)
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 
 answer = 'xro2080612'
 gateway_client = <py4j.clientserver.JavaClient object at 0x7f68d577b460>
 target_id = 'o2080611', name = 'collectToPython'
 
     def get_return_value(answer, gateway_client, target_id=None, name=None):
         """Converts an answer received from the Java gateway into a Python object.
     
         For example, string representation of integers are converted to Python
         integer, string representation of objects are converted to JavaObject
         instances, etc.
     
         :param answer: the string returned by the Java gateway
         :param gateway_client: the gateway client used to communicate with the Java
             Gateway. Only necessary if the answer is a reference (e.g., object,
             list, map)
         :param target_id: the name of the object from which the answer comes from
             (e.g., *object1* in `object1.hello()`). Optional.
         :param name: the name of the member from which the answer comes from
             (e.g., *hello* in `object1.hello()`). Optional.
         """
         if is_error(answer)[0]:
             if len(answer) > 1:
                 type = answer[1]
                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                 if answer[1] == REFERENCE_TYPE:
 >                   raise Py4JJavaError(
                         "An error occurred while calling {0}{1}{2}.\n".
                         format(target_id, ".", name), value)
 E                   py4j.protocol.Py4JJavaError: An error occurred while calling o2080611.collectToPython.
 E                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 25 in stage 25256.0 failed 1 times, most recent failure: Lost task 25.0 in stage 25256.0 (TID 792318) (10.136.6.4 executor 1): java.lang.IllegalArgumentException: ArrayType(DecimalType(20,2),true) is not supported for GPU processing yet.
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.getNonNestedRapidsType(GpuColumnVector.java:423)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.typeConversionAllowed(GpuColumnVector.java:564)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.typeConversionAllowed(GpuColumnVector.java:593)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.typeConversionAllowed(GpuColumnVector.java:593)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:709)
...... 
 E                   at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
 E                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
 E                   	at java.base/java.lang.Thread.run(Thread.java:833)
 E                   Caused by: java.lang.IllegalArgumentException: ArrayType(DecimalType(20,2),true) is not supported for GPU processing yet.
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.getNonNestedRapidsType(GpuColumnVector.java:423)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.typeConversionAllowed(GpuColumnVector.java:564)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.typeConversionAllowed(GpuColumnVector.java:593)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.typeConversionAllowed(GpuColumnVector.java:593)
 E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:709)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$performReduction$3(GpuAggregateExec.scala:363)
 E                   	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$performReduction$2(GpuAggregateExec.scala:361)
 E                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
 E                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
 E                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$performReduction$1(GpuAggregateExec.scala:357)
 E                   	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
 E                   	at com.nvidia.spark.rapids.AggHelper.performReduction(GpuAggregateExec.scala:355)
 E                   	at com.nvidia.spark.rapids.AggHelper.aggregate(GpuAggregateExec.scala:294)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$4(GpuAggregateExec.scala:311)
 E                   	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
 E                   	at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$3(GpuAggregateExec.scala:309)
.....
 E                   	at org.apache.spark.scheduler.Task.run(Task.scala:136)
 E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
 E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
 E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
 E                   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 E                   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 E                   	... 1 more
 
 /var/lib/jenkins/spark/spark-3.3.0-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326: Py4JJavaError


 =========================== short test summary info ============================
 FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_reduction_collect_set_on_nested_array_type[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Array(Array(Decimal(12,2)))))]][DATAGEN_SEED=1707264818, INJECT_OOM, IGNORE_ORDER({'local': True, 'arrays': ['collect_set']}), ALLOW_NON_GPU(ProjectExec)]
 FAILED ../../src/main/python/hash_aggregate_test.py::test_hash_reduction_collect_set_on_nested_array_type[[('a', RepeatSeq(Long)), ('b', RepeatSeq(Array(Array(Decimal(20,2)))))]][DATAGEN_SEED=1707264818, IGNORE_ORDER({'local': True, 'arrays': ['collect_set']}), ALLOW_NON_GPU(ProjectExec)]
 = 2 failed, 21486 passed, 1743 skipped, 720 xfailed, 2502 xpassed, 12115 warnings in 23993.95s (6:39:53) =```

**Comment by NvTimLiu** [comment]
Similar but not the same as https://github.com/NVIDIA/spark-rapids/issues/10388
