### ISSUE TITLE
[BUG] Databricks cache tests failing with host memory OOM

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#10656]
cache integration tests are failing on Databricks due to host OOM.

<details>
<summary>Detailed example</summary>

```
[2024-04-02T07:27:34.960Z] [1m============================= test session starts ==============================[0m
[2024-04-02T07:27:34.960Z] platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python
[2024-04-02T07:27:34.960Z] cachedir: .pytest_cache
[2024-04-02T07:27:34.960Z] rootdir: /home/ubuntu/spark-rapids/integration_tests
[2024-04-02T07:27:34.960Z] configfile: pytest.ini
[2024-04-02T07:27:34.960Z] plugins: order-1.2.0, xdist-3.5.0
[2024-04-02T07:27:34.960Z] created: 4/4 workers
[2024-04-02T07:27:34.960Z] 4 workers [583 items]
[2024-04-02T07:27:34.960Z] 
[2024-04-02T07:27:34.960Z] scheduling tests via LoadScheduling
[2024-04-02T07:27:34.960Z] 
[2024-04-02T07:27:34.960Z] ../../src/main/python/cache_test.py::test_passing_gpuExpr_as_Expr[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}][DATAGEN_SEED=1712042787, TZ=UTC, ALLOW_NON_GPU(CollectLimitExec)] 
[2024-04-02T07:27:34.960Z] ../../src/main/python/cache_test.py::test_cached_join_filter[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}-Date][DATAGEN_SEED=1712042787, TZ=UTC, INJECT_OOM, IGNORE_ORDER, ALLOW_NON_GPU(ANY)] 
[2024-04-02T07:27:34.960Z] ../../src/main/python/cache_test.py::test_cache_expand_exec[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'false'}-Float][DATAGEN_SEED=1712042787, TZ=UTC, IGNORE_ORDER, INCOMPAT] 
[2024-04-02T07:28:06.938Z] ../../src/main/python/cache_test.py::test_cache_partial_load[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}-Decimal(12,2)][DATAGEN_SEED=1712042787, TZ=UTC, INJECT_OOM, ALLOW_NON_GPU(CollectLimitExec)] 24/04/02 07:28:04 WARN GpuOverrides: 
[2024-04-02T07:28:06.938Z] ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
[2024-04-02T07:28:06.938Z]   @Expression <AttributeReference> a#47 could run on GPU
[2024-04-02T07:28:06.938Z]   @Expression <AttributeReference> b#48 could run on GPU
[2024-04-02T07:28:06.938Z] 
[2024-04-02T07:28:06.938Z] 24/04/02 07:28:04 WARN GpuOverrides: 
[2024-04-02T07:28:06.938Z] !Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
[2024-04-02T07:28:06.938Z]   @Partitioning <SinglePartition$> could run on GPU
[2024-04-02T07:28:06.938Z] 
[2024-04-02T07:28:06.938Z] 24/04/02 07:28:05 WARN GpuOverrides: 
[2024-04-02T07:28:06.938Z]             ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
[2024-04-02T07:28:06.938Z]               @Expression <AttributeReference> a#59 could run on GPU
[2024-04-02T07:28:06.938Z] 
[2024-04-02T07:28:06.938Z] 24/04/02 07:28:05 WARN BlockManager: Block rdd_19_0 could not be removed as it was not found on disk or in memory
[2024-04-02T07:28:06.938Z] 24/04/02 07:28:05 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
[2024-04-02T07:28:06.938Z] java.lang.OutOfMemoryError
[2024-04-02T07:28:06.938Z] 	at sun.misc.Unsafe.allocateMemory(Native Method)
[2024-04-02T07:28:06.938Z] 	at ai.rapids.cudf.UnsafeMemoryAccessor.allocate(UnsafeMemoryAccessor.java:79)
[2024-04-02T07:28:06.938Z] 	at ai.rapids.cudf.HostMemoryBuffer.allocate(HostMemoryBuffer.java:144)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.HostAlloc.tryAllocNonPinned(HostAlloc.scala:85)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.HostAlloc.$anonfun$tryAllocInternal$1(HostAlloc.scala:173)
[2024-04-02T07:28:06.938Z] 	at scala.Option.orElse(Option.scala:447)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.HostAlloc.tryAllocInternal(HostAlloc.scala:172)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.HostAlloc.alloc(HostAlloc.scala:218)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.HostAlloc$.alloc(HostAlloc.scala:258)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RowToColumnarIterator.$anonfun$allocBufWithRetry$1(GpuRowToColumnarExec.scala:623)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.next(RmmRapidsRetryIterator.scala:477)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:613)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:517)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RowToColumnarIterator.allocBufWithRetry(GpuRowToColumnarExec.scala:621)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RowToColumnarIterator.$anonfun$buildBatch$1(GpuRowToColumnarExec.scala:646)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RowToColumnarIterator.buildBatch(GpuRowToColumnarExec.scala:632)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RowToColumnarIterator.next(GpuRowToColumnarExec.scala:613)
[2024-04-02T07:28:06.938Z] 	at com.nvidia.spark.rapids.RowToColumnarIterator.next(GpuRowToColumnarExec.scala:590)
[2024-04-02T07:28:06.938Z] 	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
[2024-04-02T07:28:06.938Z] 	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
[2024-04-02T07:28:06.938Z] 	at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anon$2.hasNext(InMemoryRelation.scala:287)
[2024-04-02T07:28:06.938Z] 	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:227)
[2024-04-02T07:28:06.938Z] 	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:312)
[2024-04-02T07:28:06.938Z] 	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1654)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1581)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1645)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1438)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.storage.BlockManager.getOrElseUpdateRDDBlock(BlockManager.scala:1392)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:422)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:372)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.$anonfun$computeOrReadCheckpoint$1(RDD.scala:410)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:407)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.$anonfun$computeOrReadCheckpoint$1(RDD.scala:410)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:407)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.$anonfun$computeOrReadCheckpoint$1(RDD.scala:410)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:407)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.$anonfun$computeOrReadCheckpoint$1(RDD.scala:410)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:407)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:374)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:82)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:82)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:196)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:181)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:146)
[2024-04-02T07:28:06.939Z] 	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:129)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:146)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$8(Executor.scala:899)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1709)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:902)
[2024-04-02T07:28:06.939Z] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-04-02T07:28:06.939Z] 	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
[2024-04-02T07:28:06.939Z] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:797)
[2024-04-02T07:28:06.939Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2024-04-02T07:28:06.939Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2024-04-02T07:28:06.939Z] 	at java.lang.Thread.run(Thread.java:750)
[2024-04-02T07:28:06.939Z] 	Suppressed: com.nvidia.spark.rapids.jni.CpuRetryOOM: injected RetryOOM
[2024-04-02T07:28:06.939Z] 		at com.nvidia.spark.rapids.jni.SparkResourceAdaptor.preCpuAlloc(Native Method)
[2024-04-02T07:28:06.939Z] 		at com.nvidia.spark.rapids.jni.SparkResourceAdaptor.preCpuAlloc(SparkResourceAdaptor.java:262)
[2024-04-02T07:28:06.939Z] 		at com.nvidia.spark.rapids.jni.RmmSpark.preCpuAlloc(RmmSpark.java:607)
[2024-04-02T07:28:06.939Z] 		at com.nvidia.spark.rapids.HostAlloc.tryAllocInternal(HostAlloc.scala:162)
[2024-04-02T07:28:06.939Z] 		... 65 more
```
</details>

**Comment by jlowe** [comment]
May be related to #10617.
