### ISSUE TITLE
[BUG] "Could not find any rapids-4-spark jars in classpath" error when debugging UT in IDEA

### ISSUE THREAD

**Issue by thirtiseven** [NVIDIA/spark-rapids#10722]
**Describe the bug**

IDE complains "Could not find any rapids-4-spark jars in classpath" error when debugging UT in IDEA.

**Steps/Code to reproduce bug**

Debug UT directly in intellij IDEA:
```
24/84/17 14:23:13.384 ScalaTest-run-running-ProtectExorSuite ERROR Soarkcontext: Error 1n1c1a121ng Soarkcontext.
24/04/27 24:20:20.004 3CalaleSC-PUN-PUMAnO-PrOJeCLEXDI SULLE EAKUK SoarKeonteXC： CITOT 20262822200 30afonteXC
Java. Lang. IlLegalAngu int Exception Create breakpoint: regulnement talled: Could not tind any rapids-4-spark tars in the classpathi

at scala.Predefs.require(Predef.scala:28)) *Iscala-1brary-2.12.15.Jar:?)
at com.nv1d1a.spark.rap1ds.Rop1dsPluginUr11ss.detecthul1ple.ar/Pluo1n.scala:159/ ~lClasses/??
at com.mv1d1a.spark.rap1ds.Rap1dsPluoinUt11ss.de/ecthul/1pleJars(Plugin.scala:184, ~Classes/:?.
at com.nvidia.spark.rapids.RapidsPluginUt11sS.detectMultipleJars(Plugin.scala:184) ~[classes/:?]
at com.nv1018.spark.rap1ds.Rap10sDr1verPluo1n.1n1tPlugin.scala:444 •Classes/:?
at org.apache.Spark.nternal.olugzn.r/verPLugznContalner.anonfun.dr/verPlug.nsPLug.ncontalner.scala:s)~Spark-core 2.12-3.3.2.180:3.303
at scala.collec.on.traversableL.ke.anontunstlachaps1TraversableLlke.scala:zys~Scala-Llbrary-2.12.15.1a0:?
at scala.collection.nutable.RestzableArrav.foreach.RestzableArrav.scala:62)~scala-1brary-2.12.15.1am:?||
at scala.cotlectlon.hutaole.keszzadlearray.roreachkestzableArray.scala.oz~Scala-Lorary-2.12.15.180:?.
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55) ~[scala-L1brary-2.12.15.1ar:?]
at scala.cotleccion.hutaole.Arraybutter.toreach.arraybutter.scala.a ~ Scala-Lorary-2.12.15. am.?.
```

**Expected behavior**

Be able to debug in the IDE.

**Comment by thirtiseven** [comment]
Seems there is no jar in classpath when debugging UT in IDE, so following `require` fails:
```scala
require(revisionMap.size > 0, s"Could not find any $jarName jars in the classpath")
```

We should verify this behavior, if this is excepted we can remove this require and modify following logic:

```scala
conf.allowMultipleJars match {
  case AllowMultipleJars.ALWAYS =>
    if (revisionMap.size != 1 || revisionMap.values.exists(_.size != 1)) {
      logWarning(msg)
    }
  case AllowMultipleJars.SAME_REVISION =>
    val recommended = "If it is impossible to fix the classpath you can suppress the " +
          s"error by setting ${RapidsConf.ALLOW_MULTIPLE_JARS.key} to ALWAYS, but this " +
          s"can cause unpredictable behavior as the plugin may pick up the wrong jar."
    require(revisionMap.size == 1, msg + recommended)
    if (revisionMap.values.exists(_.size != 1)) {
      logWarning(msg + recommended)
    }
  case AllowMultipleJars.NEVER =>
    val recommended = "If it is impossible to fix the classpath you can suppress the " +
        s"error by setting ${RapidsConf.ALLOW_MULTIPLE_JARS.key} to SAME_REVISION or ALWAYS." +
        " But setting it to ALWAYS can cause unpredictable behavior as the plugin may pick " +
        "up the wrong jar."
    require(revisionMap.size == 1 && revisionMap.values.forall(_.size == 1), msg + recommended)
}
```
