### ISSUE TITLE
[BUG] string to timestamp conversion fails with split

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1082]
**Describe the bug**
A customer query that was working started to fail with the latest 0.3.0. It was working with Oct 23rd build. 

The error is:
```
java.lang.IllegalArgumentException: Invalid data type
	at ai.rapids.cudf.ColumnVector.castTo(Native Method)
	at ai.rapids.cudf.ColumnVector.castTo(ColumnVector.java:1703)
	at com.nvidia.spark.rapids.GpuCast.doColumnar(GpuCast.scala:466)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:121)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35)
	at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:96)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35)
	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:52)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:161)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:158)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:158)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:193)
	at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:51)
	at com.nvidia.spark.rapids.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:42)
	at com.nvidia.spark.rapids.GpuProjectExec.$anonfun$doExecuteColumnar$2(basicPhysicalOperators.scala:92)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:196)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:212)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:144)
	at org.apache.spark.scheduler.Task.run(Task.scala:117)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$9(Executor.scala:639)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1559)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:642)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I believe this is happening when spark.conf.set("spark.rapids.sql.castStringToTimestamp.enabled", "true")
and the code is doing a split and then cast:
cast(split(Values, ";")[1] as timestamp)

the cast is failing because input type is ArrayType(StringType,true) and trying to cast to TimestampType
My guess is that either the reference into the split list isn't working or we aren't changing that type properly, but it needs to be debugged further.

**Comment by tgravescs** [comment]
I happened to test another version and it appears the bug was introduced in one of these commits:
commit 4e9935432f3d31391ddaa4f949f26e64b6091c52
Author: rwlee <rwlee@users.noreply.github.com>
Date:   Fri Oct 23 19:08:59 2020 -0700

    Spark BinaryType and cast to BinaryType (#886)

    Signed-off-by: Ryan Lee <ryanlee@nvidia.com>

    Co-authored-by: Ryan Lee <ryanlee@nvidia.com>

commit d0317893724b7d56502df5b76ffe516718246d3e
Author: Kuhu Shukla <kshukla2@ncsu.edu>
Date:   Fri Oct 23 20:08:20 2020 -0500

    Change Hash Aggregate to allow pass-through on MapType (#1016)

    * Change Hash Aggregate to allow pass through on MapType

    Signed-off-by: Kuhu Shukla <kuhus@nvidia.com>

commit 27f6a0af2a50bf797f5eeb14689b263f349e0b5d
Author: Kuhu Shukla <kshukla2@ncsu.edu>
Date:   Fri Oct 23 17:54:07 2020 -0500

    Add support for MapType in selected operators  (#984)

    * Add support for getMapValue and MapType for certain operators
    Signed-off-by: Kuhu Shukla <kuhus@nvidia.com>

commit 3c3ed67792bbc00f9c85c59667d6cf6c528053ed
Author: Jason Lowe <jlowe@nvidia.com>
Date:   Fri Oct 23 09:24:07 2020 -0500

    Update for new position parameter in Spark 3.1.0 RegExpReplace

    Signed-off-by: Jason Lowe <jlowe@nvidia.com>

If you go back to hash 3ff5caf23bebfc05bed3201bea3450ba5db00779 the bug doesn't appears, but when based off hash 4e9935432f3d31391ddaa4f949f26e64b6091c52 the issue happends

**Comment by kuhushukla** [comment]
@tgravescs do you have to have a small test query to repro this with?

**Comment by tgravescs** [comment]
ok narrowed it down to this commit:

27f6a0af2a50bf797f5eeb14689b263f349e0b5d -> exception occurs
3c3ed67792bbc00f9c85c59667d6cf6c528053ed -> exception doesn't occur

so it appears the change that caused this is:
commit 27f6a0af2a50bf797f5eeb14689b263f349e0b5d (27f6a0af2a50bf797f5eeb14689b263f349e0b5d)
Author: Kuhu Shukla <kshukla2@ncsu.edu>
Date:   Fri Oct 23 17:54:07 2020 -0500

    Add support for MapType in selected operators  (#984)

    * Add support for getMapValue and MapType for certain operators
    Signed-off-by: Kuhu Shukla <kuhus@nvidia.com>

**Comment by kuhushukla** [comment]
Yup. I am on it. Will have something this weekend

**Comment by tgravescs** [comment]
This is now fixed with the latest version of the plugin.

**Comment by kuhushukla** [comment]
Verified this is fixed now with the unit test created for a cast with split in a project.
