### ISSUE TITLE
 Concat cannot accept no parameter

### ISSUE THREAD

**Issue by Feng-Jiang28** [NVIDIA/spark-rapids#10925]
Test Case:  
```
 def testConcat(inputs: String*): Unit = {
      val expected = if (inputs.contains(null)) null else inputs.mkString
      checkEvaluation(Concat(inputs.map(Literal.create(_, StringType))), expected)
    }

testConcat()
```
```
spark.sql.optimizer.excludedRules    org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation,org.apache.spark.sql.catalyst.optimizer.ConstantFolding

concat() is being evaluated with Vectorized Parameter
24/05/28 19:19:54.319 Executor task launch worker for task 1.0 in stage 0.0 (TID 1) ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
java.lang.IllegalArgumentException: Cannot resolve a ColumnVector from the value: Scalar{type=STRING value=""} (ID: 13 7f4460247c50). Please convert it to a GpuScalar or a GpuColumnVector before returning.
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.$anonfun$resolveColumnVector$1(GpuExpressions.scala:79) ~[classes/:?]
	at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:84) ~[classes/:?]
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.resolveColumnVector(GpuExpressions.scala:74) ~[classes/:?]
	at org.apache.spark.sql.rapids.GpuConcat.columnarEval(collectionOperations.scala:60) ~[classes/:?]
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35) ~[classes/:?]
	at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:110) ~[classes/:?]
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35) ~[classes/:?]
	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:110) ~[classes/:?]
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:221) ~[classes/:?]
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:218) ~[classes/:?]
	at scala.collection.immutable.List.foreach(List.scala:431) ~[scala-library-2.12.15.jar:?]
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:218) ~[classes/:?]
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:253) ~[classes/:?]
```
Concat cannot accept no paramter.

**Comment by Feng-Jiang28** [comment]
build
