### ISSUE TITLE
[BUG] UCX Shuffle With scala.MatchError 

### ISSUE THREAD

**Issue by KevinLu233** [NVIDIA/spark-rapids#11103]
When I use UCX mode to accelerate Spark on GPU, I encounter a "MatchError" in the final step. I have tested that UCX runs normally, and the multithread mode works fine as well. How should I address this issue? Thank you.

 
prod env:
UCX: Library version: 1.17.0
spark: 3.5.1(scala 2.13)
rapids: rapids-4-spark_2.13-24.06.0.jar

UCX Params:
spark.shuffle.manager=com.nvidia.spark.rapids.spark351.RapidsShuffleManager
spark.rapids.shuffle.mode=UCX
spark.shuffle.service.enabled=false
spark.dynamicAllocation.enabled=false
spark.executor.extraClassPath=hdfs:///data/libs/spark3_5_1_a1/rapids-4-spark_2.13-24.06.0-SNAPSHOT-cuda11.jar
spark.executorEnv.UCX_ERROR_SIGNALS=
spark.executorEnv.UCX_MEMTYPE_CACHE=n
spark.executorEnv.UCX_IB_RX_QUEUE_LEN=1024
spark.executorEnv.UCX_TLS=cuda_copy,cuda_ipc,rc,tcp
spark.executorEnv.UCX_RNDV_SCHEME=put_zcopy
spark.executorEnv.UCX_MAX_RNDV_RAILS=1
spark.rapids.memory.host.spillStorageSize=2G

Error log:
----------------------------------------------------------------------------------------------------------------------------------

4/06/27 07:25:57 INFO MapOutputTrackerWorker: Updating epoch to 1 and clearing cache
24/06/27 07:25:57 INFO TorrentBroadcast: Started reading broadcast variable 2 with 1 pieces (estimated total size 4.0 MiB)
24/06/27 07:25:57 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 7.9 KiB, free 23.8 GiB)
24/06/27 07:25:57 INFO TorrentBroadcast: Reading broadcast variable 2 took 6 ms
24/06/27 07:25:57 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 21.3 KiB, free 23.8 GiB)
24/06/27 07:25:57 INFO RapidsShuffleInternalManagerBase: Asking map output tracker for dependency GPU Shuffle Dependency, map output sizes for: 0, parts=0-1
24/06/27 07:25:57 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 0, fetching them
24/06/27 07:25:57 INFO MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@ip-10-12-4-15.tj.testlab.co:13939)
24/06/27 07:25:57 INFO MapOutputTrackerWorker: Got the map output locations
24/06/27 07:25:57 INFO RapidsCachingReader: Will read 8 cached blocks, 5 remote blocks from the RapidsShuffleTransport. 
24/06/27 07:25:58 INFO CodeGenerator: Code generated in 217.860412 ms
24/06/27 07:25:58 INFO RapidsShuffleIterator: Fetching 5 blocks.
24/06/27 07:25:58 WARN RapidsShuffleIterator: Iterator for task 45 closing, but it is not done. Closing 0 resolved batches!!
24/06/27 07:25:58 ERROR Executor: Exception in task 0.2 in stage 2.0 (TID 45)
scala.MatchError: (BlockManagerId(6, ip-10-12-4-29.tj.testlab.co, 10679, Some(rapids=28687)),ListBuffer((shuffle_0_19_0,66,5), (shuffle_0_25_0,66,11), (shuffle_0_31_0,66,17), (shuffle_0_37_0,66,23), (shuffle_0_5_0,66,31), (shuffle_0_11_0,66,37))) (of class scala.Tuple2)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.$anonfun$start$3(RapidsShuffleIterator.scala:175)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.$anonfun$start$3$adapted(RapidsShuffleIterator.scala:175)
  at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1328)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.start(RapidsShuffleIterator.scala:175)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.next(RapidsShuffleIterator.scala:357)
  at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.next(RapidsShuffleIterator.scala:63)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
  at scala.collection.Iterator$ConcatIterator.next(Iterator.scala:1187)
  at org.apache.spark.util.CompletionIterator.next(CompletionIterator.scala:29)
  at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
  at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$next$1(GpuExec.scala:200)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
  at com.nvidia.spark.rapids.CollectTimeIterator.next(GpuExec.scala:199)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.populateCandidateBatches(GpuCoalesceBatches.scala:458)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$next$1(GpuCoalesceBatches.scala:620)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.next(GpuCoalesceBatches.scala:600)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.next(GpuCoalesceBatches.scala:250)
  at com.nvidia.spark.rapids.AbstractProjectSplitIterator.next(basicPhysicalOperators.scala:247)
  at com.nvidia.spark.rapids.AbstractProjectSplitIterator.next(basicPhysicalOperators.scala:227)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
  at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
  at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:576)
  at com.nvidia.spark.rapids.GpuMergeAggregateIterator.$anonfun$next$2(GpuAggregateExec.scala:751)
  at scala.Option.getOrElse(Option.scala:201)
  at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:749)
  at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:711)
  at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
  at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.$anonfun$next$6(GpuAggregateExec.scala:2042)
  at scala.Option.map(Option.scala:242)
  at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:2042)
  at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:1906)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$3(GpuColumnarToRowExec.scala:290)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:287)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:257)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:304)
  at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:576)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
  at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
  at org.apache.spark.scheduler.Task.run(Task.scala:141)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
  at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
  at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.base/java.lang.Thread.run(Thread.java:833)
24/06/27 07:25:59 INFO UCX: Got UcpListener request from /10.12.5.23:49394
24/06/27 07:25:59 INFO UCX: Created ConnectionRequest endpoint UcpEndpoint(id=140288598057472, UcpEndpointParams{errorHandlingMode=UCP_ERR_HANDLING_MODE_PEER,connectionRequest/10.12.5.23:49394) for /10.12.5.23:49394
24/06/27 07:25:59 INFO UCX: Success sending handshake header! java.nio.DirectByteBuffer[pos=0 lim=281 cap=281]
24/06/27 07:25:59 INFO UCX: Established endpoint on ConnectionRequest for executor 8: UcpEndpoint(id=140288598057472, UcpEndpointParams{errorHandlingMode=UCP_ERR_HANDLING_MODE_PEER,connectionRequest/10.12.5.23:49394)
24/06/27 07:26:02 INFO RapidsShuffleHeartbeatEndpoint: Updating shuffle manager for new executor BlockManagerId(8, ip-10-12-5-23.tj.testlab.co, 35905, Some(rapids=1144))
24/06/27 07:26:02 INFO UCX: Creating connection for executorId 8
24/06/27 07:26:02 INFO UCXClientConnection: UCX Client UCXClientConnection(ucx=com.nvidia.spark.rapids.shuffle.ucx.UCX@31f2b220, peerExecutorId=8) started
24/06/27 07:26:02 INFO RapidsShuffleHeartbeatEndpoint: Updating shuffle manager for new executor BlockManagerId(4, ip-10-12-5-23.tj.testlab.co, 25369, Some(rapids=59993))
24/06/27 07:26:02 INFO UCX: Creating connection for executorId 4
24/06/27 07:26:02 INFO UCXClientConnection: UCX Client UCXClientConnection(ucx=com.nvidia.spark.rapids.shuffle.ucx.UCX@31f2b220, peerExecutorId=4) started

@gerashegalov

**Comment by abellina** [comment]
@KevinLu233 this is an odd place to have a failure:

> (BlockManagerId(6, ip-10-12-4-29.tj.testlab.co, 10679, Some(rapids=28687)),ListBuffer((shuffle_0_19_0,66,5), (shuffle_0_25_0,66,11), (shuffle_0_31_0,66,17), (shuffle_0_37_0,66,23), (shuffle_0_5_0,66,31), (shuffle_0_11_0,66,37))) (of class scala.Tuple2)

It seems to not match:
>case (blockManagerId: BlockManagerId, blockIds: Seq[(BlockId, Long, Int)])

This looks like a class mismatch: the spark the was used to build the spark-rapids plugin 3.5.1 shim and corresponding shuffle manager isn't what is running in the executor. 

I ran a test locally against spark 3.5.1 as released using the released spark-rapids from https://mvnrepository.com/artifact/com.nvidia/rapids-4-spark_2.13/24.06.0, and I don't see the issue locally.

A few questions:

- The jar `hdfs:///data/libs/spark3_5_1_a1/rapids-4-spark_2.13-24.06.0-SNAPSHOT-cuda11.jar`: is that the same jar you are using to submit the job?
- Is the spark 3.5.1 running in the driver and executor the same exact version? 
- Did you build the snapshot with the same spark distro that is running in the driver/executors?
- Please try to repro against the released versions of spark and spark-rapids.

Thanks!

**Comment by xieshuaihu** [comment]
This is caused by scala2.13 @abellina 

Discussions in scala communicity: https://users.scala-lang.org/t/change-in-varargs-in-scala-2-13/5731

And this is a simple code to replay this error in scala 2.13

```scala
import scala.collection.mutable.ListBuffer

object Test {
  def main(args: Array[String]): Unit = {
    val data = Array.fill(10) { (math.random(), ListBuffer.fill(1)(math.random())) }
    val (l, r) = data.partition(a => a._1 > 0.5)
    (l ++ r).foreach { case (v1: Double, v2: Seq[Double]) =>
      println(v1, v2)
    }
  }
}
```

**Comment by xieshuaihu** [comment]
This patch could solve this error

```git
diff --git a/sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala b/sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
index 29f36d6f2..72c1f935e 100644
--- a/sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
+++ b/sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shuffle/RapidsShuffleIterator.scala
@@ -173,7 +173,7 @@ class RapidsShuffleIterator(
     val (local, remote) = blocksByAddress.partition(ba => ba._1.host == localHost)
 
     (local ++ remote).foreach {
-      case (blockManagerId: BlockManagerId, blockIds: Seq[(BlockId, Long, Int)]) => {
+      case (blockManagerId: BlockManagerId, blockIds: collection.Seq[(BlockId, Long, Int)]) => {
         val shuffleRequestsMapIndex: Seq[BlockIdMapIndex] =
           blockIds.map { case (blockId, _, mapIndex) =>
             /**
@@ -193,7 +193,7 @@ class RapidsShuffleIterator(
                 throw new IllegalArgumentException(
                   s"${blockId.getClass} $blockId is not currently supported")
             }
-          }
+          }.toSeq
 
         val client = try {
           transport.makeClient(blockManagerId)

```

**Comment by abellina** [comment]
@xieshuaihu thank you!!!! yes, I did not run with scala 2.13 here and neither did our tests, and sorry I didn't realize this was 2.13 though you clearly called it out in the issue description.

We'll work on incorporating your patch and to run scala 2.13 testing as well.

**Comment by abellina** [comment]
@xieshuaihu I have run with your patch locally and I am able to pass tests, so I would like to get this change into the codebase. Would you like to create a PR with the change as is, rather than me adopting your change as it works verbatim.

The requirement for PRs is that you sign your commits as outlined here https://github.com/NVIDIA/spark-rapids/blob/branch-24.08/CONTRIBUTING.md#sign-your-work (via git commit -s), and it certifies you agree with the "Developer Certificate of Origin". 

I encourage you to make the change and I'll be happy to review it. Let us know!

**Comment by xieshuaihu** [comment]
@abellina Thanks your suggestion. A pr will be submitted on monday
