### ISSUE TITLE
[BUG] Resource leaks in unit tests

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1128]
**Describe the bug**
Recently noticed this occurring sometimes at the end of unit testing.  It does not fail any tests, but it indicates something is going wrong:
```
Exception in thread "Thread-7" java.util.ConcurrentModificationException
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at ai.rapids.cudf.MemoryCleaner.stringJoin(MemoryCleaner.java:271)
	at ai.rapids.cudf.MemoryCleaner.access$200(MemoryCleaner.java:59)
	at ai.rapids.cudf.MemoryCleaner$Cleaner.logRefCountDebug(MemoryCleaner.java:94)
	at ai.rapids.cudf.ColumnVector$OffHeapState.cleanImpl(ColumnVector.java:3402)
	at ai.rapids.cudf.MemoryCleaner$Cleaner.clean(MemoryCleaner.java:104)
	at ai.rapids.cudf.MemoryCleaner$CleanerWeakReference.clean(MemoryCleaner.java:150)
	at ai.rapids.cudf.MemoryCleaner.lambda$static$1(MemoryCleaner.java:213)
	at java.lang.Thread.run(Thread.java:748)
```

That indicates the code is trying to emit a leak warning, which prompted me to check the test logs to see if we were leaking any resources.  A grep of the unit tests logs showed many resource being leaked.

**Steps/Code to reproduce bug**
```
$ mvn clean verify
$ grep LEAK tests/target/surefire-reports/*
```

**Expected behavior**
Unit tests should not leak resources

**Comment by sameerz** [comment]
Will reprioritize once we confirm whether leaks are in tests only or in production.
