### ISSUE TITLE
[BUG] A user query with from_json failed with "JSON Parser encountered an invalid format at location"

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#11293]
This is from an old issue https://github.com/NVIDIA/spark-rapids/issues/6481.
The same user query failed with below error in 24.08 snapshot while CPU run works fine:
```
ai.rapids.cudf.CudfException: CUDF failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-819-cuda11/src/main/cpp/src/map_utils.cu:149: JSON Parser encountered an invalid format at location 197291503
	at com.nvidia.spark.rapids.jni.MapUtils.extractRawMapFromJsonString(Native Method)
	at com.nvidia.spark.rapids.jni.MapUtils.extractRawMapFromJsonString(MapUtils.java:49)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.doColumnar(GpuJsonToStructs.scala:168)
	at com.nvidia.spark.rapids.GpuUnaryExpression.doItColumnar(GpuExpressions.scala:250)
	at com.nvidia.spark.rapids.GpuUnaryExpression.$anonfun$columnarEval$1(GpuExpressions.scala:261)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:260)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny$(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEvalAny(GpuExpressions.scala:244)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEvalAny(implicits.scala:39)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:310)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:309)
	at org.apache.spark.sql.rapids.GpuGetMapValue.columnarEval(complexTypeExtractors.scala:202)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny$(GpuExpressions.scala:144)
	at org.apache.spark.sql.rapids.GpuGetMapValue.columnarEvalAny(complexTypeExtractors.scala:202)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEvalAny(implicits.scala:39)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:310)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:309)
	at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEval(GpuExpressions.scala:417)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny(GpuExpressions.scala:144)
```

Reproduced using user query and data in house.

**Comment by ttnghia** [comment]
The exception is due to error token detected in `cudf::io::json::detail::get_token_stream`. I'll check with the data to see what's going on.

**Comment by ttnghia** [comment]
Closed by https://github.com/NVIDIA/spark-rapids-jni/pull/2562.
