### ISSUE TITLE
[BUG] databrick nightly failing with not able to get spark-version-info.properties

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#11346]
**Describe the bug**
```
[2024-08-16T13:50:15.399Z] [INFO]      [java] Exception in thread "main" java.lang.ExceptionInInitializerError
[2024-08-16T13:50:15.399Z] [INFO]      [java] 	at org.apache.spark.package$.<init>(package.scala:93)
[2024-08-16T13:50:15.399Z] [INFO]      [java] 	at org.apache.spark.package$.<clinit>(package.scala)
[2024-08-16T13:50:15.399Z] [INFO]      [java] 	at com.nvidia.spark.rapids.ShimLoader$.getSparkVersion(ShimLoader.scala:311)
[2024-08-16T13:50:15.399Z] [INFO]      [java] 	at com.nvidia.spark.rapids.ShimLoader$.detectShimProvider(ShimLoader.scala:205)
[2024-08-16T13:50:15.399Z] [INFO]      [java] 	at com.nvidia.spark.rapids.ShimLoader$.findShimProvider(ShimLoader.scala:299)
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	at com.nvidia.spark.rapids.ShimLoader$.initShimProviderIfNeeded(ShimLoader.scala:92)
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	at com.nvidia.spark.rapids.ShimLoader$.getShimClassLoader(ShimLoader.scala:184)
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	at com.nvidia.spark.rapids.ShimReflectionUtils$.loadClass(ShimReflectionUtils.scala:28)
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	at com.nvidia.spark.rapids.tests.DumpDefaultConfigs$.main(DumpDefaultConfigs.scala:32)
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	at com.nvidia.spark.rapids.tests.DumpDefaultConfigs.main(DumpDefaultConfigs.scala)
[2024-08-16T13:50:15.400Z] [INFO]      [java] Caused by: org.apache.spark.SparkException: Could not find spark-version-info.properties
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	at org.apache.spark.package$SparkBuildInfo$.<init>(package.scala:62)
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	at org.apache.spark.package$SparkBuildInfo$.<clinit>(package.scala)
[2024-08-16T13:50:15.400Z] [INFO]      [java] 	... 10 more
```

Several nightly builds failed with the above error in the databricks nightly builds.

rapids_databricks_nightly-dev-github 1196 and 1197

**Comment by zpuller** [comment]
This is due to https://github.com/NVIDIA/spark-rapids/pull/11283 (thanks to @jlowe for spotting this). We are rolling back.
