### ISSUE TITLE
[BUG] pyspark cli failed to init on Databricks runtimes

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#11370]
**Describe the bug**
@firestarman found that we could not init pyspark/spark-shell with plugin directly on databricks runtimes (11.3, 12.2, 13.3). We are not sure if its a known issue.

error message looks weird "This RAPIDS Plugin build does not support Spark build **3.3.0-databricks**. Supported Spark versions: 3.2.0 {buildver=320}, **3.3.0-databricks {buildver=330db}**."

```
./pyspark --conf spark.plugins=com.nvidia.spark.SQLPlugin --jars /home/ubuntu/spark-rapids/dist/target/rapids-4-spark_2.12-24.10.0-SNAPSHOT-cuda11.jar

24/08/21 08:43:23 WARN MetricsSystem: Using default name SparkStatusTracker for source because neither spark.metrics.namespace nor spark.app.id is set.
24/08/21 08:43:23 ERROR SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: This RAPIDS Plugin build does not support Spark build 3.3.0-databricks. Supported Spark versions: 3.2.0 {buildver=320}, 3.3.0-databricks {buildver=330db}. Consult the Release documentation at https://nvidia.github.io/spark-rapids/docs/download.html
        at com.nvidia.spark.rapids.ShimLoader$.$anonfun$detectShimProvider$13(ShimLoader.scala:288)
        at scala.Option.getOrElse(Option.scala:189)
        at com.nvidia.spark.rapids.ShimLoader$.detectShimProvider(ShimLoader.scala:278)
        at com.nvidia.spark.rapids.ShimLoader$.findShimProvider(ShimLoader.scala:299)
        at com.nvidia.spark.rapids.ShimLoader$.initShimProviderIfNeeded(ShimLoader.scala:92)
        at com.nvidia.spark.rapids.ShimLoader$.getShimClassLoader(ShimLoader.scala:184)
        at com.nvidia.spark.rapids.ShimReflectionUtils$.loadClass(ShimReflectionUtils.scala:28)
        at com.nvidia.spark.rapids.ShimReflectionUtils$.newInstanceOf(ShimReflectionUtils.scala:34)
        at com.nvidia.spark.rapids.ShimLoader$.newDriverPlugin(ShimLoader.scala:335)
        at com.nvidia.spark.SQLPlugin.driverPlugin(SQLPlugin.scala:28)
        at org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(PluginContainer.scala:49)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.apache.spark.internal.plugin.DriverPluginContainer.<init>(PluginContainer.scala:48)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:224)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:195)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:742)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:60)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
        at py4j.Gateway.invoke(Gateway.java:257)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
        at java.lang.Thread.run(Thread.java:750)
```

start w/o `--conf spark.plugins=com.nvidia.spark.SQLPlugin` and then create a new spark session with config of the plugin seems have no issue

**Steps/Code to reproduce bug**
build with [build.sh](https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/jenkins/databricks/build.sh)
and run `pyspark` with `--conf spark.plugins=com.nvidia.spark.SQLPlugin`

**Expected behavior**
Given that users might not directly use pyspark/spark-shell, please help assess whether we should address this issue or leave it as it is.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by pxLi** [comment]
cc @gerashegalov to help when available

**Comment by jlowe** [comment]
This has to do with how the Databricks shim works and how Databricks runs Spark from within a notebook.  Clearly pyspark works in the Databricks environment since it's used by our integration tests.  See jenkins/databricks/test.sh for how to setup the dependencies for the CLI and then integration_tests/run_pyspark_from_build.sh for how it runs it in Databricks.  The missing piece is a conf that is specified automatically when run from a notebook but needs to be specified manually when running outside of that environment, spark.databricks.clusterUsageTags.sparkVersion.  See https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/integration_tests/run_pyspark_from_build.sh#L286-L310

**Comment by pxLi** [comment]
> This has to do with how the Databricks shim works and how Databricks runs Spark from within a notebook. Clearly pyspark works in the Databricks environment since it's used by our integration tests. See jenkins/databricks/test.sh for how to setup the dependencies for the CLI and then integration_tests/run_pyspark_from_build.sh for how it runs it in Databricks. The missing piece is a conf that is specified automatically when run from a notebook but needs to be specified manually when running outside of that environment, spark.databricks.clusterUsageTags.sparkVersion. See https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/integration_tests/run_pyspark_from_build.sh#L286-L310

thanks! closing the ticket now

cc @firestarman this behavior is expected.
