### ISSUE TITLE
[BUG] cudaErrorIllegalAddress when using PTDS and DEFAULT allocator (not ARENA)

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#1141]
`ARENA` is the default allocator we run with in the plugin, and it works well with `PTDS`. I am debugging some OOM issues and went back to `DEFAULT` to see if I could reproduce there, but ran into other issues. 

If they should not be compatible, then we should disable `DEFAULT` in case we detect that `PTDS` is enabled.

This was TPCDS q6 @ SF10K using 2 DGX-2 machines. The error seems to be repeatable.

```
Caused by: ai.rapids.cudf.CudfException: CUDA error encountered at: /cudf17_nightly/cpp/src/io/utilities/hostdevice_vector.hpp:55: 700 cudaErrorIllegalAddress an illegal memory access was encountered
	at ai.rapids.cudf.Table.readParquet(Native Method)
	at ai.rapids.cudf.Table.readParquet(Table.java:675)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.$anonfun$readToTable$1(GpuParquetScan.scala:1043)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FileParquetPartitionReaderBase.withResource(GpuParquetScan.scala:477)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.readToTable(GpuParquetScan.scala:1042)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.$anonfun$readBatch$1(GpuParquetScan.scala:1002)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FileParquetPartitionReaderBase.withResource(GpuParquetScan.scala:477)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.readBatch(GpuParquetScan.scala:987)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.next(GpuParquetScan.scala:889)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:79)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:112)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:381)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$iterHasNext$1(GpuCoalesceBatches.scala:180)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$iterHasNext$1$adapted(GpuCoalesceBatches.scala:179)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.withResource(GpuCoalesceBatches.scala:132)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.iterHasNext(GpuCoalesceBatches.scala:179)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1(GpuCoalesceBatches.scala:188)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1$adapted(GpuCoalesceBatches.scala:187)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.withResource(GpuCoalesceBatches.scala:132)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:187)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:203)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:220)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManager.scala:95)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
I don't have a root cause, but this is still reproducible. It looks like having more than 1 concurrent gpu task (semaphore is set to 4 in my case) is definitely related. Setting the semaphore to 1 removes the issue (so 1 stream working on the device at a time). I don't see this with the ARENA allocator.

I see this whether I use the RapidsShuffleManager or not. The main culprit at this stage is still:

```
ai.rapids.cudf.CudfException: CUDA error at: /usr/local/rapids/include/rmm/cuda_stream_view.hpp:96: cudaErrorIllegalAddress an illegal memory access was encountered
        at ai.rapids.cudf.Table.readParquet(Native Method)
        at ai.rapids.cudf.Table.readParquet(Table.java:683)
        at com.nvidia.spark.rapids.ParquetPartitionReader.$anonfun$readToTable$4(GpuParquetScan.scala:1704)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.FileParquetPartitionReaderBase.withResource(GpuParquetScan.scala:505)
```
Where I have added a synchronized call right **before**. The call here is `synchronize()` from `rmm::cuda_stream_view` which happens while inside CUDF jni functions. I have other active threads (4 task threads + shuffle threads), and all of them show `cudaErrorIllegalAddress` at synchronize calls I have added, for example:

```
21/01/18 21:37:21 ERROR Executor: Exception in task 8.0 in stage 53.0 (TID 965)
ai.rapids.cudf.CudaException: an illegal memory access was encountered
        at ai.rapids.cudf.Cuda.streamSynchronize(Native Method)
        at ai.rapids.cudf.CudaUtil$.deviceSynchronize(CudaUtil.scala:53)
        at com.nvidia.spark.rapids.GpuHashPartitioning.partitionInternal(GpuHashPartitioning.scala:105)
        at com.nvidia.spark.rapids.GpuHashPartitioning.columnarEval(GpuHashPartitioning.scala:131)
```

I added calls to `cudaStreamSynchronize` wherever I saw `cudaErrorIllegalAddress` reported while debugging this issue (i.e. the partitioning code would complain when calling into cudf `hash_partition`). The case with `readParquet` shows a call that, even with the extra synchronize before it, is causing the issue. So it is likely that this happening while `readParquet` is being invoked in CUDF jni. 

@rongou Correct me if I am wrong here. I see that in arena you are synchronizing on free, if the block being freed is from a different arena (https://github.com/rapidsai/rmm/blob/1f398d7736a227820fb6df680f52369a20c93358/include/rmm/mr/device/arena_memory_resource.hpp#L164). 

The `stream_ordered_memory_resource` is recording an event on `do_deallocate` (https://github.com/rapidsai/rmm/blob/1f398d7736a227820fb6df680f52369a20c93358/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp#L238), and the event wait happens while allocating a block (again if the block is coming from a free list which is different than the allocating stream). 

This seems OK to me, but I am curious if others have ideas. One thought that is the synchronize in ARENA could be hiding an underlying race that the event wait can't, since a synchronize would apply to all api calls in the stream.

**Comment by abellina** [comment]
@felipeblazing FYI, it would be good to know if Blazing has tried PTDS without the ARENA allocation in RMM, and ran into similar issues. Do note we have several threads... in our case we could have ~4+ threads (and therefore streams) active at the same time.

**Comment by felipeblazing** [comment]
We have done this with many threads. ~12+ but we were seeing out of memory errors due to fragmentation of the pool in RMM. I am not quite sure what you might be seeing here but if its PTDS you may be running into the same wall we did. We found that if we tried to consistently maintain high gpu consumption this way we ran into issues. We had to let there be a big "dip" in consumption every so often to allow the pools to defragment.

**Comment by sameerz** [comment]
Will modify 0.4 to throw an error in case the `DEFAULT` allocator is specified.  Will continue to investigate memcheck and sanitize tools in 0.5.

**Comment by abellina** [comment]
> Will modify 0.4 to throw an error in case the DEFAULT allocator is specified.

This will not be possible in a good way. That we have built with PTDS is something that requires CUDF to be loaded into the process, since it is a compile time flag and it's either hard enabled or hard disabled. We don't load CUDF in the driver, so if we throw in the executors, the end result is the driver seeing its executors dying, causing the driver to create _more_ executors.

It seems the current warning is as good as it gets, unless PTDS was more dynamically configured, or we find the root cause. @sameerz  I'd like to de-prioritize this issue for branch-0.4, and continue investigation of the root cause in 0.5.

**Comment by rongou** [comment]
We are seeing a similar issue with the new async allocator, might be the same root cause.

**Comment by sameerz** [comment]
@rongou will retest and see if this has been fixed.

**Comment by rongou** [comment]
Ran TPCDS on the DGX-2 and didn't see this error. Still more prone to OOM errors than the arena allocator though.
