### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: org/apache/spark/BuildInfo$ in non-databricks environment

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#11465]
We are seeing a case where an apache spark cluster is misdetecting the Spark version and it is executing code in `DatabricksShimServiceProvider` specifically for spark330db that is not going to work because we don't have those bits in this environment.

Stack trace:

```
ava.lang.NoClassDefFoundError: org/apache/spark/BuildInfo$
06:20:09  	at com.nvidia.spark.rapids.DatabricksShimServiceProvider$.$anonfun$matchesVersion$1(DatabricksShimServiceProvider.scala:30)
06:20:09  	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
06:20:09  	at scala.util.Try$.apply(Try.scala:213)
06:20:09  	at com.nvidia.spark.rapids.DatabricksShimServiceProvider$.matchesVersion(DatabricksShimServiceProvider.scala:29)
06:20:09  	at com.nvidia.spark.rapids.shims.spark330db.SparkShimServiceProvider.matchesVersion(SparkShimServiceProvider.scala:33)
06:20:09  	at com.nvidia.spark.rapids.ShimLoader$.$anonfun$detectShimProvider$11(ShimLoader.scala:270)
06:20:09  	at com.nvidia.spark.rapids.ShimLoader$.$anonfun$detectShimProvider$11$adapted(ShimLoader.scala:269)
06:20:09  	at scala.collection.immutable.Stream.$anonfun$partition$1(Stream.scala:589)
06:20:09  	at scala.collection.immutable.Stream.$anonfun$partition$1$adapted(Stream.scala:589)
06:20:09  	at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
06:20:09  	at scala.collection.immutable.Stream.filterImpl(Stream.scala:204)
06:20:09  	at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
06:20:09  	at scala.collection.TraversableLike.filter$(TraversableLike.scala:395)
06:20:09  	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
06:20:09  	at scala.collection.immutable.Stream.partition(Stream.scala:589)
06:20:09  	at com.nvidia.spark.rapids.ShimLoader$.detectShimProvider(ShimLoader.scala:269)
06:20:09  	at com.nvidia.spark.rapids.ShimLoader$.findShimProvider(ShimLoader.scala:299)
06:20:09  	at com.nvidia.spark.rapids.ShimLoader$.initShimProviderIfNeeded(ShimLoader.scala:92)
06:20:09  	at com.nvidia.spark.rapids.ShimLoader$.getShimClassLoader(ShimLoader.scala:184)
06:20:09  	at com.nvidia.spark.rapids.ShimReflectionUtils$.loadClass(ShimReflectionUtils.scala:28)
06:20:09  	at com.nvidia.spark.rapids.ShimReflectionUtils$.newInstanceOf(ShimReflectionUtils.scala:34)
06:20:09  	at com.nvidia.spark.rapids.ShimLoader$.newDriverPlugin(ShimLoader.scala:335)
06:20:09  	at com.nvidia.spark.SQLPlugin.driverPlugin(SQLPlugin.scala:28)
06:20:09  	at org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(PluginContainer.scala:47)
06:20:09  	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
06:20:09  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
06:20:09  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
06:20:09  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
06:20:09  	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
06:20:09  	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
06:20:09  	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
06:20:09  	at org.apache.spark.internal.plugin.DriverPluginContainer.<init>(PluginContainer.scala:46)
06:20:09  	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:210)
06:20:09  	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:193)
06:20:09  	at org.apache.spark.SparkContext.<init>(SparkContext.scala:560)
06:20:09  	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
06:20:09  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
06:20:09  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
06:20:09  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
06:20:09  	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
06:20:09  	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
06:20:09  	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
06:20:09  	at py4j.Gateway.invoke(Gateway.java:238)
06:20:09  	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
06:20:09  	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
06:20:09  	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
06:20:09  	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
06:20:09  	at java.lang.Thread.run(Thread.java:750)
```

**Comment by abellina** [comment]
Assigned @gerashegalov because this code is new with https://github.com/NVIDIA/spark-rapids/pull/11455, that said it could also be a shim issue and he is also the expert at that. All roads point to Gera for help!

**Comment by gerashegalov** [comment]
This trivially reproduces with all non-DBR Spark builds. 
The testing gap is that only the DBR tests are multi-shim, and DBR Spark builds do not have the issue. 
However, non-DBR pre-merge tests do not include any DBR shim to catch it
