### ISSUE TITLE
[BUG] cudaErrorIllegalAddress an illegal memory access was encountered

### ISSUE THREAD

**Issue by KevinLu233** [NVIDIA/spark-rapids#11471]
Translation GPU memory address error causes executor to hang and fail to stop during shutdown.
 GPU-Util  is. 100%

| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:18:00.0 Off |                    0 |
| N/A   63C    P0    44W /  70W |  14527MiB / 15360MiB |    100%      Default |
|                               |                      |                  N/A |

Can you help me? Thanks! 

ENV：
spark: 3.5.1
rapids: 24.08.01

Error like This:
**cancudaErrorIllegalAddress an illegal memory access was encountered**

24/09/13 20:28:11 ERROR RapidsExecutorPlugin: Stopping the Executor based on exception being a fatal CUDA error: ai.rapids.cudf.CudaFatalException: CUDA error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni-release-39-cuda11/target/libcudf-install/include/rmm/device_uvector.hpp:323: cudaErrorIllegalAddress an illegal memory access was encountered
	at ai.rapids.cudf.ColumnView.binaryOpVS(Native Method)
	at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1334)
	at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1324)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:377)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:371)
	at com.nvidia.spark.rapids.CudfBinaryOperator.doColumnar(GpuExpressions.scala:417)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:398)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:397)
	at org.apache.spark.sql.rapids.GpuLessThanOrEqual.doColumnar(predicates.scala:475)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$3(GpuExpressions.scala:318)
	at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:84)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:311)
	at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:84)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:310)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:309)
	at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEval(GpuExpressions.scala:417)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.GpuExpression.columnarEvalAny$(GpuExpressions.scala:144)
	at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEvalAny(GpuExpressions.scala:417)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEvalAny(implicits.scala:38)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:311)
	at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:84)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:310)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:309)
	at org.apache.spark.sql.rapids.CudfBinaryPredicateWithSideEffect.columnarEval(predicates.scala:113)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuConditionalExpression.$anonfun$computeIfElse$1(conditionalExpressions.scala:163)
	at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:84)
	at com.nvidia.spark.rapids.GpuConditionalExpression.computeIfElse(conditionalExpressions.scala:162)
	at com.nvidia.spark.rapids.GpuConditionalExpression.computeIfElse$(conditionalExpressions.scala:157)
	at com.nvidia.spark.rapids.GpuCaseWhen.computeIfElse(conditionalExpressions.scala:319)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEval$15(conditionalExpressions.scala:416)
	at scala.collection.immutable.ArraySeq.foldRight(ArraySeq.scala:237)
	at com.nvidia.spark.rapids.GpuCaseWhen.columnarEval(conditionalExpressions.scala:414)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:110)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$IterableMapsSafely.$anonfun$safeMap$1(implicits.scala:220)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$IterableMapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:217)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$IterableMapsSafely.safeMap(implicits.scala:217)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:331)
	at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:110)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$project$2(basicPhysicalOperators.scala:615)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.GpuTieredProject.recurse$2(basicPhysicalOperators.scala:614)
	at com.nvidia.spark.rapids.GpuTieredProject.project(basicPhysicalOperators.scala:627)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$projectWithRetrySingleBatchInternal$5(basicPhysicalOperators.scala:563)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRestoreOnRetry(RmmRapidsRetryIterator.scala:272)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$projectWithRetrySingleBatchInternal$4(basicPhysicalOperators.scala:563)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$projectWithRetrySingleBatchInternal$3(basicPhysicalOperators.scala:561)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$NoInputSpliterator.next(RmmRapidsRetryIterator.scala:395)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:613)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:517)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.drainSingleWithVerification(RmmRapidsRetryIterator.scala:291)
	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRetryNoSplit(RmmRapidsRetryIterator.scala:185)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$projectWithRetrySingleBatchInternal$1(basicPhysicalOperators.scala:561)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:39)
	at com.nvidia.spark.rapids.GpuTieredProject.projectWithRetrySingleBatchInternal(basicPhysicalOperators.scala:558)
	at com.nvidia.spark.rapids.GpuTieredProject.projectAndCloseWithRetrySingleBatch(basicPhysicalOperators.scala:597)
	at com.nvidia.spark.rapids.GpuAggFirstPassIterator$.$anonfun$apply$1(GpuAggregateExec.scala:559)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:587)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:576)
	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.$anonfun$next$2(GpuAggregateExec.scala:766)
	at scala.Option.getOrElse(Option.scala:201)
	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:762)
	at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(GpuAggregateExec.scala:718)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.$anonfun$next$10(GpuAggregateExec.scala:2124)
	at scala.Option.map(Option.scala:242)
	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:2124)
	at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(GpuAggregateExec.scala:1975)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:333)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:355)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:179)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by sameerz** [comment]
Hi @KevinLu233 , if you would like to connect directly with us please send a mail to spark-rapids-support@nvidia.com or ask on our https://rapids-goai.slack.com/ slack workspace.
