### ISSUE TITLE
[BUG] [Spark 4] Exceptions from casting to `DATE`/`TIMESTAMP` do not match the Spark's exceptions, with ANSI enabled

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#11556]
**Description**
With ANSI **enabled**, when an invalid `STRING` row is cast to `DATE`, the exception string from Spark does not match that from Spark.

Edit: Looks like this isn't exclusive to Spark 4.  Reproducible on Spark 3.5, and likely others.

**Repro**
```scala
sql(" SELECT '7452-68-35' AS str ").write.mode("overwrite").parquet("/tmp/myth/repro")

spark.conf.set("spark.rapids.sql.hasExtendedYearValues", false )
spark.conf.set("spark.sql.ansi.enabled", true )

spark.read.parquet("/tmp/myth/repro").selectExpr(" CAST(str AS DATE) ").show
```

With Apache Spark 4, the exception looks as follows:
```
org.apache.spark.SparkDateTimeException: [CAST_INVALID_INPUT] The value '7452-68-35' of the type "STRING" cannot be cast to "DATE" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error. SQLSTATE: 22018
```

The plugin fails thus:
```
java.time.DateTimeException: One or more values could not be converted to DateType
        at com.nvidia.spark.rapids.GpuCast$.$anonfun$checkResultForAnsiMode$5(GpuCast.scala:1331)
        at com.nvidia.spark.rapids.GpuCast$.$anonfun$checkResultForAnsiMode$5$adapted(GpuCast.scala:1329)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:30)
```

**Expected behavior**
The exceptions for the same Spark version with/without the plugin should match.

This needs to be sorted out whenever ANSI mode behaviours are tackled.

**Comment by res-life** [comment]
The errors on Spark versions:

### 320 
java.time.DateTimeException: Cannot cast 2005-99-00 to DateType.

### 330 
org.apache.spark.SparkDateTimeException: The value '2005-99-00' of the type "STRING" cannot be cast to "DATE" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.

### 340 
pyspark.errors.exceptions.captured.DateTimeException: [CAST_INVALID_INPUT] The value '2005-99-00' of the type "STRING" cannot be cast to "DATE" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.

### 350 
pyspark.errors.exceptions.captured.DateTimeException: [CAST_INVALID_INPUT] The value '2005-99-00' of the type "STRING" cannot be cast to "DATE" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.

We can either add shims, or just throw the common error: DateTimeException
