### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Iannantuono-Git** [NVIDIA/spark-rapids#11828]
**Describe the bug**
java.lang.ClassNotFoundException: com.nvidia.spark.SQLPlugin when trying SparkSession build in local mode.

**Steps/Code to reproduce bug**
spark = SparkSession.builder \
        .config("spark.driver.extraClassPath", classpath) \
        .config("spark.executor.extraClassPath", classpath) \
        .config("spark.sql.repl.eagerEval.enabled", True) \
        .config("spark.sql.repl.eagerEval.maxNumRows", 10) \
        .config("spark.sql.execution.arrow.enabled", "true") \
        .config("spark.driver.memory", f"{spark_driver_size}g") \
        .config("spark.driver.maxResultSize", f"{max_result_size}g") \
        .config("spark.rapids.sql.enabled", "true") \
        .config("spark.rapids.sql.explain", "ALL") \
        .config("spark.jars", "path/to/jar/rapids-4-spark_2.12-24.10.1.jar") \
        .config("spark.plugins", "com.nvidia.spark.SQLPlugin") \
        .getOrCreate()

**Expected behavior**
Looking to get the RAPIDS Accelerator For Apache Spark for interaction use with S3 data sources.

**Environment details (please complete the following information)**
 - Environment location: Standalone/Local
 - Running on Sagemaker Jupyter Notebook
 - Scala V 2.12.15
 - Spark V 3.3.0

**Additional context**
Have added the .jar file to the class path and am able pick it up within a  spark.conf print dump.
What am I doing wrong in this situation? Seems like everything should play well together with us being within the compatibility range.

**Comment by gerashegalov** [comment]
Double check the location of the jar. In local mode when we do not need to optimize RapidsShuffleManager we do not require the plugin jar to be on extraClassPath. You can use `--jars` or `--packages`. 

The equivalent config is `spark.jars` and `spark.jars.packages`, respectively.   You can check this example notebook https://github.com/NVIDIA/spark-rapids-examples/blob/branch-24.12/examples/SQL%2BDF-Examples/tpcds/notebooks/TPCDS-SF10.ipynb 

Specifically 

```
.config('spark.jars.packages', f"com.nvidia:rapids-4-spark_{scala_version}:{rapids_version}")
```

**Comment by Iannantuono-Git** [comment]
I followed the eaxample you provided, and I took the jar file off the class path (made another dir to hold it).

spark_jar_path = "SageMaker/kernels/nvidia-rapids-py310/lib/python3.10/site-packages/sagemaker_pyspark/extra_jars/rapids-4-spark_2.12-24.10.1.jar"
    scala_v = '2.12'
    rapids_v = '24.10.1'
    
    spark = SparkSession.builder \
        .config("spark.driver.extraClassPath", classpath) \
        .config("spark.executor.extraClassPath", classpath) \
        .config("spark.sql.repl.eagerEval.enabled", True) \
        .config("spark.sql.repl.eagerEval.maxNumRows", 10) \
        .config("spark.sql.execution.arrow.enabled", "true") \
        .config("spark.driver.memory", f"{spark_driver_size}g") \
        .config("spark.driver.maxResultSize", f"{max_result_size}g") \
        .config("spark.rapids.sql.enabled", "true") \
        .config("spark.rapids.sql.explain", "ALL") \
        .config("spark.plugins", "com.nvidia.spark.SQLPlugin") \
        .config("spark.jars", spark_jar_path) \
        .config("spark.jars.packages", f"com.nvidia:rapids-4-spark_{scala_v}:{rapids_v}") \
        .getOrCreate()

When I run, I get the following runtime error "RuntimeError: Java gateway process exited before sending its port number"

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.nvidia#rapids-4-spark_2.12;24.10.1: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by Iannantuono-Git** [comment]
Just adding that I have been following the initial install and configuration steps from this guide:

https://docs.nvidia.com/spark-rapids/user-guide/latest/getting-started/on-premise.html#local-mode

**Comment by gerashegalov** [comment]
You do not need both at the same time: rapid-4-spark added via  `spark.jars`  and  via `spark.jars.packages`. If added via spark.*.extraClassPath then no need to use spark.jars

If you want to overcome this
```
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.nvidia#rapids-4-spark_2.12;24.10.1: not found]
```
since it looks like there is no default Maven repo configure in your environment some repo via spark.jars.repositories such as `https://repo1.maven.org/maven2`

if you confirm the location of the jar (maybe via `!ls location` in the notebook  you could resort to configuring extraClassPatrh. Does the path work relative to PWD of the kernel?
