### ISSUE TITLE
[BUG] 3 tests "test_window_aggregate_udf"  failed on Azure Databricks due to "NoSuchMethodError"

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#1211]
**Describe the bug**
3 tests "test_window_aggregate_udf"  failed on Azure Databricks due to "NoSuchMethodError".

Error stack
```
[2020-11-26T02:49:39.393Z]                 if answer[1] == REFERENCE_TYPE:
[2020-11-26T02:49:39.393Z]                     raise Py4JJavaError(
[2020-11-26T02:49:39.393Z]                         "An error occurred while calling {0}{1}{2}.\n".
[2020-11-26T02:49:39.393Z] >                       format(target_id, ".", name), value)
[2020-11-26T02:49:39.393Z] E                   py4j.protocol.Py4JJavaError: An error occurred while calling o545257.collectToPython.
[2020-11-26T02:49:39.393Z] E                   : java.lang.NoSuchMethodError: org.apache.spark.sql.rapids.execution.python.GpuWindowInPandasExecBase.outputBatching$(Lorg/apache/spark/sql/rapids/execution/python/GpuWindowInPandasExecBase;)Lcom/nvidia/spark/rapids/CoalesceGoal;
[2020-11-26T02:49:39.393Z] E                   	at com.nvidia.spark.rapids.shims.spark301db.GpuWindowInPandasExec.outputBatching(GpuWindowInPandasExec.scala:29)
[2020-11-26T02:49:39.393Z] E                   	at com.nvidia.spark.rapids.GpuTransitionOverrides.optimizeCoalesce(GpuTransitionOverrides.scala:161)
[2020-11-26T02:49:39.393Z] E                   	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$optimizeCoalesce$3(GpuTransitionOverrides.scala:165)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.immutable.List.foreach(List.scala:392)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.immutable.List.map(List.scala:298)
[2020-11-26T02:49:39.393Z] E                   	at com.nvidia.spark.rapids.GpuTransitionOverrides.optimizeCoalesce(GpuTransitionOverrides.scala:165)
[2020-11-26T02:49:39.393Z] E                   	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$optimizeCoalesce$3(GpuTransitionOverrides.scala:165)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.immutable.List.foreach(List.scala:392)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[2020-11-26T02:49:39.393Z] E                   	at scala.collection.immutable.List.map(List.scala:298)
```

**Steps/Code to reproduce bug**
--Working on... will update this once getting one--

**Expected behavior**
The tests should pass

**Comment by firestarman** [comment]
https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-AzureDatabricks/5/consoleText

**Comment by firestarman** [comment]
No repro on latest builds: 8 and 9.
https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-AzureDatabricks/9/

**Comment by firestarman** [comment]
Still no repro on build 10 today.
https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-AzureDatabricks/10/

**Comment by sameerz** [comment]
Please reopen if this occurs again.
