### ISSUE TITLE
[BUG]StackOverflowError on Azure Databricks

### ISSUE THREAD

**Issue by shotai** [NVIDIA/spark-rapids#1236]
**Describe the bug**
When running on Azure Databricks 7.4 ML (includes Apache Spark 3.0.1, GPU, Scala 2.12), meet the error StackOverflowError. 

**Steps/Code to reproduce bug**
1. Read data from parquet
2. Do withColumn UDF on data (
 `df.withColumn('udf_result', my_udf(...))`
3. run `df.rdd.count()` to trigger execution
4. throw the error StackOverflowError (the whole log please check attachment [stderr.txt](https://github.com/NVIDIA/spark-rapids/files/5628690/stderr.txt) )

```

Py4JJavaError: An error occurred while calling o762.javaToPython.
: java.lang.StackOverflowError
	at scala.collection.generic.Growable.$anonfun$$plus$plus$eq$1(Growable.scala:62)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
	at scala.collection.generic.GenericCompanion.apply(GenericCompanion.scala:53)
	at org.apache.spark.internal.config.ConfigEntry.readString(ConfigEntry.scala:94)
	at org.apache.spark.internal.config.FallbackConfigEntry.readFrom(ConfigEntry.scala:271)
	at org.apache.spark.sql.internal.SQLConf.getConf(SQLConf.scala:3439)
	at org.apache.spark.sql.internal.SQLConf.cboEnabled(SQLConf.scala:3220)
	at com.databricks.sql.optimizer.SparkPlanStats.computeStats(SparkPlanStats.scala:29)
	at com.databricks.sql.optimizer.SparkPlanStats.computeStats$(SparkPlanStats.scala:28)
	at org.apache.spark.sql.execution.SparkPlan.computeStats(SparkPlan.scala:70)
	at com.databricks.sql.optimizer.statsEstimation.SizeInBytesOnlyStatsSparkPlanVisitor$.default(SizeInBytesOnlyStatsSparkPlanVisitor.scala:45)
	at com.databricks.sql.optimizer.statsEstimation.SizeInBytesOnlyStatsSparkPlanVisitor$.default(SizeInBytesOnlyStatsSparkPlanVisitor.scala:38)
	at com.databricks.sql.execution.SparkPlanVisitor.visit(SparkPlanVisitor.scala:58)
	at com.databricks.sql.execution.SparkPlanVisitor.visit$(SparkPlanVisitor.scala:32)
	at com.databricks.sql.optimizer.statsEstimation.SizeInBytesOnlyStatsSparkPlanVisitor$.visit(SizeInBytesOnlyStatsSparkPlanVisitor.scala:38)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.fallback(BasicStatsSparkPlanVisitor.scala:42)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.default(BasicStatsSparkPlanVisitor.scala:44)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.default(BasicStatsSparkPlanVisitor.scala:34)
	at com.databricks.sql.execution.SparkPlanVisitor.visit(SparkPlanVisitor.scala:58)
	at com.databricks.sql.execution.SparkPlanVisitor.visit$(SparkPlanVisitor.scala:32)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.super$visit(BasicStatsSparkPlanVisitor.scala:38)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.$anonfun$visit$1(BasicStatsSparkPlanVisitor.scala:38)
	at scala.Option.getOrElse(Option.scala:189)
...

```

**Expected behavior**
Should run the code of UDF and return value

**Environment details (please complete the following information)**
 - Environment location: Azure Databricks 7.4 ML (includes Apache Spark 3.0.1, GPU, Scala 2.12),
 - Spark configuration settings related to the issue
```
spark.task.resource.gpu.amount 0.1
spark.task.cpus 1
spark.rapids.sql.incompatibleOps.enabled true
spark.executor.cores 6
spark.rapids.memory.gpu.allocFraction 0.4
spark.plugins com.nvidia.spark.SQLPlugin
spark.locality.wait 0s
spark.rapids.memory.gpu.pooling.enabled true
spark.databricks.conda.condaMagic.enabled true
spark.rapids.sql.explain ALL
py-files /dbfs/rapids-4-spark_2.12-0.3.0-SNAPSHOT.jar
spark.rapids.memory.pinnedPool.size 2G
spark.rapids.python.memory.gpu.allocFraction 0.4
spark.rapids.sql.exec.MapInPandasExec true
spark.python.daemon.module rapids.daemon_databricks
spark.rapids.python.memory.gpu.pooling.enabled false
spark.rapids.sql.exec.WindowInPandasExec true
spark.executor.extraJavaOptions "-Duser.timezone=UTC"
spark.rapids.sql.concurrentGpuTasks 6

spark.conf.set("spark.rapids.sql.exec.MapInPandasExec", "true")
spark.conf.set("spark.rapids.sql.exec.WindowInPandasExec", "true")
spark.conf.set("spark.rapids.sql.exec.FlatMapGroupsInPandasExec", "true")
spark.conf.set("spark.rapids.sql.python.gpu.enabled", "true")
spark.conf.set("spark.rapids.sql.enabled", "true")
spark.conf.set("spark.sql.shuffle.partitions", "10")
```

**Additional context**
We tried on  7.0 ML (includes Apache Spark 3.0.0, GPU, Scala 2.12), the code worked. 
But on 7.4 ML (includes Apache Spark 3.0.1, GPU, Scala 2.12), we found this error.

Also we tried write parquet
`df.write.mode("overwrite").parquet("/home/ubuntu/testdata/output")` 
But the spark context just stopped, and notebook disattached from databricks cluster. The message is like
`The spark context has stopped and the driver is restarting. Your notebook will be automatically reattached.`

The related stderr log could be found at [stderr.txt](https://github.com/NVIDIA/spark-rapids/files/5628710/stderr.txt) (The first few lines are from above StackOverflowError. Following is the error with write parquet)

**Comment by tgravescs** [comment]
we don’t support 7.4, only 7.3, but it looks like the same issue we have with a few things where databricks
statsEstimation hits an infinite loop because it doesn’t know what our gpu execs are.  

Did you turn off AQE?  We don’t support that on databricks due to this.  I think 7.3+ has AQE on by default so you need to explicitly disable it.

**Comment by sameerz** [comment]
Please reopen if there are additional questions.
