### ISSUE TITLE
[BUG]: Project build fails with: Could not find artifact com.nvidia:rapids-4-spark-tests_2.12:jar:tests:0.2.0 in central

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#1249]
I cloned the main branch of spark-rapids repo in an Ubuntu GPU enabled machine, and am trying to build/compile the project but am getting this error:

```
[ERROR] Failed to execute goal on project rapids-4-spark-integration-tests_2.12: Could not resolve dependencies for project com.nvidia:rapids-4-spark-integration-tests_2.12:jar:0.2.0: Could not find artifact com.nvidia:rapids-4-spark-tests_2.12:jar:tests:0.2.0 in central (https://repo.maven.apache.org/maven2)
```

I checked the central maven repository and see that the artifact does exist, so I'm not sure what is causing this error:

![image](https://user-images.githubusercontent.com/8151864/100957970-4a572880-34d0-11eb-886d-c352aa6be1dd.png)

**System details**:

OS: Ubuntu 18.04
Nvidia version - 440.33.01
CUDA version: 10.2
Graphics card: Tesla T4

**Additional context**:

I am also trying to understand why this building project step is needed, is the jar not available as a release somewhere? I checked it is not available in the [releases](https://github.com/NVIDIA/spark-rapids/releases/tag/v0.2.0) page, except as source code itself. Is there a reason for this?

**Comment by tgravescs** [comment]
that jar should be built when you build the project (./integration_tests/target/rapids-4-spark-integration-tests_2.12-0.2.0.jar), what command did you use to build with?

mvn clean package should work, you can  use -DskipTests to build faster if you don't want to run the tests.

If you used the command above but still have an error can you provide more of the log as to which module it was building when it failed?

**Comment by jlowe** [comment]
> I am also trying to understand why this building project step is needed, is the jar not available as a release somewhere? I checked it is not available in the releases page, except as source code itself. Is there a reason for this?

We do publish the releases to Maven Central with links at https://nvidia.github.io/spark-rapids/docs/version/stable-release.html#download---v020. I'll file an issue to make this page more prominent and also attach the official artifacts to the Github releases page.

**Comment by jlowe** [comment]
I filed #1257 to improve the visibility of the jar artifacts, including attaching them to the Github releases page.

**Comment by Niharikadutta** [comment]
> that jar should be built when you build the project (./integration_tests/target/rapids-4-spark-integration-tests_2.12-0.2.0.jar), what command did you use to build with?
> 
> mvn clean package should work, you can use -DskipTests to build faster if you don't want to run the tests.
> 
> If you used the command above but still have an error can you provide more of the log as to which module it was building when it failed?

Thanks for your reply! I have tried multiple times with `mvn clean package` and `mvn compile` but they all fail and surprisingly at different points in different times. The latest `clean package` I ran failed at `RAPIDS Accelerator for Apache Spark Tests`, here is the full stack trace:

```
[DEBUG] Forking ScalaTest via: /bin/sh -c cd '/home/azureuser/rapids-spark/spark-rapids/tests' && 'java' '-Dai.rapids.refcount.debug=true' '-Djava.awt.headless=true' '-Djava.io.tmpdir=/home/azureuser/rapids-spark/spark-rapids/tests/target/tmp' '-Drapids.shuffle.manager.override=false' '-Dspark.ui.enabled=false' '-Dspark.ui.showConsoleProgress=false' '-Dspark.unsafe.exceptionOnMemoryLeak=true' '-Dbasedir=/home/azureuser/rapids-spark/spark-rapids/tests' '-javaagent:/home/azureuser/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/azureuser/rapids-spark/spark-rapids/tests/target/jacoco.exec,append=true,includes=ai.rapids.cudf.*:com.nvidia.spark.*:org.apache.spark.sql.rapids.*,excludes=com.nvidia.shaded.spark.*' '-ea' '-Xmx4g' '-Xss4m' 'org.scalatest.tools.Runner' '-R' '/home/azureuser/rapids-spark/spark-rapids/tests/target/classes /home/azureuser/rapids-spark/spark-rapids/tests/target/test-classes' '-o' '-f' '/home/azureuser/rapids-spark/spark-rapids/tests/target/surefire-reports/scala-test-output.txt' '-u' '/home/azureuser/rapids-spark/spark-rapids/tests/target/surefire-reports/.'                                                                                                                                                                                          Discovery starting.                                                                                                                                                                           WARNING: An illegal reflective access operation has occurred                                                                                                                                  WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/azureuser/.m2/repository/org/apache/spark/spark-unsafe_2.12/3.0.0/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)                                                                                                                                                        WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform                                                                                                WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                                                                         WARNING: All illegal access operations will be denied in a future release                                                                                                                     Discovery completed in 1 second, 27 milliseconds.                                                                                                                                             Run starting. Expected test count is: 451                                                                                                                                                     HashAggregatesSuite:                                                                                                                                                                          [INFO] ------------------------------------------------------------------------                                                                                                               [INFO] Reactor Summary for RAPIDS Accelerator for Apache Spark Root Project 0.2.0:                                                                                                            [INFO]                                                                                                                                                                                        [INFO] RAPIDS Accelerator for Apache Spark Root Project ... SUCCESS [  0.686 s]                                                                                                               [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin ..... SUCCESS [ 26.013 s]                                                                                                               [INFO] RAPIDS Accelerator for Apache Spark Shuffle Plugin . SUCCESS [  0.930 s]                                                                                                               [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Shims SUCCESS [  0.043 s]                                                                                                               [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.0 Shim SUCCESS [  1.472 s]                                                                                                    [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.1 Shim SUCCESS [  0.756 s]                                                                                                    [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.0 Shim SUCCESS [  1.569 s]                                                                                                    [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.2 Shim SUCCESS [  0.342 s]                                                                                                    [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Shim Aggregator SUCCESS [  0.050 s]                                                                                                     [INFO] RAPIDS Accelerator for Apache Spark Scala UDF Plugin SUCCESS [ 19.575 s]                                                                                                               [INFO] RAPIDS Accelerator for Apache Spark Distribution ... SUCCESS [  2.123 s]                                                                                                               [INFO] RAPIDS Accelerator for Apache Spark Tests .......... FAILURE [ 23.677 s]                                                                                                               [INFO] rapids-4-spark-integration-tests_2.12 .............. SKIPPED                                                                                                                           [INFO] rapids-4-spark-api-validation ...................... SKIPPED                                                                                                                           [INFO] ------------------------------------------------------------------------                                                                                                               [INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:17 min
[INFO] Finished at: 2020-12-07T20:14:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:2.0.0:test (test) on project rapids-4-spark-tests_2.12: There are test failures -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.scalatest:scalatest-maven-plugin:2.0.0:test (test) on project rapids-4-spark-tests_2.12: There are test fa$lures
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
```

**Comment by Niharikadutta** [comment]
> > I am also trying to understand why this building project step is needed, is the jar not available as a release somewhere? I checked it is not available in the releases page, except as source code itself. Is there a reason for this?
> 
> We do publish the releases to Maven Central with links at https://nvidia.github.io/spark-rapids/docs/version/stable-release.html#download---v020. I'll file an issue to make this page more prominent and also attach the official artifacts to the Github releases page.

Thanks @jlowe for providing me with the release link (and raising an issue to make it more visible), this unblocks me!

**Comment by jlowe** [comment]
@Niharikadutta what is in `tests/target/surefire-reports`?  Is there a dumpstream file or detailed test log file that may elaborate what's going on?  My guess is that it's not able to load the cudf dependency in the tests.

**Comment by Niharikadutta** [comment]
You are right @jlowe , I just checked the test log and it seems like it cannot load the cudf jni library:

```
20/12/07 20:14:37.905 ScalaTest-main-running-HashAggregatesSuite ERROR NativeDepsLoader: Could not load cudf jni library...
java.lang.UnsatisfiedLinkError: /home/azureuser/rapids-spark/spark-rapids/tests/target/tmp/cudf12015827071741354874.so: libnvrtc.so.10.1: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
```

How can I ensure it finds it? Do I need to add the cuda location to the PATH env variable?

**Comment by jlowe** [comment]
> my installed CUDA version is 10.2

The pom builds for CUDA 10.1 by default.  You can build for CUDA 10.2 by passing the `-Dcuda.version=cuda10-2` on the Maven cmdline.

**Comment by Niharikadutta** [comment]
That worked! Thanks @jlowe , I am going to close this issue now.
