### ISSUE TITLE
[BUG] Query fails with HostColumnarToGpu doesn't support Structs

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1304]
**Describe the bug**

I hit this on databricks when I read and write from delta files. After some time it appears it tried to read checkpoint file from delta log and I had turned off our GPU parquet reader with spark.conf.set("spark.rapids.sql.format.parquet.enabled", "true")

```
java.lang.UnsupportedOperationException: Converting to GPU for StructType(StructField(id,StringType,true), StructField(name,StringType,true), StructField(description,StringType,true), StructField(format,StructType(StructField(provider,StringType,true), StructField(options,MapType(StringType,StringType,true),true)),true), StructField(schemaString,StringType,true), StructField(partitionColumns,ArrayType(StringType,true),true), StructField(configuration,MapType(StringType,StringType,true),true), StructField(createdTime,LongType,true)) is not currently supported
	at com.nvidia.spark.rapids.HostColumnarToGpu$.columnarCopy(HostColumnarToGpu.scala:140)
	at com.nvidia.spark.rapids.HostToGpuCoalesceIterator.$anonfun$addBatchToConcat$1(HostColumnarToGpu.scala:202)

```
The plan:

```
GpuColumnarToRow false
+- GpuProject [protocol#78, metaData#77, version#86L]
   +- GpuRowToColumnar TargetSize(2147483647)
      +- *(1) Project [metaData#77, protocol#78, cast(regexp_extract(input_file_name(), /_delta_log/([0-9]{20})\., 1) as bigint) AS version#86L]
         +- GpuColumnarToRow false
            +- GpuFilter (gpuisnotnull(protocol#78) OR gpuisnotnull(metaData#77))
               +- HostColumnarToGpu TargetSize(2147483647)
                  +- FileScan parquet [metaData#77,protocol#78] Batched: true, DataFilters: [(isnotnull(protocol#78) OR isnotnull(metaData#77))], Format: Parquet, Location: DeltaLogFileIndex[dbfs:/tgraves/deltaeventsParquetLargeDelta2/_delta_log/00000000000000000010.che..., PartitionFilters: [], PushedFilters: [Or(IsNotNull(protocol),IsNotNull(metaData))], ReadSchema: struct<metaData:struct<id:string,name:string,description:string,format:struct<provider:string,opt...
```

The workaround is use the GPU parquet reader.

**Comment by tgravescs** [comment]
Note I was dealing with https://github.com/NVIDIA/spark-rapids/issues/1197 at the time. I'm not sure what triggers it to checkpoint and read from the checkpoint vs the delta log files, would have to investigate more.

```
from pyspark.sql.functions import *

events = spark.read.json("/databricks-datasets/structured-streaming/events/")
eventsWithDate = events.withColumn("date_col", from_unixtime(col("time")))
eventsWithDate.write.format("delta").saveAsTable("deltaeventsPartitioned2TableLarge")
eventsWithDate.write.format("delta").saveAsTable("deltaeventsPartitioned3TableLarge")
spark.conf.set("spark.rapids.sql.format.parquet.enabled", "false")
spark.conf.set("spark.rapids.sql.enabled", "true")


from pyspark.sql import functions as F
df1 = spark.read.format('delta').load("/user/hive/warehouse/deltaeventspartitioned2tablelarge")
df2 = spark.read.format('delta').load("/user/hive/warehouse/deltaeventspartitioned3tablelarge")

dfnew = df.withColumn('extra', F.lit(0).cast('byte'))
dfnew.write.format("delta").partitionBy("time").mode("overwrite").save("dbfs:/tgraves/deltaeventsParquetLargeDelta2")

```

**Comment by revans2** [comment]
@tgravescs did you plan on looking at this for Arrow too? If not I was going to try and fix it.

**Comment by tgravescs** [comment]
I filed https://github.com/NVIDIA/spark-rapids/issues/1632 to extend the arrow support

**Comment by tgravescs** [comment]
note wasn't going to work on it immediately
