### ISSUE TITLE
[BUG] TPC-DS Query Failing on EMR 6.2 with AQE

### ISSUE THREAD

**Issue by krajendrannv** [NVIDIA/spark-rapids#1369]
**Describe the bug**
When we enable spark.conf.set(‘spark.sql.adaptive.enabled’,‘true’), TPC-DS Q38 fails.

**Steps/Code to reproduce bug**
Followed the release guide to create an GPU EMR cluster
https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-rapids.html
Used PySpark Shell and Jupyter Notebook PySpark both creates the failure

**Expected behavior**
When I enable AQE, the query fails. DIsabling thi
**Environment details (please complete the following information)**
 - Environment location: EMR 6.2, Master:1m5d.xlarge
Core:8g4dn.2xlarge
 - Spark configuration settings related to the issue
spark.conf.set('spark.rapids.sql.enabled','true')
spark.conf.set('spark.rapids.sql.concurrentGpuTasks','4')
spark.conf.set('spark.sql.shuffle.partitions', '200')
spark.conf.set('spark.sql.adaptive.enabled','true')

**Additional context**
Fail logs with query
>>> spark.conf.set('spark.rapids.sql.enabled','true')
>>> start = time.time(); spark.sql(q38).collect(); end = time.time(); print(end-start)
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>
  File "/usr/lib/spark/python/pyspark/sql/dataframe.py", line 597, in collect
    sock_info = self._jdf.collectToPython()
  File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 128, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o113.collectToPython.
: java.lang.UnsupportedOperationException: WholeStageCodegen (1) does not implement doExecuteBroadcast
	at org.apache.spark.sql.execution.SparkPlan.doExecuteBroadcast(SparkPlan.scala:298)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:193)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:189)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.doExecuteBroadcast(AdaptiveSparkPlanExec.scala:397)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:193)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:189)
	at org.apache.spark.sql.execution.exchange.BaseOutputAdapterExec.doExecuteBroadcast(Exchange.scala:110)
	at org.apache.spark.sql.execution.exchange.BaseOutputAdapterExec.doExecuteBroadcast$(Exchange.scala:109)
	at org.apache.spark.sql.execution.OutputAdapterExec.doExecuteBroadcast(OutputAdapterExec.scala:35)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:193)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:189)
	at org.apache.spark.sql.execution.SubqueryBroadcastExec.doExecuteCollect(SubqueryBroadcastExec.scala:63)
	at org.apache.spark.sql.execution.AsyncSubqueryExec$$anon$2.doCompute(basicPhysicalOperators.scala:772)
	at org.apache.spark.sql.execution.AsyncSubqueryExec$$anon$2.doCompute(basicPhysicalOperators.scala:769)
	at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$compute$1(AsyncDriverOperation.scala:73)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:104)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:227)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:219)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:202)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:248)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:199)
	at org.apache.spark.sql.execution.AsyncDriverOperation.compute(AsyncDriverOperation.scala:67)
	at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$computeFuture$1(AsyncDriverOperation.scala:53)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$1(SQLExecution.scala:270)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.checkNoFailures(AdaptiveExecutor.scala:146)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.doRun(AdaptiveExecutor.scala:88)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.tryRunningAndGetFuture(AdaptiveExecutor.scala:66)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.execute(AdaptiveExecutor.scala:57)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:164)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:163)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:360)
	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3503)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3667)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:104)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:227)
	at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:132)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:104)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:227)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:132)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:248)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:131)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3665)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3500)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

>>> 20/12/10 02:40:59 WARN TaskSetManager: Lost task 3.0 in stage 159.0 (TID 4072, ip-172-31-1-236.us-west-2.compute.internal, executor 27): TaskKilled (Stage cancelled)
20/12/10 02:40:59 WARN TaskSetManager: Lost task 5.0 in stage 159.0 (TID 4074, ip-172-31-13-150.us-west-2.compute.internal, executor 25): TaskKilled (Stage cancelled)
20/12/10 02:40:59 WARN TaskSetManager: Lost task 1.0 in stage 159.0 (TID 4070, ip-172-31-13-150.us-west-2.compute.internal, executor 25): TaskKilled (Stage cancelled)
20/12/10 02:40:59 WARN TaskSetManager: Lost task 7.0 in stage 159.0 (TID 4076, ip-172-31-1-236.us-west-2.compute.internal, executor 27): TaskKilled (Stage cancelled)
20/12/10 02:41:00 WARN TaskSetManager: Lost task 4.0 in stage 159.0 (TID 4073, ip-172-31-9-68.us-west-2.compute.internal, executor 28): TaskKilled (Stage cancelled)
20/12/10 02:41:00 WARN TaskSetManager: Lost task 0.0 in stage 159.0 (TID 4069, ip-172-31-9-68.us-west-2.compute.internal, executor 28): TaskKilled (Stage cancelled)

**Comment by tgravescs** [comment]
this looks like its fixed in 0.3 - see https://github.com/NVIDIA/spark-rapids/issues/1035
