### ISSUE TITLE
[BUG] Spark keeps creating and exiting Executor when Rapids is enabled, due to Out of Memory

### ISSUE THREAD

**Issue by mstolin** [NVIDIA/spark-rapids#1431]
**Describe the bug**
When I start a Spark application via spark-submit and RAPIDS enabled, the Spark worker keeps creating and exiting Spark executor without finishing the job until I kill the job via Spark Master UI. It does work without RAPIDS enabled. The worker discovers the GPU as expected, I can see all GPUs in the Resource column.

When I look in an exited Spark executor error log, it prints out the following:
```
Spark Executor Command: "/usr/lib/jvm/java-8-openjdk-amd64/bin/java" "-cp" "/opt/sparkRapidsPlugin/cudf-0.15-cuda11.jar:/opt/sparkRapidsPlugin/rapids-4-spark_2.12-0.2.0.jar:/usr/bin/spark/conf/:/usr/bin/spark/jars/*" "-Xmx4096M" "-Dspark.driver.port=42367" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@bd6ddeaa3173:42367" "--executor-id" "7" "--hostname" "10.0.1.10" "--cores" "1" "--app-id" "app-20201222100101-0006" "--worker-url" "spark://Worker@10.0.1.10:33661" "--resourcesFile" "/usr/bin/spark/work/app-20201222100101-0006/7/resource-executor-5454145469667487121.json"
========================================
 
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/12/22 10:01:02 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 7429@698a87e05856
20/12/22 10:01:02 INFO SignalUtils: Registered signal handler for TERM
20/12/22 10:01:02 INFO SignalUtils: Registered signal handler for HUP
20/12/22 10:01:02 INFO SignalUtils: Registered signal handler for INT
20/12/22 10:01:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/12/22 10:01:03 INFO SecurityManager: Changing view acls to: root
20/12/22 10:01:03 INFO SecurityManager: Changing modify acls to: root
20/12/22 10:01:03 INFO SecurityManager: Changing view acls groups to:
20/12/22 10:01:03 INFO SecurityManager: Changing modify acls groups to:
20/12/22 10:01:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
20/12/22 10:01:04 INFO TransportClientFactory: Successfully created connection to bd6ddeaa3173/10.0.1.15:42367 after 84 ms (0 ms spent in bootstraps)
20/12/22 10:01:04 INFO SecurityManager: Changing view acls to: root
20/12/22 10:01:04 INFO SecurityManager: Changing modify acls to: root
20/12/22 10:01:04 INFO SecurityManager: Changing view acls groups to:
20/12/22 10:01:04 INFO SecurityManager: Changing modify acls groups to:
20/12/22 10:01:04 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
20/12/22 10:01:04 INFO TransportClientFactory: Successfully created connection to bd6ddeaa3173/10.0.1.15:42367 after 2 ms (0 ms spent in bootstraps)
20/12/22 10:01:04 INFO DiskBlockManager: Created local directory at /tmp/spark-4c3f5912-5328-4eed-8143-234e8acbb91c/executor-b0767508-0ce0-4c1d-ad26-e23b8b0f4a29/blockmgr-a91e44e9-38db-45d1-bdcf-3c4228dcf4aa
20/12/22 10:01:04 INFO MemoryStore: MemoryStore started with capacity 2004.6 MiB
20/12/22 10:01:04 INFO CoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@bd6ddeaa3173:42367
20/12/22 10:01:04 INFO WorkerWatcher: Connecting to worker spark://Worker@10.0.1.10:33661
20/12/22 10:01:04 INFO TransportClientFactory: Successfully created connection to /10.0.1.10:33661 after 2 ms (0 ms spent in bootstraps)
20/12/22 10:01:04 INFO WorkerWatcher: Successfully connected to spark://Worker@10.0.1.10:33661
20/12/22 10:01:04 INFO ResourceUtils: ==============================================================
20/12/22 10:01:04 INFO ResourceUtils: Resources for spark.executor:
gpu -> [name: gpu, addresses: 3]
20/12/22 10:01:04 INFO ResourceUtils: ==============================================================
20/12/22 10:01:04 INFO CoarseGrainedExecutorBackend: Successfully registered with driver
20/12/22 10:01:04 INFO Executor: Starting executor ID 7 on host 10.0.1.10
20/12/22 10:01:05 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38819.
20/12/22 10:01:05 INFO NettyBlockTransferService: Server created on 10.0.1.10:38819
20/12/22 10:01:05 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/12/22 10:01:05 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(7, 10.0.1.10, 38819, None)
20/12/22 10:01:05 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(7, 10.0.1.10, 38819, None)
20/12/22 10:01:05 INFO BlockManager: Initialized BlockManager: BlockManagerId(7, 10.0.1.10, 38819, None)
20/12/22 10:01:05 INFO RapidsExecutorPlugin: Initializing memory from Executor Plugin
20/12/22 10:01:18 WARN GpuDeviceManager: Initial RMM allocation (29232.44921875 MB) is larger than free memory (648.875 MB)
20/12/22 10:01:18 INFO GpuDeviceManager: Initializing RMM POOLED initial size = 29232.44921875 MB, max size = 31456.5 MB on gpuId 3
20/12/22 10:01:18 ERROR RapidsExecutorPlugin: Exception in the executor plugin
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: CUDA error at: /usr/local/rapids/include/rmm/mr/device/cuda_memory_resource.hpp:68: cudaErrorMemoryAllocation out of memory
        at ai.rapids.cudf.Rmm.initializeInternal(Native Method)
        at ai.rapids.cudf.Rmm.initialize(Rmm.java:192)
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeRmm(GpuDeviceManager.scala:235)
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeMemory(GpuDeviceManager.scala:265)
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpuAndMemory(GpuDeviceManager.scala:126)
        at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:135)
        at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:111)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:99)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:164)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:152)
        at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:220)
        at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:221)
        at org.apache.spark.executor.Executor.<init>(Executor.scala:220)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:152)
        at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
        at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:203)
        at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
        at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
        at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20/12/22 10:01:18 ERROR Utils: Uncaught exception in thread Thread-2
java.lang.NullPointerException
        at org.apache.spark.executor.Executor.$anonfun$stop$3(Executor.scala:289)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:221)
        at org.apache.spark.executor.Executor.stop(Executor.scala:289)
        at org.apache.spark.executor.Executor.$anonfun$new$2(Executor.scala:74)
        at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:214)
        at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$2(ShutdownHookManager.scala:188)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1932)
        at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$1(ShutdownHookManager.scala:188)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
        at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
20/12/22 10:01:18 INFO DiskBlockManager: Shutdown hook called
20/12/22 10:01:18 INFO ShutdownHookManager: Shutdown hook called
```

**Steps/Code to reproduce bug**
Just run spark-submit with RAPIDS enabled.
```
$SPARK_HOME/bin/spark-submit \
        --master ${SARK_MASTER_URI} \
        --conf spark.executor.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR} \
        --conf spark.driver.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR} \
        --conf spark.rapids.sql.concurrentGpuTasks=1 \
        --driver-memory 2G \
        --conf spark.executor.memory=4G \
        --conf spark.executor.cores=1 \
        --conf spark.executor.resource.gpu.amount=1 \
        --conf spark.task.cpus=1 \
        --conf spark.task.resource.gpu.amount=1 \
        --conf spark.rapids.memory.pinnedPool.size=2G \
        --conf spark.locality.wait=0s \
        --conf spark.sql.files.maxPartitionBytes=512m \
        --conf spark.sql.shuffle.partitions=10 \
        --conf spark.plugins=com.nvidia.spark.SQLPlugin \
        SparkPI.py 100
```

**Expected behavior**
If the GPUs are "out of memory", Spark should not keep creating executors forever and it should finish with an error message/code, which can be analyzed for debugging.

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark Cluster with only one Worker
 - Master and worker are running in an independent Docker container
 - Runs on a NVIDIA DGX
 - Docker image used: nvidia/cuda:11.0-devel-ubuntu16.04
 - Setup done as the instructions described here: https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html

**Additional context**
Actually I dont think that my GPUs are out of memory. In general i have 8 GPUs available.

**Comment by revans2** [comment]
@mstolin sorry no one has responded before this.  Most of us have been out on vacation.

From the logs you posted it appears that you have a 32 GB GPU and that we are crashing as we try to allocate (about 29232 MiB/28 GiB) from it for a pool to be used as a part of the query. My initial guess would be that you have multiple executor processes trying to access the GPU at once and one of them succeeded and the others failed.

We try to prevent this by having the GPU be a resource that Spark is aware of so it does not over allocate the GPU.

https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#spark-standalone-cluster
https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-313-with-isolation-and-gpu-scheduling-enabled
https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-210-with-isolation-and-gpu-scheduling-enabled

all talk about getting the GPU discovery script installed and setup if this is the route you want to go.

As an alternative we also have instructions for putting the GPU in process exclusive mode.

https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-without-isolation

**Comment by mstolin** [comment]
Hey, thanks for the answer.

Ive installed the GPU discovery script as described in the documentation.

How can I prevent Spark executor from allocating all memory from the GPU?

**Comment by jlowe** [comment]
> How can I prevent Spark executor from allocating the whole GPU?

Spark does not support allocating a fractional number of GPUs to an executor.

If you are not interested in running more than one executor per GPU but simply want the RAPIDS Accelerator to use less GPU memory for the GPU that is assigned, then that is possible.  You can use the `spark.rapids.memory.gpu.maxAllocFraction` config setting to reduce the maximum fraction of total GPU memory that the RAPIDS Accelerator will allocate at once.  You will also need to ensure that the initial amount of memory allocated, controlled by `spark.rapids.memory.gpu.allocFraction`, is equal to or lower than the new max setting.  See https://nvidia.github.io/spark-rapids/docs/configs.html for more details on configuration settings.

**Comment by revans2** [comment]
If this is still an issue feel free to reopen this.
