### ISSUE TITLE
[BUG] IllegalArgumentException during shuffle

### ISSUE THREAD

**Issue by rongou** [NVIDIA/spark-rapids#1510]
**Describe the bug**
When running TPC-DS benchmarks with the shuffle manager enabled (but no UCX), getting an exception
```console
java.lang.IllegalArgumentException: requirement failed:
Attempting to handle non-rapids enabled blocks from BlockManagerId(8, 127.0.0.1, 37359, None)
```

**Steps/Code to reproduce bug**
Here is the command line:
```console
/raid/spark-team/rou/spark/bin/spark-shell\
 --master spark://127.0.0.1:7077\
 --conf spark.serializer=org.apache.spark.serializer.KryoSerializer\
 --conf spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistrator\
 --conf spark.locality.wait=0s\
 --conf spark.sql.files.maxPartitionBytes=1g\
 --conf spark.sql.shuffle.partitions=96\
 --conf spark.shuffle.manager=com.nvidia.spark.rapids.spark301.RapidsShuffleManager\
 --conf spark.shuffle.service.enabled=false\
 --conf spark.plugins=com.nvidia.spark.SQLPlugin\
 --conf spark.rapids.sql.concurrentGpuTasks=1\
 --conf spark.rapids.memory.pinnedPool.size=8G\
 --conf spark.rapids.sql.batchSizeBytes=1g\
 --conf spark.rapids.memory.gpu.direct.storage.spill.enabled=false\
 --conf spark.driver.memory=10G\
 --conf spark.driver.extraJavaOptions=-Dai.rapids.cudf.nvtx.enabled=false\
 --conf spark.executor.extraClassPath=/raid/spark-team/rou/rapids/cudf.jar:\
/raid/spark-team/rou/rapids/rapids-4-spark.jar\
 --conf spark.executor.extraJavaOptions=-Dai.rapids.cudf.nvtx.enabled=false\
 --conf spark.executor.instances=16\
 --conf spark.executor.cores=6\
 --conf spark.executor.memory=64G\
 --conf spark.executor.resource.gpu.amount=1\
 --conf spark.task.cpus=1\
 --conf spark.task.resource.gpu.amount=0.1666\
 --jars /raid/spark-team/rou/rapids/cudf.jar,\
/raid/spark-team/rou/rapids/rapids-4-spark.jar,\
/raid/spark-team/rou/rapids/rapids-4-spark-integration-tests.jar
```
and the query piped in:
```scala
import com.nvidia.spark.rapids.tests._
import com.nvidia.spark.rapids.tests.tpcds._

val args = Array("/raid/spark-team/tpcds-1TB-parquet", "q1")

TpcdsLikeSpark.setupAllParquet(spark, args(0))

val benchmark = new BenchmarkRunner(new TpcdsLikeBench(true))
benchmark.collect(spark, args(1))

System.exit(0)
```

**Expected behavior**
Should not throw exception.

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark configuration settings related to the issue
```bash
SPARK_WORKER_OPTS="-Dspark.worker.resource.gpu.amount=16 -Dspark.worker.resource.gpu.discoveryScript=/raid/spark-team/rou/rapids/getGpusResources.sh"
SPARK_LOCAL_DIRS=/raid/spark-team/rou/tmp
```

**Additional context**
Full stacktrace:
```console
21/01/13 14:51:34 WARN TaskSetManager: Lost task 86.0 in stage 32.0 (TID 770, 127.0.0.1, executor 8): java.lang.IllegalArgumentException: requirement failed: Attempting to handle non-rapids enabled blocks from BlockManagerId(5, 127.0.0.1, 34977, None)
	at scala.Predef$.require(Predef.scala:281)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$1(RapidsCachingReader.scala:110)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$1$adapted(RapidsCachingReader.scala:68)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)
	at org.apache.spark.sql.rapids.RapidsCachingReader.read(RapidsCachingReader.scala:68)
	at org.apache.spark.sql.rapids.execution.ShuffledBatchRDD.compute(ShuffledBatchRDD.scala:214)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
@rongou I submitted PR https://github.com/NVIDIA/spark-rapids/pull/1543 to help clarify as much as possible. The main issue is that at write time we do not know who is going to fetch a block. It could be the local (cache) reads, which work in the case that UCX is not present in the system, but the moment you have a second executor looking for blocks we are going to be needing a transport, and UCX is the only implementation we have.

Hence I have turned on by default `spark.rapids.shuffle.transport.enabled`, and made it internal, as only local testing should really be using this and the expectation is that the _RapidsShuffleManager_ requires UCX in the system unless there is a really good reason not to (like unit tests).
