### ISSUE TITLE
[BUG] Spark 3.1.1 test failure in writing due to removal of InMemoryFileIndex.shouldFilterOut

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1534]
**Describe the bug**
[SPARK-34075][SQL][CORE] Hidden directories are being listed for partiition inference
removed shouldFilterOut from InMemoryFileIndex and now the orc and parquet write tests are failing:

06:25:49  FAILED src/main/python/orc_write_test.py::test_write_save_table[native-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/orc_write_test.py::test_write_save_table[hive-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/orc_write_test.py::test_write_sql_save_table[native-TIMESTAMP_MICROS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/orc_write_test.py::test_write_sql_save_table[native-TIMESTAMP_MILLIS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/orc_write_test.py::test_write_sql_save_table[hive-TIMESTAMP_MICROS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/orc_write_test.py::test_write_sql_save_table[hive-TIMESTAMP_MILLIS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/parquet_write_test.py::test_write_save_table[INT96-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/parquet_write_test.py::test_write_save_table[TIMESTAMP_MICROS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/parquet_write_test.py::test_write_save_table[TIMESTAMP_MILLIS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/parquet_write_test.py::test_write_sql_save_table[INT96-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/parquet_write_test.py::test_write_sql_save_table[TIMESTAMP_MICROS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/parquet_write_test.py::test_write_sql_save_table[TIMESTAMP_MILLIS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp]]
06:25:49  FAILED src/main/python/parquet_write_test.py::test_ts_write_twice_fails_exception

**Comment by tgravescs** [comment]
```
org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.shouldFilterOut(Ljava/lang/String;)Z
06:25:49  E                   	at org.apache.spark.sql.rapids.GpuDataSource$.$anonfun$checkAndGlobPathIfNecessary$5(GpuDataSource.scala:641)
06:25:49  E                   	at org.apache.spark.sql.rapids.GpuDataSource$.$anonfun$checkAndGlobPathIfNecessary$5$adapted(GpuDataSource.scala:640)
06:25:49  E                   	at scala.collection.TraversableLike.$anonfun$partition$1(TraversableLike.scala:402)
06:25:49  E                   	at scala.collection.immutable.List.foreach(List.scala:392)
```
