### ISSUE TITLE
[BUG] TPC-DS-like query 72 at scale=3TB fails with "Maximum join output size exceeded"

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#1629]
This is with 8 executors (each with an A100 with 40GB) and 4 concurrent tasks (4 cores/exec)

```
ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/cudf-release-11.0/cpp/src/join/hash_join.cuh:149: Maximum join output size exceeded
        at ai.rapids.cudf.Table.innerJoin(Native Method)
        at ai.rapids.cudf.Table.access$3500(Table.java:44)
        at ai.rapids.cudf.Table$TableOperation.innerJoin(Table.java:2233)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin.doJoinLeftRight(GpuHashJoin.scala:307)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin.com$nvidia$spark$rapids$shims$spark300$GpuHashJoin$$doJoin(GpuHashJoin.scala:274)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:223)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:189)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:223)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at com.nvidia.spark.rapids.RowToColumnarIterator.hasNext(GpuRowToColumnarExec.scala:542)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:219)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:211)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:228)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManager.scala:95)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by revans2** [comment]
This is a rather difficult problem.

There are a number of joins that happen.  The first join is a sort merge join between inventory and catalog sales.  This makes the data size explode, then over the course of several other broadcast joins the data size drops more and more until it is finally not that big.

I did some data analysis on this query at scale factor 200 instead of 3000.  But even here the numbers do not look good for us.

Cudf does not currently let us push filters down into the joins, so in this case we are able to do the join, and then filter the results.  This produces a problem because 95% of the data is filtered out.  For Scale factor 200 this means that our join will produce about 33.5 TB of data and then filter that down to 1.7TB.  Even if we divide this data into 200 partitions we still end up with 172 GB of data before filtering and 8.7 GB of data after filtering.

So the first step to be able to support this join is to get filtering into the join.  In this case the filter is a simple inequality between two columns, so we should be able to make that work.  As a part of that work it might be nice for us to explore what it would take to not materialize all of the columns.  Spark ends up dropping the two columns used in the inequality projection after the join. It would take some work for us to optimize things so we could do this as a part of the join, but it should be possible.  We also need to make sure that we dedupe input columns so the output does not have duplicate columns in them. This would drop the final output data to 6.7 GB per partition.

But I'm not sure if that will be enough to get this to run at SF 3k. Even if we assume that the output size scales linearly with the input size ( which is not guaranteed especially with a join) we would end up with 101 GB of output data for each partition. 

The input sizes per partition are tiny. The left side is 71MB at SF200 or maybe 1GB at SF3k. The right hand side is 36MB at SF200 or about 540MB at SF3k.  Both of these are small enough to fit into the typical input partition sizes we try for.

So then we need to figure out a way to do the join in parts. This is likely going to require some help from cudf.  There are a few options that we could do, but we would have to play around with a number of things to see if any of them are not going to slow down the other queries that don't need these special cases.

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/pull/7534 and https://github.com/rapidsai/cudf/pull/7454 .

**Comment by revans2** [comment]
Even after #2310 this is not even close to working well.
