### ISSUE TITLE
[BUG] Tests `test_window_aggs_for_rows_collect_list` fails when there are null values in columns.

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#1638]
**Describe the bug**
Spark will drop nulls when collecting, but seems GPU does not yet, so exceptions as below come up.
``` java
E      Caused by: java.lang.AssertionError:  value at 350 is null
E          	at ai.rapids.cudf.HostColumnVectorCore.assertsForGet(HostColumnVectorCore.java:228)
E         	at ai.rapids.cudf.HostColumnVectorCore.getInt(HostColumnVectorCore.java:254)
E         	at com.nvidia.spark.rapids.RapidsHostColumnVectorCore.getInt(RapidsHostColumnVectorCore.java:109)
E         	at org.apache.spark.sql.vectorized.ColumnarArray.getInt(ColumnarArray.java:128)
```

**Steps/Code to reproduce bug**
Run the tests `test_window_aggs_for_rows_collect_list` with latest cudf and rapids jars.

**Expected behavior**
Tests should pass.

**Comment by firestarman** [comment]
This should be fixed by https://github.com/rapidsai/cudf/pull/7264

**Comment by firestarman** [comment]
Suppose it will be fixed when updating cudf to 0.19 .

**Comment by firestarman** [comment]
PR rapidsai/cudf#7264 is not enough, needing support in JNI.

**Comment by firestarman** [comment]
Filed a PR https://github.com/rapidsai/cudf/pull/7457 to add support in cuDF JVM .

**Comment by firestarman** [comment]
File PR #1830 to fix this issue
