### ISSUE TITLE
[BUG] GDS exception when writing shuffle file

### ISSUE THREAD

**Issue by rongou** [NVIDIA/spark-rapids#1651]
**Describe the bug**
When running TPC-DS query 4 with GDS enabled, some executors fail when spilling shuffle buffers.

**Steps/Code to reproduce bug**
TPC-DS q4 scale factor 3000 on a DGX-2.

**Expected behavior**
Should not throw exception.

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark configuration settings related to the issue
`spark.rapids.memory.gpu.direct.storage.spill.enabled=true`

**Additional context**
Stacktrace:
```console
21/02/01 18:23:37 INFO DeviceMemoryEventHandler: Device allocation of 243884544 bytes failed, device store has
 31784063232 bytes. Total RMM allocated is 32297827328 bytes.
21/02/01 18:23:37 DEBUG DeviceMemoryEventHandler: Targeting device store size of 31540178688 bytes
21/02/01 18:23:37 DEBUG RapidsDeviceMemoryStore: GPU store spilling to reduce usage from 31784063232 to 31540178688
 bytes
21/02/01 18:23:37 DEBUG RapidsDeviceMemoryStore: Spilling GPU buffer size=410496 ShuffleBufferId(shuffle_0_48_0,0) to
 gds total mem=31784063232
21/02/01 18:23:38 ERROR DeviceMemoryEventHandler:
 Error handling allocation failure ai.rapids.cudf.CudfException:
 cuDF failure at: /home/rou/src/cudf/java/src/main/native/src/CuFileJni.cpp:238:
 Failed to write buffer to file /raid/spark-team/tmp/spark-f8f539c8-5ae2-408b-b6c6-dffd67efca14/
executor-74252cbb-6f6e-4b86-a12a-bea7224e08a8/blockmgr-3946a712-5730-4b6e-94d1-5f8a80fe46de/2a/
shuffle_0_48_0: File exists
	at ai.rapids.cudf.CuFile.appendToFile(Native Method)
	at ai.rapids.cudf.CuFile.appendDeviceBufferToFile(CuFile.java:101)
	at com.nvidia.spark.rapids.RapidsGdsStore.$anonfun$createBuffer$1(RapidsGdsStore.scala:55)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.RapidsGdsStore.withResource(RapidsGdsStore.scala:31)
	at com.nvidia.spark.rapids.RapidsGdsStore.createBuffer(RapidsGdsStore.scala:40)
	at com.nvidia.spark.rapids.RapidsBufferStore.copyBuffer(RapidsBufferStore.scala:129)
	at com.nvidia.spark.rapids.RapidsBufferStore.spillAndFreeBuffer(RapidsBufferStore.scala:233)
	at com.nvidia.spark.rapids.RapidsBufferStore.trySpillAndFreeBuffer(RapidsBufferStore.scala:216)
	at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:159)
	at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:139)
	at com.nvidia.spark.rapids.DeviceMemoryEventHandler.onAllocFailure(DeviceMemoryEventHandler.scala:57)
	at ai.rapids.cudf.Table.contiguousSplit(Native Method)
	at ai.rapids.cudf.Table.contiguousSplit(Table.java:1617)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$5(SpillableColumnarBatch.scala:170)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$5$adapted(SpillableColumnarBatch.scala:169)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.withResource(SpillableColumnarBatch.scala:126)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$4(SpillableColumnarBatch.scala:169)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$4$adapted(SpillableColumnarBatch.scala:168)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.withResource(SpillableColumnarBatch.scala:126)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.addBatch(SpillableColumnarBatch.scala:168)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.apply(SpillableColumnarBatch.scala:140)
	at com.nvidia.spark.rapids.GpuCoalesceIterator.saveOnDeck(GpuCoalesceBatches.scala:557)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$2(GpuCoalesceBatches.scala:190)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$2$adapted(GpuCoalesceBatches.scala:185)
	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:67)
	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:65)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.closeOnExcept(GpuCoalesceBatches.scala:134)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1(GpuCoalesceBatches.scala:185)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1$adapted(GpuCoalesceBatches.scala:183)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.withResource(GpuCoalesceBatches.scala:134)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:183)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:207)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:224)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManager.scala:95)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rongou** [comment]
This is gone once we divided the big RAID 0 in the DGX-2 into smaller ones.
