### ISSUE TITLE
Spark 3.1 now supports the legacy behavior of parameterless count 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1737]
**Is your feature request related to a problem? Please describe.**
Spark 3.1 supports parameterless count. 

**Describe the solution you'd like**
We should test if we are supporting that, if not then we need to add this functionality

**Additional context**
Please look at this [change](https://github.com/apache/spark/commit/63eb9101f2)

**Comment by tgravescs** [comment]
this changes just makes it so you can't use the parameterless count() by default and you have to enable the config. This all works just fine already. But while testing this it seems that we don't do the right thing with parameterless count():

```
scala> spark.conf.set("spark.rapids.sql.enabled", "false")

scala> spark.sql("select count() from people_csv").show()
+-------+
|count()|
+-------+
|      0|
+-------+
```


```
scala> spark.conf.set("spark.rapids.sql.enabled", "true")

scala> spark.sql("select count() from people_csv").show()
21/02/17 18:48:34 WARN GpuOverrides:
    !Exec <HashAggregateExec> cannot run on GPU because result expressions is empty


21/02/17 18:48:34 ERROR Executor: Exception in task 0.0 in stage 7.0 (TID 7)
java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
 at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)
        at scala.collection.IterableLike.head(IterableLike.scala:109)
        at scala.collection.IterableLike.head$(IterableLike.scala:108)
        at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$head(ArrayBuffer.scala:49)
        at scala.collection.IndexedSeqOptimized.head(IndexedSeqOptimized.scala:129)
        at scala.collection.IndexedSeqOptimized.head$(IndexedSeqOptimized.scala:129)
        at scala.collection.mutable.ArrayBuffer.head(ArrayBuffer.scala:49)
        at com.nvidia.spark.rapids.GpuHashAggregateExec.computeAggregate(aggregate.scala:872)
        at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$doExecuteColumnar$1(aggregate.scala:431)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by tgravescs** [comment]
note if the config is off then it fails as expected:  spark.conf.set("spark.sql.legacy.allowParameterlessCount", "false")

```
scala> spark.sql("select count() from people_csv").show()
org.apache.spark.sql.AnalysisException: cannot resolve 'count()' due to data type mismatch: count requires at least one argument. If you have to call the function count without arguments, set the legacy configuration `spark.sql.legacy.allowParameterlessCount` as true; line 1 pos 7;
'Aggregate [unresolvedalias(count(), None)]
+- SubqueryAlias people_csv
   +- Project [name#22, age#26, _c2#18 AS job#30]
      +- Project [name#22, _c1#17 AS age#26, _c2#18]
         +- Project [_c0#16 AS name#22, _c1#17, _c2#18]
            +- Relation[_c0#16,_c1#17,_c2#18] csv

  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:161)
```
