### ISSUE TITLE
GPU support for ORC's varchar/char datatype

### ISSUE THREAD

**Issue by atam003** [NVIDIA/spark-rapids#1765]
**Is your feature request related to a problem? Please describe.**
Informatica read varchar n char datatype as string but GPU code has strict schema validation as follows.
Caused by: org.apache.spark.sql.execution.QueryExecutionException: Incompatible schemas for ORC file at s3a://infa.qa.bucket/ORC/s3_string.orc
file schema: struct<_col0:char(50),_col1:varchar(50),_col2:string>
read schema: struct<_col0:string,_col1:string,_col2:string>
at com.nvidia.spark.rapids.GpuOrcPartitionReader.$anonfun$checkSchemaCompatibility$1(GpuOrcScan.scala:567)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
at com.nvidia.spark.rapids.GpuOrcPartitionReader.checkSchemaCompatibility(GpuOrcScan.scala:564)
at com.nvidia.spark.rapids.GpuOrcPartitionReader.initializeOrcReaders(GpuOrcScan.scala:237)
at com.nvidia.spark.rapids.GpuOrcPartitionReader.<init>(GpuOrcScan.scala:219)
at com.nvidia.spark.rapids.GpuOrcPartitionReaderFactory.buildColumnarReader(GpuOrcScan.scala:152)

Requirement is to relax the validation within same datatype family.

**Describe the solution you'd like**
No strict schema validation for read

**Describe alternatives you've considered**
NA

**Additional context**
Posting on behalf of Informatica

**Comment by jlowe** [comment]
Fixed by #6188 and #8295.
