### ISSUE TITLE
[QST]Plugin only supports 1 gpu per executor

### ISSUE THREAD

**Issue by qinaigonghe** [NVIDIA/spark-rapids#1890]
**What is your question?**
When I run spark-shell and successful startup,there will generate error right away, I think the main reason is "Plugin only supports 1 gpu per executor" and at "com.nvidia.spark.rapids.GpuDeviceManager$.getGPUAddrFromResources(GpuDeviceManager.scala:106)", I don't konw how to fix it and can't find the same questions in website. I don't have much experience in GPU, so could you give me some suggestions? Here is the report and my configuration:
1.version
spark3.0.1
hadoop3.1.3
RAPIDS Accelerator v0.3
docker cloud1:master and worker , cloud2:worker with yarn
2. My instructions and report
root@cloud1:/rapids/hadoop/etc/hadoop# $SPARK_HOME/bin/spark-shell \
>      --master yarn \
>      --conf spark.rapids.sql.concurrentGpuTasks=1 \
>      --driver-memory 2G \
>      --conf spark.executor.memory=4G \
>      --conf spark.executor.cores=4 \
>      --conf spark.executor.resource.gpu.amount=1 \
>      --conf spark.task.cpus=1 \
>      --conf spark.task.resource.gpu.amount=0.25 \
>      --conf spark.rapids.memory.pinnedPool.size=2G \
>      --conf spark.locality.wait=0s \
>      --conf spark.sql.files.maxPartitionBytes=512m \
>      --conf spark.sql.shuffle.partitions=10 \
>      --conf spark.plugins=com.nvidia.spark.SQLPlugin \
>      --conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
>      --files ${SPARK_RAPIDS_DIR}/getGpusResources.sh \
>      --jars  ${SPARK_CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR}
2021-03-07 14:15:10,792 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2021-03-07 14:16:28,480 WARN rapids.SQLExecPlugin: Installing extensions to enable rapids GPU SQL support. To disable GPU support set `spark.rapids.sql.enabled` to false
2021-03-07 14:16:28,554 WARN udf.Plugin: Installing rapids UDF compiler extensions to Spark. The compiler is disabled by default. To enable it, set `spark.rapids.sql.udfCompiler.enabled` to true
Spark context Web UI available at http://cloud1:4040
Spark context available as 'sc' (master = yarn, app id = application_1615126461269_0001).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.1
      /_/
         
Using Scala version 2.12.10 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_281)
Type in expressions to have them evaluated.
Type :help for more information.

scala> 2021-03-07 14:16:36,381 ERROR cluster.YarnScheduler: Lost an executor 1 (already removed): Pending loss reason.
2021-03-07 14:16:36,652 WARN cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 1 for reason Container from a bad node: container_1615126461269_0001_01_000002 on host: cloud2. Exit status: 1. Diagnostics: [2021-03-07 14:16:36.393]Exception from container-launch.
Container id: container_1615126461269_0001_01_000002
Exit code: 1

[2021-03-07 14:16:36.434]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
 Plugin only supports 1 gpu per executor
	at com.nvidia.spark.rapids.GpuDeviceManager$.getGPUAddrFromResources(GpuDeviceManager.scala:106)
	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpu(GpuDeviceManager.scala:117)
	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpuAndMemory(GpuDeviceManager.scala:125)
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:145)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:111)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:99)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:164)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:152)
	at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:220)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:221)
	at org.apache.spark.executor.Executor.<init>(Executor.scala:220)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:152)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:203)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-07 14:16:36,011 ERROR util.Utils: Uncaught exception in thread shutdown-hook-0
java.lang.NullPointerException
	at org.apache.spark.executor.Executor.$anonfun$stop$3(Executor.scala:289)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:221)
	at org.apache.spark.executor.Executor.stop(Executor.scala:289)
	at org.apache.spark.executor.Executor.$anonfun$new$2(Executor.scala:74)
	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:214)
	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$2(ShutdownHookManager.scala:188)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1932)
	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$1(ShutdownHookManager.scala:188)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-07 14:16:36,012 INFO storage.DiskBlockManager: Shutdown hook called
2021-03-07 14:16:36,020 INFO util.ShutdownHookManager: Shutdown hook called

3.nvidia-smi
![image](https://user-images.githubusercontent.com/38580039/110243359-0410da00-7f95-11eb-902b-46d037128a0c.png)

4.yarn-site.xml

![image](https://user-images.githubusercontent.com/38580039/110244113-3d971480-7f98-11eb-962d-513972319eb0.png)
![image](https://user-images.githubusercontent.com/38580039/110244127-4daef400-7f98-11eb-98e4-5245bb3ac398.png)

5.container-executor.cfg
![image](https://user-images.githubusercontent.com/38580039/110244148-64554b00-7f98-11eb-87c8-bbb40234ac2c.png)

**Comment by wjxiz1992** [comment]
Hi, could you try to set  `--num-executors 4` ? as I saw you have 2 nodes and each with 2 P100.

**Comment by qinaigonghe** [comment]
Thinks, but I tried --num-executors 4,--num-executors 2 and --num-executors 1 get the same error, I use docker in one machine which have 2 P100.

**Comment by wjxiz1992** [comment]
Can you open the 4040 link and check the Spark executors page? There's a `Show Additional Metrics` and check `Resources`. What are the gpu indexes there?

**Comment by qinaigonghe** [comment]
Hello, I read Resources and find the solution, I choice the different  GPU with cloud1(gpu:0) and cloud2(gpu:1 as gpu:0), then in getGpusResources.sh choice gpu:0 ,and success run two executors. Thank you very much.

**Comment by tgravescs** [comment]
So you shouldn't have to manually change the script.  Ideally you run with isolation, but if you don't do that you can put the gpus in process exclusive mode and use our plugin ExclusiveModeGpuDiscoveryPlugin

please see the section for running on yarn: https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#running-on-yarn

I'm not sure what your setup is so if that is just test env or something changing the script is probably fine but if production environment you may want something better like above so you don't have to hardcode things.

**Comment by qinaigonghe** [comment]
OK, I will try this ,thanks for your suggestions.
