### ISSUE TITLE
[FEA] Let `Scalar Pandas UDF ` support array of struct type.

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#1912]
**Is your feature request related to a problem? Please describe.**
I wish the RAPIDS Accelerator for Apache Spark would support running Scalar Pandas UDF with array type as input, then it can work with `collect_list`, such as the app code as below.

```Python
@pandas_udf(returnType=IntegerType())
def pandas_udf_func(windows: pd.Series) -> pd.Series:
    return pd.Series([1]).repeat(windows.size)

spark.sql("SELECT pandas_udf_func( collect_list( struct(a, b)) ) AS ret_list FROM a_table")
```

**Comment by firestarman** [comment]
Now the cuDF complains the error as below when transfering data to Python.

```
Caused by: ai.rapids.cudf.CudfException: cuDF failure at: /home/liangcail/work/projects/on_github/cudf/cpp/src/interop/to_arrow.cpp:207: Number of field names and number of children doesn't match

	at ai.rapids.cudf.Table.convertCudfToArrowTable(Native Method)
	at ai.rapids.cudf.Table.access$1500(Table.java:46)
	at ai.rapids.cudf.Table$ArrowIPCTableWriter.write(Table.java:1010)
	at org.apache.spark.sql.rapids.execution.python.GpuArrowPythonRunner$$anon$2.$anonfun$writeIteratorToStream$5(GpuArrowEvalPythonExec.scala:455)
	at org.apache.spark.sql.rapids.execution.python.GpuArrowPythonRunner$$anon$2.$anonfun$writeIteratorToStream$5$adapted(GpuArrowEvalPythonExec.scala:453)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
```

**Comment by firestarman** [comment]
Filed an issue https://github.com/rapidsai/cudf/issues/7570 for the exception above.
