### ISSUE TITLE
[BUG] broadcast exchange can fail on 0.4

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1985]
**Describe the bug**
TEsting on databricks we found GpuBroadcastExchange can fail with:

```
21/03/22 19:52:46 WARN SQLExecution: Error executing delta metering
java.lang.IllegalArgumentException: Invalid UUID string: 3320679480415245416_7209383250436260265_04bc82aba7ea4f96acff45a04ded8ea8
	at java.util.UUID.fromString(UUID.java:194)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastExchangeExecBase.$anonfun$_runId$1(GpuBroadcastExchangeExec.scala:271)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastExchangeExecBase.<init>(GpuBroadcastExchangeExec.scala:271)
	at com.nvidia.spark.rapids.shims.spark301db.GpuBroadcastExchangeExec.<init>(GpuBroadcastExchangeExec.scala:28)
	at com.nvidia.spark.rapids.shims.spark301db.Spark301dbShims.getGpuBroadcastExchangeExec(Spark301dbShims.scala:61)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastMeta.convertToGpu(GpuBroadcastExchangeExec.scala:233)
	at org.apache.spark.sql.rapids.execution.GpuBroadcastMeta.convertToGpu(GpuBroadcastExchangeExec.scala:203)
	at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:592)
	at com.nvidia.spark.rapids.shims.spark301db.GpuBroadcastHashJoinMeta.convertToGpu(GpuBroadcastHashJoinExec.scala:68)
	at com.nvidia.spark.rapids.shims.spark301db.GpuBroadcastHashJoinMeta.convertToGpu(GpuBroadcastHashJoinExec.scala:33)
	at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:592)
	at com.nvidia.spark.rapids.GpuOverrides$$anon$147.convertToGpu(GpuOverrides.scala:2490)
	at com.nvidia.spark.rapids.GpuOverrides$$anon$147.convertToGpu(GpuOverrides.scala:2488)
	at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:592)
```

It looks like we pulled in a change from 3.1.1 that got reverted but we missed it.

Our change:
https://github.com/NVIDIA/spark-rapids/commit/b4d996b8f29dcdc89f4da666a16511ac1731dc30

We need to revert this change as well, spark reverted here:
https://github.com/apache/spark/commit/6cd009215074f0ca9eabf91b5ff641bfeee6fdfe

This will affect anyone using the job groups.  API like sc.setJobGroup.  This especially affects databricks because they seem to set the job group all the time, atleast with the interactive notebooks. On databricks just running the following code fails all the time:
df1 = df1.join(F.broadcast(df2), "key")

**Comment by tgravescs** [comment]
we need to add a test for this as well to make sure its caught in normal testing

**Comment by viadea** [comment]
Mini repro in spark-shell:
```
sc.setJobGroup("my job grp", "something")
val df1 = Seq((123)).toDF()
val df2 = Seq((456)).toDF()
df1.join(broadcast(df2), "value").show
```

**Comment by pxLi** [comment]
merged https://github.com/NVIDIA/spark-rapids/pull/1988, and passed databricks and spark standalone integration tests. please reopen if see some issue
