### ISSUE TITLE
[BUG] Intermittent NPE in RapidsBufferCatalog when running test suite

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2074]
**Describe the bug**

I'm pretty consistently seeing around 12 tests fail when running `mvn clean verify -Pspark311tests`. The first failure is in `SortExecSuite` and produces the following stack trace.

```
Cause: java.lang.NullPointerException:
  at com.nvidia.spark.rapids.RapidsBufferCatalog$.addTable(RapidsBufferCatalog.scala:200)
  at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$1(SpillableColumnarBatch.scala:178)
  at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$1$adapted(SpillableColumnarBatch.scala:158)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.SpillableColumnarBatch$.withResource(SpillableColumnarBatch.scala:128)
  at com.nvidia.spark.rapids.SpillableColumnarBatch$.addBatch(SpillableColumnarBatch.scala:158)
  at com.nvidia.spark.rapids.SpillableColumnarBatch$.apply(SpillableColumnarBatch.scala:148)
  at com.nvidia.spark.rapids.GpuCoalesceIterator.saveOnDeck(GpuCoalesceBatches.scala:440)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$2(GpuCoalesceBatches.scala:189)
```

**Steps/Code to reproduce bug**

```
mvn clean verify -Pspark311tests
```

The failing tests work fine when run individually in IntelliJ.

**Expected behavior**

Tests should pass.

**Environment details (please complete the following information)**

Ubuntu. RTX 6000.

**Additional context**

N/A

**Comment by andygrove** [comment]
I added debug logging and see this just prior to the error.

```
GpuDeviceManager.shutdown()
RapidsBufferCatalog.closeImpl()
GpuDeviceManager.initializeMemory()
GpuDeviceManager.initializeMemory() no action required - singletonMemoryInitialized == true
```

Somehow memory is not getting re-initialized in this case. I am continuing with debugging to track down the root cause.

**Comment by andygrove** [comment]
So the issue is that `GpuDeviceManager.shudown` is successfully calling `RapidsBufferCatalog.closeImpl` but the call to `RMM.shutdown` is throwing an exception (which appears to be silently consumed) and therefore we never set `singletonMemoryInitialized` to `false` so the next call to `GpuDeviceManager.initializeMemory` does not call `RapidsBufferCatalog.init`.

**Comment by andygrove** [comment]
I found the root cause, which was that registering a custom SparkListener in the new tests caused the Spark session to leak.

I have put up PR https://github.com/NVIDIA/spark-rapids/pull/2080 to at least improve the error handling for RMM shutdown failures to close this issue.
