### ISSUE TITLE
[BUG] some tests broken in the JDK11  build

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#2091]
**Describe the bug**
some tests fail when the repo is build using JDK11

**Steps/Code to reproduce bug**

```bash 
JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64 mvn clean verify -Dcuda.version=cuda11 -Dtests="test GpuArrowColumnarBatchBuilder retains reference of ArrowBuf"

GpuCoalesceBatchesSuite:
- test GpuArrowColumnarBatchBuilder retains reference of ArrowBuf *** FAILED ***
  java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
  at io.netty.util.internal.PlatformDependent.directBuffer(PlatformDependent.java:490)
  at io.netty.buffer.NettyArrowBuf.getDirectBuffer(NettyArrowBuf.java:243)
  at io.netty.buffer.NettyArrowBuf.nioBuffer(NettyArrowBuf.java:233)
  at io.netty.buffer.NettyArrowBuf.nioBuffer(NettyArrowBuf.java:223)
  at io.netty.buffer.ArrowBuf.nioBuffer(ArrowBuf.java:241)
  at com.nvidia.spark.rapids.shims.spark300.Spark300Shims.getArrowDataBuf(Spark300Shims.scala:486)
  at com.nvidia.spark.rapids.HostColumnarToGpu$.$anonfun$arrowColumnarCopy$1(HostColumnarToGpu.scala:96)
  at com.nvidia.spark.rapids.HostColumnarToGpu$.getBufferAndAddReference$1(HostColumnarToGpu.scala:90)
  at com.nvidia.spark.rapids.HostColumnarToGpu$.arrowColumnarCopy(HostColumnarToGpu.scala:96)
  at com.nvidia.spark.rapids.HostColumnarToGpu.arrowColumnarCopy(HostColumnarToGpu.scala)
```
**Expected behavior**

JDK 11 is supported with Spark 3 [with the caveat](https://spark.apache.org/docs/3.1.1/#downloading), h/t @pxLi 

> For Python 3.9, Arrow optimization and pandas UDFs might not work due to the supported Python versions in Apache Arrow. Please refer to the latest Python Compatibility page. For Java 11, -Dio.netty.tryReflectionSetAccessible=true is required additionally for Apache Arrow library. This prevents java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.(long, int) not available when Apache Arrow uses Netty internally.

**Environment details (please complete the following information)**
 - Environment location: building locally on an Ubuntu 18.04 desktop

**Additional context**
Related to #2088

**Comment by tgravescs** [comment]
fyi - the community is looking at supporting jdk 17 for Spark 3.3 -> https://issues.apache.org/jira/browse/SPARK-33772

**Comment by gerashegalov** [comment]
looks related to https://github.com/netty/netty/issues/8708
