### ISSUE TITLE
[QST] How can we catch regressions sooner?

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2246]
**What is your question?**
It seems that we had a regression sometime before 4/16 that caused benchmarks to fail but we didn't catch this until a week later on 4/23 so we should figure out how to improve our process around this.

**Comment by sameerz** [comment]
I think the question is too vague, to make this more actionable, let's ensure that benchmark failures are reported, including timeouts.  We also need more people who are looking at and can debug the benchmark environment.

**Comment by andygrove** [comment]
Our CI jobs will now fail if any queries fail. The latest run had the following failures:

- q25, q64, q78, q80, q93 failed with `Could not execute broadcast in 1000 secs`.
- q72 failed with `Maximum join output size exceeded`.
- q29, q39a, q67, q74, q95 completed but had task failures.

**Comment by revans2** [comment]
Are all of those queries expected to pass? q72 has a lot of issues for us at high scale factors. I don't see us getting around that for quite a while.  If the tests fail and they are expected to fail are we really going to have people looking at them, or will we just assume that it is the same failure again and get lazy? I know I am very lazy.

**Comment by andygrove** [comment]
The root cause of most of these failures is that Kubernetes is evicting pods. 

```
The node was low on resource: ephemeral-storage. Container ****-kubernetes-executor was using 313152Ki, which exceeds its request of 0.
```
I will work on fixing this.

I looked at q72 and I was mistaken when I said it sometimes worked at SF=1k. It is only the SF=1 benchmarks where q72 is working.

**Comment by andygrove** [comment]
Just to keep track of progress with this:

- We are now specifying ephemeral storage requests/limits in the pods and this resolved a number of issues. However, it appears that we are still using ephemeral storage for shuffles/spills rather than using `spark.local.dir` so this needs more work.
- Even with these changes, we have four queries failing at SF=1k, which are q24a, q24b, q74, and q93. I am removing those from the schedule for now so that we can get back to stable runs each day. This means that the complete list of excluded queries @ SF=1k is now: 'q14a', 'q14b', 'q23a', 'q23b', 'q24a', 'q24b', 'q25', 'q39a', 'q39b', 'q64', 'q72', 'q74', 'q78', 'q80', 'q93', 'q95' and we need to review these to see if any of these can be added back in once the shuffle/spill issue is resolved.
- Also, the data validation job has not been running smoothly and needs further debugging but the next step is to change the schedule so that benchmark and data validation runs happen on alternate days rather than trying to combine them, so the failure of one type of job doesn't impact the other.

**Comment by andygrove** [comment]
The ephemeral storage issues got resolved and we have seen fewer failures on the regular benchmark runs. We have seen q67 succeed with task failures, due to executors becoming unresponsive and getting restarted.

For the next step, we should try running the excluded queries and investigate any remaining failures.

**Comment by wjxiz1992** [comment]
I'm running those problematic queries one by one, still WIP but found _q54_ also failed due to `Could not execute broadcast in 1000 secs`. I'll update again when all information are collected.

**Comment by wjxiz1992** [comment]
Increasing broadcast timeout from 1000 to _3000_ seconds (Andy found the root cause for this issue: https://issues.apache.org/jira/browse/SPARK-33933), some queries can run successfully with _gpu-aqe-on_. (q14a, q93). Not all are tested but the rest are in progress.

**Comment by wjxiz1992** [comment]
Update: 
[q14b] time=2075062
[q23a] time=7249203
[q23b],  'took', '12386376', 'msec.', 'Status:', 'CompletedWithTaskFailures.']
[q24a],   'took', '3045898', 'msec.', 'Status:', 'CompletedWithTaskFailures']
[q24b] time=2655363

So, we can add q14b, q23a, q24b to data validation.
Remain untested: 'q25', 'q39a', 'q39b'. 
Will continue triage after the daily run finished.

**Comment by wjxiz1992** [comment]
@sameerz Yes, there're still failings. 
For new added "broadcast timeout" queries, their CPU output are WIP, as the GPU run could succeed with a 3000 seconds timeout  config, but their CPU run still timeout , so I need to continue increase the value to get CPU output. The queries are: `q23a , q24b`.

For `q23b` and `q24a`, they are "CompletedWithTaskFailures". Currently we haven't check their failure details.

**Comment by wjxiz1992** [comment]
Since individual run for those `CompleteWithTaskFailures` queries cannot reproduce the "failures", I tried to run multiple queries together.  Most queries still cannot reproduce the "CompleteWithTaskFailures" except `q74`. 

error message for q74:
```
[2021-06-08T08:04:18.966Z] org.apache.****.shuffle.MetadataFetchFailedException: Missing an output location for shuffle 58^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.MapOutputTracker$.$anonfun$convertMapStatuses$2(MapOutputTracker.scala:1000)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.MapOutputTracker$.$anonfun$convertMapStatuses$2$adapted(MapOutputTracker.scala:996)^M
[2021-06-08T08:04:18.966Z]      at scala.collection.Iterator.foreach(Iterator.scala:941)^M
[2021-06-08T08:04:18.966Z]      at scala.collection.Iterator.foreach$(Iterator.scala:941)^M
[2021-06-08T08:04:18.966Z]      at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.MapOutputTracker$.convertMapStatuses(MapOutputTracker.scala:996)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.MapOutputTrackerWorker.getMapSizesByExecutorId(MapOutputTracker.scala:821)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.shuffle.sort.SortShuffleManager.getReader(SortShuffleManager.scala:133)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.shuffle.ShuffleManager.getReader(ShuffleManager.scala:63)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.shuffle.ShuffleManager.getReader$(ShuffleManager.scala:57)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.shuffle.sort.SortShuffleManager.getReader(SortShuffleManager.scala:73)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.sql.rapids.execution.ShuffledBatchRDD.compute(ShuffledBatchRDD.scala:172)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.scheduler.Task.run(Task.scala:131)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.util.Utils$.tryWithSafeFinally(Utils.scala:1439)^M
[2021-06-08T08:04:18.966Z]      at org.apache.****.executor.Executor$TaskRunner.run(Executor.scala:500)^M
[2021-06-08T08:04:18.967Z]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)^M

[2021-06-08T08:04:18.967Z] 2021-06-08 07:36:13,796 INFO scheduler.TaskSetManager: task 0.0 in stage 283.0 (TID 5221) failed, but the task will not be re-executed (either because the task failed with a shuffle data fetch failure, so the previous stage needs to be re-run, or because a different copy of the task has already succeeded).^M
[2021-06-08T08:04:18.967Z] 2021-06-08 07:36:13,797 INFO scheduler.DAGScheduler: Marking ShuffleMapStage 283 (getFinalPhysicalPlan at NativeMethodAccessorImpl.java:0) as failed due to a fetch failure from ShuffleMapStage 281 (getFinalPhysicalPlan at NativeMethodAccessorImpl.java:0)^M
[2021-06-08T08:04:18.967Z] 2021-06-08 07:36:13,798 INFO scheduler.DAGScheduler: ShuffleMapStage 283 (getFinalPhysicalPlan at NativeMethodAccessorImpl.java:0) failed in 165.198 s due to org.apache.****.shuffle.MetadataFetchFailedException: Missing an output location for shuffle 58^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.MapOutputTracker$.$anonfun$convertMapStatuses$2(MapOutputTracker.scala:1000)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.MapOutputTracker$.$anonfun$convertMapStatuses$2$adapted(MapOutputTracker.scala:996)^M
[2021-06-08T08:04:18.967Z]      at scala.collection.Iterator.foreach(Iterator.scala:941)^M
[2021-06-08T08:04:18.967Z]      at scala.collection.Iterator.foreach$(Iterator.scala:941)^M
[2021-06-08T08:04:18.967Z]      at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.MapOutputTracker$.convertMapStatuses(MapOutputTracker.scala:996)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.MapOutputTrackerWorker.getMapSizesByExecutorId(MapOutputTracker.scala:821)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.shuffle.sort.SortShuffleManager.getReader(SortShuffleManager.scala:133)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.shuffle.ShuffleManager.getReader(ShuffleManager.scala:63)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.shuffle.ShuffleManager.getReader$(ShuffleManager.scala:57)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.shuffle.sort.SortShuffleManager.getReader(SortShuffleManager.scala:73)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.sql.rapids.execution.ShuffledBatchRDD.compute(ShuffledBatchRDD.scala:172)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.rdd.RDD.iterator(RDD.scala:337)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.scheduler.Task.run(Task.scala:131)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.util.Utils$.tryWithSafeFinally(Utils.scala:1439)^M
[2021-06-08T08:04:18.967Z]      at org.apache.****.executor.Executor$TaskRunner.run(Executor.scala:500)^M
[2021-06-08T08:04:18.967Z]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)^M
[2021-06-08T08:04:18.967Z]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)^M
[2021-06-08T08:04:18.967Z]      at java.lang.Thread.run(Thread.java:748)^M



```


Also, q25 is also found `CompleteWithTaskFailures` due to `The node was low on resource: ephemeral-storage`

**Comment by wjxiz1992** [comment]
Update:

Due to the observation  - "individual run will not produce errors", I separate the data validation queries set into 2 sets. The first set is the "always success" queries. The seconds set contains the "unstable" queries. This action should make daily run more successful.

**Comment by wjxiz1992** [comment]
@sameerz @andygrove  I finished the whole TPC-DS query set with 21.06 release candidate(staging jar). Now we have only one query "q72" with error message `Maximum join output size exceeded` like Andy mentioned above.  

Detailed call stack:

```
04:00:01  2021-06-15 13:43:27,754 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 37.0 (TID 146) (10.233.64.253 executor 2): java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: RMM failure at:/home/jenkins/agent/workspace/jenkins-cudf_nightly-pre_release-github-45-cuda11/cpp/build/_deps/rmm-src/include/rmm/mr/device/detail/arena.hpp:379: Maximum pool size exceeded
04:00:01  	at ai.rapids.cudf.Table.gather(Native Method)
04:00:01  	at ai.rapids.cudf.Table.gather(Table.java:1892)
04:00:01  	at ai.rapids.cudf.Table.gather(Table.java:1874)
04:00:01  	at com.nvidia.****.rapids.JoinGathererImpl.$anonfun$gatherNext$2(JoinGatherer.scala:519)
04:00:01  	at com.nvidia.****.rapids.Arm.withResource(Arm.scala:28)
04:00:01  	at com.nvidia.****.rapids.Arm.withResource$(Arm.scala:26)
04:00:01  	at com.nvidia.****.rapids.JoinGathererImpl.withResource(JoinGatherer.scala:480)
04:00:01  	at com.nvidia.****.rapids.JoinGathererImpl.$anonfun$gatherNext$1(JoinGatherer.scala:518)
04:00:01  	at com.nvidia.****.rapids.Arm.withResource(Arm.scala:28)
04:00:01  	at com.nvidia.****.rapids.Arm.withResource$(Arm.scala:26)
04:00:01  	at com.nvidia.****.rapids.JoinGathererImpl.withResource(JoinGatherer.scala:480)
04:00:01  	at com.nvidia.****.rapids.JoinGathererImpl.gatherNext(JoinGatherer.scala:516)
04:00:01  	at com.nvidia.****.rapids.MultiJoinGather.$anonfun$gatherNext$4(JoinGatherer.scala:588)
04:00:01  	at com.nvidia.****.rapids.Arm.withResource(Arm.scala:28)
04:00:01  	at com.nvidia.****.rapids.Arm.withResource$(Arm.scala:26)
04:00:01  	at com.nvidia.****.rapids.MultiJoinGather.withResource(JoinGatherer.scala:582)
04:00:01  	at com.nvidia.****.rapids.MultiJoinGather.gatherNext(JoinGatherer.scala:587)
04:00:01  	at org.apache.****.sql.rapids.execution.HashJoinIterator.$anonfun$nextCbFromGatherer$2(GpuHashJoin.scala:241)
04:00:01  	at scala.Option.map(Option.scala:230)
04:00:01  	at org.apache.****.sql.rapids.execution.HashJoinIterator.$anonfun$nextCbFromGatherer$1(GpuHashJoin.scala:239)
```

**Comment by andygrove** [comment]
Thanks @wjxiz1992 it is great that we can get all the queries running. If we are changing configuration parameters then it will impact the performance we get and potentially invalidates previous results. Are we changing the parameters just for q72 or for all queries?

**Comment by wjxiz1992** [comment]
@andygrove It's only changed for q72, the rest remains unchanged.

**Comment by andygrove** [comment]
Thanks @wjxiz1992.

I am going to go ahead and close this since CI is passing with all queries, and will get notified in the future if there are any regressions that cause these queries to fail.
