### ISSUE TITLE
[BUG] Close called too many times DeviceMemoryBuffer in JoinGatherer

### ISSUE THREAD

**Issue by rongou** [NVIDIA/spark-rapids#2348]
**Describe the bug**
When running against branch-0.6 (commit fdf585e) on TPC-DS queries, getting this exception.

**Steps/Code to reproduce bug**
Spark shell command:
```
/opt/spark/bin/spark-shell\
 --master spark://127.0.0.1:7077\
 --conf spark.serializer=org.apache.spark.serializer.KryoSerializer\
 --conf spark.kryoserializer.buffer=128m\
 --conf spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistrator\
 --conf spark.locality.wait=0s\
 --conf spark.sql.files.maxPartitionBytes=1g\
 --conf spark.sql.shuffle.partitions=200\
 --conf spark.sql.adaptive.enabled=true\
 --conf spark.shuffle.manager=com.nvidia.spark.rapids.spark311.RapidsShuffleManager\
 --conf spark.shuffle.service.enabled=false\
 --conf spark.sql.broadcastTimeout=600\
 --conf spark.plugins=com.nvidia.spark.SQLPlugin\
 --conf spark.rapids.sql.concurrentGpuTasks=1\
 --conf spark.rapids.memory.pinnedPool.size=8G\
 --conf spark.rapids.sql.batchSizeBytes=1g\
 --conf spark.rapids.memory.gpu.direct.storage.spill.enabled=false\
 --conf spark.rapids.shuffle.transport.enabled=true\
 --conf spark.executorEnv.UCX_TLS=cuda_copy,cuda_ipc,rc,tcp\
 --conf spark.executorEnv.UCX_ERROR_SIGNALS=\
 --conf spark.executorEnv.UCX_MAX_RNDV_RAILS=1\
 --conf spark.executorEnv.UCX_MEMTYPE_CACHE=n\
 --conf spark.rapids.shuffle.maxMetadataSize=512K\
 --conf spark.executorEnv.UCX_RNDV_SCHEME=put_zcopy\
 --conf spark.executorEnv.UCX_RC_RX_QUEUE_LEN=1024\
 --conf spark.executorEnv.UCX_UD_RX_QUEUE_LEN=1024\
 --conf spark.driver.memory=10G\
 --conf spark.driver.maxResultSize=0\
 --conf spark.driver.extraJavaOptions=-Dai.rapids.cudf.nvtx.enabled=false\
 --conf spark.executor.extraClassPath=/opt/rapids/cudf.jar:/opt/rapids/rapids-4-spark.jar\
 --conf spark.executor.extraJavaOptions=-Dai.rapids.cudf.nvtx.enabled=false\
 --conf spark.executor.instances=1\
 --conf spark.executor.cores=24\
 --conf spark.executor.memory=64G\
 --conf spark.executor.resource.gpu.amount=1\
 --conf spark.task.cpus=1\
 --conf spark.task.resource.gpu.amount=0.0416\
 --jars /opt/rapids/cudf.jar,/opt/rapids/rapids-4-spark.jar,/opt/rapids/rapids-4-spark-benchmarks.jar
```
and the query:
```scala
import com.nvidia.spark.rapids.tests._
import com.nvidia.spark.rapids.tests.tpcds._

TpcdsLikeSpark.setupAllParquet(spark, "/opt/data/tpcds-1TB", true)

val benchmark = new BenchmarkRunner(new TpcdsLikeBench(true))
benchmark.collect(spark, "q1", 1)
```

**Expected behavior**
Should not throw exception.

**Environment details (please complete the following information)**
 - Environment location: Standalone

**Additional context**
Stacktrace:
```
java.lang.IllegalStateException: Close called too many times DeviceMemoryBuffer{address=0x7fc58663c900, length=6576072, id=5336}
        at ai.rapids.cudf.MemoryBuffer.close(MemoryBuffer.java:208)
        at com.nvidia.spark.rapids.LazySpillableGatherMapImpl.$anonfun$close$3(JoinGatherer.scala:360)
        at com.nvidia.spark.rapids.LazySpillableGatherMapImpl.$anonfun$close$3$adapted(JoinGatherer.scala:360)
        at scala.Option.foreach(Option.scala:407)
        at com.nvidia.spark.rapids.LazySpillableGatherMapImpl.close(JoinGatherer.scala:360)
        at com.nvidia.spark.rapids.JoinGathererImpl.close(JoinGatherer.scala:574)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.$anonfun$close$2(GpuHashJoin.scala:216)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.$anonfun$close$2$adapted(GpuHashJoin.scala:216)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.close(GpuHashJoin.scala:216)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.$anonfun$new$1(GpuHashJoin.scala:222)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.$anonfun$new$1$adapted(GpuHashJoin.scala:222)
        at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:125)
        at org.apache.spark.TaskContextImpl.$anonfun$markTaskCompleted$1(TaskContextImpl.scala:124)
        at org.apache.spark.TaskContextImpl.$anonfun$markTaskCompleted$1$adapted(TaskContextImpl.scala:124)
        at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1(TaskContextImpl.scala:137)
        at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1$adapted(TaskContextImpl.scala:135)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:135)
        at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
        at org.apache.spark.scheduler.Task.run(Task.scala:141)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by revans2** [comment]
I have been trying to reproduce this locally and I have not been able to do it.  Could you please rerun this, but with 

```
 --conf 'spark.executor.extraJavaOptions=-Dai.rapids.cudf.nvtx.enabled=false -Dai.rapids.refcount.debug=true'\
```

My only guess right now is that we are getting some other type of error, and when the task shuts down due to the other error we end up with this exception, and the exception also happened to close the buffer because it was an error.

**Comment by rongou** [comment]
Does look like it's freeing when catching an exception. I printed the stacktrace from the `Throwable`:
```
java.lang.NullPointerException
        at com.nvidia.spark.rapids.RapidsDeviceMemoryStore.$anonfun$addBuffer$1(RapidsDeviceMemoryStore.scala:154)
        at org.apache.spark.internal.Logging.logDebug(Logging.scala:61)
        at org.apache.spark.internal.Logging.logDebug$(Logging.scala:60)
        at com.nvidia.spark.rapids.RapidsBufferStore.logDebug(RapidsBufferStore.scala:41)
        at com.nvidia.spark.rapids.RapidsDeviceMemoryStore.addBuffer(RapidsDeviceMemoryStore.scala:155)
        at com.nvidia.spark.rapids.RapidsBufferCatalog$.addBuffer(RapidsBufferCatalog.scala:284)
        at com.nvidia.spark.rapids.SpillableBuffer$.apply(SpillableColumnarBatch.scala:276)
        at com.nvidia.spark.rapids.LazySpillableGatherMap.$anonfun$allowSpilling$3(JoinGatherer.scala:325)
        at com.nvidia.spark.rapids.LazySpillableGatherMap.$anonfun$allowSpilling$3$adapted(JoinGatherer.scala:321)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.LazySpillableGatherMap.withResource(JoinGatherer.scala:293)
        at com.nvidia.spark.rapids.LazySpillableGatherMap.allowSpilling(JoinGatherer.scala:321)
        at com.nvidia.spark.rapids.JoinGathererImpl.allowSpilling(JoinGatherer.scala:452)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.$anonfun$nextCbFromGatherer$5(GpuHashJoin.scala:238)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.$anonfun$nextCbFromGatherer$5$adapted(GpuHashJoin.scala:238)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.$anonfun$nextCbFromGatherer$1(GpuHashJoin.scala:238)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.withResource(GpuHashJoin.scala:179)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.nextCbFromGatherer(GpuHashJoin.scala:225)
        at org.apache.spark.sql.rapids.execution.HashJoinIterator.hasNext(GpuHashJoin.scala:358)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:222)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:177)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:221)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:198)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:238)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithKeys_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
It's from a `logDebug` statement. To reproduce this, you can add
```
log4j.logger.com.nvidia.spark.rapids.RapidsDeviceMemoryStore=DEBUG
```
to your `${SPARK_HOME}/conf/log4j.properties` file.

**Comment by jlowe** [comment]
This is caused by `MetaUtils.ignoreTableMeta`.  It's trying to hack up a degenerate table meta but didn't bother creating a `BufferMeta` underneath it.

**Comment by jlowe** [comment]
@rongou I think the patch at #2351 should fix this issue.
