### ISSUE TITLE
[BUG] Alias is different in spark 3.1.0 but our canonicalization code doesn't handle

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2359]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/blame/branch-0.6/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuExec.scala#L265  

That uses Alias() but alias has a different signature  in 3.1.0 - https://github.com/NVIDIA/spark-rapids/commit/cce1ec1ed401bcd7465f5bef9ab28ed38aa5a9a8  

I got an error running the tests on databricks 8.2 about Alias not being present which made me track this down.  Although I only got this error after upmerging to the latest 0.6 branch.  I'm not sure why our existing test on Spark 3.1.1 aren't catching this, need to investigate. It might be we just haven't ever exercised that code for it to fail.

 ```
py4j.protocol.Py4JJavaError: An error occurred while calling o1338.collectToPython.
E                   : java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Alias.<init>(Lorg/apache/spark/sql/catalyst/expressions/Expression;Ljava/lang/String;Lorg/apache/spark/sql/catalyst/expressions/ExprId;Lscala/collection/Seq;Lscala/Option;)V
at com.nvidia.spark.rapids.GpuExec.$anonfun$doCanonicalize$2(GpuExec.scala:265)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:117)
E                   	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:81)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:117)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:128)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$3(QueryPlan.scala:133)
E                   	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
E                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
E                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
E                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
E                   	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
E                   	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
E                   	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:133)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:138)
E                   	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:251)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:138)
E                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize(GpuExec.scala:258)
E                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize$(GpuExec.scala:255)
E                   	at org.apache.spark.sql.execution.python.rapids.GpuAggregateInPandasExec.doCanonicalize(GpuAggregateInPandasExec.scala:71)
E                   	at org.apache.spark.sql.execution.python.rapids.GpuAggregateInPandasExec.doCanonicalize(GpuAggregateInPandasExec.scala:71)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized$lzycompute(QueryPlan.scala:458)
at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized$lzycompute(QueryPlan.scala:458)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized(QueryPlan.scala:457)
E                   	at com.nvidia.spark.rapids.GpuExec.$anonfun$doCanonicalize$1(GpuExec.scala:256)
E                   	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
E                   	at scala.collection.immutable.List.foreach(List.scala:392)
E                   	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
E                   	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
E                   	at scala.collection.immutable.List.map(List.scala:298)
E                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize(GpuExec.scala:256)
E                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize$(GpuExec.scala:255)
E                   	at com.nvidia.spark.rapids.GpuRowToColumnarExec.doCanonicalize(GpuRowToColumnarExec.scala:788)
E                   	at com.nvidia.spark.rapids.GpuRowToColumnarExec.doCanonicalize(GpuRowToColumnarExec.scala:788)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized$lzycompute(QueryPlan.scala:458)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized(QueryPlan.scala:457)
E                   	at com.nvidia.spark.rapids.GpuExec.$anonfun$doCanonicalize$1(GpuExec.scala:256)
E                   	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
E                   	at scala.collection.immutable.List.foreach(List.scala:392)
E                   	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
E                   	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
E                   	at scala.collection.immutable.List.map(List.scala:298)
E                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize(GpuExec.scala:256)
E                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize$(GpuExec.scala:255)
E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.doCanonicalize(GpuShuffleExchangeExec.scala:93)
E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.doCanonicalize(GpuShuffleExchangeExec.scala:93)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized$lzycompute(QueryPlan.scala:458)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized(QueryPlan.scala:457)
E                   	at com.databricks.sql.execution.ReuseExchangeAndSubquery$$anonfun$rewrite$1.applyOrElse(ReuseExchangeAndSubquery.scala:55)
E                   	at com.databricks.sql.execution.ReuseExchangeAndSubquery$$anonfun$rewrite$1.applyOrElse(ReuseExchangeAndSubquery.scala:54)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anon$1.apply(QueryPlan.scala:398)
E                   	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anon$1.apply(QueryPlan.scala:389)
```

FAILED ../../src/main/python/udf_test.py::test_group_aggregate_udf[Byte][IGNORE_ORDER, ALLOW_NON_GPU(PythonUDF,Alias)] - py4j.protocol.Py4JJavaE...
FAILED ../../src/main/python/udf_test.py::test_group_aggregate_udf[Integer][IGNORE_ORDER, ALLOW_NON_GPU(PythonUDF,Alias)] - py4j.protocol.Py4JJa...
FAILED ../../src/main/python/udf_test.py::test_group_aggregate_udf[Long][IGNORE_ORDER, ALLOW_NON_GPU(PythonUDF,Alias)] - py4j.protocol.Py4JJavaE...
FAILED ../../src/main/python/udf_test.py::test_group_aggregate_udf[Short][IGNORE_ORDER, ALLOW_NON_GPU(PythonUDF,Alias)] - py4j.protocol.Py4JJava.

The weird thing is that test allows Alias to be on the cpu:

@allow_non_gpu('PythonUDF', 'Alias')
@pytest.mark.parametrize('data_gen', integral_gens, ids=idfn)
def test_group_aggregate_udf(data_gen):

So I would have thought our regular Spark3.1.1 tests would fail.   It does look like its coming from ReuseExchangeAndSubquery so perhaps that doesn't happen on Apache Spark.  The fix for it is easy since we already have the shim layer, its just calling it.

**Comment by tgravescs** [comment]
I manually tested against apache spark 3.1.1 and the same error happens if you canonicalize a GpuAlias
