### ISSUE TITLE
[BUG] FAILED ../../src/main/python/udf_cudf_test.py::test_window

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#2372]
**Describe the bug**

db_nightly build ID: 169 170

_RAPIDS Accelerator build: {version=0.6.0-SNAPSHOT, user=ubuntu, url=https://github.com/NVIDIA/spark-rapids.git, date=2021-05-08T05:22:20Z, revision=710296c32aa6033a4d25928fe0366a128061ec20, cudf_version=0.20-SNAPSHOT, branch=HEAD}
cudf build: {version=0.20-SNAPSHOT, user=, date=2021-05-08T02:05:06Z, revision=3813d9bed12358b6e29710f1f28ede65f7ff5da8, branch=HEAD}_

```bash
[2021-05-08T06:05:59.088Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2021-05-08T06:05:59.088Z] 
[2021-05-08T06:05:59.088Z] answer = 'xro2229'
[2021-05-08T06:05:59.088Z] gateway_client = <py4j.java_gateway.GatewayClient object at 0x7f3f57235d10>
[2021-05-08T06:05:59.088Z] target_id = 'o2226', name = 'collectToPython'
[2021-05-08T06:05:59.088Z] 
[2021-05-08T06:05:59.088Z]     [94mdef[39;49;00m [92mget_return_value[39;49;00m(answer, gateway_client, target_id=[94mNone[39;49;00m, name=[94mNone[39;49;00m):
[2021-05-08T06:05:59.088Z]         [33m"""Converts an answer received from the Java gateway into a Python object.[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    For example, string representation of integers are converted to Python[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    integer, string representation of objects are converted to JavaObject[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    instances, etc.[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    :param answer: the string returned by the Java gateway[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    :param gateway_client: the gateway client used to communicate with the Java[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m        Gateway. Only necessary if the answer is a reference (e.g., object,[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m        list, map)[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    :param target_id: the name of the object from which the answer comes from[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m        (e.g., *object1* in `object1.hello()`). Optional.[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    :param name: the name of the member from which the answer comes from[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m        (e.g., *hello* in `object1.hello()`). Optional.[39;49;00m
[2021-05-08T06:05:59.088Z]     [33m    """[39;49;00m
[2021-05-08T06:05:59.088Z]         [94mif[39;49;00m is_error(answer)[[94m0[39;49;00m]:
[2021-05-08T06:05:59.088Z]             [94mif[39;49;00m [96mlen[39;49;00m(answer) > [94m1[39;49;00m:
[2021-05-08T06:05:59.088Z]                 [96mtype[39;49;00m = answer[[94m1[39;49;00m]
[2021-05-08T06:05:59.088Z]                 value = OUTPUT_CONVERTER[[96mtype[39;49;00m](answer[[94m2[39;49;00m:], gateway_client)
[2021-05-08T06:05:59.088Z]                 [94mif[39;49;00m answer[[94m1[39;49;00m] == REFERENCE_TYPE:
[2021-05-08T06:05:59.088Z]                     [94mraise[39;49;00m Py4JJavaError(
[2021-05-08T06:05:59.088Z]                         [33m"[39;49;00m[33mAn error occurred while calling [39;49;00m[33m{0}[39;49;00m[33m{1}[39;49;00m[33m{2}[39;49;00m[33m.[39;49;00m[33m\n[39;49;00m[33m"[39;49;00m.
[2021-05-08T06:05:59.088Z] >                       [96mformat[39;49;00m(target_id, [33m"[39;49;00m[33m.[39;49;00m[33m"[39;49;00m, name), value)
[2021-05-08T06:05:59.088Z] [1m[31mE                   py4j.protocol.Py4JJavaError: An error occurred while calling o2226.collectToPython.[0m
[2021-05-08T06:05:59.088Z] [1m[31mE                   : org.apache.spark.sql.catalyst.errors.package$TreeNodeException: makeCopy, tree:[0m
[2021-05-08T06:05:59.088Z] [1m[31mE                   GpuWindowInPandas [id#204L, v#205, _sum_gpu_func(v#205) gpuwindowspecdefinition(id#204L, gpuspecifiedwindowframe(RowFrame, gpuspecialframeboundary(unboundedpreceding$()), gpuspecialframeboundary(unboundedfollowing$()))) AS sum_v#209], [id#204L][0m
[2021-05-08T06:05:59.088Z] [1m[31mE                   +- GpuCoalesceBatches RequireSingleBatch[0m
[2021-05-08T06:05:59.088Z] [1m[31mE                      +- GpuSort [id#204L ASC NULLS FIRST], false, com.nvidia.spark.rapids.OutOfCoreSort$@292cba3d[0m
[2021-05-08T06:05:59.088Z] [1m[31mE                         +- GpuShuffleCoalesce 2147483647[0m
[2021-05-08T06:05:59.088Z] [1m[31mE                            +- GpuColumnarExchange gpuhashpartitioning(id#204L, 12), true, [id=#1000][0m
[2021-05-08T06:05:59.088Z] [1m[31mE                               +- GpuRowToColumnar TargetSize(2147483647)[0m
[2021-05-08T06:05:59.088Z] [1m[31mE                                  +- Scan ExistingRDD[id#204L,v#205][0m
[2021-05-08T06:05:59.088Z] [1m[31mE                   [0m
[2021-05-08T06:05:59.088Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)[0m
[2021-05-08T06:05:59.088Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.TreeNode.makeCopy(TreeNode.scala:473)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.TreeNode.makeCopy(TreeNode.scala:462)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.super$makeCopy(SparkPlan.scala:99)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$makeCopy$1(SparkPlan.scala:99)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.makeCopy(SparkPlan.scala:99)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.makeCopy(SparkPlan.scala:70)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:144)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize(GpuExec.scala:258)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize$(GpuExec.scala:255)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.shims.spark301db.GpuWindowInPandasExec.doCanonicalize(GpuWindowInPandasExec.scala:29)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.shims.spark301db.GpuWindowInPandasExec.doCanonicalize(GpuWindowInPandasExec.scala:29)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized$lzycompute(QueryPlan.scala:462)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized(QueryPlan.scala:461)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuExec.$anonfun$doCanonicalize$1(GpuExec.scala:256)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.immutable.List.foreach(List.scala:392)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.TraversableLike.map(TraversableLike.scala:238)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.immutable.List.map(List.scala:298)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize(GpuExec.scala:256)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuExec.doCanonicalize$(GpuExec.scala:255)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuColumnarToRowExecParent.doCanonicalize(GpuColumnarToRowExec.scala:268)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuColumnarToRowExecParent.doCanonicalize(GpuColumnarToRowExec.scala:268)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized$lzycompute(QueryPlan.scala:462)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.plans.QueryPlan.canonicalized(QueryPlan.scala:461)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuTransitionOverrides.apply(GpuTransitionOverrides.scala:503)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuTransitionOverrides.apply(GpuTransitionOverrides.scala:40)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$2(Columnar.scala:521)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$2$adapted(Columnar.scala:520)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:520)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:482)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:406)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at scala.collection.immutable.List.foldLeft(List.scala:89)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:406)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:139)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:135)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:131)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$writePlans$5(QueryExecution.scala:248)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.plans.QueryPlan$.append(QueryPlan.scala:576)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$writePlans(QueryExecution.scala:248)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:256)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:109)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:249)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:101)[0m
[2021-05-08T06:05:59.089Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:199)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3707)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3495)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at java.lang.reflect.Method.invoke(Method.java:498)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at py4j.Gateway.invoke(Gateway.java:295)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at py4j.GatewayConnection.run(GatewayConnection.java:251)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:748)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   Caused by: java.lang.reflect.InvocationTargetException[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$makeCopy$7(TreeNode.scala:506)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$makeCopy$1(TreeNode.scala:505)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	... 69 more[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   Caused by: java.lang.RuntimeException: Couldn't find none#0L in [id#204L,v#205][0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at scala.sys.package$.error(package.scala:30)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuBindReferences$$anonfun$1.applyOrElse(GpuBoundAttribute.scala:50)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuBindReferences$$anonfun$1.applyOrElse(GpuBoundAttribute.scala:46)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$1(TreeNode.scala:324)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:324)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:313)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuBindReferences$.bindRefInternal(GpuBoundAttribute.scala:46)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuBindReferences$.bindGpuReference(GpuBoundAttribute.scala:62)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuBindReferences$.$anonfun$bindGpuReferences$1(GpuBoundAttribute.scala:72)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at scala.collection.immutable.List.foreach(List.scala:392)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at scala.collection.TraversableLike.map(TraversableLike.scala:238)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at scala.collection.immutable.List.map(List.scala:298)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuBindReferences$.bindGpuReferences(GpuBoundAttribute.scala:72)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	at com.nvidia.spark.rapids.shims.spark301db.GpuWindowInPandasExec.<init>(GpuWindowInPandasExec.scala:66)[0m
[2021-05-08T06:05:59.090Z] [1m[31mE                   	... 77 more[0m
[2021-05-08T06:05:59.090Z] 
[2021-05-08T06:05:59.090Z] [1m[31m/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py[0m:328: Py4JJavaError
```

The abnormal plan generated,
```
16:03:48  :- _sum_gpu_func(none#1)
16:03:48  :  +- none#1: double
16:03:48  +- gpuwindowspecdefinition(none#0L, gpuspecifiedwindowframe(RowFrame, gpuspecialframeboundary(unboundedpreceding$()), gpuspecialframeboundary(unboundedfollowing$())))
16:03:48     :- none#0: bigint
16:03:48     +- gpuspecifiedwindowframe(RowFrame, gpuspecialframeboundary(unboundedpreceding$()), gpuspecialframeboundary(unboundedfollowing$()))
16:03:48        :- gpuspecialframeboundary(unboundedpreceding$())
16:03:48        +- gpuspecialframeboundary(unboundedfollowing$())
```

comparing to normal one,
```
16:03:48  :- _sum_gpu_func(v#205)
16:03:48  :  +- v#205: double
16:03:48  +- gpuwindowspecdefinition(id#204L, gpuspecifiedwindowframe(RowFrame, gpuspecialframeboundary(unboundedpreceding$()), gpuspecialframeboundary(unboundedfollowing$())))
16:03:48     :- id#204: bigint
16:03:48     +- gpuspecifiedwindowframe(RowFrame, gpuspecialframeboundary(unboundedpreceding$()), gpuspecialframeboundary(unboundedfollowing$()))
16:03:48        :- gpuspecialframeboundary(unboundedpreceding$())
16:03:48        +- gpuspecialframeboundary(unboundedfollowing$())
```

**Steps/Code to reproduce bug**
run udf_cudf_test in databricks env

**Expected behavior**
passed the test

**Environment details (please complete the following information)**
 - Environment location: databricks 301

**Additional context**
spark standalone works well

**Comment by tgravescs** [comment]
Note there is a new Databricks 8.2 shim layer as well and this test was failing there as well.
