### ISSUE TITLE
[BUG]Exception: Type conversion is not allowed from LIST(STRUCT(STRING,STRING)) to ArrayType(MapType(StringType,StringType,true),true)

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#2374]
**Describe the bug**
When i test some query contains Hive-UDF JsonToArray, it occurs error below:
```
org.apache.spark.SparkException: Failed to execute user defined function (JsonToArray: (string) => array<map<string,string>>)
                    at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$4(GpuUserDefinedFunction.scala:71)
                    at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
                    at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
                    at org.apache.spark.sql.hive.rapids.GpuHiveSimpleUDF.withResource(hiveUDFs.scala:44)
                    at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$2(GpuUserDefinedFunction.scala:59)
                    at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:37)
                    at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:35)
                    at org.apache.spark.sql.hive.rapids.GpuHiveSimpleUDF.withResource(hiveUDFs.scala:44)
                    at com.nvidia.spark.rapids.GpuUserDefinedFunction.columnarEval(GpuUserDefinedFunction.scala:57)
                    at com.nvidia.spark.rapids.GpuUserDefinedFunction.columnarEval$(GpuUserDefinedFunction.scala:56)
                    at org.apache.spark.sql.hive.rapids.GpuHiveSimpleUDF.columnarEval(hiveUDFs.scala:44)
                    at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:36)
                    at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:117)
                    at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:36)
                    at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:107)
                    at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:36)
                    at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:50)
                    at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:162)
                    at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:159)
                    at scala.collection.immutable.List.foreach(List.scala:392)
                    at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:159)
                    at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:194)
                    at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:49)
                    at com.nvidia.spark.rapids.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:40)
                    at com.nvidia.spark.rapids.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:96)
                    at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
                    at com.nvidia.spark.rapids.GpuExpandIterator.next(GpuExpandExec.scala:131)
                    at com.nvidia.spark.rapids.GpuExpandIterator.next(GpuExpandExec.scala:106)
                    at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:184)
                    at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:208)
                    at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
                    at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
                    at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
                    at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
                    at com.nvidia.spark.rapids.RowToColumnarIterator.hasNext(GpuRowToColumnarExec.scala:564)
                    at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$doExecuteColumnar$1(aggregate.scala:408)
                    at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
                    at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
                    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
                    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
                    at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
                    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
                    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
                    at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
                    at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
                    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
                    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
                    at org.apache.spark.scheduler.Task.run(Task.scala:127)
                    at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:450)
                    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1386)
                    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:453)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Type conversion is not allowed from LIST(STRUCT(STRING,STRING)) to ArrayType(MapType(StringType,StringType,true),true)
                    at com.nvidia.spark.rapids.GpuColumnVector.fromChecked(GpuColumnVector.java:766)
                    at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$5(GpuUserDefinedFunction.scala:66)
                    at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:76)
                    at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:74)
                    at org.apache.spark.sql.hive.rapids.GpuHiveSimpleUDF.closeOnExcept(hiveUDFs.scala:44)
                    at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$4(GpuUserDefinedFunction.scala:61)
```

**Comment by jlowe** [comment]
`ArrayType(MapType(StringType,StringType,true),true)` maps to `LIST(LIST(STRUCT(STRING,STRING)))`.  I'll put up a PR so the message not only shows the cudf type being returned but also the cudf type expected, so it's clear how the Spark type is mapping to a cudf type.
