### ISSUE TITLE
[BUG] NPE when running mapInPandas Pandas UDF in 0.5GA

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2421]
**Describe the bug**
NPE when running mapInPandas Pandas UDF in 0.5GA. 
The same code works fine in 0.4.1GA if I just swap the jars.
Note: All other pandas UDF tests work fine on 0.5GA.

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

```
import pyspark
from pyspark.sql.functions import udf
from pyspark.sql.functions import col, count, rand, collect_list, explode, struct, count, lit
from pyspark.sql.functions import pandas_udf
from pyspark.sql.types import *
from pyspark.sql import Row,SparkSession
import pandas as pd
import numpy as np
import cudf

spark=SparkSession \
  .builder \
  .appName("Pandas-UDF-Test") \
  .config("spark.rapids.sql.python.gpu.enabled","true") \
  .config("spark.rapids.memory.gpu.allocFraction","0.5") \
  .config("spark.rapids.python.concurrentPythonWorkers","2") \
  .config("spark.rapids.python.memory.gpu.allocFraction","0.1") \
  .config("spark.rapids.python.memory.gpu.maxAllocFraction","0.1") \
  .config("spark.sql.execution.arrow.pyspark.enabled","true") \
  .config("spark.rapids.sql.exec.ArrowEvalPythonExec","true") \
  .config("spark.rapids.sql.exec.MapInPandasExec","true") \
  .config("spark.rapids.sql.exec.FlatMapGroupsInPandasExec","true") \
  .config("spark.rapids.sql.exec.AggregateInPandasExec","true") \
  .config("spark.rapids.sql.exec.FlatMapCoGroupsInPandasExec","true") \
  .config("spark.rapids.sql.exec.WindowInPandasExec","true") \
  .getOrCreate()

df = spark.createDataFrame([(1, 21), (2, 30)], ("id", "age"))

def filter_func(iterator):
    for pdf in iterator:
        yield pdf[pdf.id == 1]

out = df.mapInPandas(filter_func, schema=df.schema)
out.printSchema()
out.show()

```

Failed with below stacktrace:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o116.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 15 in stage 0.0 failed 4 times, most recent failure: Lost task 15.3 in stage 0.0 (TID 18) (111.111.111.111 executor 0): java.lang.NullPointerException
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.$anonfun$partNextBatch$2(GpuShuffleExchangeExec.scala:240)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.$anonfun$partNextBatch$2$adapted(GpuShuffleExchangeExec.scala:239)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:239)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:249)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

if we change `show()` to `collect()`, then above code works fine.
```
>>> out.collect()
[Row(id=1, age=21)]
>>> out.explain()
== Physical Plan ==
GpuColumnarToRow false
+- GpuMapInPandas filter_func(id#0L, age#1L), [id#5L, age#6L]
   +- GpuRowToColumnar TargetSize(2147483647)
      +- *(1) Scan ExistingRDD[id#0L,age#1L]
```

**Expected behavior**
The sample pyspark code should work fine.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue
Spark 3.1.1 standalone cluster
Rapids+cudf 0.5GA release
Spark configuration please refer to above code.

**Additional context**

**Comment by viadea** [comment]
Tested using @firestarman 's built 0.5 snapshot jar, and it fixes the issue.

**Comment by firestarman** [comment]
> Tested using @firestarman 's built 0.5 snapshot jar, and it fixes the issue.

Thanks for the verification, made a PR here https://github.com/NVIDIA/spark-rapids/pull/2447

**Comment by firestarman** [comment]
I marked the PR as draft, because I am not sure whether it is reproduceable on branch-21.06 (it was 0.6 before).

**Comment by viadea** [comment]
@firestarman I can reproduce the same issue using the latest 21.06 for both rapids and cudf.

- rapids-4-spark_2.12-0.6.0-SNAPSHOT-20210519.jar (I built based on current default branch)
- cudf-21.06-20210519.143823-3-cuda11.jar

**Comment by firestarman** [comment]
Thanks @viadea for the verification on branch-21.06.
