### ISSUE TITLE
[BUG] test_union_struct_missing_children[(Struct(not_null) failed in databricks310 and spark 311

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#2427]
**Describe the bug**
rapids_databricks_nightly ID 3,4
spark 3.1.1 integration tests ID 173

test_union_struct_missing_children will fail after 3.1.1 (inclusive)

**Steps/Code to reproduce bug**
``` bash
cd spark-rapids/integration_tests
export SPARK_HOME=3.1.1_VERSION
export TEST=test_union_struct_missing_children
./run_pyspark_from_build.sh
```
FAILED ../../src/main/python/repart_test.py::test_union_struct_missing_children[(Struct(not_null)(['child0', Decimal(7,2)]), Struct(not_null)(['child1', Integer]))]

```bash
[2021-05-16T06:29:57.480Z] answer = 'xro243542'
[2021-05-16T06:29:57.480Z] gateway_client = <py4j.java_gateway.GatewayClient object at 0x7f26c6b11940>
[2021-05-16T06:29:57.480Z] target_id = 'o243539', name = 'collectToPython'
[2021-05-16T06:29:57.480Z] 
[2021-05-16T06:29:57.480Z]     [94mdef[39;49;00m [92mget_return_value[39;49;00m(answer, gateway_client, target_id=[94mNone[39;49;00m, name=[94mNone[39;49;00m):
[2021-05-16T06:29:57.480Z]         [33m"""Converts an answer received from the Java gateway into a Python object.[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m    For example, string representation of integers are converted to Python[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m    integer, string representation of objects are converted to JavaObject[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m    instances, etc.[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m    :param answer: the string returned by the Java gateway[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m    :param gateway_client: the gateway client used to communicate with the Java[39;49;00m
[2021-05-16T06:29:57.480Z]     [33m        Gateway. Only necessary if the answer is a reference (e.g., object,[39;49;00m
[2021-05-16T06:29:57.481Z]     [33m        list, map)[39;49;00m
[2021-05-16T06:29:57.481Z]     [33m    :param target_id: the name of the object from which the answer comes from[39;49;00m
[2021-05-16T06:29:57.481Z]     [33m        (e.g., *object1* in `object1.hello()`). Optional.[39;49;00m
[2021-05-16T06:29:57.481Z]     [33m    :param name: the name of the member from which the answer comes from[39;49;00m
[2021-05-16T06:29:57.481Z]     [33m        (e.g., *hello* in `object1.hello()`). Optional.[39;49;00m
[2021-05-16T06:29:57.481Z]     [33m    """[39;49;00m
[2021-05-16T06:29:57.481Z]         [94mif[39;49;00m is_error(answer)[[94m0[39;49;00m]:
[2021-05-16T06:29:57.481Z]             [94mif[39;49;00m [96mlen[39;49;00m(answer) > [94m1[39;49;00m:
[2021-05-16T06:29:57.481Z]                 [96mtype[39;49;00m = answer[[94m1[39;49;00m]
[2021-05-16T06:29:57.481Z]                 value = OUTPUT_CONVERTER[[96mtype[39;49;00m](answer[[94m2[39;49;00m:], gateway_client)
[2021-05-16T06:29:57.481Z]                 [94mif[39;49;00m answer[[94m1[39;49;00m] == REFERENCE_TYPE:
[2021-05-16T06:29:57.481Z] >                   [94mraise[39;49;00m Py4JJavaError(
[2021-05-16T06:29:57.481Z]                         [33m"[39;49;00m[33mAn error occurred while calling [39;49;00m[33m{0}[39;49;00m[33m{1}[39;49;00m[33m{2}[39;49;00m[33m.[39;49;00m[33m\n[39;49;00m[33m"[39;49;00m.
[2021-05-16T06:29:57.481Z]                         [96mformat[39;49;00m(target_id, [33m"[39;49;00m[33m.[39;49;00m[33m"[39;49;00m, name), value)
[2021-05-16T06:29:57.481Z] [1m[31mE                   py4j.protocol.Py4JJavaError: An error occurred while calling o243539.collectToPython.[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   : org.apache.spark.SparkException: Task not serializable[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:416)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:406)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.SparkContext.clean(SparkContext.scala:2723)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDD.$anonfun$map$1(RDD.scala:427)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:125)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDD.withScope(RDD.scala:419)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDD.map(RDD.scala:426)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuUnionExec.doExecuteColumnar(basicPhysicalOperators.scala:398)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:223)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:240)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:236)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:219)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuColumnarToRowExecParent.doExecute(GpuColumnarToRowExec.scala:295)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:196)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:240)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:236)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:192)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:79)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:88)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:496)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at scala.Option.getOrElse(Option.scala:189)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:495)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:399)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:374)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:389)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3577)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3789)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:126)[0m
[2021-05-16T06:29:57.481Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:267)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:104)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:852)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:217)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3787)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3575)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at java.lang.reflect.Method.invoke(Method.java:498)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at py4j.Gateway.invoke(Gateway.java:295)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at py4j.GatewayConnection.run(GatewayConnection.java:251)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:748)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   Caused by: java.io.NotSerializableException: com.nvidia.spark.rapids.GpuScalar[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   Serialization stack:[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object not serializable (class: com.nvidia.spark.rapids.GpuScalar, value: com.nvidia.spark.rapids.GpuScalar@1037ee8f)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- writeObject data (class: scala.collection.immutable.List$SerializationProxy)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class scala.collection.immutable.List$SerializationProxy, scala.collection.immutable.List$SerializationProxy@6fc3d95c)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- writeReplace data (class: scala.collection.immutable.List$SerializationProxy)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class scala.collection.immutable.$colon$colon, List(com.nvidia.spark.rapids.GpuScalar@1037ee8f, com.nvidia.spark.rapids.GpuScalar@65f1c94a))[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- field (class: org.apache.spark.sql.rapids.GpuCreateNamedStruct, name: names, type: class scala.collection.immutable.List)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class org.apache.spark.sql.rapids.GpuCreateNamedStruct, named_struct(child0, a#136604.child0, child1, null))[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- field (class: com.nvidia.spark.rapids.GpuAlias, name: child, type: class org.apache.spark.sql.catalyst.expressions.Expression)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class com.nvidia.spark.rapids.GpuAlias, named_struct(child0, a#136604.child0, child1, null) AS a#136614)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- writeObject data (class: scala.collection.immutable.List$SerializationProxy)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class scala.collection.immutable.List$SerializationProxy, scala.collection.immutable.List$SerializationProxy@73b95f9e)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- writeReplace data (class: scala.collection.immutable.List$SerializationProxy)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class scala.collection.immutable.$colon$colon, List(named_struct(child0, a#136604.child0, child1, null) AS a#136614, named_struct(child0, b#136605.child0, child1, null) AS b#136615))[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- field (class: com.nvidia.spark.rapids.GpuProjectExec, name: projectList, type: class scala.collection.immutable.List)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class com.nvidia.spark.rapids.GpuProjectExec, GpuProject [named_struct(child0, a#136604.child0, child1, null) AS a#136614, named_struct(child0, b#136605.child0, child1, null) AS b#136615][0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   +- GpuRowToColumnar TargetSize(2147483647)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                      +- *(1) Scan ExistingRDD[a#136604,b#136605][0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   )[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- writeObject data (class: scala.collection.immutable.List$SerializationProxy)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class scala.collection.immutable.List$SerializationProxy, scala.collection.immutable.List$SerializationProxy@117574f)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- writeReplace data (class: scala.collection.immutable.List$SerializationProxy)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   	- object (class scala.collection.immutable.$colon$colon, List(GpuProject [named_struct(child0, a#136604.child0, child1, null) AS a#136614, named_struct(child0, b#136605.child0, child1, null) AS b#136615][0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   +- GpuRowToColumnar TargetSize(2147483647)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                      +- *(1) Scan ExistingRDD[a#136604,b#136605][0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   , GpuProject [named_struct(child0, null, child1, a#136608.child1) AS a#136612, named_struct(child0, null, child1, b#136609.child1) AS b#136613][0m
[2021-05-16T06:29:57.482Z] [1m[31mE                   +- GpuRowToColumnar TargetSize(2147483647)[0m
[2021-05-16T06:29:57.482Z] [1m[31mE                      +- *(2) Scan ExistingRDD[a#136608,b#136609][0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   ))[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- field (class: com.nvidia.spark.rapids.GpuUnionExec, name: children, type: interface scala.collection.Seq)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- object (class com.nvidia.spark.rapids.GpuUnionExec, GpuUnion[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   :- GpuProject [named_struct(child0, a#136604.child0, child1, null) AS a#136614, named_struct(child0, b#136605.child0, child1, null) AS b#136615][0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   :  +- GpuRowToColumnar TargetSize(2147483647)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   :     +- *(1) Scan ExistingRDD[a#136604,b#136605][0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   +- GpuProject [named_struct(child0, null, child1, a#136608.child1) AS a#136612, named_struct(child0, null, child1, b#136609.child1) AS b#136613][0m
[2021-05-16T06:29:57.483Z] [1m[31mE                      +- GpuRowToColumnar TargetSize(2147483647)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                         +- *(2) Scan ExistingRDD[a#136608,b#136609][0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   )[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- element of array (index: 0)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- array (class [Ljava.lang.Object;, size 4)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class com.nvidia.spark.rapids.GpuUnionExec, functionalInterfaceMethod=scala/Function1.apply:(Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic com/nvidia/spark/rapids/GpuUnionExec.$anonfun$doExecuteColumnar$5:(Lcom/nvidia/spark/rapids/GpuUnionExec;Lcom/nvidia/spark/rapids/GpuMetric;Lcom/nvidia/spark/rapids/GpuMetric;Lcom/nvidia/spark/rapids/GpuMetric;Lorg/apache/spark/sql/vectorized/ColumnarBatch;)Lorg/apache/spark/sql/vectorized/ColumnarBatch;, instantiatedMethodType=(Lorg/apache/spark/sql/vectorized/ColumnarBatch;)Lorg/apache/spark/sql/vectorized/ColumnarBatch;, numCaptured=4])[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- writeReplace data (class: java.lang.invoke.SerializedLambda)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	- object (class com.nvidia.spark.rapids.GpuUnionExec$$Lambda$8566/14039391, com.nvidia.spark.rapids.GpuUnionExec$$Lambda$8566/14039391@455ccb)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:41)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:413)[0m
[2021-05-16T06:29:57.483Z] [1m[31mE                   	... 51 more[0m
[2021-05-16T06:29:57.483Z] 
```

**Expected behavior**
Passed tests

**Environment details (please complete the following information)**
 - Environment location: databrick310 and spark standalone 311

**Comment by sameerz** [comment]
This fails on Spark 3.1.1, regardless of environment.
