### ISSUE TITLE
[BUG] GpuCreateNamedStruct serializable issue

### ISSUE THREAD

**Issue by wbo4958** [NVIDIA/spark-rapids#2443]
**Describe the bug**

test_union_struct_missing_children will fail after 3.1.1 (inclusive)

**Steps/Code to reproduce bug**
``` bash
cd spark-rapids/integration_tests
export SPARK_HOME=3.1.1_VERSION
export TEST=test_union_struct_missing_children
./run_pyspark_from_build.sh
```

**Failure info**
```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o480.collectToPython.
E                   : org.apache.spark.SparkException: Task not serializable
E                   	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:416)
E                   	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:406)
E                   	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
E                   	at org.apache.spark.SparkContext.clean(SparkContext.scala:2465)
E                   	at org.apache.spark.rdd.RDD.$anonfun$map$1(RDD.scala:422)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
E                   	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
E                   	at org.apache.spark.rdd.RDD.map(RDD.scala:421)
E                   	at com.nvidia.spark.rapids.GpuUnionExec.doExecuteColumnar(basicPhysicalOperators.scala:398)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:207)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:203)
E                   	at com.nvidia.spark.rapids.GpuColumnarToRowExecParent.doExecute(GpuColumnarToRowExec.scala:295)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
E                   	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
E                   	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:321)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:387)
E                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3519)
E                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
E                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
E                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3516)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Thread.java:748)
E                   Caused by: java.io.NotSerializableException: com.nvidia.spark.rapids.GpuScalar
E                   Serialization stack:
E                   	- object not serializable (class: com.nvidia.spark.rapids.GpuScalar, value: com.nvidia.spark.rapids.GpuScalar@5d1d4fe7)
E                   	- writeObject data (class: scala.collection.immutable.List$SerializationProxy)
E                   	- object (class scala.collection.immutable.List$SerializationProxy, scala.collection.immutable.List$SerializationProxy@24526353)
E                   	- writeReplace data (class: scala.collection.immutable.List$SerializationProxy)
E                   	- object (class scala.collection.immutable.$colon$colon, List(com.nvidia.spark.rapids.GpuScalar@5d1d4fe7, com.nvidia.spark.rapids.GpuScalar@739a1ff6))
E                   	- field (class: org.apache.spark.sql.rapids.GpuCreateNamedStruct, name: names, type: class scala.collection.immutable.List)
E                   	- object (class org.apache.spark.sql.rapids.GpuCreateNamedStruct, named_struct(child0, a#42.child0, child1, null))
E                   	- field (class: com.nvidia.spark.rapids.GpuAlias, name: child, type: class org.apache.spark.sql.catalyst.expressions.Expression)
E                   	- object (class com.nvidia.spark.rapids.GpuAlias, named_struct(child0, a#42.child0, child1, null) AS a#52)
E                   	- writeObject data (class: scala.collection.immutable.List$SerializationProxy)
E                   	- object (class scala.collection.immutable.List$SerializationProxy, scala.collection.immutable.List$SerializationProxy@584753e9)
E                   	- writeReplace data (class: scala.collection.immutable.List$SerializationProxy)
E                   	- object (class scala.collection.immutable.$colon$colon, List(named_struct(child0, a#42.child0, child1, null) AS a#52, named_struct(child0, b#43.child0, child1, null) AS b#53))
E                   	- field (class: com.nvidia.spark.rapids.GpuProjectExec, name: projectList, type: class scala.collection.immutable.List)
E                   	- object (class com.nvidia.spark.rapids.GpuProjectExec, GpuProject [named_struct(child0, a#42.child0, child1, null) AS a#52, named_struct(child0, b#43.child0, child1, null) AS b#53]
E                   +- GpuRowToColumnar TargetSize(2147483647)
E                      +- *(1) Scan ExistingRDD[a#42,b#43]
E                   )
E                   	- writeObject data (class: scala.collection.immutable.List$SerializationProxy)
E                   	- object (class scala.collection.immutable.List$SerializationProxy, scala.collection.immutable.List$SerializationProxy@2e190f6e)
E                   	- writeReplace data (class: scala.collection.immutable.List$SerializationProxy)
E                   	- object (class scala.collection.immutable.$colon$colon, List(GpuProject [named_struct(child0, a#42.child0, child1, null) AS a#52, named_struct(child0, b#43.child0, child1, null) AS b#53]
E                   +- GpuRowToColumnar TargetSize(2147483647)
E                      +- *(1) Scan ExistingRDD[a#42,b#43]
E                   , GpuProject [named_struct(child0, null, child1, a#46.child1) AS a#50, named_struct(child0, null, child1, b#47.child1) AS b#51]
E                   +- GpuRowToColumnar TargetSize(2147483647)
E                      +- *(2) Scan ExistingRDD[a#46,b#47]
E                   ))
E                   	- field (class: com.nvidia.spark.rapids.GpuUnionExec, name: children, type: interface scala.collection.Seq)
E                   	- object (class com.nvidia.spark.rapids.GpuUnionExec, GpuUnion
E                   :- GpuProject [named_struct(child0, a#42.child0, child1, null) AS a#52, named_struct(child0, b#43.child0, child1, null) AS b#53]
E                   :  +- GpuRowToColumnar TargetSize(2147483647)
E                   :     +- *(1) Scan ExistingRDD[a#42,b#43]
E                   +- GpuProject [named_struct(child0, null, child1, a#46.child1) AS a#50, named_struct(child0, null, child1, b#47.child1) AS b#51]
E                      +- GpuRowToColumnar TargetSize(2147483647)
E                         +- *(2) Scan ExistingRDD[a#46,b#47]
E                   )
E                   	- element of array (index: 0)
E                   	- array (class [Ljava.lang.Object;, size 4)
E                   	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
E                   	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class com.nvidia.spark.rapids.GpuUnionExec, functionalInterfaceMethod=scala/Function1.apply:(Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic com/nvidia/spark/rapids/GpuUnionExec.$anonfun$doExecuteColumnar$5:(Lcom/nvidia/spark/rapids/GpuUnionExec;Lcom/nvidia/spark/rapids/GpuMetric;Lcom/nvidia/spark/rapids/GpuMetric;Lcom/nvidia/spark/rapids/GpuMetric;Lorg/apache/spark/sql/vectorized/ColumnarBatch;)Lorg/apache/spark/sql/vectorized/ColumnarBatch;, instantiatedMethodType=(Lorg/apache/spark/sql/vectorized/ColumnarBatch;)Lorg/apache/spark/sql/vectorized/ColumnarBatch;, numCaptured=4])
E                   	- writeReplace data (class: java.lang.invoke.SerializedLambda)
E                   	- object (class com.nvidia.spark.rapids.GpuUnionExec$$Lambda$3289/382757335, com.nvidia.spark.rapids.GpuUnionExec$$Lambda$3289/382757335@341005f4)
E                   	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:41)
E                   	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
E                   	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
E                   	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:413)
E                   	... 42 more

```

**Comment by jlowe** [comment]
Is this a duplicate of #2427?

**Comment by wbo4958** [comment]
> Is this a duplicate of #2427?

Oh, Yeah, Just saw it. I will duplicate it to https://github.com/NVIDIA/spark-rapids/issues/2427
