### ISSUE TITLE
[BUG] GpuExec failed to find metric totalTime in databricks env

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#2497]
**Describe the bug**

Integration tests failed in databricks env.
This error is related to https://github.com/NVIDIA/spark-rapids/pull/2462, 
```
Caused by: java.util.NoSuchElementException: key not found: totalTime[0m
	at scala.collection.MapLike.default(MapLike.scala:235)[0m
	at scala.collection.MapLike.default$(MapLike.scala:234)[0m
	at scala.collection.AbstractMap.default(Map.scala:63)[0m
	at scala.collection.MapLike.apply(MapLike.scala:144)[0m
	at scala.collection.MapLike.apply$(MapLike.scala:143)[0m
	at scala.collection.AbstractMap.apply(Map.scala:63)[0m
	at com.nvidia.spark.rapids.GpuExec.gpuLongMetric(GpuExec.scala:229)[0m
	at com.nvidia.spark.rapids.GpuExec.gpuLongMetric$(GpuExec.scala:229)[0m
	at com.nvidia.spark.rapids.shims.spark310db.GpuBroadcastHashJoinExec.gpuLongMetric(GpuBroadcastHashJoinExec.scala:84)[0m
	at com.nvidia.spark.rapids.shims.spark310db.GpuBroadcastHashJoinExec.doExecuteColumnar(GpuBroadcastHashJoinExec.scala:135)[0m
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:223)[0m
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:240)[0m
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)[0m
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:236)[0m
	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:219)[0m
	at com.nvidia.spark.rapids.GpuProjectExec.doExecuteColumnar(basicPhysicalOperators.scala:115)[0m
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:223)[0m
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:240)[0m
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)[0m
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:236)[0m
	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:219)[0m
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.inputBatchRDD$lzycompute(GpuShuffleExchangeExec.scala:133)[0m
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.inputBatchRDD(GpuShuffleExchangeExec.scala:133)[0m
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.shuffleDependencyColumnar$lzycompute(GpuShuffleExchangeExec.scala:143)[0m
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.shuffleDependencyColumnar(GpuShuffleExchangeExec.scala:141)[0m
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.$anonfun$doExecuteColumnar$1(GpuShuffleExchangeExec.scala:165)[0m
	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)[0m
	... 85 more[0m
```

**Comment by andygrove** [comment]
Thanks @pxLi I'm looking at this now.
