### ISSUE TITLE
[BUG] cast can throw NPE

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#2680]
**Describe the bug**
When I try to run an user query on GPU, there is a NullPointerException.

```
java.lang.NullPointerException
at com.nvidia.spark.rapids.GpuCast.castStringToInts(GpuCast.scala:674)
at com.nvidia.spark.rapids.GpuCast.$anonfun$recursiveDoColumnar$39(GpuCast.scala:404)
at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
at com.nvidia.spark.rapids.GpuUnaryExpression.withResource(GpuExpressions.scala:156)
```

**Comment by nvliyuan** [comment]
It happened in V21.06.0

**Comment by revans2** [comment]
From looking at the stack trace it appears that if we are casting one array to another and the input array has no data column in it (because all the values were null or because all of the arrays were empty), then we can get a null pointer exception.
