### ISSUE TITLE
Needed to add `--conf spark.driver.extraClassPath=` 

### ISSUE THREAD

**Issue by satindern** [NVIDIA/spark-rapids#269]
The Documentation says to install for example the _cudf-0.15-SNAPSHOT-cuda10-1.jar_ and _rapids-4-spark_2.12-0.1.0.jar_ into the `/opt/sparkRapidsPlugin` directory.
Then export 
```
export SPARK_RAPIDS_DIR=/opt/sparkRapidsPlugin
export SPARK_CUDF_JAR=${SPARK_RAPIDS_DIR}/cudf-0.15-SNAPSHOT-cuda10-1.jar
export SPARK_RAPIDS_PLUGIN_JAR=${SPARK_RAPIDS_DIR}/rapids-4-spark_2.12-0.2.0-SNAPSHOT.jar
```

Under https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/docs/getting-started.md#spark-gpu-scheduling-overview, you discuss the need to specify `--conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh`

however I also needed to include `--conf spark.driver.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR}`

@krajendrannv @sameerz

**Comment by tgravescs** [comment]
so there are cluster manager specific sections and unfortunately need slightly different configs for them. I'm assuming you are running in standalone mode?  Were you running interactive mode (spark-shell or pyspark) or spark-submit in cluster mode?

What error did you get without specifying that? You definitely need the spark.executor.extraClassPath but didn't think you needed the driver one but perhaps something has changed there.

**Comment by satindern** [comment]
Yes this was in standalone mode. I no longer have the error.
I either had to copy/move _cudf-0.15-SNAPSHOT-cuda10-1.jar_ and _rapids-4-spark_2.12-0.1.0.jar_ into /opt/spark/spark-3.0.1-SNAPSHOT-bin-hadoop3/jars or use the additional `--conf spark.driver.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR}`

**Comment by tgravescs** [comment]
ok thanks, we should reproduce and investigate

**Comment by tgravescs** [comment]
I was testing 0.1 release with standalone mode and I also had to specify the driver extra classpath to get this to work. The issue is the plugin we are trying to load.

20/08/11 08:33:20 ERROR SparkContext: Error initializing SparkContext.
java.lang.ClassNotFoundException: com.nvidia.spark.SQLPlugin
        at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:72)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:206)
        at org.apache.spark.util.Utils$.$anonfun$loadExtensions$1(Utils.scala:2696)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2694)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:160)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:146)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:525)
