### ISSUE TITLE
[BUG] nightly test failed with lists: `testStringReplaceWithBackrefs`

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2750]
```
08:25:40  [ERROR] testStringReplaceWithBackrefs  Time elapsed: 0.005 s  <<< FAILURE!
08:25:40  org.opentest4j.AssertionFailedError: Column unnamed Row 0 ==> array lengths differ, expected: <14> but was: <19>
08:25:40  	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
08:25:40  	at org.junit.jupiter.api.AssertArrayEquals.assertArraysHaveSameLength(AssertArrayEquals.java:423)
08:25:40  	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:208)
08:25:40  	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:66)
08:25:40  	at org.junit.jupiter.api.Assertions.assertArrayEquals(Assertions.java:1217)
08:25:40  	at ai.rapids.cudf.TableTest.assertPartialColumnsAreEqual(TableTest.java:224)
08:25:40  	at ai.rapids.cudf.TableTest.assertPartialColumnsAreEqual(TableTest.java:152)
08:25:40  	at ai.rapids.cudf.TableTest.assertColumnsAreEqual(TableTest.java:102)
08:25:40  	at ai.rapids.cudf.TableTest.assertColumnsAreEqual(TableTest.java:92)
08:25:40  	at ai.rapids.cudf.ColumnVectorTest.testStringReplaceWithBackrefs(ColumnVectorTest.java:4266)
08:25:40  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:25:40  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:25:40  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:25:40  	at java.lang.reflect.Method.invoke(Method.java:498)
08:25:40  	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
08:25:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
08:25:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
08:25:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
08:25:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
08:25:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
08:25:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
08:25:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
08:25:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
08:25:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
08:25:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
08:25:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
08:25:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
08:25:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
08:25:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
08:25:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:132)
08:25:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:111)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

**Comment by sperlingxx** [comment]
It appears to be related with #8460

**Comment by abellina** [comment]
Replaced by https://github.com/rapidsai/cudf/issues/8569
