### ISSUE TITLE
[BUG] new integration test failures w/ maxFailures=1

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#2772]
**Describe the bug**
related to maxFailures change https://github.com/NVIDIA/spark-rapids/pull/2743,  and should be the sequel to https://github.com/NVIDIA/spark-rapids/issues/2698

intermittently failed ExecutorLostFailure, not-always reproducible. 
Failed Tests (plz add if you see others):
1. join_test.py::test_cartesean_join[100-Array(Null)0][IGNORE_ORDER({'local': True})]
2. window_function_test.py::test_window_aggs_for_rows_lead_lag_on_arrays[partBy:Long-orderBy:Long-orderBy:LongRange(not_null)-agg:Array(Long)-1000][IGNORE_ORDER({'local': True})]

sample executor log,
```
21/06/22 07:29:51 INFO CoarseGrainedExecutorBackend: Got assigned task 331736
21/06/22 07:29:51 INFO CoarseGrainedExecutorBackend: Got assigned task 331737
21/06/22 07:29:51 INFO Executor: Running task 0.0 in stage 44655.0 (TID 331736)
21/06/22 07:29:51 INFO CoarseGrainedExecutorBackend: Got assigned task 331738
21/06/22 07:29:51 INFO Executor: Running task 1.0 in stage 44655.0 (TID 331737)
21/06/22 07:29:51 INFO Executor: Running task 2.0 in stage 44655.0 (TID 331738)
21/06/22 07:29:51 INFO CoarseGrainedExecutorBackend: Got assigned task 331739
21/06/22 07:29:51 INFO Executor: Running task 3.0 in stage 44655.0 (TID 331739)
21/06/22 07:29:51 INFO CoarseGrainedExecutorBackend: Got assigned task 331740
21/06/22 07:29:51 INFO Executor: Running task 5.0 in stage 44655.0 (TID 331740)
21/06/22 07:29:51 INFO CoarseGrainedExecutorBackend: Got assigned task 331741
21/06/22 07:29:51 INFO Executor: Running task 7.0 in stage 44655.0 (TID 331741)
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Updating epoch to 14283 and clearing cache
21/06/22 07:29:51 INFO TorrentBroadcast: Started reading broadcast variable 44525 with 1 pieces (estimated total size 4.0 MiB)
21/06/22 07:29:51 INFO MemoryStore: Block broadcast_44525_piece0 stored as bytes in memory (estimated size 18.6 KiB, free 6.2 GiB)
21/06/22 07:29:51 INFO TorrentBroadcast: Reading broadcast variable 44525 took 3 ms
21/06/22 07:29:51 INFO MemoryStore: Block broadcast_44525 stored as values in memory (estimated size 40.3 KiB, free 6.2 GiB)
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 14281, fetching them
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@it-ub16-302-14-z17mn-87d0q:46005)
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 14281, fetching them
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 14281, fetching them
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 14281, fetching them
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 14281, fetching them
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Don't have map outputs for shuffle 14281, fetching them
21/06/22 07:29:51 INFO MapOutputTrackerWorker: Got the output locations
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Getting 6 (44.2 KiB) non-empty blocks including 6 (44.2 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Getting 6 (18.7 KiB) non-empty blocks including 6 (18.7 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Getting 6 (44.3 KiB) non-empty blocks including 6 (44.3 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Getting 6 (34.3 KiB) non-empty blocks including 6 (34.3 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Getting 6 (33.3 KiB) non-empty blocks including 6 (33.3 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Getting 6 (47.9 KiB) non-empty blocks including 6 (47.9 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) remote blocks
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/06/22 07:29:51 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
21/06/22 07:29:51 INFO CodeGenerator: Code generated in 13.560419 ms
21/06/22 07:29:51 INFO CodeGenerator: Code generated in 13.591383 ms
21/06/22 07:29:51 ERROR CoarseGrainedExecutorBackend: RECEIVED SIGNAL
```

driver log,
```
 21/06/22 07:29:51 WARN HeartbeatReceiver: Removing executor 1 with no recent heartbeats: 151811 ms exceeds timeout 120000 ms
15:28:55  21/06/22 07:29:51 ERROR TaskSchedulerImpl: Lost executor 1 on 10.233.122.131: Executor heartbeat timed out after 151811 ms
15:28:55  21/06/22 07:29:51 WARN TaskSetManager: Lost task 0.0 in stage 44655.0 (TID 331736, 10.233.122.131, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 151811 ms
15:28:55  21/06/22 07:29:51 ERROR TaskSetManager: Task 0 in stage 44655.0 failed 1 times; aborting job
15:28:55  21/06/22 07:29:51 WARN TaskSetManager: Lost task 3.0 in stage 44655.0 (TID 331739, 10.233.122.131, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 151811 ms
15:28:55  21/06/22 07:29:51 WARN TaskSetManager: Lost task 7.0 in stage 44655.0 (TID 331741, 10.233.122.131, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 151811 ms
15:28:55  21/06/22 07:29:51 WARN TaskSetManager: Lost task 2.0 in stage 44655.0 (TID 331738, 10.233.122.131, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 151811 ms
15:28:55  21/06/22 07:29:51 WARN TaskSetManager: Lost task 1.0 in stage 44655.0 (TID 331737, 10.233.122.131, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 151811 ms
15:28:55  21/06/22 07:29:51 WARN TaskSetManager: Lost task 5.0 in stage 44655.0 (TID 331740, 10.233.122.131, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 151811 ms

-------------------------------------
15:34:49                  if answer[1] == REFERENCE_TYPE:
15:34:49  >                   raise Py4JJavaError(
15:34:49                          "An error occurred while calling {0}{1}{2}.\n".
15:34:49                          format(target_id, ".", name), value)
15:34:49  E                   py4j.protocol.Py4JJavaError: An error occurred while calling o1160474.collectToPython.
15:34:49  E                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 44655.0 failed 1 times, most recent failure: Lost task 0.0 in stage 44655.0 (TID 331736, 10.233.122.131, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 151811 ms
15:34:49  E                   Driver stacktrace:
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2059)
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2008)
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2007)
15:34:49  E                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
15:34:49  E                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
15:34:49  E                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2007)
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:973)
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:973)
15:34:49  E                   	at scala.Option.foreach(Option.scala:407)
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:973)
15:34:49  E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2239)
15:34:49  E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2188)
15:34:49  E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2177)
15:34:49  E                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
15:34:49  E                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:775)
15:34:49  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
15:34:49  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2135)
15:34:49  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2154)
15:34:49  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2179)
15:34:49  E                   	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
15:34:49  E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
15:34:49  E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
15:34:49  E                   	at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
15:34:49  E                   	at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
15:34:49  E                   	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:390)
15:34:49  E                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3450)
15:34:49  E                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3618)
15:34:49  E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
15:34:49  E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
15:34:49  E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
15:34:49  E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
15:34:49  E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
15:34:49  E                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3616)
15:34:49  E                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3447)
15:34:49  E                   	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
15:34:49  E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:34:49  E                   	at java.lang.reflect.Method.invoke(Method.java:498)
15:34:49  E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
15:34:49  E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
15:34:49  E                   	at py4j.Gateway.invoke(Gateway.java:282)
15:34:49  E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
15:34:49  E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
15:34:49  E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
15:34:49  E                   	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
Anything before 07:29:51 in the executor log? Specifically around the 151 seconds before? Curious if this is another instance of the `CollectionAccumulator` issue. I am just not sure what is triggering it.

**Comment by abellina** [comment]
We are thinking to set `num_slices` for all tasks when spark is < 3.1, and also not set max failures (should default to 4 and improve our chances). If anyone has other thoughts please chime in.
