### ISSUE TITLE
[BUG] Window integration tests failing with `Lead expected at least 3 but found 0`

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#2939]
There are failures in integration tests for window-functions. They manifest with the following stack trace:
<details>
<summary> Click to expand: `java.lang.AssertionError: assertion failed: Lead expected at least 3 but found 0` </summary>

```
py4j.protocol.Py4JJavaError: An error occurred while calling o4934.collectToPython.
: java.lang.AssertionError: assertion failed: Lead expected at least 3 but found 0
    at scala.Predef$.assert(Predef.scala:223)
    at com.nvidia.spark.rapids.ContextChecks.tag(TypeChecks.scala:584)
    at com.nvidia.spark.rapids.ExprChecksImpl.tag(TypeChecks.scala:766)
    at com.nvidia.spark.rapids.BaseExprMeta.$anonfun$tagSelfForGpu$3(RapidsMeta.scala:878)
    at com.nvidia.spark.rapids.BaseExprMeta.$anonfun$tagSelfForGpu$3$adapted(RapidsMeta.scala:878)
    at scala.Option.foreach(Option.scala:407)
    at com.nvidia.spark.rapids.BaseExprMeta.tagSelfForGpu(RapidsMeta.scala:878)
    at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:290)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3(RapidsMeta.scala:267)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3$adapted(RapidsMeta.scala:267)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:267)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3(RapidsMeta.scala:267)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3$adapted(RapidsMeta.scala:267)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:267)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3(RapidsMeta.scala:267)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3$adapted(RapidsMeta.scala:267)
    at scala.collection.immutable.Stream.foreach(Stream.scala:533)
    at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:267)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$5(RapidsMeta.scala:269)
    at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$5$adapted(RapidsMeta.scala:269)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:269)
    at com.nvidia.spark.rapids.GpuOverrides.applyOverrides(GpuOverrides.scala:3141)
    at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:3133)
    at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:3119)
    at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1(Columnar.scala:532)
    at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1$adapted(Columnar.scala:531)
    at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
    at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
    at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:531)
    at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:495)
    at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:372)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
    at scala.collection.immutable.List.foldLeft(List.scala:89)
    at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:371)
    at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:117)
    at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
    at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
    at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
    at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:117)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:110)
    at org.apache.spark.sql.execution.QueryExecution.$anonfun$simpleString$2(QueryExecution.scala:161)
    at org.apache.spark.sql.execution.ExplainUtils$.processPlan(ExplainUtils.scala:115)
    at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:161)
    at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:206)
    at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:175)
    at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:98)
    at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
    at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
    at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
    at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
    at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3516)
    at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:282)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:238)
    at java.lang.Thread.run(Thread.java:748)
```
</details>

This is related to the changes to support `STRUCT`/`STRING` for `LEAD()`/`LAG()`, added in #2842. The failures seem isolated to Spark 3.1.x. The tests run fine against Spark 3.0.2.

**Comment by mythrocks** [comment]
Just completed the `git-bisect`. Here's the commit where things broke:
```git
1a093229037d9303a8975b1070b41a9a06fa01d1 is the first bad commit
commit 1a093229037d9303a8975b1070b41a9a06fa01d1
Author: Alfred Xu <lovedreamf@gmail.com>
Date:   Wed Jul 14 09:50:53 2021 +0800

    Type check with the information from RapidsMeta (#2888)

    Signed-off-by: sperlingxx <lovedreamf@gmail.com>

    fetch data type from RapidsMeta instead of wrapped instances

 .../nvidia/spark/rapids/CostBasedOptimizer.scala   |  23 +++--
 .../com/nvidia/spark/rapids/GpuExpandExec.scala    |   6 +-
 .../com/nvidia/spark/rapids/GpuOverrides.scala     |   6 +-
 .../nvidia/spark/rapids/GpuWindowExpression.scala  |   2 +-
 .../scala/com/nvidia/spark/rapids/RapidsMeta.scala | 107 ++++++++++++++++++++-
 .../scala/com/nvidia/spark/rapids/TypeChecks.scala | 101 ++++++++++---------
 .../spark/rapids/CostBasedOptimizerSuite.scala     |   6 +-
 7 files changed, 187 insertions(+), 64 deletions(-)
```
I will double-check to confirm.

**Comment by mythrocks** [comment]
> I will double-check to confirm.

Yep. This test began failing after #2888. I'll look more closely.

**Comment by mythrocks** [comment]
I think I've found the problem. Will post a fix shortly.
