### ISSUE TITLE
[BUG] When lots of NULLs in partition-column of the window, GPU run has task skew and is much slower than CPU.

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#3021]
**Describe the bug**
When lots of NULLs in partition-column of the window, GPU run has task skew and is much slower than CPU.

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

Just use NDS dataset to reproduce because the table `store_sales` has lots of NULLs in column `ss_customer_sk`.
```
val df = spark.read.parquet("/xxx/xxx/xxx/xxx_100G_parquet/store_sales")
df.createOrReplaceTempView("df")
spark.sql("""
select ss_customer_sk,avg(avg_price) as avg_price
from
(
 SELECT ss_customer_sk ,avg(ss_sales_price) OVER (PARTITION BY ss_customer_sk order by ss_sold_date_sk ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) as avg_price
    FROM df
) group by ss_customer_sk order by 2 desc limit 10
""").collect
```
GPU run: 6mins
CPU run: 30s
This is because in GPU run, here are several skewed tasks(16 out of 200 tasks) took around 6mins while other tasks only took 3s.

If we filter out the NULLs:
```
spark.conf.set("spark.sql.files.maxPartitionBytes","1g")
val df = spark.read.parquet("/xxx/xxx/data/xxx_100G_parquet/store_sales")
df.createOrReplaceTempView("df")
spark.sql("""
select ss_customer_sk,avg(avg_price) as avg_price
from
(
 SELECT ss_customer_sk ,avg(ss_sales_price) OVER (PARTITION BY ss_customer_sk order by ss_sold_date_sk ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) as avg_price
    FROM df
    where ss_customer_sk is not null
) group by ss_customer_sk order by 2 desc limit 10
""").collect
```
GPU run: 7s
CPU run: 30s

**Expected behavior**

GPU runs faster even though there are lots of NULLs in partition column of window.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

Spark 3.1.1 Standalone
21.08 snapshot jars(2021-07-26 version)

**Additional context**

**Comment by viadea** [comment]
When the skewed task is running, I sampled the stacktrace of the executor JVM and also checked  the GPU utilization:
```
$ nvidia-smi --query-gpu=utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv  -l 1 -i 0
utilization.gpu [%], utilization.memory [%], memory.total [MiB], memory.free [MiB], memory.used [MiB]
100 %, 9 %, 40537 MiB, 3964 MiB, 36573 MiB
100 %, 9 %, 40537 MiB, 3964 MiB, 36573 MiB
100 %, 9 %, 40537 MiB, 3964 MiB, 36573 MiB
100 %, 9 %, 40537 MiB, 3964 MiB, 36573 MiB
```

Stacktrace of the skewed task:
```
"Executor task launch worker for task 42.0 in stage 4.0 (TID 1234)" #80 daemon prio=5 os_prio=0 tid=0x0000xxxxxxxx nid=0x1e368 runnable [0x0000xxxxxxxxxx]
   java.lang.Thread.State: RUNNABLE
	at ai.rapids.cudf.Table.rollingWindowAggregate(Native Method)
	at ai.rapids.cudf.Table.access$3100(Table.java:38)
	at ai.rapids.cudf.Table$GroupByOperation.aggregateWindows(Table.java:2478)
	at com.nvidia.spark.rapids.GroupedAggregations.$anonfun$doRowAggs$1(GpuWindowExec.scala:712)
	at com.nvidia.spark.rapids.GroupedAggregations$$Lambda$4489/1913643218.apply(Unknown Source)
	at com.nvidia.spark.rapids.GroupedAggregations.$anonfun$doAggInternal$4(GpuWindowExec.scala:688)
	at com.nvidia.spark.rapids.GroupedAggregations$$Lambda$4517/2101224909.apply(Unknown Source)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GroupedAggregations.withResource(GpuWindowExec.scala:639)
	at com.nvidia.spark.rapids.GroupedAggregations.$anonfun$doAggInternal$2(GpuWindowExec.scala:687)
	at com.nvidia.spark.rapids.GroupedAggregations$$Lambda$4503/275837072.apply(Unknown Source)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GroupedAggregations.withResource(GpuWindowExec.scala:639)
	at com.nvidia.spark.rapids.GroupedAggregations.$anonfun$doAggInternal$1(GpuWindowExec.scala:683)
	at com.nvidia.spark.rapids.GroupedAggregations.$anonfun$doAggInternal$1$adapted(GpuWindowExec.scala:677)
	at com.nvidia.spark.rapids.GroupedAggregations$$Lambda$4492/1912721628.apply(Unknown Source)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashMap$$Lambda$276/1958402562.apply(Unknown Source)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at com.nvidia.spark.rapids.GroupedAggregations.doAggInternal(GpuWindowExec.scala:677)
	at com.nvidia.spark.rapids.GroupedAggregations.doRowAggs(GpuWindowExec.scala:712)
	at com.nvidia.spark.rapids.GroupedAggregations.doAggs(GpuWindowExec.scala:942)
	at com.nvidia.spark.rapids.BasicWindowCalc.$anonfun$computeBasicWindow$3(GpuWindowExec.scala:1050)
	at com.nvidia.spark.rapids.BasicWindowCalc.$anonfun$computeBasicWindow$3$adapted(GpuWindowExec.scala:1048)
	at com.nvidia.spark.rapids.BasicWindowCalc$$Lambda$4487/1555805191.apply(Unknown Source)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuWindowIterator.withResource(GpuWindowExec.scala:1067)
	at com.nvidia.spark.rapids.BasicWindowCalc.$anonfun$computeBasicWindow$1(GpuWindowExec.scala:1048)
	at com.nvidia.spark.rapids.BasicWindowCalc$$Lambda$4473/1738728848.apply(Unknown Source)
	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:109)
	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:107)
	at com.nvidia.spark.rapids.GpuWindowIterator.closeOnExcept(GpuWindowExec.scala:1067)
	at com.nvidia.spark.rapids.BasicWindowCalc.computeBasicWindow(GpuWindowExec.scala:1040)
	at com.nvidia.spark.rapids.BasicWindowCalc.computeBasicWindow$(GpuWindowExec.scala:1039)
	at com.nvidia.spark.rapids.GpuWindowIterator.computeBasicWindow(GpuWindowExec.scala:1067)
	at com.nvidia.spark.rapids.GpuWindowIterator.$anonfun$next$2(GpuWindowExec.scala:1084)
	at com.nvidia.spark.rapids.GpuWindowIterator$$Lambda$4470/482270770.apply(Unknown Source)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuWindowIterator.withResource(GpuWindowExec.scala:1067)
	at com.nvidia.spark.rapids.GpuWindowIterator.$anonfun$next$1(GpuWindowExec.scala:1083)
	at com.nvidia.spark.rapids.GpuWindowIterator$$Lambda$4467/55837467.apply(Unknown Source)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuWindowIterator.withResource(GpuWindowExec.scala:1067)
	at com.nvidia.spark.rapids.GpuWindowIterator.next(GpuWindowExec.scala:1082)
	at com.nvidia.spark.rapids.GpuWindowIterator.next(GpuWindowExec.scala:1067)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:312)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:267)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator$$Lambda$4327/1464378153.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:264)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:207)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:312)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:267)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator$$Lambda$4327/1464378153.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:264)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:207)
	at com.nvidia.spark.rapids.GpuTopN$$anon$2.next(limit.scala:211)
	at com.nvidia.spark.rapids.GpuTopN$$anon$2.next(limit.scala:204)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:230)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:246)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.executor.Executor$TaskRunner$$Lambda$784/730644207.apply(Unknown Source)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by viadea** [comment]
As per my tests, seems this issue only happen when using `avg`. It works fine in `max`, `rank`.

**Comment by revans2** [comment]
Please see #3022 which describes the state of performance optimizations for window operations. If we want to "fix" this for `avg` I can do it, but it would only be for running windows. If we want to do more than that we are going to need to work on #3023 to add more options for optimizations.

**Comment by mattahrens** [comment]
@viadea This should be fixed now.  Can you re-test to verify?

**Comment by viadea** [comment]
@mattahrens  Just tested 22.06 snapshot, and this is fixed.
GPU: 12s vs CPU: 33s.
