### ISSUE TITLE
CDP - Flakiness in JoinSuite in Integration tests

### ISSUE THREAD

**Issue by sririshindra** [NVIDIA/spark-rapids#3266]
**Describe the bug**
We are seeing flakiness with the JoinSuite in Integration tests with following error.

Caused by: java.io.IOException: com.esotericsoftware.kryo.KryoException: Error during Java serialization.
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1412)
	at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:226)
	at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:103)
	at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.init(Unknown Source)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.$anonfun$doExecute$4(WholeStageCodegenExec.scala:752)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.$anonfun$doExecute$4$adapted(WholeStageCodegenExec.scala:749)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:915)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:915)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)

**Steps/Code to reproduce bug**
Launch an 4 nodes cluster(1-m4.2xlarge, 3-g4dn.2xlarge) with CDP-7.6 and SPARK3-RAPIDS product.
Install spark-rapids(branch-21.06) on the one of the nodes and launch the full Integration test suite.

**Expected behavior**
JoinSuite is supposed to pass every time without any flakiness.

**Environment details (please complete the following information)**
 - Environment location: YARN, AWS
 - Additional spark configurations that we set is as follows( --conf  spark.kryoserializer.buffer.max=2047m)
 

**Additional context**
We are looking to integrate the spark-rapids integration tests within the Cloudera test schedules. 

[Kryoerror.txt](https://github.com/NVIDIA/spark-rapids/files/7021702/Kryoerror.txt)

**Comment by tgravescs** [comment]
Note also reported:
> It is running perfectly when run Individually and it is also works sometimes when the whole test suite is running. 
> The flakiness seem to reduce when I upgraded to “g4dn.4xlarge” from “g4dn.xlarge” instances, but the issue still persists.

**Comment by tgravescs** [comment]
more of the stack trace shows I think this is happening when it spills:

```
Caused by: com.esotericsoftware.kryo.KryoException: Error during Java serialization.
    at com.esotericsoftware.kryo.serializers.JavaSerializer.write(JavaSerializer.java:54)
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
    at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:259)
    at org.apache.spark.serializer.SerializationStream.writeAll(Serializer.scala:140)
    at org.apache.spark.serializer.SerializerManager.dataSerializeStream(SerializerManager.scala:176)
    at org.apache.spark.storage.BlockManager.$anonfun$dropFromMemory$3(BlockManager.scala:1790)
    at org.apache.spark.storage.BlockManager.$anonfun$dropFromMemory$3$adapted(BlockManager.scala:1785)
    at org.apache.spark.storage.DiskStore.put(DiskStore.scala:70)
    at org.apache.spark.storage.BlockManager.dropFromMemory(BlockManager.scala:1785)
    at org.apache.spark.storage.memory.MemoryStore.dropBlock$1(MemoryStore.scala:473)
    at org.apache.spark.storage.memory.MemoryStore.$anonfun$evictBlocksToFreeSpace$4(MemoryStore.scala:499)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
    at org.apache.spark.storage.memory.MemoryStore.evictBlocksToFreeSpace(MemoryStore.scala:490)
    at org.apache.spark.memory.StorageMemoryPool.acquireMemory(StorageMemoryPool.scala:92)
    at org.apache.spark.memory.StorageMemoryPool.acquireMemory(StorageMemoryPool.scala:73)
    at org.apache.spark.memory.UnifiedMemoryManager.acquireStorageMemory(UnifiedMemoryManager.scala:181)
    at org.apache.spark.memory.UnifiedMemoryManager.acquireUnrollMemory(UnifiedMemoryManager.scala:188)
    at org.apache.spark.storage.memory.MemoryStore.reserveUnrollMemoryForThisTask(MemoryStore.scala:552)
    at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:229)
    at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
    at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
    at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
    at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
    at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:1269)
    at org.apache.spark.storage.BlockManager.putSingle(BlockManager.scala:1758)

```

that might be something to do with why we don't see it all the time.

**Comment by revans2** [comment]
Looking at the code it appears that this could happen if the SerializeConcatHostBuffersDeserializeBatch is deserialized and then serialized again. I am not sure if that is the case here, but I thought I should point it out. We made the assumption that it would never happen.

**Comment by tgravescs** [comment]
it certainly looks like that may be the case from the stack trace, I'll try to confirm.

**Comment by revans2** [comment]
If that is true we should be able to detect it and just write out the concated data again. It is just a case we never expected to see.

**Comment by tgravescs** [comment]
I was able to reproduce this running the cache_test and then join_test on yarn:

```
$SPARK_HOME/bin/spark-submit --conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true  --conf spark.sql.shuffle.partitions=12  --conf spark.executor.memoryOverhead=
   --conf spark.sql.cache.serializer=com.nvidia.spark.rapids.shims.spark311.ParquetCachedBatchSerializer --conf spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_TYPE=docker --conf spark.executorE
.YARN_CONTAINER_RUNTIME_TYPE=docker --conf spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE=XXX
DOCKER_IMAGE=XXX --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistra
r --master yarn  --num-executors 4  --conf spark.locality.wait=0s   --conf spark.executor.resource.gpu.amount=1 --conf spark.executor.resource.gpu.discoveryScript=./getGpus --conf spark.task.re
urce.gpu.amount=0.25   --files /home/user/getGpus  --conf spark.rapids.sql.concurrentGpuTasks=4   --conf spark.rapids.sql.explain="NOT_ON_GPU"  --conf spark.driver.extraJavaOptions=-Duser.ti
zone=GMT --conf spark.sql.session.timeZone=UTC --conf spark.executor.extraJavaOptions=-Duser.timezone=GMT --jars /home/tgraves/spark-rapids/dist/target/rapids-4-spark_2.12-21.06.2-SNAPSHOT.jar,
ome/tgraves/spark-rapids/integration_tests/target/rapids-4-spark-integration-tests_2.12-21.06.2-SNAPSHOT-jar-with-dependencies.jar,/home/tgraves/.m2/repository/ai/rapids/cudf/21.06.1/cudf-21.06
-cuda11.jar integration_tests/runtests.py integration_tests/src/main/python -v -rfExXs --std_input_path=hdfs:/user/tgraves/resources --color=yes --test_type developer ''  ./integration_tests/sr
main/python/cache_test.py ./integration_tests/src/main/python/join_test.py
```
