### ISSUE TITLE
[BUG] Failed to read file into buffer in `CuFile.readFromFile` in gds standalone test

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#3331]
This is one of the exceptions seen in the latest gds standalone nightly job run. @rongou could you take a look?

```
CuFileJni.cpp:218: Failed to read file into buffer: Operation not permitted
```

Full stack:

```
17:55:03 INFO TaskSetManager: Starting task 16.0 in stage 29.2 (TID 288, 10.136.6.4, executor 4, partition 22, NODE_LOCAL, 7600 bytes)
21/08/28 17:55:03 WARN TaskSetManager: Lost task 1.0 in stage 29.2 (TID 273, 10.136.6.4, executor 4): ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-dev-github-435-cuda11/java/src/main/native/src/CuFileJni.cpp:218: Failed to read file into buffer: Operation not permitted
  at ai.rapids.cudf.CuFile.readFromFile(Native Method)
  at ai.rapids.cudf.CuFile.readFileToDeviceMemory(CuFile.java:154)
  at com.nvidia.spark.rapids.RapidsGdsStore$BatchSpiller$RapidsGdsBatchedBuffer.$anonfun$materializeMemoryBuffer$3(RapidsGdsStore.scala:249)
  at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:87)
  at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:85)
  at com.nvidia.spark.rapids.RapidsBufferStore$RapidsBufferBase.closeOnExcept(RapidsBufferStore.scala:261)
  at com.nvidia.spark.rapids.RapidsGdsStore$BatchSpiller$RapidsGdsBatchedBuffer.materializeMemoryBuffer(RapidsGdsStore.scala:242)
  at com.nvidia.spark.rapids.RapidsBufferStore$RapidsBufferBase.getDeviceMemoryBuffer(RapidsBufferStore.scala:370)
  at com.nvidia.spark.rapids.RapidsBufferStore$RapidsBufferBase.getColumnarBatch(RapidsBufferStore.scala:314)
  at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$9(RapidsCachingReader.scala:146)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at org.apache.spark.sql.rapids.RapidsCachingReader.withResource(RapidsCachingReader.scala:49)
  at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$8(RapidsCachingReader.scala:145)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
  at scala.collection.Iterator$ConcatIterator.next(Iterator.scala:230)
  at org.apache.spark.util.CompletionIterator.next(CompletionIterator.scala:29)
  at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
  at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$next$1(GpuExec.scala:182)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.RebaseHelper$.withResource(RebaseHelper.scala:25)
  at com.nvidia.spark.rapids.CollectTimeIterator.next(GpuExec.scala:181)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1(GpuCoalesceBatches.scala:242)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1$adapted(GpuCoalesceBatches.scala:240)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.withResource(GpuCoalesceBatches.scala:196)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:240)
  at com.nvidia.spark.rapids.ConcatAndConsumeAll$.getSingleBatchWithVerification(GpuCoalesceBatches.scala:80)
  at com.nvidia.spark.rapids.GpuShuffledHashJoinBase.$anonfun$doExecuteColumnar$1(GpuShuffledHashJoinBase.scala:79)
  at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
  at org.apache.spark.scheduler.Task.run(Task.scala:127)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
I saw another instance of this in last night's run. @rongou fyi.

**Comment by rongou** [comment]
Upgraded to CUDA 11.4 and the public release of GDS, so far the job has been passing.
