### ISSUE TITLE
[BUG] Qualification tool: check for metadata being null

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#3350]
**Describe the bug**
For task tacking 
```
21/08/20 09:55:31 WARN QualAppInfo: Got unexpected exception processing file: application_1626709192160_199049.lz4
java.lang.NullPointerException
at org.apache.spark.sql.rapids.tool.AppBase.getPlanMetaWithSchema(AppBase.scala:140)
at org.apache.spark.sql.rapids.tool.AppBase.checkMetadataForReadSchema(AppBase.scala:155)
at org.apache.spark.sql.rapids.tool.qualification.QualAppInfo.processSQLPlan(QualAppInfo.scala:218)
at org.apache.spark.sql.rapids.tool.qualification.QualEventProcessor.doSparkListenerSQLExecutionStart(QualEventProcessor.scala:90)
```

**Comment by pxLi** [comment]
fixed by #3343
