### ISSUE TITLE
[BUG] q93 failed w/ UCX

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#3379]
**Describe the bug**
benchmark q93 failed w/ UCX on egx machine. Remove `--conf spark.shuffle.manager` the test works fine

```
16:03:51  21/09/03 08:06:51 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 2 to 10.136.6.4:48304
16:03:51  21/09/03 08:06:51 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 2 to 10.136.6.4:48308
16:03:51  21/09/03 08:06:51 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 2 to 10.136.6.4:48302
16:03:51  21/09/03 08:06:51 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 2 to 10.136.6.4:48306
16:03:51  21/09/03 08:06:51 INFO TaskSetManager: Starting task 16.0 in stage 33.0 (TID 306, 10.136.6.4, executor 0, partition 16, NODE_LOCAL, 7318 bytes)
16:03:51  21/09/03 08:06:51 WARN TaskSetManager: Lost task 11.0 in stage 33.0 (TID 301, 10.136.6.4, executor 0): scala.MatchError: com.nvidia.spark.rapids.GpuPackedTableColumn@33daca7c (of class com.nvidia.spark.rapids.GpuPackedTableColumn)
16:03:51  	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.$anonfun$writeValue$2(GpuColumnarBatchSerializer.scala:82)
16:03:51  	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
16:03:51  	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.writeValue(GpuColumnarBatchSerializer.scala:81)
16:03:51  	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:249)
16:03:51  	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:158)
16:03:51  	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
16:03:51  	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
16:03:51  	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
16:03:51  	at org.apache.spark.scheduler.Task.run(Task.scala:127)
16:03:51  	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
16:03:51  	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
16:03:51  	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
16:03:51  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:03:51  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:03:51  	at java.lang.Thread.run(Thread.java:748)
16:03:51  
16:03:51  21/09/03 08:06:51 INFO TaskSetManager: Starting task 11.1 in stage 33.0 (TID 307, 10.136.6.4, executor 0, partition 11, NODE_LOCAL, 7318 bytes)
16:03:51  21/09/03 08:06:51 WARN TaskSetManager: Lost task 3.0 in stage 33.0 (TID 293, 10.136.6.4, executor 0): scala.MatchError: com.nvidia.spark.rapids.GpuPackedTableColumn@70afd40e (of class com.nvidia.spark.rapids.GpuPackedTableColumn)
16:03:51  	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.$anonfun$writeValue$2(GpuColumnarBatchSerializer.scala:82)
16:03:51  	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
16:03:51  	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.writeValue(GpuColumnarBatchSerializer.scala:81)
16:03:51  	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:249)
16:03:51  	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:158)
16:03:51  	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
16:03:51  	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
16:03:51  	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
16:03:51  	at org.apache.spark.scheduler.Task.run(Task.scala:127)
16:03:51  	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
16:03:51  	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
16:03:51  	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
16:03:51  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:03:51  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:03:51  	at java.lang.Thread.run(Thread.java:748)
```

executor log,
```
21/09/03 05:52:23 INFO ShuffleBlockFetcherIterator: Started 3 remote fetches in 8 ms
21/09/03 05:52:23 INFO ShuffleBlockFetcherIterator: Started 3 remote fetches in 8 ms
21/09/03 05:52:23 INFO ShuffleBlockFetcherIterator: Started 3 remote fetches in 8 ms
21/09/03 05:52:23 INFO ShuffleBlockFetcherIterator: Started 3 remote fetches in 8 ms
21/09/03 05:52:23 INFO CodeGenerator: Code generated in 24.346028 ms
21/09/03 05:52:23 INFO CodeGenerator: Code generated in 23.757556 ms
21/09/03 05:52:24 ERROR Executor: Exception in task 4.0 in stage 33.0 (TID 294)
scala.MatchError: com.nvidia.spark.rapids.GpuPackedTableColumn@5ae1cc37 (of class com.nvidia.spark.rapids.GpuPackedTableColumn)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.$anonfun$writeValue$2(GpuColumnarBatchSerializer.scala:82)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.writeValue(GpuColumnarBatchSerializer.scala:81)
        at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:249)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:158)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
21/09/03 05:52:24 ERROR Executor: Exception in task 0.0 in stage 33.0 (TID 290)
scala.MatchError: com.nvidia.spark.rapids.GpuPackedTableColumn@763c68e9 (of class com.nvidia.spark.rapids.GpuPackedTableColumn)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.$anonfun$writeValue$2(GpuColumnarBatchSerializer.scala:82)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.writeValue(GpuColumnarBatchSerializer.scala:81)
        at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:249)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:158)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
21/09/03 05:52:24 ERROR Executor: Exception in task 8.0 in stage 33.0 (TID 298)
```

**Steps/Code to reproduce bug**
version info,
```
16:12:41  21/09/03 08:15:41 INFO SQLExecPlugin: RAPIDS Accelerator build: {version=21.10.0-SNAPSHOT, user=, url=https://github.com/NVIDIA/spark-rapids.git, date=2021-09-02T15:16:12Z, revision=f1f55225a4748cb90402a379126ac611a4c3d99e, cudf_version=21.10.0-SNAPSHOT, branch=HEAD}
16:12:41  21/09/03 08:15:41 INFO SQLExecPlugin: cudf build: {version=21.10.0-SNAPSHOT, user=, date=2021-09-02T12:15:38Z, revision=cc7108729fe08f2ee3f03728b03d4072890b1570, branch=HEAD}
# and rapids-4-spark-benchmarks_2.12-0.4.0-SNAPSHOT.jar
# UCT version=1.11.0 revision fa84605
```

command,
```
spark-submit ....
--conf spark.shuffle.manager="com.nvidia.spark.rapids.spark302.RapidsShuffleManager" \
--conf spark.executorEnv.UCX_TLS=cuda_copy,cuda_ipc,rc,tcp \
--conf spark.executorEnv.UCX_ERROR_SIGNALS= \
--conf spark.executorEnv.UCX_RNDV_SCHEME=put_zcopy \
--conf spark.executorEnv.UCX_MAX_RNDV_RAILS=1 \
--conf spark.executorEnv.UCX_MEMTYPE_CACHE=n \
--conf spark.executorEnv.UCX_IB_RX_QUEUE_LEN=1024 \
--class com.nvidia.spark.rapids.tests.BenchmarkRunner \
"benchmark.jar" \
--benchmark tpcds --query q93 --input /spark-data/tpcds --input-format parquet --output /raid/tmp/q93-output --output-format parquet \
--summary-file-prefix q93 --iterations 1
```

**Comment by abellina** [comment]
This looks like the partitioning code went the GPU route (with `contiguous_split`) but the shuffle was actually on the CPU. I'll take this one.
