### ISSUE TITLE
[BUG] Resource cleanup issues with Spark 3.2

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#3416]
**Describe the bug**
When running queries in Spark shell in local mode with Spark 3.2.0-SNAPSHOT, I consistently see `Close called too many times` errors when closing the spark session. 

For example, running an NDS benchmark query produces this:

```
[BENCHMARK RUNNER] [q58] Iteration 0 took 17607 msec. Status: Completed.
[BENCHMARK RUNNER] [q58] Iteration 0 took 17607 msec. Status: Completed
[BENCHMARK RUNNER] [q58] Saving benchmark report to tpcds-adhoc-q58-1631142002844.json
21/09/08 23:00:20 INFO RapidsBufferCatalog: Closing storage
21/09/08 23:00:21 INFO BlockManagerInfo: Removed broadcast_48_piece0 on 192.168.0.6:46319 in memory (size: 72.5 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_31_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_37_piece0 on 192.168.0.6:46319 in memory (size: 354.0 B, free: 34.0 GiB)
21/09/08 23:00:23 WARN MemoryStore: Fail to close a memory entry
java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bec003130, length=64, id=451}
	at ai.rapids.cudf.MemoryBuffer.close(MemoryBuffer.java:208)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1(implicits.scala:76)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1$adapted(implicits.scala:73)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.safeClose(implicits.scala:73)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableArray.safeClose(implicits.scala:94)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.close(GpuBroadcastExchangeExec.scala:132)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1(MemoryStore.scala:397)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1$adapted(MemoryStore.scala:394)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.spark.storage.memory.MemoryStore.freeMemoryEntry(MemoryStore.scala:394)
	at org.apache.spark.storage.memory.MemoryStore.remove(MemoryStore.scala:412)
	at org.apache.spark.storage.BlockManager.removeBlockInternal(BlockManager.scala:1950)
	at org.apache.spark.storage.BlockManager.removeBlock(BlockManager.scala:1934)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3$adapted(BlockManager.scala:1920)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.spark.storage.BlockManager.removeBroadcast(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManagerStorageEndpoint$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$4(BlockManagerStorageEndpoint.scala:69)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at org.apache.spark.storage.BlockManagerStorageEndpoint.$anonfun$doAsync$1(BlockManagerStorageEndpoint.scala:89)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_28_piece0 on 192.168.0.6:46319 in memory (size: 2.1 MiB, free: 34.0 GiB)
21/09/08 23:00:23 WARN MemoryStore: Fail to close a memory entry
java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0be40db070, length=446016, id=289}
	at ai.rapids.cudf.MemoryBuffer.close(MemoryBuffer.java:208)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1(implicits.scala:76)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1$adapted(implicits.scala:73)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.safeClose(implicits.scala:73)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableArray.safeClose(implicits.scala:94)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.close(GpuBroadcastExchangeExec.scala:132)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1(MemoryStore.scala:397)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1$adapted(MemoryStore.scala:394)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.spark.storage.memory.MemoryStore.freeMemoryEntry(MemoryStore.scala:394)
	at org.apache.spark.storage.memory.MemoryStore.remove(MemoryStore.scala:412)
	at org.apache.spark.storage.BlockManager.removeBlockInternal(BlockManager.scala:1950)
	at org.apache.spark.storage.BlockManager.removeBlock(BlockManager.scala:1934)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3$adapted(BlockManager.scala:1920)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.spark.storage.BlockManager.removeBroadcast(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManagerStorageEndpoint$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$4(BlockManagerStorageEndpoint.scala:69)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at org.apache.spark.storage.BlockManagerStorageEndpoint.$anonfun$doAsync$1(BlockManagerStorageEndpoint.scala:89)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bec06d680, length=442240, id=163}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0be406e7e0, length=444544, id=205}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0c08070e60, length=440768, id=162}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bec0d9610, length=439616, id=246}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bf0081fd0, length=436480, id=288}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0c080dc830, length=431808, id=247}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bf00035b0, length=433088, id=121}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0c08007b90, length=430784, id=78}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bec003330, length=435008, id=79}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0be4005490, length=430912, id=120}
		... 37 more
	Suppressed: java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bf006d180, length=85568, id=204}
		... 37 more
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_41_piece0 on 192.168.0.6:46319 in memory (size: 361.0 B, free: 34.0 GiB)
21/09/08 23:00:23 WARN MemoryStore: Fail to close a memory entry
java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0c08005030, length=64, id=525}
	at ai.rapids.cudf.MemoryBuffer.close(MemoryBuffer.java:208)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1(implicits.scala:76)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1$adapted(implicits.scala:73)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.safeClose(implicits.scala:73)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableArray.safeClose(implicits.scala:94)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.close(GpuBroadcastExchangeExec.scala:132)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1(MemoryStore.scala:397)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1$adapted(MemoryStore.scala:394)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.spark.storage.memory.MemoryStore.freeMemoryEntry(MemoryStore.scala:394)
	at org.apache.spark.storage.memory.MemoryStore.remove(MemoryStore.scala:412)
	at org.apache.spark.storage.BlockManager.removeBlockInternal(BlockManager.scala:1950)
	at org.apache.spark.storage.BlockManager.removeBlock(BlockManager.scala:1934)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3$adapted(BlockManager.scala:1920)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.spark.storage.BlockManager.removeBroadcast(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManagerStorageEndpoint$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$4(BlockManagerStorageEndpoint.scala:69)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at org.apache.spark.storage.BlockManagerStorageEndpoint.$anonfun$doAsync$1(BlockManagerStorageEndpoint.scala:89)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_43_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_30_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 WARN MemoryStore: Fail to close a memory entry
java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0be4004110, length=64, id=486}
	at ai.rapids.cudf.MemoryBuffer.close(MemoryBuffer.java:208)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1(implicits.scala:76)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1$adapted(implicits.scala:73)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.safeClose(implicits.scala:73)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableArray.safeClose(implicits.scala:94)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.close(GpuBroadcastExchangeExec.scala:132)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1(MemoryStore.scala:397)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1$adapted(MemoryStore.scala:394)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.spark.storage.memory.MemoryStore.freeMemoryEntry(MemoryStore.scala:394)
	at org.apache.spark.storage.memory.MemoryStore.remove(MemoryStore.scala:412)
	at org.apache.spark.storage.BlockManager.removeBlockInternal(BlockManager.scala:1950)
	at org.apache.spark.storage.BlockManager.removeBlock(BlockManager.scala:1934)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3$adapted(BlockManager.scala:1920)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.spark.storage.BlockManager.removeBroadcast(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManagerStorageEndpoint$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$4(BlockManagerStorageEndpoint.scala:69)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at org.apache.spark.storage.BlockManagerStorageEndpoint.$anonfun$doAsync$1(BlockManagerStorageEndpoint.scala:89)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_38_piece0 on 192.168.0.6:46319 in memory (size: 354.0 B, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_36_piece0 on 192.168.0.6:46319 in memory (size: 354.0 B, free: 34.0 GiB)
21/09/08 23:00:23 WARN MemoryStore: Fail to close a memory entry
java.lang.IllegalStateException: Close called too many times HostMemoryBuffer{address=0x7f0bf00030f0, length=64, id=402}
	at ai.rapids.cudf.MemoryBuffer.close(MemoryBuffer.java:208)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1(implicits.scala:76)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.$anonfun$safeClose$1$adapted(implicits.scala:73)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableSeq.safeClose(implicits.scala:73)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableArray.safeClose(implicits.scala:94)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.close(GpuBroadcastExchangeExec.scala:132)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1(MemoryStore.scala:397)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$freeMemoryEntry$1$adapted(MemoryStore.scala:394)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.apache.spark.storage.memory.MemoryStore.freeMemoryEntry(MemoryStore.scala:394)
	at org.apache.spark.storage.memory.MemoryStore.remove(MemoryStore.scala:412)
	at org.apache.spark.storage.BlockManager.removeBlockInternal(BlockManager.scala:1950)
	at org.apache.spark.storage.BlockManager.removeBlock(BlockManager.scala:1934)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManager.$anonfun$removeBroadcast$3$adapted(BlockManager.scala:1920)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.spark.storage.BlockManager.removeBroadcast(BlockManager.scala:1920)
	at org.apache.spark.storage.BlockManagerStorageEndpoint$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$4(BlockManagerStorageEndpoint.scala:69)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at org.apache.spark.storage.BlockManagerStorageEndpoint.$anonfun$doAsync$1(BlockManagerStorageEndpoint.scala:89)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_32_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_42_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_39_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_24_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_25_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:23 INFO BlockManagerInfo: Removed broadcast_45_piece0 on 192.168.0.6:46319 in memory (size: 34.1 KiB, free: 34.0 GiB)
21/09/08 23:00:24 INFO ExecutorPluginContainer: Exception while shutting down plugin com.nvidia.spark.SQLPlugin.
ai.rapids.cudf.RmmException: Could not shut down RMM there appear to be outstanding allocations
	at ai.rapids.cudf.Rmm.shutdown(Rmm.java:330)
	at ai.rapids.cudf.Rmm.shutdown(Rmm.java:290)
	at com.nvidia.spark.rapids.GpuDeviceManager$.shutdown(GpuDeviceManager.scala:139)
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.shutdown(Plugin.scala:246)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$shutdown$4(PluginContainer.scala:144)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$shutdown$4$adapted(PluginContainer.scala:141)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.shutdown(PluginContainer.scala:141)
	at org.apache.spark.executor.Executor.$anonfun$stop$4(Executor.scala:340)
	at org.apache.spark.executor.Executor.$anonfun$stop$4$adapted(Executor.scala:340)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.executor.Executor.$anonfun$stop$3(Executor.scala:340)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:231)
	at org.apache.spark.executor.Executor.stop(Executor.scala:340)
	at org.apache.spark.executor.Executor.$anonfun$stopHookReference$1(Executor.scala:76)
	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:214)
	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$2(ShutdownHookManager.scala:188)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2019)
	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$1(ShutdownHookManager.scala:188)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/09/08 23:00:24 INFO SparkContext: Invoking stop() from shutdown hook
21/09/08 23:00:24 INFO SparkUI: Stopped Spark web UI at http://192.168.0.6:4040
21/09/08 23:00:24 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/09/08 23:00:24 INFO MemoryStore: MemoryStore cleared
21/09/08 23:00:24 INFO BlockManager: BlockManager stopped
21/09/08 23:00:24 INFO BlockManagerMaster: BlockManagerMaster stopped
21/09/08 23:00:24 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/09/08 23:00:24 INFO SparkContext: Successfully stopped SparkContext
21/09/08 23:00:24 INFO DiskBlockManager: Shutdown hook called
21/09/08 23:00:24 INFO ShutdownHookManager: Shutdown hook called
21/09/08 23:00:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-a3595199-3d8d-41c5-b275-2eeb45ed6151
21/09/08 23:00:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-91e5d017-ecd7-4cba-9703-71d00e13e05a
```

**Steps/Code to reproduce bug**
Run queries in spark shell with 3.2

**Expected behavior**
Should not produce these errors

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by andygrove** [comment]
I added some debug logging and do see that we are closing buffers twice (when running against Spark 3.2):

```
SerializeBatchDeserializeHostBuffer closing buffer HostMemoryBuffer{address=0x7f9278001220, length=64, id=520}
SerializeConcatHostBuffersDeserializeBatch closing buffers:HostMemoryBuffer{address=0x7f9278001220, length=64, id=520}
```

`SerializeConcatHostBuffersDeserializeBatch` close method:

```scala
override def close(): Unit = {
  data.safeClose()
  buffers.safeClose()
  if (batchInternal != null) {
    batchInternal.close()
  }
}
```

The call to `data.safeClose` above calls the `SerializeBatchDeserializeHostBuffer` close method, which closes the underlying memory buffer, and on return, the call to `buffers.safeClose` above will try and close it again. 

```scala
override def close(): Unit = {
  columns.safeClose()
  if (buffer != null) {
    buffer.close()
  }
}
```

I found one Spark change that is maybe related to this: https://github.com/apache/spark/commit/63ab38f917b3936f5bc025ac7b0d4e281414efef
