### ISSUE TITLE
[DOC] update instructions/test script for udf_cudf_test.py on databricks 

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#3481]
I see the following failure  when running the integration tests in databricks (7.3 or 8.2). I used `./jenkins/databricks/build.sh` and `./jenkins/databricks/test.sh`. It seems like we are missing an install in the python distribution.

```
=========================== short test summary info ============================
FAILED ../../src/main/python/udf_cudf_test.py::test_with_column[small data]
FAILED ../../src/main/python/udf_cudf_test.py::test_with_column[large data]
FAILED ../../src/main/python/udf_cudf_test.py::test_sql - py4j.protocol.Py4JJ...
FAILED ../../src/main/python/udf_cudf_test.py::test_select - py4j.protocol.Py...
FAILED ../../src/main/python/udf_cudf_test.py::test_map_in_pandas - py4j.prot...
FAILED ../../src/main/python/udf_cudf_test.py::test_group_apply - py4j.protoc...
FAILED ../../src/main/python/udf_cudf_test.py::test_group_apply_in_pandas - p...
FAILED ../../src/main/python/udf_cudf_test.py::test_group_agg - py4j.protocol...
FAILED ../../src/main/python/udf_cudf_test.py::test_sql_group - py4j.protocol...
FAILED ../../src/main/python/udf_cudf_test.py::test_window - py4j.protocol.Py...
FAILED ../../src/main/python/udf_cudf_test.py::test_cogroup[ALLOW_NON_GPU(GpuFlatMapCoGroupsInPandasExec,PythonUDF)]
============== 11 failed, 10532 deselected, 22 warnings in 48.86s ==============
```

Stack trace looks similar for all of the above:
```
21/09/14 16:20:59 WARN PythonWorkerFactory: Assuming that daemon unexpectedly quit, attempting to restart
INFO: Process 13967 found CUDA visible device(s): 0
Traceback (most recent call last):
  File "/home/ubuntu/spark-rapids/dist/target/rapids-4-spark_2.12-21.10.0-SNAPSHOT.jar/rapids/daemon_databricks.py", line 132, in manager
  File "/home/ubuntu/spark-rapids/dist/target/rapids-4-spark_2.12-21.10.0-SNAPSHOT.jar/rapids/worker.py", line 37, in initialize_gpu_mem
    from cudf import rmm
ModuleNotFoundError: No module named 'cudf'
21/09/14 16:20:59 ERROR Executor: Exception in task 5.2 in stage 35.0 (TID 220)
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.spark.api.python.PythonWorkerFactory.createSocket$1(PythonWorkerFactory.scala:210)
	at org.apache.spark.api.python.PythonWorkerFactory.liftedTree1$1(PythonWorkerFactory.scala:233)
	at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:225)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:119)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:192)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:183)
	at org.apache.spark.sql.execution.python.PandasGroupUtils$.executePython(PandasGroupUtils.scala:44)
	at org.apache.spark.sql.execution.python.rapids.GpuPandasUtils$.executePython(GpuPandasUtils.scala:35)
	at org.apache.spark.sql.rapids.execution.python.GpuFlatMapCoGroupsInPandasExec.$anonfun$doExecute$1(GpuFlatMapCoGroupsInPandasExec.scala:137)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:101)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:356)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:320)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:144)
	at org.apache.spark.scheduler.Task.run(Task.scala:117)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$9(Executor.scala:655)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1581)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:658)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tgravescs** [comment]
cudf_udf test needs more setup I think, the databricks nightly handles, we may need to document this better

**Comment by abellina** [comment]
I have missed a step in my installation, we need to have a conda environment created with cudf installed. The `jenkins/databricks/test.sh` script could try and detect an environment that isn't configured all the way, but I don't think there's a real bug here we need to be too worried about. 

I am trying to find a doc that points at the environment creation.  The doc here https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/docs/additional-functionality/rapids-udfs.md, doesn't point me at what the requirements in the system/pyhton install are. I am probably missing another doc somewhere.

**Comment by abellina** [comment]
Ah, here it is: https://github.com/NVIDIA/spark-rapids/blob/c0adff3e5149481d6e7f8620c9cb346ae420be1d/integration_tests/README.md#enabling-cudf_udf-tests

**Comment by tgravescs** [comment]
updated internal docs for running on databricks as well

**Comment by tgravescs** [comment]
the test.sh script only tries to run cudf_udf tests if its expcliilty asked for and now by default so with the documentation I think this is fine. If we hit more issues with this we can open a new issue.
