### ISSUE TITLE
[BUG] Nightly tests failed with RMM outstanding allocations on shutdown

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3518]
Nightly dev test failed with this error in the scala-test-detailed-output.log:
```
21/09/16 16:31:43.525 ScalaTest-main-running-GpuPartitioningSuite WARN SparkSession: An existing Spark session exists as the active or default session.
This probably means another suite leaked it. Attempting to stop it before continuing.
This existing Spark session was created at:

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:953)
com.nvidia.spark.rapids.SparkSessionHolder$.createSparkSession(SparkQueryCompareTestSuite.scala:96)
com.nvidia.spark.rapids.SparkSessionHolder$.reinitSession(SparkQueryCompareTestSuite.scala:100)
com.nvidia.spark.rapids.SparkSessionHolder$.resetSparkSessionConf(SparkQueryCompareTestSuite.scala:114)
com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:130)
com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:188)
com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession$(SparkQueryCompareTestSuite.scala:183)
com.nvidia.spark.rapids.CostBasedOptimizerSuite.withGpuSparkSession(CostBasedOptimizerSuite.scala:35)
com.nvidia.spark.rapids.CostBasedOptimizerSuite.$anonfun$new$5(CostBasedOptimizerSuite.scala:122)
org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
org.scalatest.Transformer.apply(Transformer.scala:22)
org.scalatest.Transformer.apply(Transformer.scala:20)
org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)

         
21/09/16 16:31:43.525 dispatcher-event-loop-0 INFO RapidsBufferCatalog: Closing storage
21/09/16 16:31:43.526 dispatcher-event-loop-1 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/09/16 16:31:46.141 ScalaTest-main-running-GpuPartitioningSuite INFO MemoryStore: MemoryStore cleared
21/09/16 16:31:46.141 ScalaTest-main-running-GpuPartitioningSuite INFO BlockManager: BlockManager stopped
21/09/16 16:31:46.141 ScalaTest-main-running-GpuPartitioningSuite INFO BlockManagerMaster: BlockManagerMaster stopped
21/09/16 16:31:46.141 dispatcher-event-loop-1 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/09/16 16:31:47.531 dispatcher-event-loop-0 INFO ExecutorPluginContainer: Exception while shutting down plugin com.nvidia.spark.SQLPlugin.
ai.rapids.cudf.RmmException: Could not shut down RMM there appear to be outstanding allocations
	at ai.rapids.cudf.Rmm.shutdown(Rmm.java:347)
	at ai.rapids.cudf.Rmm.shutdown(Rmm.java:307)
	at com.nvidia.spark.rapids.GpuDeviceManager$.shutdown(GpuDeviceManager.scala:139)
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.shutdown(Plugin.scala:235)
```

I'm guessing a recent test change may have introduced a leak.

**Comment by tgravescs** [comment]
this didn't happen on latest build, it might have been some issues with mismatch, going to close for now and reopen if we see again.
