### ISSUE TITLE
[BUG] Java heap OOM while running integration tests in cloudera

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#3525]
I am running the tests with the build changes put in as of late in cloudera and got this OOM. My heap is _huge_ (at 24G `-Xmx24576m`), so I think we have some sort of leak going on. This is a distributed case, as I am running with Yarn.

Error:

```
PASSED [ 77%]
src/main/python/parquet_write_test.py::test_write_sql_save_table[TIMESTAMP_MILLIS-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp]), Struct(['child0', Struct(['child1', Byte])]), Struct(['child0', Map(String(not_null),String)],['child1', Integer]), Array(Byte), Array(Short), Array(Integer), Array(Long), Array(Float), Array(Double), Array(String), Array(Boolean), Array(Date), Array(Timestamp), Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp])), Array(Struct(['child0', Struct(['child1', Byte])])), Array(Struct(['child0', Map(String(not_null),String)],['child1', Integer])), Array(Array(Byte)), Array(Array(Short)), Array(Array(Integer)), Array(Array(Long)), Array(Array(Float)), Array(Array(Double)), Array(Array(String)), Array(Array(Boolean)), Array(Array(Date)), Array(Array(Timestamp)), Array(Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp]))), Array(Array(Struct(['child0', Struct(['child1', Byte])]))), Array(Array(Struct(['child0', Map(String(not_null),String)],['child1', Integer]))), Decimal(18,0), Decimal(7,3), Decimal(7,7), Decimal(12,2), Map(Boolean(not_null),Boolean), Map(Byte(not_null),Byte), Map(Short(not_null),Short), Map(Integer(not_null),Integer), Map(Long(not_null),Long), Map(Float(not_null),Float), Map(Double(not_null),Double), Map(Date(not_null),Date), Map(Timestamp(not_null),Timestamp), Map(String(not_null),String), Map(String(not_null),Array(String)), Map(RepeatSeq(not_null)(Integer(not_null)),Long), Map(String(not_null),Map(String(not_null),String)), Map(Struct(not_null)(['child0', String],['child1', String]),Float), Map(Struct(not_null)(['child0', String]),String)]] 21/09/17 09:15:41 WARN scheduler.TaskSetManager: Stage 49537 contains a task of very large size (33285 KiB). The maximum recommended task size is 1000 KiB.
21/09/17 09:15:48 ERROR netty.Inbox: An error happened while processing message in the inbox for CoarseGrainedScheduler
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at org.apache.spark.util.ByteBufferOutputStream.write(ByteBufferOutputStream.scala:41)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at java.io.ObjectOutputStream$BlockDataOutputStream.write(ObjectOutputStream.java:1853)
        at java.io.ObjectOutputStream.write(ObjectOutputStream.java:709)
        at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458)
        at org.apache.spark.util.SerializableBuffer.$anonfun$writeObject$1(SerializableBuffer.scala:49)
        at org.apache.spark.util.SerializableBuffer$$Lambda$2441/1470023943.apply(Unknown Source)
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1405)
        at org.apache.spark.util.SerializableBuffer.writeObject(SerializableBuffer.scala:47)
        at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1154)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:44)
        at org.apache.spark.rpc.netty.RequestMessage.serialize(NettyRpcEnv.scala:601)
        at org.apache.spark.rpc.netty.NettyRpcEnv.send(NettyRpcEnv.scala:199)
        at org.apache.spark.rpc.netty.NettyRpcEndpointRef.send(NettyRpcEnv.scala:564)
        at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint.$anonfun$launchTasks$1(CoarseGrainedSchedulerBackend.scala:383)
        at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint.$anonfun$launchTasks$1$adapted(CoarseGrainedSchedulerBackend.scala:352)
        at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$Lambda$1224/286757413.apply(Unknown Source)
```

Configs:

```
--conf spark.rapids.sql.concurrentGpuTasks=4 
--conf spark.executor.resource.gpu.amount=1 
--conf spark.task.resource.gpu.amount=0.167 
--conf spark.sql.shuffle.partitions=12 
--conf spark.task.maxFailures=4 
--conf spark.dynamicAllocation.enabled=false 
--executor-cores 6 
--total-executor-cores 24 
--master yarn 
--executor-memory 24G 
--num-executors 4 
```

**Comment by abellina** [comment]
I'll look into this. I removed some tests (`cache_test` and then `test_write_sql_save_table`) to see if I get further, then will come back.

**Comment by abellina** [comment]
So, a few updates:

- This is not the executor heap. When I filed this I was a bit confused because the stack points at the driver OOMing while serializing some tasks. The task sizes are large and warnings are being thrown by Spark.
- The driver is running with 1 GiB Xmx (the default). Most memory is concentrated at:
  - A heap dump of the driver shows ~300 MiB retained by `SharedInMemoryCache`, which is used to cache partition file status according to the class header. This looks to be using a guava cache, and is configured to ~200 MiB maximum, but it looks to be above that. We can tune down some settings here (`spark.sql.hive.filesourcePartitionFileCacheSize`).
  - The `AsyncEventQueue` is at 164MiB (i.e. event listener).
  - The hive session catalog is about 140MiB. All of this is in `tempViews`. To me it seems the best way to do that is to change the call to `createTempView` and then call `dropTempView`. Listing temp views wasn't working easily from a shell debug session I had, and I don't see a `dropAllTempViews` function call.

**Comment by abellina** [comment]
I re-ran the tests with a 4GB heap in the driver, an they passed. Just noting that increasing the size of the driver heap allows (no fairly large spark app) to run to completion. We can still work on improving memory usage, and I have some culprits above, but it needs more investigation on heap dumps I've collected.

**Comment by abellina** [comment]
I do not think this is a big issue, but I'll leave this open in the context of "lets look at the heap for a long job, and make sure there isn't an actual leak".

**Comment by jlowe** [comment]
Old issue, closing.  Please reopen if it's still relevant.
