### ISSUE TITLE
[BUG] Query error in spark 320 and AQE environment : "Unexpected partitioning for coalesced shuffle read: gpuhashpartitioning" 

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#3540]
**Describe the bug**
Query error in spark 320 and AQE environment when executing simple SQL query:
   "Unexpected partitioning for coalesced shuffle read: gpuhashpartitioning" 

**Steps/Code to reproduce bug**
```
  # compile
  git checkout branch-21.10
  git pull
  mvn clean package -Dbuildver=320 -DskipTests
  
  # start pyspart
  export SPARK_CUDF_JAR=~/code/spark-rapids/integration_tests/target/dependency/*
  export SPARK_RAPIDS_PLUGIN_JAR=~/code/spark-rapids/dist/target/rapids-4-spark_2.12-21.10.0-SNAPSHOT.jar
  ls $SPARK_CUDF_JAR $SPARK_RAPIDS_PLUGIN_JAR
  $SPARK_HOME/bin/pyspark \
  --master local \
  --num-executors 1 \
  --conf spark.executor.cores=1 \
  --conf spark.rapids.sql.concurrentGpuTasks=1 \
  --driver-memory 10g \
  --conf spark.rapids.memory.pinnedPool.size=2G \
  --conf spark.locality.wait=0s \
  --conf spark.sql.files.maxPartitionBytes=512m \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --jars ${SPARK_CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR}
  
  # execute group by
  from pyspark.sql.types import *
  schema = StructType([
      StructField("a", StringType()),
      StructField("b", StringType()),
      StructField("c", StringType()),
      StructField("i", IntegerType()),
  ])
  data = [
	  ('s11','s12','s31',1),
	  ('s11','s12','s32',2),
  ]
  df = spark.createDataFrame(data, schema)
  df.createOrReplaceTempView("t")
  sql = spark.sql("select a,b, sum(i) from t group by a,b")
  sql.show()


# error:
Traceback (most recent call last):                                  (0 + 1) / 1]
  File "<stdin>", line 1, in <module>
  File "/home/chonggao/spark-home/python/pyspark/sql/dataframe.py", line 494, in show
    print(self._jdf.showString(n, 20, vertical))
  File "/home/chonggao/spark-home/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1309, in __call__
  File "/home/chonggao/spark-home/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/chonggao/spark-home/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o55.showString.
: java.lang.IllegalStateException: Unexpected partitioning for coalesced shuffle read: gpuhashpartitioning(a#0, b#1, 200)
	at org.apache.spark.sql.execution.adaptive.AQEShuffleReadExec.outputPartitioning$lzycompute(AQEShuffleReadExec.scala:86)
	at org.apache.spark.sql.execution.adaptive.AQEShuffleReadExec.outputPartitioning(AQEShuffleReadExec.scala:55)
	at org.apache.spark.sql.execution.exchange.ValidateRequirements$.$anonfun$validateInternal$1(ValidateRequirements.scala:53)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:23)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.apache.spark.sql.execution.exchange.ValidateRequirements$.validateInternal(ValidateRequirements.scala:53)
	at org.apache.spark.sql.execution.exchange.ValidateRequirements$.validate(ValidateRequirements.scala:38)
	at org.apache.spark.sql.execution.exchange.ValidateRequirements$.$anonfun$validate$1(ValidateRequirements.scala:38)
	at org.apache.spark.sql.execution.exchange.ValidateRequirements$.$anonfun$validate$1$adapted(ValidateRequirements.scala:38)
	at scala.collection.Iterator.forall(Iterator.scala:955)
	at scala.collection.Iterator.forall$(Iterator.scala:953)
	at scala.collection.AbstractIterator.forall(Iterator.scala:1431)
	at scala.collection.IterableLike.forall(IterableLike.scala:77)
	at scala.collection.IterableLike.forall$(IterableLike.scala:76)
	at scala.collection.AbstractIterable.forall(Iterable.scala:56)
	at org.apache.spark.sql.execution.exchange.ValidateRequirements$.validate(ValidateRequirements.scala:38)
	at org.apache.spark.sql.execution.exchange.ValidateRequirements$.validate(ValidateRequirements.scala:34)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$optimizeQueryStage$2(AdaptiveSparkPlanExec.scala:156)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$optimizeQueryStage$1(AdaptiveSparkPlanExec.scala:144)
	at org.apache.spark.sql.execution.QueryExecution.withCteMap(QueryExecution.scala:73)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.optimizeQueryStage(AdaptiveSparkPlanExec.scala:143)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:317)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:226)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:365)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:338)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3728)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2728)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3719)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3717)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2728)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2935)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:287)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:748)
```

@sperlingxx did some investigation on this, the following is from Alfred
In version 3.2, before apply GpuOverrideRule to FinalPlan, there is an additional step of optimizeQueryStage (some of the previous strategies have been optimized)
```
	val distribution = if (isFinalStage) {
	  // If `requiredDistribution` is None, it means `EnsureRequirements` will not optimize
	  // out the user-specified repartition, thus we don't have a distribution requirement
	  // for the final plan.
	  requiredDistribution.getOrElse(UnspecifiedDistribution)
	} else {
	  UnspecifiedDistribution
	}
	if (ValidateRequirements.validate(applied, distribution)) {
	  applied
	} else {
	  logDebug(s"Rule ${rule.ruleName} is not applied as it breaks the " +
	    "distribution requirement of the query plan.")
	  latestPlan
	}
```
Here, the distribution in QueryStageExchange will be validated. In the case of GpuOverrides, GpuHashPartitoning will be returned. However, GpuHashPartitoning does not inherit HashPartitoning, so it is illegal and an error is reported. 
Alfred think just need to change the inheritance relationship 

@andygrove  can you take a look?

**Comment by andygrove** [comment]
This should have been resolved by https://github.com/apache/spark/pull/33910 so I am guessing that you are using Spark 3.2.0-rc2 when running the tests and this release does not have the fix. It will be necessary to build a Spark distribution from the latest from Spark's branch-3.2.

**Comment by andygrove** [comment]
Spark 3.2.0 RC3 is now available: https://dist.apache.org/repos/dist/dev/spark/v3.2.0-rc3-bin/

**Comment by res-life** [comment]
You are right, Spark 3.2.0 RC3 does not have this issue.
