### ISSUE TITLE
[FEA] Support approx_percentile on GPU with decimal type

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#3606]
**Is your feature request related to a problem? Please describe.**
I ran into an issue with approx_percentile and decimal types so I am planning on having these fall back to CPU in https://github.com/NVIDIA/spark-rapids/pull/3301 unless I can resolve the issue quickly and then address this in a follow-on PR.

```
E                   Caused by: java.lang.AssertionError:  value at 0 is null
E                   	at ai.rapids.cudf.HostColumnVectorCore.assertsForGet(HostColumnVectorCore.java:228)
E                   	at ai.rapids.cudf.HostColumnVectorCore.getLong(HostColumnVectorCore.java:301)
E                   	at com.nvidia.spark.rapids.RapidsHostColumnVectorCore.getDecimal(RapidsHostColumnVectorCore.java:171)
E                   	at org.apache.spark.sql.vectorized.ColumnarArray.getDecimal(ColumnarArray.java:143)
E                   	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
E                   	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
E                   	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:346)
E                   	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
```

**Describe the solution you'd like**
Enable the commented out tests in hash_aggregate_test,py

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
This was a red herring - the issue went away after upmerging cuDF
