### ISSUE TITLE
[BUG] Latest 21.10 snapshot jars failing with java.lang.IllegalArgumentException: Could not find Spark Shim Loader

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#3641]
**Describe the bug**
The latest snapshot jars from 09/23 for v21.10 are failing with the following error:

```
21/09/23 21:31:54 INFO ShimLoader: Loading shim for Spark version: 3.1.2.5.0-43944377
21/09/23 21:31:54 WARN ShimLoader: Overriding Spark shims provider to com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider. This may be an untested configuration!
21/09/23 21:31:54 ERROR SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: Could not find Spark Shim Loader for 3.1.2.5.0-43944377
	at com.nvidia.spark.rapids.ShimLoader$.$anonfun$detectShimProvider$14(ShimLoader.scala:244)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.ShimLoader$.detectShimProvider(ShimLoader.scala:244)
	at com.nvidia.spark.rapids.ShimLoader$.findShimProvider(ShimLoader.scala:262)
	at com.nvidia.spark.rapids.ShimLoader$.initShimProviderIfNeeded(ShimLoader.scala:92)
	at com.nvidia.spark.rapids.ShimLoader$.getShimClassLoader(ShimLoader.scala:161)
	at com.nvidia.spark.rapids.ShimLoader$.loadClass(ShimLoader.scala:293)
	at com.nvidia.spark.rapids.ShimLoader$.newInstanceOf(ShimLoader.scala:299)
	at com.nvidia.spark.rapids.ShimLoader$.newDriverPlugin(ShimLoader.scala:328)
	at com.nvidia.spark.SQLPlugin.driverPlugin(SQLPlugin.scala:29)
```

Looks like the `spark.rapids.shims-provider-override` config is not being honored and it is looking for internal spark version shim layer which is not provided.

**Steps/Code to reproduce bug**
Submit a simple Spark RAPIDS app using the latest snapshot jars from 09/23 for v21.10 and setting the `spark.rapids.shims-provider-override config`

Environment details (please complete the following information)

Environment location: YARN, Spark 3.1.2
Spark configuration settings related to the issue: `spark.rapids.shims-provider-override com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider`

**Comment by viadea** [comment]
@Niharikadutta I just shared a new snapshot jar with you. There are some snapshot jar issue currently. So we can close this case.
