### ISSUE TITLE
[BUG] Spark executors failing with error `no CUDA-capable device is detected` when `spark.plugins` is not set

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#3755]
**Describe the bug**
I recently started seeing this issue, when trying to submit a job to a regular non-GPU cluster, where executors start failing with the following error:

```
ERROR YarnCoarseGrainedExecutorBackend [dispatcher-Executor]: Executor self-exiting due to : Unable to create executor due to no CUDA-capable device is detected
ai.rapids.cudf.CudaException: no CUDA-capable device is detected
	at ai.rapids.cudf.Cuda.getDeviceCount(Native Method)
	at com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin.discoverResource(ExclusiveModeGpuDiscoveryPlugin.scala:54)
	at org.apache.spark.resource.ResourceUtils$.$anonfun$discoverResource$1(ResourceUtils.scala:391)
	at org.apache.spark.resource.ResourceUtils$.$anonfun$discoverResource$1$adapted(ResourceUtils.scala:390)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.resource.ResourceUtils$.discoverResource(ResourceUtils.scala:390)
	at org.apache.spark.resource.ResourceUtils$.$anonfun$getOrDiscoverAllResourcesForResourceProfile$3(ResourceUtils.scala:360)
```
This is for a YARN setup that does NOT have any GPU scheduling, NOR IS the following config set:
```
spark.plugins=com.nvidia.spark.SQLPlugin
```
Other Spark RAPIDS conf are set as follows, but I thought the main config enabling RAPIDS was the `spark.plugins` one which as I mentioned, IS NOT SET:

```
spark.rapids.sql.enabled true
spark.rapids.shims-provider-override com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider
spark.rapids.sql.concurrentGpuTasks 2
spark.executor.resource.gpu.amount 1
spark.executor.resource.gpu.discoveryScript /opt/spark/examples/src/main/scripts/getGpusResources.sh
spark.jars /path/to/rapids-4-spark_2.12-21.08.0.jar,/path/to/cudf-21.08.2-cuda11.jar
spark.resources.discoveryPlugin com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin
spark.kryo.registrator com.nvidia.spark.rapids.GpuKryoRegistrator
spark.task.resource.gpu.amount 0.25
spark.rapids.sql.explain NOT_ON_GPU
```
**Steps/Code to reproduce bug**
Submitting a job to a non-GPU Yarn cluster, with above mentioned configurations set.

**Expected behavior**
Job should run successfully and RAPIDS CuDF logic should not be initiated if `spark.plugins` is not set to `com.nvidia.spark.SQLPlugin`

**Environment details (please complete the following information)**
 - Environment location: YARN, Synapse
 - Spark configuration settings related to the issue: Mentioned above

**Comment by Niharikadutta** [comment]
@jlowe I'm re-opening this issue as it seems like despite removing the above mentioned Spark configs I'm still seeing jobs failing the following error:
```
21/10/2022:50:39INFOSparkContext:Submittedapplication:Sparkshell         
21/10/2022:50:39ERRORSparkContext:ErrorinitializingSparkContext.         
org.apache.spark.SparkException:Youmustspecifyanamountforgpu         
atorg.apache.spark.resource.ResourceUtils$.$anonfun$parseResourceRequest$1(ResourceUtils.scala:143)         
atscala.collection.immutable.Map$Map1.getOrElse(Map.scala:119)         
atorg.apache.spark.resource.ResourceUtils$.parseResourceRequest(ResourceUtils.scala:143)         
atorg.apache.spark.resource.ResourceUtils$.$anonfun$parseAllResourceRequests$1(ResourceUtils.scala:165)         
atscala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)         
atscala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:75)         
atscala.collection.TraversableLike.map(TraversableLike.scala:238)         
atscala.collection.TraversableLike.map$(TraversableLike.scala:231)         
atscala.collection.AbstractTraversable.map(Traversable.scala:108)         
atorg.apache.spark.resource.ResourceUtils$.parseAllResourceRequests(ResourceUtils.scala:165)
```

These are all the Spark configs I have set:

```
spark.rapids.sql.enabled true
spark.rapids.shims-provider-override com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider
spark.rapids.sql.concurrentGpuTasks 2
spark.executor.resource.gpu.discoveryScript /opt/spark/examples/src/main/scripts/getGpusResources.sh
spark.jars /path/to/rapids-4-spark_2.12-21.10.0-SNAPSHOT.jar,/path/to/cudf-21.10.0-cuda11.jar
spark.rapids.sql.explain NOT_ON_GPU
```

After I removed the `spark.executor.resource.gpu.discoveryScript /opt/spark/examples/src/main/scripts/getGpusResources.sh` config it seemed to have started. Does that mean there are total 5 configs that decide whether Spark/YARN is going to look for GPUs while submitting a job?
Could you please config all the configs that decide this since our environment will change based on these configurations for whether or not job is submitted to a CPU or GPU cluster:
```
spark.plugins
spark.resources.discoveryPlugin
spark.executor.resource.gpu.amount
spark.task.resource.gpu.amount
spark.executor.resource.gpu.discoveryScript
```

cc: @tgravescs , @viadea

**Comment by viadea** [comment]
I think the reason is : @Niharikadutta  if you want to run the spark jobs on CPU cluster, you should at least disable below parameter:
```
spark.rapids.sql.enabled false
```

Please try to disable spark.rapids.sql.enabled=false to see if you still face any issues

**Comment by rtarasov-mg** [comment]
Hi!
In our Hadoop cluster, we have one node with GPU and we will try to test SPARK-RAPIDS.
And the same issue when run spark-shell

```
21/12/08 08:41:29 INFO ShimLoader: Loading shim for Spark version: 3.1.2
21/12/08 08:41:29 INFO ShimLoader: Complete Spark build info: 3.1.2, , , , 2021-07-06T07:51:26Z
21/12/08 08:41:29 INFO ShimLoader: Forcing shim caller classloader update (default behavior). If it causes issues with userClassPathFirst, set spark.rapids.force.caller.classloader to false!
21/12/08 08:41:29 INFO ShimLoader: Falling back on ShimLoader caller's classloader org.apache.spark.util.MutableURLClassLoader@5138cb0f
21/12/08 08:41:29 INFO ShimLoader: Updating spark classloader org.apache.spark.util.MutableURLClassLoader@5138cb0f with the URLs: jar:file:/disk/yarn/usercache/analytics/appcache/application_1638445765009_9128/container_e37_1638445765009_9128_01_000002/rapids-4-spark_2.12-21.12.0.jar!/spark3xx-common/, jar:file:/disk/yarn/usercache/analytics/appcache/application_1638445765009_9128/container_e37_1638445765009_9128_01_000002/rapids-4-spark_2.12-21.12.0.jar!/spark312/
21/12/08 08:41:29 INFO ShimLoader: Spark classLoader org.apache.spark.util.MutableURLClassLoader@5138cb0f updated successfully
21/12/08 08:41:29 INFO RapidsPluginUtils: RAPIDS Accelerator build: {version=21.12.0, user=root, url=https://github.com/NVIDIA/spark-rapids.git, date=2021-12-08T14:16:26Z, revision=56a0f4c3e36a1fea920244dac3719d2914f14e3e, cudf_version=21.12.0, branch=main}
21/12/08 08:41:29 INFO RapidsPluginUtils: cudf build: {version=21.12.0, user=, date=2021-12-04T01:54:29Z, revision=f1ef2d2daf1a6053c8629f09956d52a5cf28c8f8, branch=HEAD}
21/12/08 08:41:29 WARN RapidsPluginUtils: RAPIDS Accelerator 21.12.0 using cudf 21.12.0. To disable GPU support set `spark.rapids.sql.enabled` to false
21/12/08 08:41:29 INFO RapidsExecutorPlugin: RAPIDS Accelerator build: {version=21.12.0, user=root, url=https://github.com/NVIDIA/spark-rapids.git, date=2021-12-08T14:16:26Z, revision=56a0f4c3e36a1fea920244dac3719d2914f14e3e, cudf_version=21.12.0, branch=main}
21/12/08 08:41:29 INFO RapidsExecutorPlugin: cudf build: {version=21.12.0, user=, date=2021-12-04T01:54:29Z, revision=f1ef2d2daf1a6053c8629f09956d52a5cf28c8f8, branch=HEAD}
21/12/08 08:41:29 INFO RapidsExecutorPlugin: Initializing memory from Executor Plugin
21/12/08 08:41:36 ERROR RapidsExecutorPlugin: Exception in the executor plugin
ai.rapids.cudf.CudaException: no CUDA-capable device is detected
	at ai.rapids.cudf.Cuda.setDevice(Native Method)
	at com.nvidia.spark.rapids.GpuDeviceManager$.setGpuDeviceAndAcquire(GpuDeviceManager.scala:95)
	at com.nvidia.spark.rapids.GpuDeviceManager$.$anonfun$initializeGpu$1(GpuDeviceManager.scala:125)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:23)
	at scala.Option.map(Option.scala:230)
	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpu(GpuDeviceManager.scala:125)
	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpuAndMemory(GpuDeviceManager.scala:134)
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:204)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:125)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:113)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:211)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:199)
	at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:253)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:222)
	at org.apache.spark.executor.Executor.<init>(Executor.scala:253)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:159)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

We prepare Yarn with Isolation and GPU Scheduling for this node.
Our test config
```
spark-shell \
     --master yarn \
     --conf spark.yarn.am.nodeLabelExpression=GPU \
     --conf spark.yarn.executor.nodeLabelExpression=GPU \
     --conf spark.rapids.sql.concurrentGpuTasks=1 \
     --driver-memory 2G \
     --num-executors 1 \
     --conf spark.executor.memory=4G \
     --conf spark.executor.cores=4 \
     --conf spark.executor.resource.gpu.amount=1 \
     --conf spark.task.cpus=1 \
     --conf spark.task.resource.gpu.amount=0.25 \
     --conf spark.rapids.memory.pinnedPool.size=2G \
     --conf spark.locality.wait=0s \
     --conf spark.rapids.sql.enabled=true \
     --conf spark.rapids.sql.explain=NOT_ON_GPU \
     --conf spark.plugins=com.nvidia.spark.SQLPlugin \
     --conf spark.sql.files.maxPartitionBytes=512m \
     --conf spark.executor.resource.gpu.discoveryScript=/home/analytics/getGpusResources.sh \
     --jars ${SPARK_CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR}
```

nvidia-smi on node with gpu
```
nvidia-smi
Wed Dec  8 09:01:22 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 30%   32C    P0    95W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by tgravescs** [comment]
so most likely this happens because your YARN setup is not right and the GPU is not visible in the yarn container.  Are you also using Docker?

You might try starting up an application but disable the sql plugin and then run a command to make sure the executors can see the GPUs.
ie remove  --conf spark.plugins=com.nvidia.spark.SQLPlugin
When spark-shell starts run something like:
```
val data = 1 to 20
val dataRDD =  sc.makeRDD(data, 20)
val pipeRDD = dataRDD.pipe("nvidia-smi")
pipeRDD.collect().foreach(println)
```

make sure the parallelism is enough to hit all your executors, or only use 1 executor to start with. You need to make sure the GPU is visible from the executor container.

Also if you are using GPU scheduling, make sure the executor was assigned a gpu. higher up in the executor log you should see something like:

```
21/12/06 18:41:28 INFO ResourceUtils: Resources for spark.executor:
gpu -> [name: gpu, addresses: 0]
21/12/06 18:41:28 INFO ResourceUtils: 
```

**Comment by rtarasov-mg** [comment]
Thanks for your reply!

Yarn without Docker.
I launched spark-shell without --conf spark.plugins=com.nvidia.spark.SQLPlugin
And tried your example
in the executor log
```
21/12/08 09:50:13 ERROR Executor: Exception in task 10.0 in stage 0.0 (TID 10)
java.lang.IllegalStateException: Subprocess exited with status 6. Command ran: nvidia-smi
	at org.apache.spark.rdd.PipedRDD$$anon$3.hasNext(PipedRDD.scala:200)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at org.apache.spark.rdd.PipedRDD$$anon$3.foreach(PipedRDD.scala:184)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
	at org.apache.spark.rdd.PipedRDD$$anon$3.to(PipedRDD.scala:184)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307)
	at org.apache.spark.rdd.PipedRDD$$anon$3.toBuffer(PipedRDD.scala:184)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
	at org.apache.spark.rdd.PipedRDD$$anon$3.toArray(PipedRDD.scala:184)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1030)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

And in executor log about gpu
```
21/12/08 09:49:28 INFO ResourceDiscoveryScriptPlugin: Discovering resources for gpu with script: /home/analytics/getGpusResources.sh
21/12/08 09:49:28 INFO ResourceUtils: ==============================================================
21/12/08 09:49:28 INFO ResourceUtils: Custom resources for spark.executor:
gpu -> [name: gpu, addresses: 0]
21/12/08 09:49:28 INFO ResourceUtils: ==============================================================
21/12/08 09:49:28 INFO YarnCoarseGrainedExecutorBackend: Successfully registered with driver
```

**Comment by tgravescs** [comment]
its good to see it assigned you a GPU address at least. So YARN and Spark are scheduling it.  I don't know what that error is though, it might be just because its not there or not executable.  Could you try just some basic linux command like:

val pipeRDD = dataRDD.pipe("ls /usr/bin/nvidia-smi")

If that errors its likely not there so something isn't setup right.

you could also:

val pipeRDD = dataRDD.pipe("ls /usr/bin/")

And parse that output looking for nvidia-smi.

**Comment by rtarasov-mg** [comment]
Of course
```
scala> val pipeRDD = dataRDD.pipe("ls /usr/bin/nvidia-smi")
pipeRDD: org.apache.spark.rdd.RDD[String] = PipedRDD[1] at pipe at <console>:25

scala> val pipeRDD = dataRDD.pipe("ls /usr/bin/")
pipeRDD: org.apache.spark.rdd.RDD[String] = PipedRDD[2] at pipe at <console>:25

scala>
```

**Comment by tgravescs** [comment]
you have to print out the results after running each:
```
val pipeRDD = dataRDD.pipe("ls /usr/bin/nvidia-smi")
pipeRDD.collect().foreach(println)
```

```
val pipeRDD = dataRDD.pipe("ls /usr/bin/")
pipeRDD.collect().foreach(println)

```

**Comment by rtarasov-mg** [comment]
Oh I'm sorry
I have no experience with it
```

scala> val pipeRDD = dataRDD.pipe("ls /usr/bin/nvidia-smi")
pipeRDD: org.apache.spark.rdd.RDD[String] = PipedRDD[3] at pipe at <console>:25

scala> pipeRDD.collect().foreach(println)
/usr/bin/nvidia-smi
/usr/bin/nvidia-smi
/usr/bin/nvidia-smi
```

**Comment by tgravescs** [comment]
Sorry this is a bit odd for me as I've never hit this. nvidia-smi there but it doesn't seem to let you run it. Perhaps croups permissions issue.

If you run the pipe with "/usr/bin/nvidia-smi" can you check the executor logs to see if there are any other errors there?  

 I guess one other thing is do you have the proper cuda runtime installed? Check /usr/local/cuda*.

if you haven't yet you may also just try running the Rapids Plugin in local mode to take YARN out of the picture and make sure the node itself has everything it needs. Sometimes its easier to see logs in local-cluster mode actually, you could try:

```
$SPARK_HOME/bin/spark-shell  --master local-cluster[1,1,2048] \
 --conf spark.plugins=com.nvidia.spark.SQLPlugin \
     --jars ${SPARK_CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR} \
    --conf spark.executor.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR}  \
    --conf spark.driver.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR}
```

Once that starts in a different terminal look at $SPARK_HOME/work/app-*/0/stderr.  where app-* is actually the app id given when you started the spark-shell:
`Spark context available as 'sc' (master = local-cluster[1,1,2048], app id = app-20211208200458-0000).
`
If that started ok and you see the plugin initialize ok:
21/12/08 20:05:06 INFO GpuDeviceManager: Initializing RMM ARENA pool size = 15301.4375 MB on gpuId 0

Then I'm guessing its something with cgroups but unfortunately I don't know what off hand.

**Comment by tgravescs** [comment]
Actually thinking about this some more, if the executor log has:

```
21/12/08 09:49:28 INFO ResourceDiscoveryScriptPlugin: Discovering resources for gpu with script: /home/analytics/getGpusResources.sh
21/12/08 09:49:28 INFO ResourceUtils: ==============================================================
21/12/08 09:49:28 INFO ResourceUtils: Custom resources for spark.executor:
gpu -> [name: gpu, addresses: 0]
21/12/08 09:49:28 INFO ResourceUtils: ==============================================================
21/12/08 09:49:28 INFO YarnCoarseGrainedExecutorBackend: Successfully registered with driver
```

That means that the executor did run nvidia-smi (assuming your /home/analytics/getGpusResources.sh script is the normal one Spark has). So perhaps it is more in the cuda setup so hopefully running in local-cluster mode on that node might show help.  or manually check the /usr/local/cuda* and make sure it has 11.0 or newer runtime in there.

```
$ ls -d /usr/local/cuda*
/usr/local/cuda-11.0
```

**Comment by rtarasov-mg** [comment]
>If you run the pipe with "/usr/bin/nvidia-smi" can you check the executor logs to see if there are any other errors there?
No one errors

In local mode works :)
```
21/12/08 12:44:09 INFO GpuDeviceManager: Initializing RMM ARENA initial size = 22698.5625 MB, max size = 23244.3125 MB on gpuId 0
21/12/08 12:44:09 INFO GpuDeviceManager: Using per-thread default stream
21/12/08 12:44:09 INFO ShimDiskBlockManager: Created local directory at /tmp/spark-00f84643-a8d1-4777-86af-2029ee983cfa/executor-3879e325-cf13-40bc-bc13-fb53ee2d38a3/blockmgr-a89b9975-09ac-48b5-bb03-205148e79f9e
21/12/08 12:44:09 INFO RapidsBufferCatalog: Installing GPU memory handler for spill
21/12/08 12:44:09 INFO RapidsExecutorPlugin: The number of concurrent GPU tasks allowed is 1
21/12/08 12:44:09 INFO ExecutorPluginContainer: Initialized executor component for plugin com.nvidia.spark.SQLPlugin.

[root@bigdata1a-gpu root]# nvidia-smi
Wed Dec  8 12:47:15 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 30%   25C    P8     8W / 350W |  23245MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     21794      C   ...k64/jdk1.8.0_112/bin/java    23243MiB |
+-----------------------------------------------------------------------------+
```

```
[root@bigdata1a-gpu ~]# ls -d /usr/local/cuda*
/usr/local/cuda  /usr/local/cuda-11  /usr/local/cuda-11.5
```

**Comment by rtarasov-mg** [comment]
As a result, I found a solution.
The problem was that the YARN client needed to be reinstalled with new config after YARN on GPU scheduling was enabled.
I missed it.
@tgravescs Thank you for taking the time to help me.
