### ISSUE TITLE
[BUG] Databricks class cast exception failure 

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3760]
**Describe the bug**
Running a SQL query on databricks failed with the following:

java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2411)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)

Note the failure happens on the driver trying to fetch the task results

**Comment by tgravescs** [comment]
fixed by https://github.com/NVIDIA/spark-rapids/pull/3756
