### ISSUE TITLE
[BUG] Hash aggregate with structs crashes with IllegalArgumentException

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3775]
**Describe the bug**
A query with a hash aggregate on structs can crash with an `IllegalArgumentException` stating the struct type "is not supported for GPU processing yet."

**Steps/Code to reproduce bug**
Execute the following in a Scala Spark shell:
```
import org.apache.spark.sql.Row
import org.apache.spark.sql.types._

val data = Seq(
    Row(Row("Adam ","","Green"),"1","M",1000),
    Row(Row("Bob ","Middle","Green"),"2","M",2000),
    Row(Row("Cathy ","","Green"),"3","F",3000)
)

val schema = (new StructType()
  .add("name",new StructType()
    .add("firstname",StringType)
    .add("middlename",StringType)
    .add("lastname",StringType))
  .add("id",StringType)
  .add("gender",StringType)
  .add("salary",IntegerType))

val df = spark.createDataFrame(spark.sparkContext.parallelize(data),schema)
df.write.format("parquet").mode("overwrite").save("/tmp/testparquet")

val df2 = spark.read.parquet("/tmp/testparquet")
val df3 = spark.read.parquet("/tmp/testparquet")

df2.createOrReplaceTempView("df2")
df3.createOrReplaceTempView("df3")

val nested_struct_df=spark.sql("select struct(name, struct(name.firstname, name.lastname) as newname) as col,name from df2")
nested_struct_df.createOrReplaceTempView("nested_struct_df")

val resultdf=spark.sql("select struct(name, struct(name.firstname, name.lastname) as newname) as col,name from df2 union select struct(name, struct(name.firstname, name.lastname) as newname) as col,name from df3")

resultdf.createOrReplaceTempView("resultdf")
spark.sql("select a.* from resultdf a, resultdf b where a.name=b.name").show
```

This will result in a stacktrace like the following:
```
Caused by: java.lang.IllegalArgumentException: StructType(StructField(name,StructType(StructField(firstname,StringType,true), StructField(middlename,StringType,true), StructField(lastname,StringType,true)),true), StructField(newname,StructType(StructField(firstname,StringType,true), StructField(lastname,StringType,true)),false)) is not supported for GPU processing yet.
  at com.nvidia.spark.rapids.GpuColumnVector.getNonNestedRapidsType(GpuColumnVector.java:504)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$processIncomingBatch$3(aggregate.scala:614)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:247)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$processIncomingBatch$2(aggregate.scala:613)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:163)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:160)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:160)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:195)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$processIncomingBatch$1(aggregate.scala:608)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:247)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.processIncomingBatch(aggregate.scala:607)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$aggregateInputBatches$1(aggregate.scala:354)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:247)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:352)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:307)
  at scala.Option.getOrElse(Option.scala:189)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:304)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:247)
  at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:291)
  at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:307)
  at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
  at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
```

**Expected behavior**
The query should not crash.

**Comment by abellina** [comment]
The parquet part is not the issue. I get it to happen from the original in memory df.

**Comment by jlowe** [comment]
This is a case of the type comparison failing because nullability of fields can change as a batch flows through the expressions.  We should be checking for structural equivalence instead of an exact type match.
