### ISSUE TITLE
[BUG] Yarn setup with Isolation mode causes Spark executors to die

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#3794]
**Describe the bug**
I am trying to setup YARN with isolation as outlined in [this documentation](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-313-with-isolation-and-gpu-scheduling-enabled), and am seeing some issues running a Spark job on 64-core GPU VMs (having 4 GPUs in it).

I see a lot of Connection refused errors like so sprinkled throughout the driver logs:
```
21/10/12 01:44:24 ERROR RawSocketSender: org.fluentd.logger.sender.RawSocketSender
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.fluentd.logger.sender.RawSocketSender.connect(RawSocketSender.java:85)
	at org.fluentd.logger.sender.RawSocketSender.reconnect(RawSocketSender.java:94)
	at org.fluentd.logger.sender.RawSocketSender.flush(RawSocketSender.java:193)
	at org.fluentd.logger.sender.RawSocketSender.send(RawSocketSender.java:184)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:149)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:131)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:126)
	at org.fluentd.logger.FluentLogger.log(FluentLogger.java:101)
	at org.fluentd.logger.FluentLogger.log(FluentLogger.java:86)
	at com.microsoft.mdsdclient.MessageSendingRunnable$1.call(Unknown Source)
	at com.microsoft.mdsdclient.MessageSendingRunnable$1.call(Unknown Source)
	at com.microsoft.mdsdclient.RetryUtil.retry(Unknown Source)
	at com.microsoft.mdsdclient.RetryUtil.retry(Unknown Source)
	at com.microsoft.mdsdclient.MessageSendingRunnable.sendMessage(Unknown Source)
	at com.microsoft.mdsdclient.MessageSendingRunnable.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```
And all executors start and then get killed due to the following error as seen in executor logs:
```
ERROR RapidsExecutorPlugin [dispatcher-Executor]: Exception in the executor plugin
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: CUDA error at: /home/jenkins/agent/workspace/jenkins-cudf-release-26-cuda11/cpp/build/_deps/rmm-src/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory
	at ai.rapids.cudf.Rmm.initializeInternal(Native Method)
	at ai.rapids.cudf.Rmm.initialize(Rmm.java:228)
	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeRmm(GpuDeviceManager.scala:289)
```
These are all the additional properties I have added in my `yarn-site.xml` file as per above mentioned documentation:
```
    <property>
      <name>yarn.resource-types</name>
      <value>yarn.io/gpu</value>
    </property>
    <property>
      <name>yarn.scheduler.capacity.resource-calculator</name>
      <value>org.apache.hadoop.yarn.util.resource.DominantResourceCalculator</value>
    </property>
    <property>
      <name>yarn.nodemanager.resource-plugins</name>
      <value>yarn.io/gpu</value>
    </property>
    <property>
      <name>yarn.nodemanager.linux-container-executor.cgroups.mount</name>
      <value>true</value>
    </property>
    <property>
      <name>yarn.nodemanager.linux-container-executor.cgroups.mount-path</name>
      <value>/sys/fs/cgroup</value>
    </property>
    <property>
      <name>yarn.nodemanager.linux-container-executor.cgroups.hierarchy</name>
      <value>yarn</value>
    </property>
```
In addition to this I've created a new `container-executor.cfg` file the contents of which are as follows:
```
yarn.nodemanager.linux-container-executor.group=yarn

[gpu]
module.enabled=true

[cgroups]
# This should be same as yarn.nodemanager.linux-container-executor.cgroups.mount-path inside yarn-site.xml
root=/sys/fs/cgroup
# This should be same as yarn.nodemanager.linux-container-executor.cgroups.hierarchy inside yarn-site.xml
yarn-hierarchy=yarn
```
Besides the above, here are all my Spark RAPIDS related config (I have a 3 node cluster, using 64-core T4s, 4 GPUs each):
```
spark.plugins com.nvidia.spark.SQLPlugin
spark.rapids.sql.enabled true
spark.rapids.shims-provider-override com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider
spark.rapids.sql.concurrentGpuTasks 2
spark.executor.resource.gpu.amount 1
spark.executor.resource.gpu.discoveryScript /opt/spark/examples/src/main/scripts/getGpusResources.sh
spark.jars /path/to/rapids-4-spark_2.12-21.08.0.jar,/path/to/cudf-21.08.2-cuda11.jar
spark.resources.discoveryPlugin com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin
spark.kryo.registrator com.nvidia.spark.rapids.GpuKryoRegistrator
spark.task.resource.gpu.amount 0.25
spark.rapids.sql.explain NOT_ON_GPU
spark.driver.memory 96g
spark.driver.cores 16
spark.executor.memory 96g
spark.executor.cores 16
spark.executor.instances 11
```
Please let me know if I am missing something in the setup or what I need to be doing differently to not face this issue. To add, the above Spark configs have worked on Yarn without isolation, when setting `exclusive_mode` on all the GPUs inside the cluster.

**Steps/Code to reproduce bug**
Provided all information above.

**Expected behavior**
Spark job should run successfully with requested configuration

**Environment details (please complete the following information)**
 - Environment location: YARN, Synapse
 - Spark configuration settings related to the issue: provided above

**Additional context**
The same environment works fine on a 16-core VM cluster (which has only 1 GPU in it).

**Comment by viadea** [comment]
And the key is to make cgroups work. 
```
GPU isolation uses CGroup devices controller to do per-GPU device isolation. Following configs should be added to yarn-site.xml to automatically mount CGroup sub devices, otherwise admin has to manually create devices subfolder in order to use this feature.
```
I would suggest you troubleshoot with cgroup expert on this.
