### ISSUE TITLE
[BUG] Spark3.1 StringFallbackSuite regexp_replace null cpu fall back test fails.

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#382]
StringFallbackSuite:
- NOT ON GPU[ProjectExec,Alias,RegExpReplace,AttributeReference,Literal]: String regexp_replace null cpu fall back *** FAILED ***
  java.lang.AssertionError: assertion failed: Could not find RegExpReplace in the GPU plan
*(1) GpuColumnarToRow false
+- GpuProject [null AS regexp_replace(strings, CAST(NULL AS STRING), D)#18652]
   +- GpuCoalesceBatches TargetSize(2147483647)
      +- GpuColumnarExchange gpuroundrobinpartitioning(1), false, [id=#36347]
         +- GpuFileGpuScan csv [] Batched: true, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/home/tgraves/workspace/spark-rapids/tests/target/test-classes/strings.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<>
  at scala.Predef$.assert(Predef.scala:223)
  at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertDidFallBack(Plugin.scala:194)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.$anonfun$testGpuFallback$1(SparkQueryCompareTestSuite.scala:273)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)

Spark 3.1 has tagged nullIntolerant, plan shows up as
 +- GpuProject [null AS regexp_replace(strings, CAST(NULL AS STRING), D)#18652]

Spark 3.0:
*(1) Project [regexp_replace(strings#0, null, D) AS regexp_replace(strings, CAST(NULL AS STRING), D)#4]

**Comment by kuhushukla** [comment]
I will take this up first thing tomorrow

**Comment by tgravescs** [comment]
sorry I should have added, it might be hard for you without other changes for spark 3.1, I got this writing the shim layer.

**Comment by tgravescs** [comment]
once https://github.com/NVIDIA/spark-rapids/pull/414/f gets in we can look at this.

**Comment by kuhushukla** [comment]
> once #414 gets in we can look at this.

Sounds good
