### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ad895d** [NVIDIA/spark-rapids#3872]
When using Rapids plugin with Databricks pass through authentication doesn’t work.

when selecting from delta tables Security Token Expired” error is displayed. 

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
When creating Databricks cluster enable pass through authentication on standard cluster. Issue select statement on any delta table which is not on dbfs.

**Expected behavior**
Pass through authentication should work.

**Environment details (please complete the following information)**
 - Environment : Databricks 8.2 runtime 
 
 - Spark configuration settings related to the issue
 Pass through authentication enabled on Databricks runtime environment 8.2

**Additional context**
All functionality works as intended when data is on dbfs

**Comment by viadea** [comment]
@jlowe You are right. 
I just used latest 21.12 snapshot jars and verified that https://github.com/NVIDIA/spark-rapids/issues/3903 is fixed.
However when writing dataframe to blob storage using passthrough auth, the issue still exists.

Here is my reproduce statement:
```
dfcustomer.write.mode("overwrite").format("delta").save("abfss://containerxxx@storagexxx.dfs.core.windows.net/delta/tablename")
```

It will fail with:
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 25.0 failed 4 times, most recent failure: Lost task 1.3 in stage 25.0 (TID 488) (10.13.1.6 executor 0): java.util.concurrent.ExecutionException: com.databricks.backend.daemon.data.client.adl.AzureCredentialNotFoundException: Could not find ADLS Gen2 Token
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readPartFiles$7(GpuMultiFileReader.scala:820)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readPartFiles$7$adapted(GpuMultiFileReader.scala:819)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readPartFiles$4(GpuMultiFileReader.scala:819)
	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:87)
	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:85)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.closeOnExcept(GpuMultiFileReader.scala:236)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readPartFiles$1(GpuMultiFileReader.scala:804)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:236)
```

**Comment by viadea** [comment]
As @jlowe shared, setting `spark.rapids.sql.format.parquet.reader.type=PERFILE` can workaround this issue.

When `spark.rapids.sql.format.parquet.reader.type=COALESCING` or `MULTITHREADED`, the issue can be reproduced.

**Comment by sameerz** [comment]
Moving to the backlog as the PERFILE option resolved the issue for the time being.

**Comment by jlowe** [comment]
> Moving to the backlog as the PERFILE option resolved the issue for the time being.

Has there been any performance measurements done on the workaround?  `PERFILE` will likely perform noticeably worse than the default, and that may influence the priority.
