### ISSUE TITLE
[BUG] Some TPC-DS queries are failing using the latest v21.10 RAPIDS jars

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#3913]
**Describe the bug**
Some TPC-DS queries (q10, q35, q95) fail using the latest v21.10 jars with the following error:

```
ERROR ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.SortExec.(Lscala/collection/Seq;ZLorg/apache/spark/sql/execution/SparkPlan;I)V
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.SortExec.(Lscala/collection/Seq;ZLorg/apache/spark/sql/execution/SparkPlan;I)V
	at com.nvidia.spark.rapids.GpuOverrides.$anonfun$ensureOrdering$1(GpuOverrides.scala:3646)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at com.nvidia.spark.rapids.GpuOverrides.com$nvidia$spark$rapids$GpuOverrides$$ensureOrdering(GpuOverrides.scala:3641)
	at com.nvidia.spark.rapids.GpuOverrides$$anonfun$addSortsIfNeeded$1.applyOrElse(GpuOverrides.scala:3664)
	at com.nvidia.spark.rapids.GpuOverrides$$anonfun$addSortsIfNeeded$1.applyOrElse(GpuOverrides.scala:3662)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$2(TreeNode.scala:342)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:74)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:342)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:339)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
```
This could be happening due to the internal changes made in our custom Spark distro but I just wanted to confirm if that is the case, and if so, to get some guidance on how to provide the shim layer of custom Spark version.

**Environment details**
 - Environment location: YARN, Azure Synapse]

**Additional context**
This is run against custom Spark distro.

**Comment by viadea** [comment]
Hi @tgravescs , I can have a minimum repro for this issue now.
Here is the mini repro:
```
select
  count(*)
from
  customer c
where
  exists (select * from store_sales
          where c.c_customer_sk = ss_customer_sk) 
          AND
   (exists (select * from web_sales
            where c.c_customer_sk = ws_bill_customer_sk) or
    exists (select * from catalog_sales
            where c.c_customer_sk = cs_ship_customer_sk))
```
Of course, this only happens in Synapse, not reproduced locally.
The reason why I say this is minimum reproduce is:
1. If I remove any of the "exists" join condition, the query will work fine.
2. If I changed "OR" to "AND", the query will work fine.
3. If I change `AND` to `OR`, the query will work fine.

So basically it needs 3 SMJs there with below condition to reproduce.
Exists_SMJ AND (Exists_SMJ OR Exists_SMJ)

Below are the full stacktrace:
```
Py4JJavaError: An error occurred while calling o822.showString.
: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.SortExec.<init>(Lscala/collection/Seq;ZLorg/apache/spark/sql/execution/SparkPlan;I)V
    at com.nvidia.spark.rapids.GpuOverrides.$anonfun$ensureOrdering$1(GpuOverrides.scala:3646)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at scala.collection.TraversableLike.map(TraversableLike.scala:238)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
    at scala.collection.immutable.List.map(List.scala:298)
    at com.nvidia.spark.rapids.GpuOverrides.com$nvidia$spark$rapids$GpuOverrides$$ensureOrdering(GpuOverrides.scala:3641)
    at com.nvidia.spark.rapids.GpuOverrides$$anonfun$addSortsIfNeeded$1.applyOrElse(GpuOverrides.scala:3664)
    at com.nvidia.spark.rapids.GpuOverrides$$anonfun$addSortsIfNeeded$1.applyOrElse(GpuOverrides.scala:3662)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$2(TreeNode.scala:342)
    at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:74)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:342)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:406)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:359)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:406)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:359)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:406)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:359)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:406)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:359)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:406)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:359)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:339)
    at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:408)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:406)
    at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:359)
    at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:339)
    at com.nvidia.spark.rapids.GpuOverrides.addSortsIfNeeded(GpuOverrides.scala:3662)
    at com.nvidia.spark.rapids.GpuOverrides.applyOverrides(GpuOverrides.scala:3620)
    at com.nvidia.spark.rapids.GpuOverrides.$anonfun$apply$2(GpuOverrides.scala:3576)
    at com.nvidia.spark.rapids.GpuOverrides$.logDuration(GpuOverrides.scala:454)
    at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:3568)
    at com.nvidia.spark.rapids.GpuQueryStagePrepOverrides.apply(GpuOverrides.scala:3554)
    at com.nvidia.spark.rapids.GpuQueryStagePrepOverrides.apply(GpuOverrides.scala:3550)
    at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec$.$anonfun$applyPhysicalRules$2(AdaptiveSparkPlanExec.scala:690)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
    at scala.collection.immutable.List.foldLeft(List.scala:89)
    at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec$.applyPhysicalRules(AdaptiveSparkPlanExec.scala:689)
    at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$initialPlan$1(AdaptiveSparkPlanExec.scala:134)
    at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
    at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.<init>(AdaptiveSparkPlanExec.scala:133)
    at org.apache.spark.sql.execution.adaptive.InsertAdaptiveSparkPlan.applyInternal(InsertAdaptiveSparkPlan.scala:61)
    at org.apache.spark.sql.execution.adaptive.InsertAdaptiveSparkPlan.apply(InsertAdaptiveSparkPlan.scala:42)
    at org.apache.spark.sql.execution.adaptive.InsertAdaptiveSparkPlan.apply(InsertAdaptiveSparkPlan.scala:39)
    at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:383)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
    at scala.collection.immutable.List.foldLeft(List.scala:89)
    at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:382)
    at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:118)
    at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
    at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:144)
    at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
    at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:144)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:118)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:111)
    at org.apache.spark.sql.execution.QueryExecution.$anonfun$simpleString$2(QueryExecution.scala:162)
    at org.apache.spark.sql.execution.ExplainUtils$.processPlan(ExplainUtils.scala:115)
    at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:162)
    at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:207)
    at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:176)
    at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:98)
    at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
    at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
    at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
    at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
    at org.apache.spark.sql.Dataset.head(Dataset.scala:2722)
    at org.apache.spark.sql.Dataset.take(Dataset.scala:2929)
    at org.apache.spark.sql.Dataset.getRows(Dataset.scala:301)
    at org.apache.spark.sql.Dataset.showString(Dataset.scala:338)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:282)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:238)
    at java.lang.Thread.run(Thread.java:748)
```

Below are driver log snippet:
```
21/11/03 22:24:35 WARN GpuOverrides: 
*Exec <HashAggregateExec> will run on GPU
  *Expression <AggregateExpression> count(1) will run on GPU
    *Expression <Count> count(1) will run on GPU
  *Expression <Alias> cast(count(1)#409L as string) AS count(1)#413 will run on GPU
    *Expression <Cast> cast(count(1)#409L as string) will run on GPU
  *Exec <ShuffleExchangeExec> will run on GPU
    *Partitioning <SinglePartition$> will run on GPU
    *Exec <HashAggregateExec> will run on GPU
      *Expression <AggregateExpression> partial_count(1) will run on GPU
        *Expression <Count> count(1) will run on GPU
      *Exec <ProjectExec> will run on GPU
        *Exec <FilterExec> will run on GPU
          *Expression <Or> (exists#415 OR exists#416) will run on GPU
          !Exec <SortMergeJoinExec> cannot run on GPU because ExistenceJoin(exists#416) currently is not supported
            @Expression <AttributeReference> c_customer_sk#0 could run on GPU
            @Expression <AttributeReference> cs_ship_customer_sk#132 could run on GPU
            !Exec <SortMergeJoinExec> cannot run on GPU because ExistenceJoin(exists#415) currently is not supported
              @Expression <AttributeReference> c_customer_sk#0 could run on GPU
              @Expression <AttributeReference> ws_bill_customer_sk#197 could run on GPU
              *Exec <SortMergeJoinExec> will run on GPU
                #Exec <SortExec> could run on GPU but is going to be removed because replacing sortMergeJoin with shuffleHashJoin
                  #Expression <SortOrder> c_customer_sk#0 ASC NULLS FIRST could run on GPU but is going to be removed because parent plan is removed
                  *Exec <ShuffleExchangeExec> will run on GPU
                    *Partitioning <HashPartitioning> will run on GPU
                    *Exec <FileSourceScanExec> will run on GPU
                #Exec <SortExec> could run on GPU but is going to be removed because replacing sortMergeJoin with shuffleHashJoin
                  #Expression <SortOrder> ss_customer_sk#82 ASC NULLS FIRST could run on GPU but is going to be removed because parent plan is removed
                  *Exec <ShuffleExchangeExec> will run on GPU
                    *Partitioning <HashPartitioning> will run on GPU
                    *Exec <ProjectExec> will run on GPU
                      *Exec <FileSourceScanExec> will run on GPU
              *Exec <SortExec> will run on GPU
                *Expression <SortOrder> ws_bill_customer_sk#197 ASC NULLS FIRST will run on GPU
                *Exec <ShuffleExchangeExec> will run on GPU
                  *Partitioning <HashPartitioning> will run on GPU
                  *Exec <ProjectExec> will run on GPU
                    *Exec <FileSourceScanExec> will run on GPU
            *Exec <SortExec> will run on GPU
              *Expression <SortOrder> cs_ship_customer_sk#132 ASC NULLS FIRST will run on GPU
              *Exec <ShuffleExchangeExec> will run on GPU
                *Partitioning <HashPartitioning> will run on GPU
                *Exec <ProjectExec> will run on GPU
                  *Exec <FileSourceScanExec> will run on GPU
```

**Comment by viadea** [comment]
But I can reproduce the fallback on local workstation for above query in 21.10 or 21.08 release:
```
scala> spark.sql(query).explain()
21/11/03 23:19:56 WARN GpuOverrides:
          !Exec <SortMergeJoinExec> cannot run on GPU because ExistenceJoin(exists#225) currently is not supported
            @Expression <AttributeReference> c_customer_sk#0 could run on GPU
            @Expression <AttributeReference> cs_ship_customer_sk#156 could run on GPU
            !Exec <SortMergeJoinExec> cannot run on GPU because ExistenceJoin(exists#224) currently is not supported
              @Expression <AttributeReference> c_customer_sk#0 could run on GPU
              @Expression <AttributeReference> ws_bill_customer_sk#85 could run on GPU
```

**Comment by Niharikadutta** [comment]
Thanks @viadea and @tgravescs for helping with this issue. I was able to get these queries to run by adding the Synapse Spark shim for RAPIDS. I am closing this issue now.
