### ISSUE TITLE
[FEA] Support arrays with nulls in the input of `GpuRowBasedUDF` for Spark 3.1.1+

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#3942]
This is a follow on issue for #3897.

When the input of `GpuRowBasedUDF` contains arrays with nulls, the UDF will run into the below error for Spark 3.1.1+ during our Unit tests where the Java assertion is enabled.
```
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 27.0 failed 1 times, most recent failure: Lost task 0.0 in stage 27.0 (TID 27) (liangcail-ubuntu18 executor driver): java.lang.AssertionError:  value at 6 is null
	at ai.rapids.cudf.HostColumnVectorCore.assertsForGet(HostColumnVectorCore.java:228)
	at ai.rapids.cudf.HostColumnVectorCore.getInt(HostColumnVectorCore.java:254)
	at com.nvidia.spark.rapids.RapidsHostColumnVectorCore.getInt(RapidsHostColumnVectorCore.java:107)
	at org.apache.spark.sql.vectorized.ColumnarArray.getInt(ColumnarArray.java:128)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.MapObjects_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:182)
	at org.apache.spark.sql.rapids.GpuRowBasedScalaUDF.$anonfun$scalaConverter$2(GpuScalaUDF.scala:123)
	at org.apache.spark.sql.rapids.GpuRowBasedScalaUDF.$anonfun$childAccessors$2(GpuScalaUDF.scala:156)
```

So in the PR #3897, we let it fall back to CPU for this case for now.
However, we need to eventually support this case for Spark 3.1.1+, since we already do for Spark3.0.x.

[Update] Everything works well as the CPU under production envs where the Java assertion is disabled.

**Comment by firestarman** [comment]
The null error mentioned in description is probably a bug of code generation in Spark .

The below code is generated from the 3 lines [1095-1097](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/objects/objects.scala#L1095) for this test case here.
```
/* 076 */       while (loopIndex_0 < dataLength_0) {
/* 077 */         value_MapObject_lambda_variable_1 = (int) (value_4.getInt(loopIndex_0));
/* 078 */         isNull_MapObject_lambda_variable_1 = value_4.isNullAt(loopIndex_0);
```
`value_4` is an ArrayData, and you can see here `getInt` is called before `isNullAt`.
```
/* 061 */     boolean isNull_4 = i.isNullAt(0);
/* 062 */     ArrayData value_4 = isNull_4 ?
/* 063 */     null : (i.getArray(0));
``` 

And the log I added for debugging in `RapidsHostColumnVectorCore` also proved this calling order.
```
Array of Int
====> lilc getArray: row at 0 is not null
====> lilc getInt: row at 0 is not null
====> lilc isNullAt: row at 0 is not null
====> lilc getInt: row at 1 is not null
====> lilc isNullAt: row at 1 is not null
====> lilc getArray: row at 1 is not null
...
```
So we can choose to use Catalyst converter for arrays with nulls until this was fixed in Spark.

**Comment by firestarman** [comment]
On the other hand, seems it was not always reasonale to throw exception when trying to get a null value.
For this case here, even the `getInt ` is called first, but the value will be not used. So we can return any value when readin nulls instead of throwing an exception.
