### ISSUE TITLE
[BUG] cudf_udf tests fail on nightly Integration test run

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4042]
**Describe the bug**
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_with_column[small data]
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_with_column[large data]
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_sql - py4j.protocol.Py4JJ...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_select - py4j.protocol.Py...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_map_in_pandas - py4j.prot...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_group_apply - py4j.protoc...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_group_apply_in_pandas - p...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_group_agg - py4j.protocol...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_sql_group - py4j.protocol...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_window - py4j.protocol.Py...
14:16:01  FAILED ../../src/main/python/udf_cudf_test.py::test_cogroup[ALLOW_NON_GPU(GpuFlatMapCoGroupsInPandasExec,PythonUDF)]
14:16:01  ========= 11 failed, 11340 deselected, 20 warnings in 91.04s (0:01:31) =========

**Comment by pxLi** [comment]
**ImportError: /opt/conda/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference**

executor logs.
```
21/11/05 19:14:42 INFO PythonWorkerFactory: Python daemon module in PySpark is set to [rapids.daemon] in 'spark.python.daemon.module', using this to start the daemon up. Note that this configuration only has an effect when 'spark.python.use.daemon' is enabled and the platform is not Windows.
INFO: Process 20502 found CUDA visible device(s): 0
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/jenkins-rapids_it-3.0.x-SNAPSHOT-dev-github-249/jars/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar/rapids/daemon.py", line 131, in manager
  File "/home/jenkins/agent/workspace/jenkins-rapids_it-3.0.x-SNAPSHOT-dev-github-249/jars/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar/rapids/worker.py", line 37, in initialize_gpu_mem
    from cudf import rmm
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/opt/conda/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /opt/conda/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
INFO: Process 20503 found CUDA visible device(s): 0
21/11/05 19:14:43 ERROR Executor: Exception in task 3.0 in stage 1.0 (TID 9)
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.api.python.PythonWorkerFactory.createSocket$1(PythonWorkerFactory.scala:120)
	at org.apache.spark.api.python.PythonWorkerFactory.liftedTree1$1(PythonWorkerFactory.scala:136)
	at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:135)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:105)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:119)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:131)
	at org.apache.spark.sql.rapids.execution.python.GpuArrowEvalPythonExec.$anonfun$doExecuteColumnar$2(GpuArrowEvalPythonExec.scala:618)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:463)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/11/05 19:14:43 INFO CoarseGrainedExecutorBackend: Got assigned task 12
21/11/05 19:14:43 INFO Executor: Running task 3.1 in stage 1.0 (TID 12)
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/jenkins-rapids_it-3.0.x-SNAPSHOT-dev-github-249/jars/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar/rapids/daemon.py", line 131, in manager
  File "/home/jenkins/agent/workspace/jenkins-rapids_it-3.0.x-SNAPSHOT-dev-github-249/jars/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar/rapids/worker.py", line 37, in initialize_gpu_mem
    from cudf import rmm
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/opt/conda/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /opt/conda/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
INFO: Process 20506 found CUDA visible device(s): 0
21/11/05 19:14:43 ERROR Executor: Exception in task 1.0 in stage 1.0 (TID 7)
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.api.python.PythonWorkerFactory.createSocket$1(PythonWorkerFactory.scala:120)
	at org.apache.spark.api.python.PythonWorkerFactory.liftedTree1$1(PythonWorkerFactory.scala:136)
	at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:135)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:105)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:119)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:131)
	at org.apache.spark.sql.rapids.execution.python.GpuArrowEvalPythonExec.$anonfun$doExecuteColumnar$2(GpuArrowEvalPythonExec.scala:618)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:463)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/11/05 19:14:43 INFO CoarseGrainedExecutorBackend: Got assigned task 13
21/11/05 19:14:43 INFO Executor: Running task 1.1 in stage 1.0 (TID 13)
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/jenkins-rapids_it-3.0.x-SNAPSHOT-dev-github-249/jars/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar/rapids/daemon.py", line 131, in manager
  File "/home/jenkins/agent/workspace/jenkins-rapids_it-3.0.x-SNAPSHOT-dev-github-249/jars/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar/rapids/worker.py", line 37, in initialize_gpu_mem
    from cudf import rmm
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/opt/conda/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /opt/conda/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
21/11/05 19:14:43 INFO PythonRunner: Times: total = 7, boot = -1990, init = 1997, finish = 0
21/11/05 19:14:43 ERROR Executor: Exception in task 5.0 in stage 1.0 (TID 11)
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.api.python.PythonWorkerFactory.createSocket$1(PythonWorkerFactory.scala:120)
	at org.apache.spark.api.python.PythonWorkerFactory.liftedTree1$1(PythonWorkerFactory.scala:136)
	at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:135)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:105)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:119)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:131)
	at org.apache.spark.sql.rapids.execution.python.GpuArrowEvalPythonExec.$anonfun$doExecuteColumnar$2(GpuArrowEvalPythonExec.scala:618)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:463)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by firestarman** [comment]
Looks like the `import` error caused a crash in Python process, so the JVM read the `EOF` unexpectedly and threw the exception up.

**Comment by firestarman** [comment]
Only a single `import` will cause the same error.
@pxLi Could you help check which version of cudf python is currently packed into this image ? I will try that outside docker.
```
(base) liangcail@liangcail-ubuntu18:~$ docker run --runtime=nvidia -it --name udf-debug urm.nvidia.com/sw-spark-docker/plugin:it-centos7-cuda11.0-blossom-dev
[root@02553eedc24e /]# import cudf
bash: import: command not found
[root@02553eedc24e /]# 
[root@02553eedc24e /]# 
[root@02553eedc24e /]# python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/opt/conda/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /opt/conda/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference
>>> import rmm
Segmentation fault (core dumped)
[root@02553eedc24e /]# 

```

**Comment by firestarman** [comment]
Filed an issue to cudf 
https://github.com/rapidsai/cudf/issues/9622

**Comment by pxLi** [comment]
libcudf 211105-211107 builds have the issue, newer libcudf like 21.12.00a211108/21.12.00a211109 works fine

verified cudf_udf in all our nightly test scenarios

**Comment by pxLi** [comment]
reopened, this is still failing for new packages

>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/opt/conda/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
ImportError: /opt/conda/lib/python3.8/site-packages/rmm/_lib/memory_resource.cpython-38-x86_64-linux-gnu.so: symbol cudaMemPoolCreate, version libcudart.so.11.0 not defined in file libcudart.so.11.0 with link time reference

**Comment by GaryShen2008** [comment]
I'm thinking if we should move the cudf udf test case out of Pandas UDF tests.
We met several times for the cudf python package issue, which is not related to plugin features.
We can create another CI job to test cudf udf individually. so that the plugin integration test won't be blocked by the cudf  python packaging issue again.

**Comment by pxLi** [comment]
created a ticket to track cudf_udf CI change https://github.com/NVIDIA/spark-rapids/issues/4065

let me disable cudf_udf test and wait for https://github.com/rapidsai/cudf/issues/9622 to get fixed

**Comment by GaryShen2008** [comment]
Let's close this issue and keep the cudf side issue.

**Comment by jlowe** [comment]
> Let's close this issue and keep the cudf side issue.

Don't we need to keep this issue open to track reverting #4066?

**Comment by GaryShen2008** [comment]
Since this test case always failed by cuDF python package issue, I'm thinking if we should move this test case out of integration test.

> > Let's close this issue and keep the cudf side issue.
> 
> Don't we need to keep this issue open to track reverting #4066?
