### ISSUE TITLE
[BUG] CUDF 22.02 nightly test failure

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4127]
**Describe the bug**
the nightly 22.02 cudf build failed with following test:

15:14:19  [ERROR] Tests run: 285, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 10.668 s <<< FAILURE! - in ai.rapids.cudf.ColumnVectorTest
15:14:19  [ERROR] testIsIntegerWithBounds  Time elapsed: 0.002 s  <<< FAILURE!
15:14:19  java.lang.AssertionError
15:14:19  	at ai.rapids.cudf.ColumnView.isInteger(ColumnView.java:406)
15:14:19  	at ai.rapids.cudf.ColumnVectorTest.testIsIntegerWithBounds(ColumnVectorTest.java:4760)

**Comment by pxLi** [comment]
seeing new build tests based latest commit 4d13d81bb04a51a1ad7f476184c2b1eb88038126

```
14:35:34  [INFO] Results:
14:35:34  [INFO] 
14:35:34  [ERROR] Failures: 
14:35:34  [ERROR]   ArrowColumnVectorTest.testArrowStructThrows:333 Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <ai.rapids.cudf.CudfException>
14:35:34  [ERROR]   ColumnVectorTest.testReplaceIllegalIndexColumnInStruct:5760 expected: <true> but was: <false>
14:35:34  [ERROR]   ColumnVectorTest.testReplaceSameIndexColumnInStruct:5775 expected: <true> but was: <false>
14:35:34  [ERROR] Errors: 
14:35:34  [ERROR]   ColumnVectorTest.testDropListDuplicatesWithKeysValues:4227 ? IllegalArgument C...
14:35:34  [ERROR]   ColumnVectorTest.testFromScalar:1463 ? Cudf cuDF failure at: /home/jenkins/age...
14:35:34  [ERROR]   ColumnVectorTest.testFromScalarListOfStruct:1618 ? Cudf cuDF failure at: /home...
14:35:34  [ERROR]   ColumnVectorTest.testFromScalarNullList:1563 ? IllegalArgument Could not trans...
14:35:34  [ERROR]   ColumnVectorTest.testFromScalarNullStruct:1657 ? IllegalArgument Could not tra...
14:35:34  [ERROR]   ColumnVectorTest.testFromScalarZeroRows:1286 ? IllegalArgument Could not trans...
14:35:34  [ERROR]   ColumnVectorTest.testGetDeviceMemorySizeStructs:1100 ? Cudf cuDF failure at: /...
14:35:34  [ERROR]   ColumnVectorTest.testGetMapKeyExistence:5489 ? Cudf cuDF failure at: /home/jen...
14:35:34  [ERROR]   ColumnVectorTest.testGetMapValue:5460 ? Cudf cuDF failure at: /home/jenkins/ag...
14:35:34  [ERROR]   ColumnVectorTest.testGetMapValueEmptyInput:5472 ? Cudf cuDF failure at: /home/...
14:35:34  [ERROR]   ColumnVectorTest.testHcvForStruct:5389 ? Cudf cuDF failure at: /home/jenkins/a...
14:35:34  [ERROR]   ColumnVectorTest.testListOfStructsOfStructs:5518 ? Cudf cuDF failure at: /home...
14:35:34  [ERROR]   ColumnVectorTest.testMakeStruct:5596 ? Cudf cuDF failure at: /home/jenkins/age...
14:35:34  [ERROR]   ColumnVectorTest.testMakeStructEmpty:5588 ? Cudf cuDF failure at: /home/jenkin...
14:35:34  [ERROR]   ColumnVectorTest.testReplaceColumnInStruct:5728 ? Cudf cuDF failure at: /home/...
14:35:34  [ERROR]   ColumnVectorTest.testScanDenseRank:3010 ? IllegalArgument Could not translate ...
14:35:34  [ERROR]   ColumnVectorTest.testScanRank:2987 ? IllegalArgument Could not translate 28 in...
14:35:34  [ERROR]   ColumnVectorTest.testSpark32BitMurmur3HashStruct:744 ? IllegalArgument Could n...
14:35:34  [ERROR]   ColumnVectorTest.testStructChildValidity:5420 ? Cudf cuDF failure at: /home/je...
14:35:34  [ERROR]   ScalarTest.testNull:86 ? IllegalArgument Could not translate 28 into a DType
14:35:34  [ERROR]   ScalarTest.testStruct:390 ? Cudf cuDF failure at: /home/jenkins/agent/workspac...
14:35:34  [ERROR]   TableTest.testArrowIPCWriteToBufferChunked:7019->getExpectedFileTable:6715->getExpectedFileTable:6748 ? Cudf
14:35:34  [ERROR]   TableTest.testExplode:7470->buildExplodeTestTableWithNestedTypes:7419 ? Cudf c...
14:35:34  [ERROR]   TableTest.testExplodeOuter:7512->buildExplodeTestTableWithNestedTypes:7419 ? Cudf
14:35:34  [ERROR]   TableTest.testExplodeOuterPosition:7533->buildExplodeTestTableWithNestedTypes:7419 ? Cudf
14:35:34  [ERROR]   TableTest.testExplodePosition:7491->buildExplodeTestTableWithNestedTypes:7419 ? Cudf
14:35:34  [ERROR]   TableTest.testGroupByApproxPercentile:3594 ? IllegalArgument Could not transla...
14:35:34  [ERROR]   TableTest.testGroupByApproxPercentileReproCase:3571 ? IllegalArgument Could no...
14:35:34  [ERROR]   TableTest.testGroupByMergeLists:6258 ? Cudf cuDF failure at: /home/jenkins/age...
14:35:34  [ERROR]   TableTest.testGroupByMergeM2:5916 ? Cudf cuDF failure at: /home/jenkins/agent/...
14:35:34  [ERROR]   TableTest.testMergeApproxPercentile:3615 ? IllegalArgument Could not translate...
14:35:34  [ERROR]   TableTest.testMergeApproxPercentile2:3643 ? IllegalArgument Could not translat...
14:35:34  [ERROR]   TableTest.testORCWriteMapChunked:7099 ? Cudf cuDF failure at: /home/jenkins/ag...
14:35:34  [ERROR]   TableTest.testORCWriteToBufferChunked:7052->getExpectedFileTable:6715->getExpectedFileTable:6748 ? Cudf
14:35:34  [ERROR]   TableTest.testORCWriteToFileChunked:7070->getExpectedFileTable:6715->getExpectedFileTable:6748 ? Cudf
14:35:34  [ERROR]   TableTest.testParquetWriteMap:6847 ? Cudf cuDF failure at: /home/jenkins/agent...
14:35:34  [ERROR]   TableTest.testParquetWriteToBufferChunked:6906->getExpectedFileTable:6748 ? Cudf
14:35:34  [ERROR]   TableTest.testParquetWriteToBufferChunkedWithNested:6882->getExpectedFileTable:6715->getExpectedFileTable:6748 ? Cudf
14:35:34  [ERROR]   TableTest.testRemoveNullMasksIfNeeded:6604 ? Cudf cuDF failure at: /home/jenki...
14:35:34  [ERROR]   TableTest.testRemoveNullMasksIfNeededWithNulls:6670 ? Cudf cuDF failure at: /h...
14:35:34  [ERROR]   TableTest.testSerializationReconstructFromMetadata:3476->buildTestTable:7345 ? Cudf
14:35:34  [ERROR]   TableTest.testSerializationRoundTripConcatHostSide:3269->buildTestTable:7345 ? Cudf
14:35:34  [ERROR]   TableTest.testSerializationRoundTripSliced:3454->buildTestTable:7345 ? Cudf cu...
14:35:34  [ERROR]   TableTest.testSerializationRoundTripSlicedHostSide:3403->buildTestTable:7345 ? Cudf
14:35:34  [ERROR]   TableTest.testSerializationRoundTripToHost:3312->buildTestTable:7345 ? Cudf cu...
14:35:34  [ERROR]   TableTest.testStructColumnFilter:7178 ? Cudf cuDF failure at: /home/jenkins/ag...
14:35:34  [ERROR]   TableTest.testStructColumnFilterStrings:7203 ? Cudf cuDF failure at: /home/jen...
14:35:34  [ERROR]   TableTest.testWindowingCollectList:3993 ? Cudf cuDF failure at: /home/jenkins/...
14:35:34  [ERROR]   TableTest.testWindowingLag:4391 ? Cudf cuDF failure at: /home/jenkins/agent/wo...
14:35:34  [ERROR]   TableTest.testWindowingLead:4170 ? Cudf cuDF failure at: /home/jenkins/agent/w...
14:35:34  [INFO] 
14:35:34  [ERROR] Tests run: 1092, Failures: 3, Errors: 50, Skipped: 11
```

**Comment by pxLi** [comment]
above error also failed in branch-21.12, could be related to the dec128 change

**Comment by pxLi** [comment]
both 21.12 and 22.02 builds passed after https://github.com/rapidsai/cudf/pull/9485 merged
