### ISSUE TITLE
[BUG] test `string_test.py::test_regexp_replace_null_pattern_fallback` fails on DB301

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#4249]
**Describe the bug**
Test `string_test.py::test_regexp_replace_null_pattern_fallback` failed on db301, may also fail on db311, which aborted according to the latest premerge build(# 3398).

```log
[2021-12-01T09:34:45.327Z] FAILED ../../src/main/python/string_test.py::test_regexp_replace_null_pattern_fallback[ALLOW_NON_GPU(ProjectExec,RegExpReplace)]
[2021-12-01T09:34:45.327Z] XFAIL ../../src/main/python/orc_test.py::test_read_round_trip[-{'spark.rapids.sql.format.orc.reader.type': 'PERFILE'}-read_orc_df-[Timestamp]]
......
[2021-12-01T09:34:45.326Z]         if is_error(answer)[0]:
[2021-12-01T09:34:45.326Z]             if len(answer) > 1:
[2021-12-01T09:34:45.326Z]                 type = answer[1]
[2021-12-01T09:34:45.326Z]                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
[2021-12-01T09:34:45.326Z]                 if answer[1] == REFERENCE_TYPE:
[2021-12-01T09:34:45.326Z] >                   raise Py4JJavaError(
[2021-12-01T09:34:45.326Z]                         "An error occurred while calling {0}{1}{2}.\n".
[2021-12-01T09:34:45.326Z]                         format(target_id, ".", name), value)
[2021-12-01T09:34:45.326Z] E                   py4j.protocol.Py4JJavaError: An error occurred while calling z:com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertDidFallBack.
[2021-12-01T09:34:45.326Z] E                   : java.lang.AssertionError: assertion failed: Could not find RegExpReplace in the GPU plan
[2021-12-01T09:34:45.326Z] E                   GpuColumnarToRow false
[2021-12-01T09:34:45.326Z] E                   +- GpuProject [null AS regexp_replace(a, CAST(NULL AS STRING), A)#375282]
[2021-12-01T09:34:45.326Z] E                      +- GpuRowToColumnar targetsize(2147483647)
[2021-12-01T09:34:45.326Z] E                         +- *(1) Scan ExistingRDD[a#375280]
[2021-12-01T09:34:45.326Z] E                   
[2021-12-01T09:34:45.326Z] E                   	at scala.Predef$.assert(Predef.scala:223)
[2021-12-01T09:34:45.326Z] E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertDidFallBack(Plugin.scala:337)
[2021-12-01T09:34:45.326Z] E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertDidFallBack(Plugin.scala:342)
[2021-12-01T09:34:45.326Z] E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertDidFallBack(Plugin.scala)
[2021-12-01T09:34:45.327Z] E                   	at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source)
[2021-12-01T09:34:45.327Z] E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-01T09:34:45.327Z] E                   	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-12-01T09:34:45.327Z] E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2021-12-01T09:34:45.327Z] E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
[2021-12-01T09:34:45.327Z] E                   	at py4j.Gateway.invoke(Gateway.java:295)
[2021-12-01T09:34:45.327Z] E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2021-12-01T09:34:45.327Z] E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2021-12-01T09:34:45.327Z] E                   	at py4j.GatewayConnection.run(GatewayConnection.java:251)
[2021-12-01T09:34:45.327Z] E                   	at java.lang.Thread.run(Thread.java:748)
[2021-12-01T09:34:45.327Z] 
[2021-12-01T09:34:45.327Z] /databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py:326: Py4JJavaError
```

**Steps/Code to reproduce bug**
Run a premerge build over branch 22.02 will see this failure.

**Expected behavior**
The test should also pass on DB.

**Comment by tgravescs** [comment]
this is dup of https://github.com/NVIDIA/spark-rapids/issues/4243
