### ISSUE TITLE
[BUG] crash if we have a decimal128 in a struct in an array 

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#4600]
**Describe the bug**
```
spark.range(10).selectExpr("id", "array(struct('a', CAST(9 as DECIMAL(29,0))))").collect().length
```

throws

```
java.lang.IllegalStateException: Unexpected element type: class java.math.BigInteger
  at ai.rapids.cudf.HostColumnVector$ColumnBuilder.appendChildOrNull(HostColumnVector.java:1146)
  at ai.rapids.cudf.HostColumnVector$ColumnBuilder.append(HostColumnVector.java:1053)
  at ai.rapids.cudf.HostColumnVector$ColumnBuilder.appendStructValues(HostColumnVector.java:926)
  at ai.rapids.cudf.HostColumnVector.fromStructs(HostColumnVector.java:302)
  at ai.rapids.cudf.ColumnVector.fromStructs(ColumnVector.java:1193)
  at com.nvidia.spark.rapids.GpuScalar$.columnVectorFromLiterals(literals.scala:202)
  at com.nvidia.spark.rapids.GpuScalar$.from(literals.scala:325)
  at com.nvidia.spark.rapids.GpuScalar.getBase(literals.scala:469)
  at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:877)
  at com.nvidia.spark.rapids.GpuExpressionsUtils$.$anonfun$resolveColumnVector$1(GpuExpressions.scala:74)
  at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
  at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
  at com.nvidia.spark.rapids.GpuExpressionsUtils$.withResourceIfAllowed(GpuExpressions.scala:30)
  at com.nvidia.spark.rapids.GpuExpressionsUtils$.resolveColumnVector(GpuExpressions.scala:72)
  at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:93)
  at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:102)
  at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:109)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:162)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:159)
  at scala.collection.immutable.List.foreach(List.scala:431)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:159)
  at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:194)
  at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:109)
  at com.nvidia.spark.rapids.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:73)
  at com.nvidia.spark.rapids.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:149)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:242)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:188)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:239)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:216)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:256)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
  at org.apache.spark.scheduler.Task.run(Task.scala:131)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

This was found as a part of https://github.com/NVIDIA/spark-rapids/pull/4470

**Comment by revans2** [comment]
https://github.com/rapidsai/cudf/pull/10105 was just merged into CUDF and should fix the issue. I just kicked the build and once it is in and the premerge build for #4470 passes I'll call it good.

**Comment by nartal1** [comment]
Thanks @revans2 for fixing this issue.
