### ISSUE TITLE
[BUG] MortgageAdaptiveSparkSuite failed with duplicate buffer exception

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#4664]
Nightly tests failed on Spark 3.0.2 with this error:
```
[2022-01-29T13:14:16.578Z]   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 6, nightly-test-339-9q329-fq4cf, executor driver): com.nvidia.spark.rapids.DuplicateBufferException: Buffer ID ShuffleBufferId(shuffle_2_6_0,2) at tier device memory already registered device memory buffer size=273792
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsBufferCatalog$$anon$1.apply(RapidsBufferCatalog.scala:120)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsBufferCatalog$$anon$1.apply(RapidsBufferCatalog.scala:111)
[2022-01-29T13:14:16.578Z] 	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsBufferCatalog.registerNewBuffer(RapidsBufferCatalog.scala:126)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsBufferStore.addBuffer(RapidsBufferStore.scala:218)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsDeviceMemoryStore.$anonfun$addContiguousTable$1(RapidsDeviceMemoryStore.scala:117)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsDeviceMemoryStore.$anonfun$addContiguousTable$1$adapted(RapidsDeviceMemoryStore.scala:113)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.Arm.freeOnExcept(Arm.scala:142)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.Arm.freeOnExcept$(Arm.scala:140)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsBufferStore.freeOnExcept(RapidsBufferStore.scala:41)
[2022-01-29T13:14:16.578Z] 	at com.nvidia.spark.rapids.RapidsDeviceMemoryStore.addContiguousTable(RapidsDeviceMemoryStore.scala:113)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.sql.rapids.RapidsCachingWriter.$anonfun$write$1(RapidsShuffleInternalManagerBase.scala:114)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.sql.rapids.RapidsCachingWriter.$anonfun$write$1$adapted(RapidsShuffleInternalManagerBase.scala:98)
[2022-01-29T13:14:16.578Z] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2022-01-29T13:14:16.578Z] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2022-01-29T13:14:16.578Z] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManagerBase.scala:98)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.scheduler.Task.run(Task.scala:127)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
[2022-01-29T13:14:16.578Z] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
[2022-01-29T13:14:16.578Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-01-29T13:14:16.578Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-01-29T13:14:16.578Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
I can get this to repro locally. I am now trying to get it to repro again with some debug logging, I am capturing the stack when the first registration happened, in hopes that it can shed light on what's going on.

**Comment by abellina** [comment]
The reason for this is that the `RapidsBufferCatalog` is a singleton and it isn't always removing all the buffers in its `bufferMap`.  In this particular scenario we have 2 tests, one after the other, that want a brand new `SparkContext`. This restarts the shuffle id to 0, so we have a collision with a block stored from the first suite.

We do call `RapidsBufferCatalog.close()` a static method that cleans each tier's storage, but we are not removing the buffers from the `bufferMap` unless there is a shuffle unregistration happening. My guess is that when this fails we have two live `SparkContext` instances, so we are holding on to some shuffle blocks non-deterministically.

My plan is to add to the `close()` method in the object-class a step to remove all buffers from `bufferMap`, but I am not sure if that's going to break something else. Taking a closer look at that before I post a PR.

**Comment by abellina** [comment]
Note that the `ShuffleBufferCatalog` is NOT a singleton, and therefore we sholdn't need to worry about late arrivals of `unregisterShuffle` calls (as those will happen) after the first test finishes. Our init code already creates a new `ShuffleBufferCatalog` so there is not going to be a conflict there.
