### ISSUE TITLE
[BUG] test_compress_write_round_trip failed on Spark 3.3

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#4841]
`test_compress_write_round_trip` failed in a nightly integration test run on Spark 3.3:
```
[2022-02-22T21:08:33.016Z] __________ test_compress_write_round_trip[parquet-reader_confs1-none] __________
[2022-02-22T21:08:33.016Z] 
[2022-02-22T21:08:33.016Z] spark_tmp_path = '/tmp/pyspark_tests//it-test-33x-46-krpkn-h7sn2-main-19639-918769696/'
[2022-02-22T21:08:33.016Z] compress = 'none', v1_enabled_list = 'parquet'
[2022-02-22T21:08:33.016Z] reader_confs = {'spark.rapids.sql.format.parquet.reader.type': 'MULTITHREADED'}
[2022-02-22T21:08:33.016Z] 
[2022-02-22T21:08:33.016Z]     @pytest.mark.parametrize('compress', parquet_write_compress_options)
[2022-02-22T21:08:33.016Z]     @pytest.mark.parametrize('reader_confs', reader_opt_confs)
[2022-02-22T21:08:33.016Z]     @pytest.mark.parametrize('v1_enabled_list', ["", "parquet"])
[2022-02-22T21:08:33.016Z]     def test_compress_write_round_trip(spark_tmp_path, compress, v1_enabled_list, reader_confs):
[2022-02-22T21:08:33.016Z]         data_path = spark_tmp_path + '/PARQUET_DATA'
[2022-02-22T21:08:33.016Z]         all_confs = copy_and_update(reader_confs, {
[2022-02-22T21:08:33.016Z]             'spark.sql.sources.useV1SourceList': v1_enabled_list,
[2022-02-22T21:08:33.016Z]             'spark.sql.parquet.compression.codec': compress})
[2022-02-22T21:08:33.016Z] >       assert_gpu_and_cpu_writes_are_equal_collect(
[2022-02-22T21:08:33.016Z]                 lambda spark, path : binary_op_df(spark, long_gen).coalesce(1).write.parquet(path),
[2022-02-22T21:08:33.016Z]                 lambda spark, path : spark.read.parquet(path),
[2022-02-22T21:08:33.016Z]                 data_path,
[2022-02-22T21:08:33.016Z]                 conf=all_confs)
[2022-02-22T21:08:33.016Z] 
[2022-02-22T21:08:33.016Z] ../../src/main/python/parquet_write_test.py:187: 
[2022-02-22T21:08:33.016Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-02-22T21:08:33.016Z] ../../src/main/python/asserts.py:265: in assert_gpu_and_cpu_writes_are_equal_collect
[2022-02-22T21:08:33.016Z]     _assert_gpu_and_cpu_writes_are_equal(write_func, read_func, base_path, 'COLLECT', conf=conf)
[2022-02-22T21:08:33.016Z] ../../src/main/python/asserts.py:240: in _assert_gpu_and_cpu_writes_are_equal
[2022-02-22T21:08:33.016Z]     with_gpu_session(lambda spark : write_func(spark, gpu_path), conf=conf)
[2022-02-22T21:08:33.016Z] ../../src/main/python/spark_session.py:109: in with_gpu_session
[2022-02-22T21:08:33.016Z]     return with_spark_session(func, conf=copy)
[2022-02-22T21:08:33.016Z] ../../src/main/python/spark_session.py:76: in with_spark_session
[2022-02-22T21:08:33.016Z]     ret = func(_spark)
[2022-02-22T21:08:33.016Z] ../../src/main/python/asserts.py:240: in <lambda>
[2022-02-22T21:08:33.016Z]     with_gpu_session(lambda spark : write_func(spark, gpu_path), conf=conf)
[2022-02-22T21:08:33.016Z] ../../src/main/python/parquet_write_test.py:188: in <lambda>
[2022-02-22T21:08:33.016Z]     lambda spark, path : binary_op_df(spark, long_gen).coalesce(1).write.parquet(path),
[2022-02-22T21:08:33.016Z] /home/jenkins/agent/workspace/jenkins-rapids_it-3.3.x-SNAPSHOT-dev-github-46/jars/spark-3.3.0-SNAPSHOT-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/readwriter.py:1150: in parquet
[2022-02-22T21:08:33.016Z]     self._jwrite.parquet(path)
[2022-02-22T21:08:33.016Z] /home/jenkins/agent/workspace/jenkins-rapids_it-3.3.x-SNAPSHOT-dev-github-46/jars/spark-3.3.0-SNAPSHOT-bin-hadoop3.2/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py:1321: in __call__
[2022-02-22T21:08:33.016Z]     return_value = get_return_value(
[2022-02-22T21:08:33.016Z] /home/jenkins/agent/workspace/jenkins-rapids_it-3.3.x-SNAPSHOT-dev-github-46/jars/spark-3.3.0-SNAPSHOT-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/sql/utils.py:190: in deco
[2022-02-22T21:08:33.016Z]     return f(*a, **kw)
[2022-02-22T21:08:33.016Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-02-22T21:08:33.016Z] 
[2022-02-22T21:08:33.016Z] answer = 'xro3025'
[2022-02-22T21:08:33.016Z] gateway_client = <py4j.clientserver.JavaClient object at 0x7f3571ae4400>
[2022-02-22T21:08:33.016Z] target_id = 'o3024', name = 'parquet'
[2022-02-22T21:08:33.016Z] 
[2022-02-22T21:08:33.016Z]     def get_return_value(answer, gateway_client, target_id=None, name=None):
[2022-02-22T21:08:33.016Z]         """Converts an answer received from the Java gateway into a Python object.
[2022-02-22T21:08:33.016Z]     
[2022-02-22T21:08:33.016Z]         For example, string representation of integers are converted to Python
[2022-02-22T21:08:33.016Z]         integer, string representation of objects are converted to JavaObject
[2022-02-22T21:08:33.016Z]         instances, etc.
[2022-02-22T21:08:33.016Z]     
[2022-02-22T21:08:33.016Z]         :param answer: the string returned by the Java gateway
[2022-02-22T21:08:33.016Z]         :param gateway_client: the gateway client used to communicate with the Java
[2022-02-22T21:08:33.016Z]             Gateway. Only necessary if the answer is a reference (e.g., object,
[2022-02-22T21:08:33.016Z]             list, map)
[2022-02-22T21:08:33.016Z]         :param target_id: the name of the object from which the answer comes from
[2022-02-22T21:08:33.016Z]             (e.g., *object1* in `object1.hello()`). Optional.
[2022-02-22T21:08:33.016Z]         :param name: the name of the member from which the answer comes from
[2022-02-22T21:08:33.016Z]             (e.g., *hello* in `object1.hello()`). Optional.
[2022-02-22T21:08:33.016Z]         """
[2022-02-22T21:08:33.016Z]         if is_error(answer)[0]:
[2022-02-22T21:08:33.016Z]             if len(answer) > 1:
[2022-02-22T21:08:33.017Z]                 type = answer[1]
[2022-02-22T21:08:33.017Z]                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
[2022-02-22T21:08:33.017Z]                 if answer[1] == REFERENCE_TYPE:
[2022-02-22T21:08:33.017Z] >                   raise Py4JJavaError(
[2022-02-22T21:08:33.017Z]                         "An error occurred while calling {0}{1}{2}.\n".
[2022-02-22T21:08:33.017Z]                         format(target_id, ".", name), value)
[2022-02-22T21:08:33.017Z] E                   py4j.protocol.Py4JJavaError: An error occurred while calling o3024.parquet.
[2022-02-22T21:08:33.017Z] E                   : org.apache.spark.SparkException: Job aborted.
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.write(GpuFileFormatWriter.scala:259)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.rapids.GpuInsertIntoHadoopFsRelationCommand.runColumnar(GpuInsertIntoHadoopFsRelationCommand.scala:166)
[2022-02-22T21:08:33.017Z] E                   	at com.nvidia.spark.rapids.GpuDataWritingCommandExec.sideEffectResult$lzycompute(GpuDataWritingCommandExec.scala:97)
[2022-02-22T21:08:33.017Z] E                   	at com.nvidia.spark.rapids.GpuDataWritingCommandExec.sideEffectResult(GpuDataWritingCommandExec.scala:96)
[2022-02-22T21:08:33.017Z] E                   	at com.nvidia.spark.rapids.GpuDataWritingCommandExec.doExecuteColumnar(GpuDataWritingCommandExec.scala:120)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:220)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:231)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:228)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:216)
[2022-02-22T21:08:33.017Z] E                   	at com.nvidia.spark.rapids.GpuColumnarToRowExecParent.doExecute(GpuColumnarToRowExec.scala:319)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:193)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:231)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:228)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:189)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:339)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:405)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:83)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:128)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)
[2022-02-22T21:08:33.017Z] E                   	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:793)
[2022-02-22T21:08:33.017Z] E                   	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
[2022-02-22T21:08:33.017Z] E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-02-22T21:08:33.017Z] E                   	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-02-22T21:08:33.017Z] E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2022-02-22T21:08:33.017Z] E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2022-02-22T21:08:33.017Z] E                   	at py4j.Gateway.invoke(Gateway.java:282)
[2022-02-22T21:08:33.017Z] E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2022-02-22T21:08:33.017Z] E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2022-02-22T21:08:33.017Z] E                   	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2022-02-22T21:08:33.017Z] E                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2022-02-22T21:08:33.017Z] E                   	at java.lang.Thread.run(Thread.java:748)
[2022-02-22T21:08:33.018Z] E                   Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 40.0 failed 1 times, most recent failure: Lost task 0.0 in stage 40.0 (TID 40) (10.233.92.115 executor 0): java.lang.IllegalArgumentException: For input string: "null"
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringLike.parseBoolean(StringLike.scala:330)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringLike.toBoolean(StringLike.scala:289)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringLike.toBoolean$(StringLike.scala:289)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:33)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.execution.datasources.parquet.SparkToParquetSchemaConverter.<init>(ParquetSchemaConverter.scala:455)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.init(ParquetWriteSupport.scala:114)
[2022-02-22T21:08:33.018Z] E                   	at com.nvidia.spark.rapids.GpuParquetWriter.<init>(GpuParquetFileFormat.scala:343)
[2022-02-22T21:08:33.018Z] E                   	at com.nvidia.spark.rapids.GpuParquetFileFormat$$anon$1.newInstance(GpuParquetFileFormat.scala:249)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.newOutputWriter(GpuFileFormatDataWriter.scala:139)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.<init>(GpuFileFormatDataWriter.scala:121)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:297)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$write$14(GpuFileFormatWriter.scala:238)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.Task.run(Task.scala:136)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:507)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1475)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:510)
[2022-02-22T21:08:33.018Z] E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-02-22T21:08:33.018Z] E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-02-22T21:08:33.018Z] E                   	at java.lang.Thread.run(Thread.java:748)
[2022-02-22T21:08:33.018Z] E                   
[2022-02-22T21:08:33.018Z] E                   Driver stacktrace:
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2662)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2598)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2597)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2597)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)
[2022-02-22T21:08:33.018Z] E                   	at scala.Option.foreach(Option.scala:407)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1182)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2850)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2792)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2781)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2228)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.write(GpuFileFormatWriter.scala:228)
[2022-02-22T21:08:33.018Z] E                   	... 54 more
[2022-02-22T21:08:33.018Z] E                   Caused by: java.lang.IllegalArgumentException: For input string: "null"
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringLike.parseBoolean(StringLike.scala:330)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringLike.toBoolean(StringLike.scala:289)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringLike.toBoolean$(StringLike.scala:289)
[2022-02-22T21:08:33.018Z] E                   	at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:33)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.execution.datasources.parquet.SparkToParquetSchemaConverter.<init>(ParquetSchemaConverter.scala:455)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.init(ParquetWriteSupport.scala:114)
[2022-02-22T21:08:33.018Z] E                   	at com.nvidia.spark.rapids.GpuParquetWriter.<init>(GpuParquetFileFormat.scala:343)
[2022-02-22T21:08:33.018Z] E                   	at com.nvidia.spark.rapids.GpuParquetFileFormat$$anon$1.newInstance(GpuParquetFileFormat.scala:249)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.newOutputWriter(GpuFileFormatDataWriter.scala:139)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.<init>(GpuFileFormatDataWriter.scala:121)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:297)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$write$14(GpuFileFormatWriter.scala:238)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.scheduler.Task.run(Task.scala:136)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:507)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1475)
[2022-02-22T21:08:33.018Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:510)
[2022-02-22T21:08:33.018Z] E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-02-22T21:08:33.018Z] E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-02-22T21:08:33.018Z] E                   	... 1 more
```

**Comment by res-life** [comment]
Same as https://github.com/NVIDIA/spark-rapids/issues/4846.
