### ISSUE TITLE
[Audit][FEA][SPARK-38094] GPU write Parquet failed after Spark added "spark.sql.parquet.fieldId.write.enabled" key in ParquetFileFormat in Parquet

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#4846]
**Describe the bug**
[SPARK-38094](https://issues.apache.org/jira/browse/SPARK-38094) added a new key in ParquetFileFormat for Spark 3.3.0 Parquet: "spark.sql.parquet.fieldId.write.enabled".
And this causes GPU write Parquet failed, the GpuParquetFileFormat should also handle it.

**Steps/Code to reproduce bug**
Download the latest Spark 3.3.0 Snapshot tar.gz file
Run a parquet write IT like:
```
def test_parquet_write(spark_tmp_path):
    data_path = spark_tmp_path + '/PARQUET_DATA'
    gen = IntegerGen()

    assert_gpu_and_cpu_writes_are_equal_collect(
        lambda spark, path: unary_op_df(spark, gen).coalesce(1).write.parquet(path),
        lambda spark, path: spark.read.parquet(path),
        data_path)
```
Errors are:
```
Caused by: java.lang.IllegalArgumentException: For input string: "null"
	at scala.collection.immutable.StringLike.parseBoolean(StringLike.scala:330) ~[scala-library-2.12.15.jar:?]
	at scala.collection.immutable.StringLike.toBoolean(StringLike.scala:289) ~[scala-library-2.12.15.jar:?]
	at scala.collection.immutable.StringLike.toBoolean$(StringLike.scala:289) ~[scala-library-2.12.15.jar:?]
	at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:33) ~[scala-library-2.12.15.jar:?]
	at org.apache.spark.sql.execution.datasources.parquet.SparkToParquetSchemaConverter.<init>(ParquetSchemaConverter.scala:455) ~[spark-sql_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.init(ParquetWriteSupport.scala:114) ~[spark-sql_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
	at com.nvidia.spark.rapids.GpuParquetWriter.<init>(GpuParquetFileFormat.scala:343) ~[spark3xx-common/:?]
	at com.nvidia.spark.rapids.GpuParquetFileFormat$$anon$1.newInstance(GpuParquetFileFormat.scala:249) ~[spark3xx-common/:?]
	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.newOutputWriter(GpuFileFormatDataWriter.scala:139) ~[spark3xx-common/:?]
	at org.apache.spark.sql.rapids.GpuSingleDirectoryDataWriter.<init>(GpuFileFormatDataWriter.scala:121) ~[spark3xx-common/:?]
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:297) ~[spark3xx-common/:?]
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$write$14(GpuFileFormatWriter.scala:238) ~[spark3xx-common/:?]
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) ~[spark-core_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
	at org.apache.spark.scheduler.Task.run(Task.scala:136) ~[spark-core_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:507) ~[spark-core_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1475) ~[spark-core_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:510) ~[spark-core_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
```

**Expected behavior**
GpuParquetFileFormat add the code
```
    conf.set(
      SQLConf.PARQUET_FIELD_ID_WRITE_ENABLED.key,
      sparkSession.sessionState.conf.parquetFieldIdWriteEnabled.toString)
```
The GPU writes parquet sucessfully.

**Additional context**
Seems should add a shim layer because this key is only for 3.3.0+

**Comment by res-life** [comment]
Duplicated, close it.

**Comment by res-life** [comment]
**Currently cuDF does not support writting field id to Parquet metadata**
```
Below is a simple example.

// Meta of CPU generated parquet file
message spark_schema {
  optional int32 c1 = 1;
}

// Meta of GPU generated parquet file
message schema {
  optional int32 c1;
}
```
**Description of [Spark PR](https://issues.apache.org/jira/browse/SPARK-38094) is**

Field Id is a native field in the Parquet schema (https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L398)

After this PR, when the requested schema has field IDs, Parquet readers will first use the field ID to determine which Parquet columns to read, before falling back to using column names as before. It enables matching columns by field id for supported DWs like iceberg and Delta.

**Do we need to match this feature?**
We now use column name to match columns.
I do not know if there are requirements for this feature.
If not, we can simply disable this feature by checking a config item.

@jlowe  @revans2  Do you have more information?

**Comment by res-life** [comment]
Filed a cuDF issue: https://github.com/rapidsai/cudf/issues/10375

**Comment by res-life** [comment]
https://github.com/rapidsai/cudf/issues/10375 is merged.
Remove the `cudf_dependency` tag.
