### ISSUE TITLE
[BUG] Spark 3.3 IT cache_test:test_passing_gpuExpr_as_Expr failure

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4960]
**Describe the bug**
```
01:59:04  FAILED ../../src/main/python/cache_test.py::test_passing_gpuExpr_as_Expr[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}][ALLOW_NON_GPU(CollectLimitExec)]
01:59:04  FAILED ../../src/main/python/cache_test.py::test_passing_gpuExpr_as_Expr[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'false'}][ALLOW_NON_GPU(CollectLimitExec)]

```

```
12:59:04  [1m[31mE                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 26) (10.233.67.146 executor 0): java.lang.IllegalArgumentException: For input string: "null"[0m
12:59:04  [1m[31mE                   	at scala.collection.immutable.StringLike.parseBoolean(StringLike.scala:330)[0m
12:59:04  [1m[31mE                   	at scala.collection.immutable.StringLike.toBoolean(StringLike.scala:289)[0m
12:59:04  [1m[31mE                   	at scala.collection.immutable.StringLike.toBoolean$(StringLike.scala:289)[0m
12:59:04  [1m[31mE                   	at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:33)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.sql.execution.datasources.parquet.SparkToParquetSchemaConverter.<init>(ParquetSchemaConverter.scala:455)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport.init(ParquetWriteSupport.scala:114)[0m
12:59:04  [1m[31mE                   	at com.nvidia.spark.rapids.shims.ParquetOutputFileFormat.getRecordWriter(ParquetCachedBatchSerializer.scala:1505)[0m
12:59:04  [1m[31mE                   	at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$InternalRowToCachedBatchIterator.$anonfun$next$1(ParquetCachedBatchSerializer.scala:1247)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.sql.internal.SQLConf$.withExistingConf(SQLConf.scala:158)[0m
12:59:04  [1m[31mE                   	at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$InternalRowToCachedBatchIterator.next(ParquetCachedBatchSerializer.scala:1247)[0m
12:59:04  [1m[31mE                   	at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorProducer$InternalRowToCachedBatchIterator.next(ParquetCachedBatchSerializer.scala:1116)[0m
12:59:04  [1m[31mE                   	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:224)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:302)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1508)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1435)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1499)[0m
12:59:04  [1m[31mE                   	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1322)[0m
```

**Comment by firestarman** [comment]
I saw the latest build passed 
https://blossom.nvidia.com/sw-gpu-spark-jenkins/job/rapids_it-3.3.x-SNAPSHOT-dev-github/54/

**Comment by razajafri** [comment]
unable to reproduce. 

It's passing on (blossom)[https://blossom.nvidia.com/sw-gpu-spark-jenkins/job/rapids_it-3.3.x-SNAPSHOT-dev-github/57/] and locally on the latest snapshot of spark 3.3.0
