### ISSUE TITLE
[FEA] CUDA error debug

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5028]
I wish when executors failed with unknown CUDA error or some other CUDA errors, the executor log can print more debug information such as nvidia-smi output to show the reason why.

For example, 
```
ai.rapids.cudf.CudaException: unknown error
	at ai.rapids.cudf.Cuda.freeZero(Native Method)
	at com.nvidia.spark.rapids.GpuDeviceManager$.setGpuDeviceAndAcquire(GpuDeviceManager.scala:99)
	at com.nvidia.spark.rapids.GpuDeviceManager$.$anonfun$initializeGpu$1(GpuDeviceManager.scala:125)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:23)
	at scala.Option.map(Option.scala:230)
	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpu(GpuDeviceManager.scala:125)
	at 
```

**Comment by jbrennan333** [comment]
For some clarification, do we want to print out debug info for task failures caused by any CudaException, or only for CudaFatalExceptions?   I think the distinction is the that CudaFatalExceptions are sticky.
