### ISSUE TITLE
[BUG] Profiling tool fails process custom task accumulators of type CollectionAccumulator

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5091]
**Describe the bug**
The profiling tool can fail to process an event log if it has custom task accumulables of type CollectionAccumulator

The code assumes it can do a toString.toLong but this is an array type and it fails:

```
java.lang.NumberFormatException: For input string: "[]"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
        at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
        at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
        at org.apache.spark.sql.rapids.tool.profiling.EventsProcessor.$anonfun$doSparkListenerTaskEnd$4(EventsProcessor.scala:197)
        at org.apache.spark.sql.rapids.tool.profiling.EventsProcessor.$anonfun$doSparkListenerTaskEnd$4$adapted(EventsProcessor.scala:197)
```

**Comment by tgravescs** [comment]
I'll actually close this one with pr and open separate one to handle better

**Comment by sameerz** [comment]
Closing for 22.04, will follow up on remaining tasks in issue #5101
