### ISSUE TITLE
[BUG]XGBoost Transformation will fail if we enable PCBS

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#5156]
**Describe the bug**
If we enable PCBS, and do ETL job with a larger dataset(use 2 Years 1GB splits dataset in https://docs.rapids.ai/datasets/mortgage-data) , the [notebook](https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.04/examples/Spark-ETL%2BXGBoost/mortgage/notebooks/python/MortgageETL%2BXGBoost.ipynb) will fail while running XGBoost Transformation process with Error.
```
22/04/07 11:21:26 ERROR Utils: Uncaught exception in thread stdout writer for /opt/conda/bin/python
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.copy(rows.scala:74)
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.copy$(rows.scala:72)
        at org.apache.spark.sql.catalyst.expressions.SpecificInternalRow.copy(SpecificInternalRow.scala:193)
        at org.apache.spark.sql.catalyst.expressions.SpecificInternalRow.copy(SpecificInternalRow.scala:193)
        at org.apache.spark.sql.catalyst.InternalRow$.copyValue(InternalRow.scala:119)
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.copy(rows.scala:77)
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.copy$(rows.scala:72)
        at org.apache.spark.sql.catalyst.expressions.SpecificInternalRow.copy(SpecificInternalRow.scala:193)
        at org.apache.spark.sql.catalyst.expressions.SpecificInternalRow.copy(SpecificInternalRow.scala:193)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.$anonfun$convertCachedBatchToInternalRowIter$3(ParquetCachedBatchSerializer.scala:753)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.$anonfun$convertCachedBatchToInternalRowIter$3$adapted(ParquetCachedBatchSerializer.scala:751)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3$$Lambda$2076/157291715.apply(Unknown Source)
        at scala.collection.immutable.Range.foreach(Range.scala:158)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.$anonfun$convertCachedBatchToInternalRowIter$1(ParquetCachedBatchSerializer.scala:751)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3$$Lambda$2060/387735387.apply(Unknown Source)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer.withResource(ParquetCachedBatchSerializer.scala:264)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.convertCachedBatchToInternalRowIter(ParquetCachedBatchSerializer.scala:734)
        at com.nvidia.spark.rapids.shims.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.hasNext(ParquetCachedBatchSerializer.scala:714)

```
If we disable PCBS, the job is good.

**Expected behavior**
The job will not fail.

**Environment details (please complete the following information)**
spark version and mode: spark3.2.0 standalone
GPU: Quadro RTX 6000
plugin version: cudf-22.04.0-20220403.002254-65.jar  rapids-4-spark_2.12-22.04.0-20220403.053109-51.jar
```
export XGBOOST4J_JAR=/XXX/xgboost4j_3.0-1.4.2-0.2.0.jar
export XGBOOST4J_SPARK_JAR=/XXX/xgboost4j-spark_3.0-1.4.2-0.2.0.jar

#--conf spark.sql.shuffle.partitions=1 \

$SPARK_HOME/bin/pyspark --master ${SPARK_MASTER_URL} \
  --driver-memory 2G \
  --executor-cores 4 \
  --executor-memory 4G \
  --jars ${CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR},$XGBOOST4J_JAR,$XGBOOST4J_SPARK_JAR \
  --py-files ${CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR},$XGBOOST4J_JAR,$XGBOOST4J_SPARK_JAR \
  --conf spark.executor.resource.gpu.amount=1 \
  --conf spark.task.resource.gpu.amount=1 \
  --conf spark.rapids.sql.concurrentGpuTasks=2 \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.rapids.sql.explain=True \
  --conf spark.rapids.sql.enabled=True \
  --conf spark.rapids.sql.hasNans=False \
  --conf spark.rapids.sql.variableFloatAgg.enabled=true \
  --conf spark.rapids.sql.csv.read.long.enabled=true \
  --conf spark.rapids.sql.csv.read.double.enabled=true \
  --conf spark.rapids.sql.csv.read.integer.enabled=true \
  --conf spark.rapids.sql.castFloatToString.enabled=true \
  --conf spark.rapids.sql.castFloatToDecimal.enabled=true \
  --conf spark.rapids.sql.castDecimalToFloat.enabled=true \
  --conf spark.rapids.memory.gpu.pooling.enabled=false \
  --conf spark.rapids.memory.gpu.minAllocFraction=0.0001 \
  --conf spark.rapids.memory.gpu.reserve=20 \
  !!--conf spark.sql.cache.serializer=com.nvidia.spark.ParquetCachedBatchSerializer \!!
  --conf spark.driver.extraJavaOptions="-Duser.timezone=UTC" \
  --conf spark.executor.extraJavaOptions="-Duser.timezone=UTC" \
  --conf spark.driver.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} \
  --conf spark.executor.extraClassPath=${CUDF_JAR}:${RAPIDS_JAR} 
```

**Comment by nvliyuan** [comment]
reproduced with this dataset
![image](https://user-images.githubusercontent.com/84758614/162192384-8c31917f-97b1-4a52-b875-d1ebac60b7e1.png)

**Comment by razajafri** [comment]
This doesn't sound like a bug. This can be circumvented by doing either of the following 
1. Increase executor memory
2. Change the storage level to `DISK_ONLY`
3. As per @revans2 we can possibly avoid this by limiting the number of rows we read in to memory. This is more of a long term fix which can be handled as part of a separate [issue](https://github.com/NVIDIA/spark-rapids/issues/5187)

**Comment by nvliyuan** [comment]
@razajafri thanks for the explanation, verified and it works, close this issue
