### ISSUE TITLE
[BUG] cudaErrorIllegalAddress crash during join

### ISSUE THREAD

**Issue by tonglei19961121** [NVIDIA/spark-rapids#519]
**Describe the bug**
we tested spark3.0 on gpu on datasets with different size, It works pretty well with small dataset. But when we tested it on a 2.8G dataset, a error appear

**Steps/Code to reproduce bug**
scala> data_a.select( $"sepal_length" as "a").join(data_b.select($"sepal_length" as "b"), $"a" === $"b").count

**Expected behavior**
select and join operation on two tables.

**Environment details (please complete the following information)**
 - Environment location: [Standalone,spark3.0 gpu, nvidia v100]
 - Spark configuration settings related to the issue

**Additional context**
scala> data_a.select( $"sepal_length" as "a").join(data_b.select($"sepal_length" as "b"), $"a" === $"b").count
20/08/04 16:06:10 WARN TaskSetManager: Lost task 0.0 in stage 18.0 (TID 90, 30.99.70.120, executor 0): ai.rapids.cudf.CudfException: CUDA error at: /usr/local/rapids/include/rmm/device_scalar.hpp189: cudaErrorIllegalAddress an illegal memory access was encountered
        at ai.rapids.cudf.Table.innerJoin(Native Method)
        at ai.rapids.cudf.Table.access$1900(Table.java:35)
        at ai.rapids.cudf.Table$TableOperation.innerJoin(Table.java:1632)
        at com.nvidia.spark.rapids.GpuHashJoin.doJoinLeftRight(GpuHashJoin.scala:120)
        at com.nvidia.spark.rapids.GpuHashJoin.doJoinLeftRight$(GpuHashJoin.scala:115)
        at com.nvidia.spark.rapids.GpuShuffledHashJoinExec.doJoinLeftRight(GpuShuffledHashJoinExec.scala:59)
        at com.nvidia.spark.rapids.GpuHashJoin.doJoin(GpuHashJoin.scala:97)
        at com.nvidia.spark.rapids.GpuHashJoin.doJoin$(GpuHashJoin.scala:72)
        at com.nvidia.spark.rapids.GpuShuffledHashJoinExec.doJoin(GpuShuffledHashJoinExec.scala:59)
        at com.nvidia.spark.rapids.GpuShuffledHashJoinExec.$anonfun$doExecuteColumnar$5(GpuShuffledHashJoinExec.scala:130)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$doExecuteColumnar$1(aggregate.scala:341)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20/08/04 16:06:10 WARN TaskSetManager: Lost task 4.0 in stage 18.0 (TID 94, 30.99.70.120, executor 0): ai.rapids.cudf.CudaException: an illegal memory access was encountered
        at ai.rapids.cudf.Cuda.memcpy(Native Method)
        at ai.rapids.cudf.Cuda.memcpy(Cuda.java:272)
        at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:43)
        at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:113)
        at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1481)
        at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1522)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.tryReadNext(GpuColumnarBatchSerializer.scala:152)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.hasNext(GpuColumnarBatchSerializer.scala:175)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:31)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.RemoveEmptyBatchIterator.hasNext(GpuCoalesceBatches.scala:124)
        at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:176)
        at com.nvidia.spark.rapids.ConcatAndConsumeAll$.getSingleBatchWithVerification(GpuCoalesceBatches.scala:77)
        at com.nvidia.spark.rapids.GpuShuffledHashJoinExec.$anonfun$doExecuteColumnar$2(GpuShuffledHashJoinExec.scala:105)
        at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20/08/04 16:06:10 ERROR TaskSetManager: Task 0 in stage 18.0 failed 4 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 18.0 failed 4 times, most recent failure: Lost task 0.3 in stage 18.0 (TID 99, 30.99.70.120, executor 0): ai.rapids.cudf.CudaException: an illegal memory access was encountered
        at ai.rapids.cudf.Cuda.memcpy(Native Method)
        at ai.rapids.cudf.Cuda.memcpy(Cuda.java:272)
        at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:43)
        at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:113)
        at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1481)
        at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1522)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.tryReadNext(GpuColumnarBatchSerializer.scala:152)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.hasNext(GpuColumnarBatchSerializer.scala:175)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:31)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at com.nvidia.spark.rapids.RemoveEmptyBatchIterator.hasNext(GpuCoalesceBatches.scala:124)
        at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:176)
        at com.nvidia.spark.rapids.ConcatAndConsumeAll$.getSingleBatchWithVerification(GpuCoalesceBatches.scala:77)
        at com.nvidia.spark.rapids.GpuShuffledHashJoinExec.$anonfun$doExecuteColumnar$2(GpuShuffledHashJoinExec.scala:105)
        at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2023)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1972)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1971)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1971)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:950)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:950)
  at scala.Option.foreach(Option.scala:407)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:950)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2203)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2152)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2141)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:752)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2093)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2133)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2158)
  at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
  at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:385)
  at org.apache.spark.sql.Dataset.$anonfun$count$1(Dataset.scala:2979)
  at org.apache.spark.sql.Dataset.$anonfun$count$1$adapted(Dataset.scala:2978)
  at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3616)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:763)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3614)
  at org.apache.spark.sql.Dataset.count(Dataset.scala:2978)
  ... 47 elided
Caused by: ai.rapids.cudf.CudaException: an illegal memory access was encountered
  at ai.rapids.cudf.Cuda.memcpy(Native Method)
  at ai.rapids.cudf.Cuda.memcpy(Cuda.java:272)
  at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:43)
  at ai.rapids.cudf.BaseDeviceMemoryBuffer.copyFromHostBuffer(BaseDeviceMemoryBuffer.java:113)
  at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1481)
  at ai.rapids.cudf.JCudfSerialization.readTableFrom(JCudfSerialization.java:1522)
  at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.tryReadNext(GpuColumnarBatchSerializer.scala:152)
  at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2$$anon$3.hasNext(GpuColumnarBatchSerializer.scala:175)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
  at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:31)
  at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
  at com.nvidia.spark.rapids.RemoveEmptyBatchIterator.hasNext(GpuCoalesceBatches.scala:124)
  at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:176)
  at com.nvidia.spark.rapids.ConcatAndConsumeAll$.getSingleBatchWithVerification(GpuCoalesceBatches.scala:77)
  at com.nvidia.spark.rapids.GpuShuffledHashJoinExec.$anonfun$doExecuteColumnar$2(GpuShuffledHashJoinExec.scala:105)
  at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
  at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
  at org.apache.spark.scheduler.Task.run(Task.scala:127)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

**Comment by jlowe** [comment]
Thanks for the bug report @tonglei19961121 .  It would be really helpful if we could reproduce this locally, e.g.: is there a way we could obtain the data to reproduce (if the data is public) or a way to generate sample data that reproduces the issue?

The error indicates something triggered an address error on the GPU, but due to the nature of how GPUs run asynchronously, the line reporting the error may not actually be the code that originally triggered the error.  If we are unable to reproduce this locally, you could try running a few experiments to see if we can narrow down where the address fault is originating.  First step would be to turn off GPU memory pooling so each GPU allocation is a separate CUDA allocation.  You can do this by setting the config: `spark.rapids.memory.gpu.pooling.enabled=false`.  This will significantly slow down the performance but may expose the address error closer to the source.

You could also try running the executor under `cuda-memcheck`.  This will probably require running in Spark local mode so the checker is check against the all-in-one JVM process.  Performance may be very slow as well.

Some other questions to try to narrow down the issue:
- Does this always happen regardless of the number of shuffle partitions?
- Are multiple tasks failing with this error or only a single task?  If only a single task fails, it may be related to specific data that is triggering the issue.

**Comment by tonglei19961121** [comment]
Yes, the dataset is easy to copy. Our dataset is from the public iris dataset. We just simply extended the iris data by copying the rows through a sh file. Last Friday, we did one more test and we found that the error would happen when the data is extended to 28m.(It works well with the origin data, a and b is the same). But everything in the office computer is not allowed to be sent to the internet, so I can't provide the data for you, which I am really sorry for.

**Comment by tonglei19961121** [comment]
Yes, we can provide the method to reproduce the problem. The data is from iris dataset (https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) ,we just simply convert the label into integer (Iris-setosa: 0.0, Iris-versicolor:1.0, Iris-virginica:2.0), and use a shell script to expand the file size. We tested this procedure again, found that this error would happen when the file was exceeded to 28MB. Hope those information would help, please feel free to contact me if have questions.

content in shell script：
#!/bin/bash

time = 10

while(($time>=0))
  do 
    cat iris.data >> iris_extened_10.data
    let "time=time-1"
    echo "times left ${time}"
  done

**Comment by wjxiz1992** [comment]
@tonglei19961121 Hi, are you able to monitor the GPU memory usage when this job is running?  like using `watch -n 0.5 nvidia-smi`

I used to get a similar issue, it is caused by "inner join memory explosion".  As inner join may produce a n*n level output in one task(partition)

Can you make a rough estimation about how many rows will be produced for a most duplicated "sepal_length" ?

**Comment by tonglei19961121** [comment]
Thank you for your reply! n is about 1,500,000. But this join operation works on CPU version of spark.

**Comment by wjxiz1992** [comment]
@tonglei19961121 n = 1, 500, 000 this is a very large number. I don't think GPU could handle this size properly.

I think CPU works well for this because it supports "spill to disk" but currently gpu doesn't support it yet.

**Comment by revans2** [comment]
It is possible that we are running out of memory, but I would want to reproduce the issue just to be sure.

Looking at the iris data set linked above it looks like you have 4 float/double values and a string.  If we assume that they are stored as doubles then we have (8 * 4) bytes to store the 4 doubles and (4 + 15) bytes to stored the string (longest string was 15 characters and a offset/length value) or about 51 bytes per row.  If you stored all of the float values as strings it would be similar with 4 bytes for the offset/length and 4 bytes of actual data. All the numbers look to be 3 bytes i.e. `4.4` , but 4 means I don't have to do extra math).  That means we would have about 73MB of data for 1,500,000 rows.  Since it is a join we need to double that for each column or about 150 MB of data. But there could be overhead with how we are doing the join.  I would expect even on a 12 GB card that you could make this work if you partitioned the data more.

Could you give us the schema that you used for reading the data so we can try to reproduce it?

**Comment by jlowe** [comment]
This has likely been fixed a long time ago, either via libcudf changes or improved GPU memory handling in the Spark plugin.  Reopen with repro details if this is still occurring.
