### ISSUE TITLE
[BUG][22.04] Driver depends on cuDF libaray. 

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#5194]
**Describe the bug**
In https://github.com/NVIDIA/spark-rapids/pull/5122, below change caused the driver depended on cuDF library.
When you submit the job from a non-gpu master node, it reported below error.

Thread-6 22/04/11 02:13:56:351 ERROR NativeDepsLoader: Could not load cudf jni library...
java.io.IOException: Error loading dependencies
        at ai.rapids.cudf.NativeDepsLoader.loadNativeDeps(NativeDepsLoader.java:166)
        at ai.rapids.cudf.NativeDepsLoader.loadNativeDeps(NativeDepsLoader.java:74)
        at ai.rapids.cudf.Cuda.<clinit>(Cuda.java:27)
        at com.nvidia.spark.rapids.GpuColumnarToRowExecParent$.isAcceleratedTransposeSupported$lzycompute(GpuColumnarToRowExec.scala:356)
        at com.nvidia.spark.rapids.GpuColumnarToRowExecParent$.isAcceleratedTransposeSupported(GpuColumnarToRowExec.scala:356)
        at com.nvidia.spark.rapids.GpuColumnarToRowExecParent$.makeIteratorFunc(GpuColumnarToRowExec.scala:377)
        at com.nvidia.spark.rapids.GpuColumnarToRowExecParent.doExecute(GpuColumnarToRowExec.scala:317)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:321)
        at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:439)
        at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:425)
        at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:47)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:277)
        at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3519)
        at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
        at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3516)
        at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /tmp/cudf6770903182327468423.so: libcuda.so.1: cannot open shared object file: No such file or directory
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at ai.rapids.cudf.NativeDepsLoader.loadNativeDeps(NativeDepsLoader.java:164)

The related code is
[[GpuColumnarToRowExec.scala](https://github.com/NVIDIA/spark-rapids/pull/5122/files#diff-6d75862946807626a1cbb5fae97f11ab37e90a844dd5b00dc4874880fabf6d67)](https://github.com/NVIDIA/spark-rapids/pull/5122/files#diff-6d75862946807626a1cbb5fae97f11ab37e90a844dd5b00dc4874880fabf6d67R356)

**Steps/Code to reproduce bug**
We reproduced it when running NDS 2.0.

**Expected behavior**
Driver shouldn't depend on cudf lib since we don't guarantee it's a GPU node.

**Environment details (please complete the following information)**
Spark2a

**Comment by GaryShen2008** [comment]
Seems duplicate this issue https://github.com/NVIDIA/spark-rapids/issues/5181.
Close it.
