### ISSUE TITLE
GpuHashAggregateIterator.mergePass OOM and improve batch size handling 

### ISSUE THREAD

**Issue by ericrife** [NVIDIA/spark-rapids#5231]
Received the following error during NDS v1 run on Q67 when running in dataproc

java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: RMM failure at:/home/jenkins/agent/workspace/jenkins-cudf-release-36-cuda11/cpp/build/_deps/rmm-src/include/rmm/mr/device/arena_memory_resource.hpp:159: Maximum pool size exceeded

Runtime options
spark.rapids.memory.gpu.pool=ARENA
spark.rapids.sql.batchSizeBytes=1GB
spark.driver.maxResultSize=2GB
spark.executor.cores=16
spark.locality.wait=0
spark.rapids.sql.concurrentGpuTasks=2
spark.executor.resource.gpu.amount=1
spark.task.resource.gpu.amount=0.0625
spark.executor.memory=16G
spark.driver.memory=50G
spark.sql.shuffle.partitions=200
spark.sql.files.maxPartitionBytes=2gb
spark.driver.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR:$CUDF_JAR:$SPARK_RAPIDS_PLUGIN_INTEGRATION_TEST_JAR:$SCALLOP_JAR
spark.executor.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR:$CUDF_JAR
spark.executor.extraJavaOptions=-Dai.rapids.cudf.nvtx.enabled=true
spark.rapids.memory.host.spillStorageSize=32G
spark.sql.adaptive.enabled=true
spark.plugins=com.nvidia.spark.SQLPlugin
spark.rapids.memory.pinnedPool.size=8g
spark.rapids.shuffle.maxMetadataSize=512KB

Capturing here as this was part of VPR

**Comment by tgravescs** [comment]
Note this looks like potentially a memory fragmentation issue, it is asking for 1.9GB and rmm should have close to 9GB free, but need to investigate more.

`22/04/12 18:31:16 INFO com.nvidia.spark.rapids.GpuDeviceManager: Initializing RMM ARENA pool size = 14055.75 MB on gpuId 0
`

```
22/04/12 18:39:36 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Device allocation of 1115853760 bytes failed, device store has 5852808064 bytes. Total RMM allocated is 9847463424 bytes.
22/04/12 18:39:37 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Spilled 1196781184 bytes from the device store
22/04/12 18:39:38 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Device allocation of 187891248 bytes failed, device store has 5771880640 bytes. Total RMM allocated is 13110171904 bytes.
22/04/12 18:39:39 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Spilled 1115855296 bytes from the device store
22/04/12 18:39:39 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Device allocation of 1474401024 bytes failed, device store has 4656025344 bytes. Total RMM allocated is 8589462016 bytes.
22/04/12 18:39:40 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Spilled 1580935744 bytes from the device store
22/04/12 18:39:41 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Device allocation of 1919754752 bytes failed, device store has 3783583808 bytes. Total RMM allocated is 8237836288 bytes.
22/04/12 18:39:41 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Spilled 1976281408 bytes from the device store
22/04/12 18:39:41 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Device allocation of 1919754752 bytes failed, device store has 1827207104 bytes. Total RMM allocated is 5788981504 bytes.
22/04/12 18:39:43 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Spilled 1827207104 bytes from the device store
22/04/12 18:39:43 INFO com.nvidia.spark.rapids.DeviceMemoryEventHandler: Device allocation of 1919754752 bytes failed, device store has 0 bytes. Total RMM allocated is 4632892416 bytes.
22/04/12 18:39:43 WARN com.nvidia.spark.rapids.DeviceMemoryEventHandler: Device store exhausted, unable to allocate 1919754752 bytes. Total RMM allocated is 4645616128 bytes.
22/04/12 18:39:43 ERROR org.apache.spark.executor.Executor: Exception in task 4.0 in stage 34.0 (TID 12078)
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: RMM failure at:/arena_memory_resource.hpp:159: Maximum pool size exceeded
	at ai.rapids.cudf.Table.contiguousSplit(Native Method)
	at ai.rapids.cudf.Table.contiguousSplit(Table.java:2062)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$3(SpillableColumnarBatch.scala:204)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$3$adapted(SpillableColumnarBatch.scala:203)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.withResource(SpillableColumnarBatch.scala:131)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$1(SpillableColumnarBatch.scala:203)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$1$adapted(SpillableColumnarBatch.scala:181)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.withResource(SpillableColumnarBatch.scala:131)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.addBatch(SpillableColumnarBatch.scala:181)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.apply(SpillableColumnarBatch.scala:151)
	at com.nvidia.spark.rapids.LazySpillableColumnarBatchImpl.$anonfun$allowSpilling$1(JoinGatherer.scala:297)
	at com.nvidia.spark.rapids.LazySpillableColumnarBatchImpl.$anonfun$allowSpilling$1$adapted(JoinGatherer.scala:293)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.LazySpillableColumnarBatchImpl.withResource(JoinGatherer.scala:262)
	at com.nvidia.spark.rapids.LazySpillableColumnarBatchImpl.allowSpilling(JoinGatherer.scala:293)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.mergePass(aggregate.scala:367)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$tryMergeAggregatedBatches$1(aggregate.scala:308)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$tryMergeAggregatedBatches$1$adapted(aggregate.scala:306)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.withResource(aggregate.scala:181)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.tryMergeAggregatedBatches(aggregate.scala:306)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:239)
	at scala.Option.getOrElse(Option.scala:189)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
	at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:288)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:304)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
```

**Comment by tgravescs** [comment]
it looks like we ran this query with 2 executors instead of 8.  That doesn't change the fact it can happen.  Not sure we can make the merge here smarter to deal with this error by merging partial matches instead of a full batch, it might be something we look into more.

**Comment by ericrife** [comment]
The query ran successfully with 8 executors.

**Comment by revans2** [comment]
> it looks like we ran this query with 2 executors instead of 8. That doesn't change the fact it can happen. Not sure we can make the merge here smarter to deal with this error by merging partial matches instead of a full batch, it might be something we look into more.

That is an interesting idea. If we are going for a target size, not a single batch or a specific value range, would it be better for us to catch the exception and output multiple smaller batches instead? @tgravescs do you want to file an issue for this or should I?

**Comment by tgravescs** [comment]
I'm just going to convert this issue to see if we can improve the handling. @revans2  if you have specific ideas please just add here.

**Comment by jlowe** [comment]
Moved to async allocator  to reduce fragmentation and many OOM handling improvements since this was filed.
