### ISSUE TITLE
[BUG] Spark 3.3 integration test failures logic_test.py::test_logical_with_side_effect

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5244]
**Describe the bug**
```
10:23:26  FAILED ../../src/main/python/logic_test.py::test_logical_with_side_effect[NULL-2147483647-true-AND]
10:23:26  FAILED ../../src/main/python/logic_test.py::test_logical_with_side_effect[NULL-2147483647-true-OR]
10:23:26  FAILED ../../src/main/python/logic_test.py::test_logical_with_side_effect[a-2147483647-true-OR]
10:23:26  FAILED ../../src/main/python/logic_test.py::test_logical_with_side_effect[b-2147483647-true-AND]
```

```
10:23:26  ../../src/main/python/logic_test.py::test_logical_with_side_effect[NULL-2147483647-true-AND] 22/04/13 15:23:15 WARN TaskSetManager: Lost task 0.0 in stage 10.0 (TID 20) (executor 0): org.apache.spark.SparkArithmeticException: integer overflow. If necessary set spark.sql.ansi.enabled to false (except for ANSI interval type) to bypass this error.
10:23:26  == SQL(line 1, position 10) ==
10:23:26  NULL AND (c + 2) > 0
10:23:26            ^^^^^
10:23:26  
10:23:26  	at org.apache.spark.sql.errors.QueryExecutionErrors$.arithmeticOverflowError(QueryExecutionErrors.scala:458)
10:23:26  	at org.apache.spark.sql.catalyst.util.MathUtils$.withOverflow(MathUtils.scala:76)
10:23:26  	at org.apache.spark.sql.catalyst.util.MathUtils$.addExact(MathUtils.scala:30)
10:23:26  	at org.apache.spark.sql.catalyst.util.MathUtils.addExact(MathUtils.scala)
10:23:26  	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
```

**Comment by andygrove** [comment]
The test is expecting `java.lang.ArithmeticException` but Spark 3.3 now throws a `SparkArithmeticException`

**Comment by sameerz** [comment]
Is this related to https://github.com/NVIDIA/spark-rapids/issues/5196 ?

**Comment by andygrove** [comment]
> Is this related to #5196 ?

Yes, #5196 is the real fix for this. #5247 is a temporary workaround until we implement that.

**Comment by andygrove** [comment]
Fixed in https://github.com/NVIDIA/spark-rapids/pull/5247
