### ISSUE TITLE
[BUG] ColumnarRdd(df) is not working on databricks 10.4 LTS ML with 22.04.0 release

### ISSUE THREAD

**Issue by wbo4958** [NVIDIA/spark-rapids#5292]
When extracting the RDD[Table] by ColumnarRdd(df) on Databricks 10.4 GPU, **StackOverflowError** is thrown.

## How to reproduce

``` scala
val input = "xxx"
val rawInput = spark.read.parquet(input)
rawInput.explain()
```

== Physical Plan ==
GpuColumnarToRow false
+- GpuFileGpuScan parquet [orig_channel#320,first_home_buyer#321,loan_purpose#322,property_type#323,occupancy_status#324,property_state#325,product_type#326,relocation_mortgage_indicator#327,seller_name#328,mod_flag#329,orig_interest_rate#330,orig_upb#331,orig_loan_term#332,orig_ltv#333,orig_cltv#334,num_borrowers#335,dti#336,borrower_credit_score#337,num_units#338,zip#339,mortgage_insurance_percent#340,current_loan_delinquency_status#341,current_actual_upb#342,interest_rate#343,... 4 more fields] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[xxx], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<orig_channel:int,first_home_buyer:int,loan_purpose:int,property_type:int,occupancy_status:...

``` scala
import com.nvidia.spark.rapids.ColumnarRdd
val df1 = rawInput.repartition(2)
val rdd = ColumnarRdd(df1)
```

Then **StackOverflowError** will be thrown

``` console
	at scala.collection.generic.Growable.loop$1(Growable.scala:55)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
	at scala.collection.generic.GenericTraversableTemplate.$anonfun$flatten$1(GenericTraversableTemplate.scala:174)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.generic.GenericTraversableTemplate.flatten(GenericTraversableTemplate.scala:173)
	at scala.collection.generic.GenericTraversableTemplate.flatten$(GenericTraversableTemplate.scala:171)
	at scala.collection.AbstractTraversable.flatten(Traversable.scala:108)
	at org.apache.spark.internal.config.ConfigEntry.readString(ConfigEntry.scala:95)
	at org.apache.spark.internal.config.FallbackConfigEntry.readFrom(ConfigEntry.scala:271)
	at org.apache.spark.sql.internal.SQLConf.$anonfun$getConf$4(SQLConf.scala:4644)
	at com.databricks.spark.DatabricksSparkConf$AioaLazyConfigConf$.recordConfigEntryAccessDuringWarmUp(DatabricksSparkConf.scala:943)
	at org.apache.spark.sql.internal.SQLConf.getConf(SQLConf.scala:4642)
	at org.apache.spark.sql.internal.SQLConf.cboEnabled(SQLConf.scala:4342)
	at com.databricks.sql.optimizer.SparkPlanStats.computeStats(SparkPlanStats.scala:29)
	at com.databricks.sql.optimizer.SparkPlanStats.computeStats$(SparkPlanStats.scala:28)
	at org.apache.spark.sql.execution.SparkPlan.computeStats(SparkPlan.scala:89)
	at com.databricks.sql.optimizer.statsEstimation.SizeInBytesOnlyStatsSparkPlanVisitor$.default(SizeInBytesOnlyStatsSparkPlanVisitor.scala:49)
	at com.databricks.sql.optimizer.statsEstimation.SizeInBytesOnlyStatsSparkPlanVisitor$.default(SizeInBytesOnlyStatsSparkPlanVisitor.scala:41)
	at com.databricks.sql.execution.SparkPlanVisitor.visit(SparkPlanVisitor.scala:83)
	at com.databricks.sql.execution.SparkPlanVisitor.visit$(SparkPlanVisitor.scala:33)
	at com.databricks.sql.optimizer.statsEstimation.SizeInBytesOnlyStatsSparkPlanVisitor$.visit(SizeInBytesOnlyStatsSparkPlanVisitor.scala:41)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.fallback(BasicStatsSparkPlanVisitor.scala:43)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.default(BasicStatsSparkPlanVisitor.scala:45)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.default(BasicStatsSparkPlanVisitor.scala:35)
	at com.databricks.sql.execution.SparkPlanVisitor.visit(SparkPlanVisitor.scala:83)
	at com.databricks.sql.execution.SparkPlanVisitor.visit$(SparkPlanVisitor.scala:33)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.super$visit(BasicStatsSparkPlanVisitor.scala:39)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.$anonfun$visit$1(BasicStatsSparkPlanVisitor.scala:39)
	at scala.Option.getOrElse(Option.scala:189)
	at com.databricks.sql.optimizer.statsEstimation.BasicStatsSparkPlanVisitor$.visit(BasicStatsSparkPlanVisitor.scala:39)
	at com.databricks.sql.optimizer.SparkPlanStats.computeStats(SparkPlanStats.scala:30)
	at com.databricks.sql.optimizer.SparkPlanStats.computeStats$(SparkPlanStats.scala:28)
```

BTW, it can pass without repartition

``` scala
val input = "dbfs:/bobwang/mortgage/etled/2000"
val rawInput = spark.read.parquet(input)
rawInput.explain()
import com.nvidia.spark.rapids.ColumnarRdd
val rdd = ColumnarRdd(rawInput)
```

## Envs

- version
spark 3.2.1
rapids/cudf 22.04.0

- conf

``` XML
spark.task.resource.gpu.amount 1
spark.executor.resource.gpu.amount 1
spark.plugins com.nvidia.spark.SQLPlugin
spark.task.cpus 8
```

**Comment by wbo4958** [comment]
After disabling AQE, this issue is gone. Do we need to check that?

**Comment by tgravescs** [comment]
its a known issue AQE doesn't work with databricks and we document you have to turn it off.

**Comment by wbo4958** [comment]
Thx for the info, close this issue.
