### ISSUE TITLE
[BUG] OOM in Power Run when UCX is on with mono-plugin jar

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#5303]
**Describe the bug**
Start from 04/21, NDS Power Run with UCX on started to fail in our daily CI job with the following error message in executors
```
dispatcher-Executor 22/04/24 07:24:20:786 ERROR RapidsExecutorPlugin: Exception in the executor plugin, shutting down!
ai.rapids.cudf.CudaException: out of memory
        at ai.rapids.cudf.Cuda.freeZero(Native Method)
        at com.nvidia.spark.rapids.GpuDeviceManager$.setGpuDeviceAndAcquire(GpuDeviceManager.scala:99)
        at com.nvidia.spark.rapids.GpuDeviceManager$.$anonfun$initializeGpu$1(GpuDeviceManager.scala:125)
        at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:23)
        at scala.Option.map(Option.scala:230)
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpu(GpuDeviceManager.scala:125)
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpuAndMemory(GpuDeviceManager.scala:136)
        at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:232)
        at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:125)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:113)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:211)
        at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:199)
        at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:253)
        at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:222)
        at org.apache.spark.executor.Executor.<init>(Executor.scala:253)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:159)
        at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
        at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
        at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
        at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
        at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
**Steps/Code to reproduce bug**
Run NDS power with our latest NDS2.0 script:
```
./spark-submit-template power_run_gpu.template \
nds_power.py \
hdfs:/data/nds2.0/parquet_sf3k_decimal \
/home/rladmin/nds2.0/query_streams_sf3k/query_1.sql \
time.csv \
```

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark configuration settings related to the issue:
```
--conf spark.driver.maxResultSize=2GB \
--conf spark.driver.memory=50G \
--conf spark.executor.cores=16 \
--conf spark.executor.instances=8 \
--conf spark.executor.memory=16G \
--conf spark.locality.wait=0 \
--conf spark.sql.shuffle.partitions=1024 \
--conf spark.sql.adaptive.enabled=true \
--conf spark.executor.resource.gpu.amount=1 \
--conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
--conf spark.plugins=com.nvidia.spark.SQLPlugin \
--conf spark.rapids.memory.host.spillStorageSize=32G \
--conf spark.rapids.memory.pinnedPool.size=8g \
--conf spark.rapids.sql.concurrentGpuTasks=4 \
--conf spark.rapids.sql.explain=NOT_ON_GPU \
--conf spark.rapids.sql.incompatibleOps.enabled=true \
--conf spark.sql.files.maxPartitionBytes=2gb \
--conf spark.task.cpus=1 \
--conf spark.task.resource.gpu.amount=0.0625 \
--conf spark.shuffle.manager=com.nvidia.spark.rapids.spark312.RapidsShuffleManager \
--conf spark.shuffle.service.enabled=false \
--conf spark.driver.extraClassPath=/opt/sparkRapidsPlugin/spark-raplab-cicd/jenkins-nds2-test-raplab-10/jars/rapids-4-spark_2.12-22.06.0-20220423.070304-22-cuda11.jar \
--conf spark.executor.extraClassPath=/opt/sparkRapidsPlugin/spark-raplab-cicd/jenkins-nds2-test-raplab-10/jars/rapids-4-spark_2.12-22.06.0-20220423.070304-22-cuda11.jar \
--conf spark.executorEnv.UCX_ERROR_SIGNALS= \
--conf spark.executorEnv.UCX_IB_GPU_DIRECT_RDMA=yes \
--conf spark.executorEnv.UCX_IB_RX_QUEUE_LEN=1024 \
--conf spark.executorEnv.UCX_MEMTYPE_CACHE=n \
--conf spark.executorEnv.UCX_RNDV_SCHEME=put_zcopy \
--conf spark.rapids.memory.host.pageablePool.size=32G \
--conf spark.rapids.shuffle.transport.enabled=true \
--conf spark.rapids.shuffle.maxMetadataSize=1MB \
--conf spark.rapids.shuffle.ucx.bounceBuffers.device.count=64 \
--conf spark.rapids.shuffle.ucx.bounceBuffers.host.count=64 \
--conf spark.rapids.shuffle.ucx.bounceBuffers.size=4MB \
--files /opt/spark/spark-3.1.2-bin-hadoop3.2/examples/src/main/scripts/getGpusResources.sh \
--jars /opt/sparkRapidsPlugin/spark-raplab-cicd/jenkins-nds2-test-raplab-10/jars/rapids-4-spark_2.12-22.06.0-20220423.070304-22-cuda11.jar \
nds_power.py \
hdfs:/data/nds2.0/parquet_sf3k_decimal \
/home/rladmin/nds2.0/query_streams_sf3k/query_1.sql \
time-1650779949.csv
```

**Additional context**
The error doesn't happen to specific query in different runs but happens to non-deterministic query. 
Power Run with the jar right before our mono-plugin jar change is good. the jars are : cudf-22.06.0-20220417.022449-22.jar and rapids-4-spark_2.12-22.06.0-20220417.093742-14.jar.

non-UCX run is always good till now.

**Comment by abellina** [comment]
From what I see in the logs @wjxiz1992 the issue in the description is not the actual problem. The description is pointing at a brand new executor that is trying to start, but it can't, because the GPU is busy with a prior executor that is having issues. 

The earlier failure is an OOM with the async allocator that according to the logs looks just like fragmentation (which seems odd). 

1. We have 4 tasks with the semaphore (task 88, 89, 92, 94). Tasks 89, 94, and 92 are allocating ~50MB, and task 88 is trying to allocate 560MB. 
2. RMM was at 3.3 GB aand we spill 300MB trying to let these allocations through. 
3. With RMM at 3.0 GB we still can't handle the allocations, note this is a 40GB GPU and our pool was sized correctly from the beginning (`dispatcher-Executor 22/04/24 05:24:25:995 INFO GpuDeviceManager: Initializing RMM ASYNC pool size = 39164.1875 MB on gpuId 0`)

So this seems like exactly the type of case where the async allocator should be helping. Alternatively we could have our stats wrong on what the RMM pool actually has allocated. It needs to be investigated further.

Pertinent logs:

```
Executor task launch worker for task 89.0 in stage 1128.0 (TID 139363) 22/04/24 05:41:10:533 INFO DeviceMemoryEventHandler: Device allocation of 45350928 bytes failed, device store has 0 bytes. Total RMM allocated is 3325171712 bytes.
Executor task launch worker for task 94.0 in stage 1128.0 (TID 139368) 22/04/24 05:41:10:534 INFO DeviceMemoryEventHandler: Device allocation of 47549192 bytes failed, device store has 0 bytes. Total RMM allocated is 3325171712 bytes.
Executor task launch worker for task 92.0 in stage 1128.0 (TID 139366) 22/04/24 05:41:10:534 INFO DeviceMemoryEventHandler: Device allocation of 45360496 bytes failed, device store has 0 bytes. Total RMM allocated is 3325171712 bytes.
Executor task launch worker for task 88.0 in stage 1128.0 (TID 139362) 22/04/24 05:41:10:534 INFO DeviceMemoryEventHandler: Device allocation of 560718784 bytes failed, device store has 0 bytes. Total RMM allocated is 3043957504 bytes.
Executor task launch worker for task 89.0 in stage 1128.0 (TID 139363) 22/04/24 05:41:10:548 ERROR Executor: Exception in task 89.0 in stage 1128.0 (TID 139363)
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: CUDA error at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-dev-github-683-cuda11/java/target/cmake-build/_deps/rmm-src/include/rmm/mr/device/cuda_async_view_memory_resource.hpp:120: cudaErrorMemoryAllocation out of memory
```

**Comment by abellina** [comment]
I believe this is a P1 because the logs are telling me this is a fragmentation issue and I was surprised by this behavior with the ASYNC allocator.

**Comment by abellina** [comment]
I can reproduce this easily. I also computed the amount of memory allocated on the GPU manually using the RMM log and I ran OOM with 9GB allocated for example in a 40GB GPU while trying to allocate 500MB, so this seems like fragmentation still.

**Comment by wjxiz1992** [comment]
> From what I see in the logs @wjxiz1992 the issue in the description is not the actual problem. The description is pointing at a brand new executor that is trying to start, but it can't, because the GPU is busy with a prior executor that is having issues.
> 
> The earlier failure is an OOM with the async allocator that according to the logs looks just like fragmentation (which seems odd).
> 
> @wjxiz1992 could you confirm that prior runs (without the mono jar) were actually using ASYNC allocator? Or where they using ARENA? My guess is that this is what actually changed.
> 
> 1. We have 4 tasks with the semaphore (task 88, 89, 92, 94). Tasks 89, 94, and 92 are allocating ~50MB, and task 88 is trying to allocate 560MB.
> 2. RMM was at 3.3 GB and we spill 300MB trying to let these allocations through.
> 3. With RMM at 3.0 GB we still can't handle the allocations, note this is a 40GB GPU and our pool was sized correctly from the beginning (`dispatcher-Executor 22/04/24 05:24:25:995 INFO GpuDeviceManager: Initializing RMM ASYNC pool size = 39164.1875 MB on gpuId 0`)
> 
> So this seems like exactly the type of case where the async allocator should be helping. Alternatively we could have our stats wrong on what the RMM pool actually has allocated. It needs to be investigated further.
> 
> Pertinent logs:
> 
> ```
> Executor task launch worker for task 89.0 in stage 1128.0 (TID 139363) 22/04/24 05:41:10:533 INFO DeviceMemoryEventHandler: Device allocation of 45350928 bytes failed, device store has 0 bytes. Total RMM allocated is 3325171712 bytes.
> Executor task launch worker for task 94.0 in stage 1128.0 (TID 139368) 22/04/24 05:41:10:534 INFO DeviceMemoryEventHandler: Device allocation of 47549192 bytes failed, device store has 0 bytes. Total RMM allocated is 3325171712 bytes.
> Executor task launch worker for task 92.0 in stage 1128.0 (TID 139366) 22/04/24 05:41:10:534 INFO DeviceMemoryEventHandler: Device allocation of 45360496 bytes failed, device store has 0 bytes. Total RMM allocated is 3325171712 bytes.
> Executor task launch worker for task 88.0 in stage 1128.0 (TID 139362) 22/04/24 05:41:10:534 INFO DeviceMemoryEventHandler: Device allocation of 560718784 bytes failed, device store has 0 bytes. Total RMM allocated is 3043957504 bytes.
> Executor task launch worker for task 89.0 in stage 1128.0 (TID 139363) 22/04/24 05:41:10:548 ERROR Executor: Exception in task 89.0 in stage 1128.0 (TID 139363)
> java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: CUDA error at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-dev-github-683-cuda11/java/target/cmake-build/_deps/rmm-src/include/rmm/mr/device/cuda_async_view_memory_resource.hpp:120: cudaErrorMemoryAllocation out of memory
> ```

I didn't set this parameter in our template file, so it should always be the default one. I can switch to ARENA for another run.

**Comment by sameerz** [comment]
> I didn't set this parameter in our template file, so it should always be the default one. I can switch to ARENA for another run.

@wjxiz1992 can you please try with ARENA and let us know whether the same problem occurs?
