### ISSUE TITLE
[BUG] com.nvidia.spark.rapids.RegexCharacterClass cannot be cast to com.nvidia.spark.rapids.RegexCharacterClassComponent

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5492]
When running below query, it failed 
```
: java.lang.ClassCastException: com.nvidia.spark.rapids.RegexCharacterClass cannot be cast to com.nvidia.spark.rapids.RegexCharacterClassComponent
```
Env:
22.06 snapshot jar

Minimum repro in pyspark:
```
from pyspark.sql.types import StructType,StructField, StringType, IntegerType
import pyspark.sql.functions as F
from pyspark.sql.functions import regexp_replace, col

data2 = [("a","","Smith","1111","M",2222),
    ("b","c","","3333","M",4444),
    ("d","","e","5555","M",6666),
    ("f","g","h","6666","F",4000),
    ("i","j","k","","F",-1)
  ]
 
schema = StructType([ \
    StructField("firstname",StringType(),True), \
    StructField("middlename",StringType(),True), \
    StructField("lastname",StringType(),True), \
    StructField("id", StringType(), True), \
    StructField("gender", StringType(), True), \
    StructField("salary", IntegerType(), True) \
  ])


df = spark.createDataFrame(data=data2,schema=schema)
df.printSchema()
df.show(truncate=False)


df.withColumn("firstname", regexp_replace(F.col("firstname"), '[^\sa-zA-Z0-9]', '')).collect()
```

**Comment by viadea** [comment]
Full stacktrace is:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o109.collectToPython.
: java.lang.ClassCastException: com.nvidia.spark.rapids.RegexCharacterClass cannot be cast to com.nvidia.spark.rapids.RegexCharacterClassComponent
	at com.nvidia.spark.rapids.CudfRegexTranspiler.$anonfun$rewrite$2(RegexParser.scala:706)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:38)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:38)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:47)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.nvidia.spark.rapids.CudfRegexTranspiler.rewrite(RegexParser.scala:704)
	at com.nvidia.spark.rapids.CudfRegexTranspiler.$anonfun$rewrite$5(RegexParser.scala:818)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at scala.collection.generic.TraversableForwarder.foldLeft(TraversableForwarder.scala:47)
	at scala.collection.generic.TraversableForwarder.foldLeft$(TraversableForwarder.scala:47)
	at scala.collection.mutable.ListBuffer.foldLeft(ListBuffer.scala:47)
	at com.nvidia.spark.rapids.CudfRegexTranspiler.rewrite(RegexParser.scala:778)
	at com.nvidia.spark.rapids.CudfRegexTranspiler.transpile(RegexParser.scala:470)
	at com.nvidia.spark.rapids.GpuRegExpReplaceMeta.tagExprForGpu(GpuRegExpReplaceMeta.scala:43)
	at com.nvidia.spark.rapids.BaseExprMeta.tagSelfForGpu(RapidsMeta.scala:990)
	at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:302)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3(RapidsMeta.scala:279)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3$adapted(RapidsMeta.scala:279)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:279)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3(RapidsMeta.scala:279)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$3$adapted(RapidsMeta.scala:279)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:279)
	at com.nvidia.spark.rapids.GpuOverrides$.wrapAndTagPlan(GpuOverrides.scala:4017)
	at com.nvidia.spark.rapids.GpuOverrides.applyOverrides(GpuOverrides.scala:4247)
	at com.nvidia.spark.rapids.GpuOverrides.$anonfun$apply$4(GpuOverrides.scala:4220)
	at com.nvidia.spark.rapids.GpuOverrides$.logDuration(GpuOverrides.scala:466)
	at com.nvidia.spark.rapids.GpuOverrides.$anonfun$apply$2(GpuOverrides.scala:4218)
	at com.nvidia.spark.rapids.GpuOverrideUtil$.$anonfun$tryOverride$1(GpuOverrides.scala:4187)
	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:4230)
	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:4210)
	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1(Columnar.scala:545)
	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1$adapted(Columnar.scala:544)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:544)
	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:505)
	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:449)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:448)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$2(QueryExecution.scala:170)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:196)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:196)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:170)
	at org.apache.spark.sql.execution.QueryExecution.withCteMap(QueryExecution.scala:73)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:163)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:163)
	at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:214)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:259)
	at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:228)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3704)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3535)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by andygrove** [comment]
The bug is that the `\s` in `'[^\sa-zA-Z0-9]'` is being transpiled to another character class and we don't support nested character classes. We probably need to fall back to CPU in this case.
