### ISSUE TITLE
[BUG]`test_cache_expand_exec` is failing on 330

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#5673]
**Describe the bug**
`test_cache_expand_exec` is failing according to the 330 nightly IT.
```
[2022-05-07T10:58:56.458Z] FAILED ../../src/main/python/cache_test.py::test_cache_expand_exec[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}-Decimal(20,2)][IGNORE_ORDER]
[2022-05-07T10:58:56.458Z] FAILED ../../src/main/python/cache_test.py::test_cache_expand_exec[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'false'}-String][IGNORE_ORDER]


  Caused by: java.lang.NoSuchMethodException: org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.readBatch(int, org.apache.spark.sql.execution.vectorized.WritableColumnVector)
[2022-05-07T10:58:56.457Z] E                   	at java.lang.Class.getDeclaredMethod(Class.java:2130)
[2022-05-07T10:58:56.457Z] E                   	at com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer.<init>(ParquetCachedBatchSerializer.scala:693)
[2022-05-07T10:58:56.457Z] E                   	at com.nvidia.spark.rapids.ParquetCachedBatchSerializer.$anonfun$convertCachedBatchToInternalRow$1(ParquetCachedBatchSerializer.scala:595)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.scheduler.Task.run(Task.scala:136)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
[2022-05-07T10:58:56.457Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
[2022-05-07T10:58:56.457Z] E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-05-07T10:58:56.457Z] E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-05-07T10:58:56.457Z] E                   	... 1 more
```

**Comment by tgravescs** [comment]
This is odd, these tests have been failing since April 9th.

These tests passed for me running against official rc3 spark 3.3 image yesterday though.

**Comment by tgravescs** [comment]
this should have been fixed with https://github.com/NVIDIA/spark-rapids/pull/5425, my guess is something wrong with integration env, the line number if complains about is from before that change

**Comment by tgravescs** [comment]
I think you may have looked at the old IT build, last nights passed as well, closing.

**Comment by firestarman** [comment]
The NO. I checked were 81 and 82, but maybe they still referred to the old spark images.
