### ISSUE TITLE
[BUG] test_parquet_compress_read_round_trip tests failed in spark320+

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#5914]
**Describe the bug**
related to https://github.com/NVIDIA/spark-rapids/pull/5898

failures,
```
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[-reader_confs0-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[-reader_confs1-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[-reader_confs2-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[-reader_confs3-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[-reader_confs4-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[-reader_confs5-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[parquet-reader_confs0-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[parquet-reader_confs1-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[parquet-reader_confs2-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[parquet-reader_confs3-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[parquet-reader_confs4-zstd]
[2022-06-26T07:51:57.938Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_compress_read_round_trip[parquet-reader_confs5-zstd]
```

detailed log,
```
[2022-06-26T07:51:57.658Z] 
[2022-06-26T07:51:57.658Z] answer = 'xro756891'
[2022-06-26T07:51:57.658Z] gateway_client = <py4j.clientserver.JavaClient object at 0x7fd298abb7c0>
[2022-06-26T07:51:57.658Z] target_id = 'o756888', name = 'collectToPython'
[2022-06-26T07:51:57.658Z] 
[2022-06-26T07:51:57.658Z]     [94mdef[39;49;00m [92mget_return_value[39;49;00m(answer, gateway_client, target_id=[94mNone[39;49;00m, name=[94mNone[39;49;00m):
[2022-06-26T07:51:57.658Z]         [33m"""Converts an answer received from the Java gateway into a Python object.[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    For example, string representation of integers are converted to Python[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    integer, string representation of objects are converted to JavaObject[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    instances, etc.[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    :param answer: the string returned by the Java gateway[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    :param gateway_client: the gateway client used to communicate with the Java[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m        Gateway. Only necessary if the answer is a reference (e.g., object,[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m        list, map)[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    :param target_id: the name of the object from which the answer comes from[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m        (e.g., *object1* in `object1.hello()`). Optional.[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    :param name: the name of the member from which the answer comes from[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m        (e.g., *hello* in `object1.hello()`). Optional.[39;49;00m
[2022-06-26T07:51:57.658Z]     [33m    """[39;49;00m
[2022-06-26T07:51:57.658Z]         [94mif[39;49;00m is_error(answer)[[94m0[39;49;00m]:
[2022-06-26T07:51:57.658Z]             [94mif[39;49;00m [96mlen[39;49;00m(answer) > [94m1[39;49;00m:
[2022-06-26T07:51:57.658Z]                 [96mtype[39;49;00m = answer[[94m1[39;49;00m]
[2022-06-26T07:51:57.658Z]                 value = OUTPUT_CONVERTER[[96mtype[39;49;00m](answer[[94m2[39;49;00m:], gateway_client)
[2022-06-26T07:51:57.658Z]                 [94mif[39;49;00m answer[[94m1[39;49;00m] == REFERENCE_TYPE:
[2022-06-26T07:51:57.658Z] >                   [94mraise[39;49;00m Py4JJavaError(
[2022-06-26T07:51:57.658Z]                         [33m"[39;49;00m[33mAn error occurred while calling [39;49;00m[33m{0}[39;49;00m[33m{1}[39;49;00m[33m{2}[39;49;00m[33m.[39;49;00m[33m\n[39;49;00m[33m"[39;49;00m.
[2022-06-26T07:51:57.658Z]                         [96mformat[39;49;00m(target_id, [33m"[39;49;00m[33m.[39;49;00m[33m"[39;49;00m, name), value)
[2022-06-26T07:51:57.658Z] [1m[31mE                   py4j.protocol.Py4JJavaError: An error occurred while calling o756888.collectToPython.[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 11823.0 failed 1 times, most recent failure: Lost task 0.0 in stage 11823.0 (TID 39101) (10.2.128.4 executor driver): ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-139-cuda11/thirdparty/cudf/cpp/src/io/comp/nvcomp_adapter.cpp:150: Zstandard compression is experimental, you can enable it through `LIBCUDF_NVCOMP_POLICY` environment variable.[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at ai.rapids.cudf.Table.readParquet(Native Method)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at ai.rapids.cudf.Table.readParquet(Table.java:1035)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.$anonfun$readBufferToTable$4(GpuParquetScan.scala:2088)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.$anonfun$readBufferToTable$3(GpuParquetScan.scala:2087)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.readBufferToTable(GpuParquetScan.scala:2072)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.readBatch(GpuParquetScan.scala:2051)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.liftedTree2$1(GpuMultiFileReader.scala:430)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:429)[0m
[2022-06-26T07:51:57.658Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:389)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:420)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:239)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:155)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.run(Task.scala:95)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:748)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   [0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   Driver stacktrace:[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2984)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2931)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2925)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2925)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1345)[0m
[2022-06-26T07:51:57.659Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1345)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at scala.Option.foreach(Option.scala:407)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1345)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3193)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3134)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3122)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1107)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2637)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:241)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:276)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:81)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:87)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.collectResult$1(ResultCacheManager.scala:589)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.computeResult(ResultCacheManager.scala:596)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:542)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at scala.Option.getOrElse(Option.scala:189)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:541)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:438)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:417)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:422)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3718)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3930)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:213)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:360)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:160)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:968)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:115)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:310)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3928)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3716)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at java.lang.reflect.Method.invoke(Method.java:498)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at py4j.Gateway.invoke(Gateway.java:295)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:748)[0m
[2022-06-26T07:51:57.660Z] [1m[31mE                   Caused by: ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-139-cuda11/thirdparty/cudf/cpp/src/io/comp/nvcomp_adapter.cpp:150: Zstandard compression is experimental, you can enable it through `LIBCUDF_NVCOMP_POLICY` environment variable.[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at ai.rapids.cudf.Table.readParquet(Native Method)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at ai.rapids.cudf.Table.readParquet(Table.java:1035)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.$anonfun$readBufferToTable$4(GpuParquetScan.scala:2088)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.$anonfun$readBufferToTable$3(GpuParquetScan.scala:2087)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.readBufferToTable(GpuParquetScan.scala:2072)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.readBatch(GpuParquetScan.scala:2051)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.liftedTree2$1(GpuMultiFileReader.scala:430)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:429)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:389)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:420)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:239)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:155)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.run(Task.scala:95)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:826)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:829)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[2022-06-26T07:51:57.661Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2022-06-26T07:51:57.662Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)[0m
[2022-06-26T07:51:57.662Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2022-06-26T07:51:57.662Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[2022-06-26T07:51:57.662Z] [1m[31mE                   	... 1 more[0m
[2022-06-26T07:51:57.662Z] 
[2022-06-26T07:51:57.662Z] [1m[31m/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/protocol.py[0m:326: Py4JJavaError
```

**Comment by jbrennan333** [comment]
Sorry about this.  I should have remembered that zstd support is still experimental, and requires that we set LIBCUDF_NVCOMP_POLICY=ALWAYS in order to test it (I had it set in my test environment).   Once 2.3.1 is released and we update cudf to use it, this will no longer be necessary. 

What is the right thing to do for this?   Should I revert #5898 and resubmit it once we have 2.3.1?

**Comment by jbrennan333** [comment]
Actually, this will still be necessary with 2.3.1, because there are still known bugs.  Once we have a release that is stable enough, it will no longer be needed.
