### ISSUE TITLE
[FEA] Fallback Iceberg reads to CPU at query planning time

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#5944]
#5941 adds basic support for Iceberg reads but it currently crashes at task runtime when an Iceberg scan is found that has delete operations that need to be applied by the reader.  It should be possible to detect these delete operations at query planning time after the driver collects the Iceberg table metadata as part of planning the scan.  See `FileScanTask#deletes`.  Falling back for reader-applied deletes at query planning time allows the query to complete (albeit as a CPU scan) rather than crashing the query as it does now.

**Comment by wjxiz1992** [comment]
@jlowe is this issue talking about the error when I try to run a  "DELETE" query in Iceberg:
```
: java.lang.IllegalStateException: Row-based execution should not occur for this class
        at com.nvidia.spark.rapids.GpuHashAggregateExec.doExecute(aggregate.scala:1532)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at com.nvidia.spark.rapids.GpuBringBackToHost.doExecute(GpuBringBackToHost.scala:38)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:321)
        at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:387)
        at org.apache.spark.sql.execution.datasources.v2.DynamicFileFilterExec.doPrepare(DynamicFileFilterExec.scala:103)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:267)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$prepare$1$adapted(SparkPlan.scala:263)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.execution.SparkPlan.prepare(SparkPlan.scala:263)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:216)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.doExecute(AdaptiveSparkPlanExec.scala:295)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
        at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:338)
        at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2$(WriteToDataSourceV2Exec.scala:336)
        at org.apache.spark.sql.execution.datasources.v2.ReplaceDataExec.writeWithV2(ReplaceDataExec.scala:26)
        at org.apache.spark.sql.execution.datasources.v2.ReplaceDataExec.run(ReplaceDataExec.scala:34)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:40)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:40)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:46)
        at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:228)
        at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3700)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3698)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:228)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:750)

```

**Comment by jlowe** [comment]
@wjxiz1992 that exception is a completely different issue.  This is about handling `merge-on-read` mode for Iceberg, where it can encode row deletes in metadata rather than rewriting data partitions to remove the rows.  That does not mean we cannot support DELETE operations, as v1 style deletes where it rewrites the data partitions is supported.

The exception you're getting above has to do with writes crashing and does not seem to have anything to do with reads. Please file a separate issue to track this.
