### ISSUE TITLE
[BUG] When old Hive partition has different schema than new partition& Hive Schema, read old partition fails with "Found no metadata for schema index"

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6005]
**Env:**
Spark RAPIDS 22.06GA (also tested rapids-4-spark_2.12-22.08.0-20220715.110044-29.jar)
Spark Standalone cluster (also tested on Spark on YARN)

**Symptom**
When old Hive partition has different schema than new partition& Hive Schema, read old partition fails with "Found no metadata for schema index"

**Minimum reproduce**

```
1. Hive
drop table test_diff_schema;
create external table test_diff_schema(a string, b int, c STRUCT<`ca`: STRING, `cb`: STRING>) PARTITIONED BY (k string)
STORED AS PARQUET LOCATION '/home/hazhu/data/hive/test_diff_schema';

2. Generate sample data

import spark.implicits._
import org.apache.spark.sql.types._
import org.apache.spark.sql.Row

val data = Seq(
    Row("Adam",1000),
    Row("Bob",2000),
    Row("Cathy",9999)
)

val schema = StructType( Array(
                 StructField("a", StringType,true),
                 StructField("b", IntegerType,true)
             ))

val df = spark.createDataFrame(spark.sparkContext.parallelize(data),schema)
df.createOrReplaceTempView("df")
spark.sql("select a,b, struct(a as ca) as c from df").write.format("parquet").mode("overwrite").save("/home/hazhu/data/hive/test_diff_schema/2021")
spark.sql("select a,b, struct(a as ca,a as cb) as c from df").write.format("parquet").mode("overwrite").save("/home/hazhu/data/hive/test_diff_schema/2022")

3. Hive
ALTER TABLE test_diff_schema ADD PARTITION (k='2021') LOCATION '/home/hazhu/data/hive/test_diff_schema/2021';
ALTER TABLE test_diff_schema ADD PARTITION (k='2022') LOCATION '/home/hazhu/data/hive/test_diff_schema/2022';


4. Spark shell
--GPU run failed:
spark.conf.set("spark.rapids.sql.enabled",true)
spark.sql("""select * from test_diff_schema where k=2021 """).show

--CPU run works fine
spark.conf.set("spark.rapids.sql.enabled",false)
spark.sql("""select * from test_diff_schema where k=2021 """).show
+-----+----+-------------+----+
|    a|   b|            c|   k|
+-----+----+-------------+----+
|Cathy|9999|{Cathy, null}|2021|
| Adam|1000| {Adam, null}|2021|
|  Bob|2000|  {Bob, null}|2021|
+-----+----+-------------+----+
```

**Stacktrace:**
```
22/07/15 15:58:44 WARN TaskSetManager: Lost task 2.0 in stage 22.0 (TID 151) (xxx.xxx.xxx.xxx executor 0): ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni-release-1-cuda11/thirdparty/cudf/cpp/src/io/parquet/reader_impl.cu:422: Found no metadata for schema index
	at ai.rapids.cudf.Table.readParquet(Native Method)
	at ai.rapids.cudf.Table.readParquet(Table.java:1035)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.$anonfun$readBufferToTable$1(GpuParquetScan.scala:1702)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:264)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.readBufferToTable(GpuParquetScan.scala:1701)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readToTable$1(GpuMultiFileReader.scala:845)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:264)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readToTable(GpuMultiFileReader.scala:841)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$1(GpuMultiFileReader.scala:815)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:264)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readBatch(GpuMultiFileReader.scala:797)
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.next(GpuMultiFileReader.scala:783)
	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:420)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at com.nvidia.spark.rapids.GpuBaseLimitExec$$anon$1.hasNext(limit.scala:70)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:287)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:304)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by viadea** [comment]
Reading directly from parquet file works fine:
```
scala> spark.read.parquet("/home/hazhu/data/hive/test_diff_schema/2021").printSchema
root
 |-- a: string (nullable = true)
 |-- b: integer (nullable = true)
 |-- c: struct (nullable = true)
 |    |-- ca: string (nullable = true)


scala> spark.read.parquet("/home/hazhu/data/hive/test_diff_schema/2022").printSchema
root
 |-- a: string (nullable = true)
 |-- b: integer (nullable = true)
 |-- c: struct (nullable = true)
 |    |-- ca: string (nullable = true)
 |    |-- cb: string (nullable = true)


scala> spark.read.parquet("/home/hazhu/data/hive/test_diff_schema/2021").show

+-----+----+-------+
|    a|   b|      c|
+-----+----+-------+
|Cathy|9999|{Cathy}|
| Adam|1000| {Adam}|
|  Bob|2000|  {Bob}|
+-----+----+-------+


scala> spark.read.parquet("/home/hazhu/data/hive/test_diff_schema/2022").show

+-----+----+--------------+
|    a|   b|             c|
+-----+----+--------------+
|Cathy|9999|{Cathy, Cathy}|
| Adam|1000|  {Adam, Adam}|
|  Bob|2000|    {Bob, Bob}|
+-----+----+--------------+
```

**Comment by jlowe** [comment]
The array index error is not really related to the original problem.  Filed rapidsai/cudf#11278 to track that separately.

This appears to be a bug in the plugin.  I dumped the in-memory Parquet file being sent to cudf, and trying to load it directly reproduces the cudf crash as expected.  However Spark CPU is not able to load the file either, so we're generating an invalid Parquet file for cudf to load.

**Comment by jlowe** [comment]
According to the CPU exception, we're encoding the missing column into the footer despite the column data not being present in the file:
```
Caused by: java.lang.IllegalArgumentException: [c, cb] optional binary cb (STRING) is not in the store: [[a] optional binary a (STRING), [b] optional int32 b, [c, ca] optional binary ca (STRING)] 1
  at org.apache.parquet.hadoop.ColumnChunkPageReadStore.getPageReader(ColumnChunkPageReadStore.java:272)
  at org.apache.parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:77)
  at org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:271)
  at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:147)
  at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:109)
  at org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:177)
  at org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:109)
  at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:136)
  at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:225)
  ... 21 more
```

**Comment by jlowe** [comment]
The culprit is that `filterClippedSchema` does not handle the need to filter nested columns -- it only filters top-level columns.  In this case there's a nested column that needs to be removed from the read schema when building the new file schema for libcudf.

**Comment by viadea** [comment]
[part-00015-c6657dc5-aafc-4d9d-ac0a-e129472d835b-c000.snappy.parquet.zip](https://github.com/NVIDIA/spark-rapids/files/9124676/part-00015-c6657dc5-aafc-4d9d-ac0a-e129472d835b-c000.snappy.parquet.zip) Attach a sample parquet file.
