### ISSUE TITLE
[BUG] cache tests throws ClassCastException on Databricks

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#6035]
cache_test had many failures in last night's Databricks test.  Sampling a few, they all had the same type of exception.  One example:
```
data_gen = Byte
enable_vectorized_conf = {'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}

    @pytest.mark.parametrize('data_gen', all_gen, ids=idfn)
    @pytest.mark.parametrize('enable_vectorized_conf', enable_vectorized_confs, ids=idfn)
    @ignore_order
    def test_cache_join(data_gen, enable_vectorized_conf):
        def do_join(spark):
            left, right = create_df(spark, data_gen, 500, 500)
            cached = left.join(right, left.a == right.r_a, 'Inner').cache()
            cached.count() # populates cache
            return cached
>       assert_gpu_and_cpu_are_equal_collect(do_join, conf=enable_vectorized_conf)

../../src/main/python/cache_test.py:71: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../src/main/python/asserts.py:508: in assert_gpu_and_cpu_are_equal_collect
    _assert_gpu_and_cpu_are_equal(func, 'COLLECT', conf=conf, is_cpu_first=is_cpu_first)
../../src/main/python/asserts.py:427: in _assert_gpu_and_cpu_are_equal
    run_on_cpu()
../../src/main/python/asserts.py:413: in run_on_cpu
    from_cpu = with_cpu_session(bring_back, conf=conf)
../../src/main/python/spark_session.py:115: in with_cpu_session
    return with_spark_session(func, conf=copy)
../../src/main/python/spark_session.py:99: in with_spark_session
    ret = func(_spark)
../../src/main/python/asserts.py:201: in <lambda>
    bring_back = lambda spark: limit_func(spark).collect()
../../src/main/python/asserts.py:184: in with_sorted
    df = func(spark)
../../src/main/python/cache_test.py:68: in do_join
    cached = left.join(right, left.a == right.r_a, 'Inner').cache()
/databricks/spark/python/pyspark/sql/dataframe.py:812: in cache
    self._jdf.cache()
/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py:1304: in __call__
    return_value = get_return_value(
/databricks/spark/python/pyspark/sql/utils.py:117: in deco
    return f(*a, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

answer = 'xro406'
gateway_client = <py4j.java_gateway.GatewayClient object at 0x7efd5e0376d0>
target_id = 'o405', name = 'cache'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.
    
        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.
    
        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
>                   raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
                        format(target_id, ".", name), value)
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o405.cache.
E                   : java.lang.ClassCastException: class com.databricks.sql.acl.PlaceholderScimClient
E                   	at java.lang.Class.asSubclass(Class.java:3404)
E                   	at com.databricks.sql.acl.ScimClient$.buildClient(DatabricksScimClient.scala:71)
E                   	at com.databricks.sql.DatabricksEdge.scimClient(DatabricksEdge.scala:70)
E                   	at com.databricks.sql.DatabricksEdge.scimClient$(DatabricksEdge.scala:70)
E                   	at org.apache.spark.sql.hive.HiveSessionStateBuilder.scimClient$lzycompute(HiveSessionStateBuilder.scala:44)
E                   	at org.apache.spark.sql.hive.HiveSessionStateBuilder.scimClient(HiveSessionStateBuilder.scala:44)
E                   	at com.databricks.sql.DatabricksEdge.customResolutionRules(DatabricksEdge.scala:84)
E                   	at com.databricks.sql.DatabricksEdge.customResolutionRules$(DatabricksEdge.scala:76)
E                   	at org.apache.spark.sql.hive.HiveSessionStateBuilder.customResolutionRules(HiveSessionStateBuilder.scala:44)
E                   	at org.apache.spark.sql.hive.HiveSessionStateBuilder$$anon$1.<init>(HiveSessionStateBuilder.scala:104)
E                   	at org.apache.spark.sql.hive.HiveSessionStateBuilder.analyzer(HiveSessionStateBuilder.scala:87)
E                   	at org.apache.spark.sql.internal.BaseSessionStateBuilder.$anonfun$build$2(BaseSessionStateBuilder.scala:376)
E                   	at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:102)
E                   	at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:102)
E                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:96)
E                   	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
E                   	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:134)
E                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:180)
E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
E                   	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:180)
E                   	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:97)
E                   	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:94)
E                   	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:86)
E                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$withCachedData$1(QueryExecution.scala:102)
E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
E                   	at org.apache.spark.sql.execution.QueryExecution.withCachedData$lzycompute(QueryExecution.scala:101)
E                   	at org.apache.spark.sql.execution.QueryExecution.withCachedData(QueryExecution.scala:101)
E                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:112)
E                   	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
E                   	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:134)
E                   	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:180)
E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
E                   	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:180)
E                   	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:109)
E                   	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:109)
E                   	at org.apache.spark.sql.execution.columnar.InMemoryRelation$.apply(InMemoryRelation.scala:302)
E                   	at org.apache.spark.sql.execution.CacheManager.$anonfun$cacheQuery$3(CacheManager.scala:165)
E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:854)
E                   	at org.apache.spark.sql.execution.CacheManager.cacheQuery(CacheManager.scala:160)
E                   	at org.apache.spark.sql.Dataset.persist(Dataset.scala:3257)
E                   	at org.apache.spark.sql.Dataset.cache(Dataset.scala:3267)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
E                   	at py4j.Gateway.invoke(Gateway.java:295)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:251)
E                   	at java.lang.Thread.run(Thread.java:748)
```

**Comment by razajafri** [comment]
I couldn't reproduce this on DB 3.1.2. I have kicked off the job again to see if this happens again

**Comment by razajafri** [comment]
It was probably a glitch somewhere in the CI causing the failure. I couldn't repro it and kicking it off again resolved the failure
