### ISSUE TITLE
[BUG] Test Parquet nested unsigned int: uint8, uint16, uint32 FAILED in spark 320+

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#6054]
**Describe the bug**
seems related to recent cudf parquet reader changes https://github.com/rapidsai/cudf/commits/branch-22.08

UT failed in spark 32X, and 33X. 31X skip this test by default https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/tests/src/test/scala/com/nvidia/spark/rapids/ParquetScanSuite.scala#L162
`cudf/cpp/src/table/table.cpp:42: Column size mismatch: 4 != 2` failed jni submodule targets to https://github.com/rapidsai/cudf/commit/406bce7efb808330e4d3b1c02c909582402f561e

```
11:20:39  - Test Parquet nested unsigned int: uint8, uint16, uint32 *** FAILED ***
11:20:39    org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 250.0 failed 1 times, most recent failure: Lost task 0.0 in stage 250.0 (TID 1124) (jdk11-nightly-jdk11-nightly-dev-gk0s9-w40x3 executor driver): ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-166-cuda11/thirdparty/cudf/cpp/src/table/table.cpp:42: Column size mismatch: 4 != 2
11:20:39  	at ai.rapids.cudf.Table.readParquet(Native Method)
11:20:39  	at ai.rapids.cudf.Table.readParquet(Table.java:1019)
11:20:39  	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.$anonfun$readBufferToTable$1(GpuParquetScan.scala:1805)
11:20:39  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
11:20:39  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
11:20:39  	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)
11:20:39  	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.readBufferToTable(GpuParquetScan.scala:1804)
11:20:39  	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readToTable$1(GpuMultiFileReader.scala:814)
11:20:39  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
11:20:39  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
11:20:39  	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)
11:20:39  	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readToTable(GpuMultiFileReader.scala:810)
11:20:39  	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$1(GpuMultiFileReader.scala:784)
11:20:39  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
11:20:39  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
11:20:39  	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)
11:20:39  	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readBatch(GpuMultiFileReader.scala:766)
11:20:39  	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.next(GpuMultiFileReader.scala:752)
11:20:39  	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
11:20:39  	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
11:20:39  	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
11:20:39  	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:420)
11:20:39  	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:287)
11:20:39  	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:304)
11:20:39  	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
11:20:39  	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
11:20:39  	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
11:20:39  	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
11:20:39  	at org.apache.spark.scheduler.Task.run(Task.scala:131)
11:20:39  	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
11:20:39  	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
11:20:39  	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
11:20:39  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:20:39  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:20:39  	at java.base/java.lang.Thread.run(Thread.java:829)
11:20:39  
11:20:39  Driver stacktrace:
11:20:39    at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2403)
11:20:39    at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2352)
11:20:39    at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2351)
11:20:39    at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
11:20:39    at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
11:20:39    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
11:20:39    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2351)
11:20:39    at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1109)
11:20:39    at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1109)
11:20:39    at scala.Option.foreach(Option.scala:407)
11:20:39    ...
11:20:39    Cause: ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-166-cuda11/thirdparty/cudf/cpp/src/table/table.cpp:42: Column size mismatch: 4 != 2
11:20:39    at ai.rapids.cudf.Table.readParquet(Native Method)
11:20:39    at ai.rapids.cudf.Table.readParquet(Table.java:1019)
11:20:39    at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.$anonfun$readBufferToTable$1(GpuParquetScan.scala:1805)
11:20:39    at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
11:20:39    at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
11:20:39    at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:254)
11:20:39    at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.readBufferToTable(GpuParquetScan.scala:1804)
11:20:39    at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readToTable$1(GpuMultiFileReader.scala:814)
11:20:39    at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
11:20:39    at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
11:20:39    ...
```

**Steps/Code to reproduce bug**
`mvn clean test -Dbuildver=320 -DwildcardSuites=com.nvidia.spark.rapids.ParquetScanSuite`

**Comment by pxLi** [comment]
cc @res-life to help investigate

**Comment by res-life** [comment]
It's related to cuDF change, see comment:  https://github.com/rapidsai/cudf/pull/11252#issuecomment-1192428770

**Comment by nvdbaranec** [comment]
Bug identified. Fix being tested.

**Comment by nvdbaranec** [comment]
@res-life After looking at this a bit, there's something very odd with this file.  It appears to be partially malformed.  Basically:

- The pages for several non-nested columns say they contain 4 values, which corresponds to 4 rows.
- There is only 1 row group in the file containing 2 rows.   Because of this, there is no legitimate reason for any non-list pages to contain more than 2 values.

How was this file created?   @jlowe  says that Spark can't produce parquet files containing unsigned types.  Was this file created via the gpu writer in cudf by any chance?   I'd like to determine if this is something that can actually happen in the wild, or if we're just dealing with a singular bogus file.

**Comment by nvdbaranec** [comment]
Fixed with:
https://github.com/rapidsai/cudf/pull/11353
