### ISSUE TITLE
[BUG] AnsiCastOpSuite fail in spark331 shim

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#6165]
**Describe the bug**
AnsiCastOpSuite UT failed in spark331 shim (branch-22.10)

```
[31m- Write longs to int (values within range) *** FAILED ***[0m
[31m  java.lang.IllegalStateException: Expected 1 ansi_cast expressions, found 0[0m
[31m  at com.nvidia.spark.rapids.AnsiCastOpSuite.assertContainsAnsiCast(AnsiCastOpSuite.scala:837)[0m
[31m  at com.nvidia.spark.rapids.AnsiCastOpSuite.doTableInsert(AnsiCastOpSuite.scala:743)[0m
[31m  at com.nvidia.spark.rapids.AnsiCastOpSuite.$anonfun$new$136(AnsiCastOpSuite.scala:579)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect(SparkQueryCompareTestSuite.scala:495)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect$(SparkQueryCompareTestSuite.scala:491)[0m
[31m  at com.nvidia.spark.rapids.GpuExpressionTestSuite.collect(GpuExpressionTestSuite.scala:21)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.$anonfun$runOnCpuAndGpu$1(SparkQueryCompareTestSuite.scala:427)[0m
[31m  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:134)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession(SparkQueryCompareTestSuite.scala:195)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession$(SparkQueryCompareTestSuite.scala:190)[0m
[31m  ...[0m
[31m- Write longs to short (values within range) *** FAILED ***[0m
[31m  java.lang.IllegalStateException: Expected 1 ansi_cast expressions, found 0[0m
[31m  at com.nvidia.spark.rapids.AnsiCastOpSuite.assertContainsAnsiCast(AnsiCastOpSuite.scala:837)[0m
[31m  at com.nvidia.spark.rapids.AnsiCastOpSuite.doTableInsert(AnsiCastOpSuite.scala:743)[0m
[31m  at com.nvidia.spark.rapids.AnsiCastOpSuite.$anonfun$new$138(AnsiCastOpSuite.scala:584)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect(SparkQueryCompareTestSuite.scala:495)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect$(SparkQueryCompareTestSuite.scala:491)[0m
[31m  at com.nvidia.spark.rapids.GpuExpressionTestSuite.collect(GpuExpressionTestSuite.scala:21)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.$anonfun$runOnCpuAndGpu$1(SparkQueryCompareTestSuite.scala:427)[0m
[31m  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:134)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession(SparkQueryCompareTestSuite.scala:195)[0m
[31m  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession$(SparkQueryCompareTestSuite.scala:190)[0m
[31m  ...[0m
```

```
[31m- Detect overflow from int to byte *** FAILED ***[0m
[31m  AnsiCastOpSuite.this.exceptionContains(e, msg) was false "Column contains at least one value that is not in the required range" not in "Part of the plan is not columnar class org.apache.spark.sql.execution.ProjectExec[0m
[31m  Project [checkoverflowintableinsert(cast(c0#41800 as tinyint), a) AS a#41804][0m
[31m  +- Exchange SinglePartition, REPARTITION_BY_NUM, [plan_id=119874][0m
[31m     +- LocalTableScan [c0#41800][0m
[31m  " (AnsiCastOpSuite.scala:796)[0m
[31m- Detect overflow from short to byte *** FAILED ***[0m
[31m  AnsiCastOpSuite.this.exceptionContains(e, msg) was false "Column contains at least one value that is not in the required range" not in "Part of the plan is not columnar class org.apache.spark.sql.execution.ProjectExec[0m
[31m  Project [checkoverflowintableinsert(cast(c0#41805 as tinyint), a) AS a#41809][0m
[31m  +- Exchange SinglePartition, REPARTITION_BY_NUM, [plan_id=119947][0m
[31m     +- LocalTableScan [c0#41805][0m
[31m  " (AnsiCastOpSuite.scala:796)[0m
```

**Steps/Code to reproduce bug**
mvn clean package -Dbuildver=331  -DwildcardSuites=com.nvidia.spark.rapids.AnsiCastOpSuite

**Comment by tgravescs** [comment]
might be related to https://github.com/NVIDIA/spark-rapids/issues/6185

**Comment by pxLi** [comment]
hi, as this is block the nightly build and tests, are we OK to skip the test in 331 for now before we get the fix merged?

**Comment by tgravescs** [comment]
If @amahussein can't figure out root cause today, I would say yes we skip it.

**Comment by amahussein** [comment]
I won't be able to finish the fix today.

The cause:

- As mentioned in #6185 , Spark331 added a new unaryExpression `CheckOverflowInTableInsert`. This breaks the tests on both CPU and GPU:
- the new executed plan for insertion is now 
```
|-- a: integer (nullable = true)
), org.apache.spark.sql.execution.datasources.InMemoryFileIndex@c4cf8fe5, [a]
     +- *(1) Project [checkoverflowintableinsert(cast(c0#28L as int), a) AS a#32]
        +- Exchange SinglePartition, REPARTITION_BY_NUM, [plan_id=198]
           +- LocalTableScan [c0#28L]
```
Instead of 
```
 |-- a: integer (nullable = true)
), org.apache.spark.sql.execution.datasources.InMemoryFileIndex@abab41d5, [a]
      +- *(1) Project [ansi_cast(c0#4L as int) AS a#8]
         +- Exchange SinglePartition, REPARTITION_BY_NUM, [id=#22]
            +- LocalTableScan [c0#4L]
```
This breaks the test on both CPU and GPU

For CPU, counting cast needs to handle that the Alias may have `CheckOverflowInTableInsert` instead of `castBase`.
For GPU, the new expression is not handled.

**Comment by amahussein** [comment]
Posted a new PR  #6218
