### ISSUE TITLE
[BUG] Query failed with java.lang.NullPointerException when doing GpuSubqueryBroadcastExec

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6232]
One customer hit this issue that one query ailed with java.lang.NullPointerException when doing GpuSubqueryBroadcastExec.

**Env:**
Dataproc 2.0
Spark 3.1.3
rapids-4-spark_2.12-22.08.0-20220803.095308-37.jar

**Symptom**
There is no job/stage/task error in Spark eventlog.
The full stacktrace is from Spark driver log:
```
Caused by: java.lang.NullPointerException
	at ai.rapids.cudf.HostColumnVectorCore.getStartListOffset(HostColumnVectorCore.java:275)
	at ai.rapids.cudf.HostColumnVectorCore.getUTF8(HostColumnVectorCore.java:365)
	at com.nvidia.spark.rapids.RapidsHostColumnVectorCore.getUTF8String(RapidsHostColumnVectorCore.java:183)
	at org.apache.spark.sql.vectorized.ColumnarBatchRow.getUTF8String(ColumnarBatch.java:220)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$5(GpuSubqueryBroadcastExec.scala:199)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuilder$ofRef.$plus$plus$eq(ArrayBuilder.scala:109)
	at scala.collection.mutable.ArrayBuilder$ofRef.$plus$plus$eq(ArrayBuilder.scala:66)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$3(GpuSubqueryBroadcastExec.scala:197)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:55)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:53)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.withResource(GpuSubqueryBroadcastExec.scala:142)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$2(GpuSubqueryBroadcastExec.scala:196)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:139)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:137)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$1(GpuSubqueryBroadcastExec.scala:182)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by viadea** [comment]
I can repro locally with a minimum repro.
Env:
Spark 3.2.1 standalone cluster
Spark RAPIDS 22.06 GA jar
Apache Hive 3.1.2  `spark.sql.hive.metastore.version 3.1`


Reproduce steps:
```
create table debugdb.dim (
`id` string)
PARTITIONED BY (                                   
  `dt` date,                            
  `hr` string,                          
  `mins` string)                         
Stored as parquet;
insert into debugdb.dim(id,dt,hr,mins) values ('somevalue', date('2022-01-01'), '11', '59');


CREATE TABLE debugdb.fact(
  `id` string)                     
PARTITIONED BY (                                   
  `dt` date,                                 
  `hr` string,                               
  `mins` string)                              
Stored as parquet;

insert into debugdb.fact(id,dt,hr,mins)
select 'somevalue', to_date('2022-01-01'), '11', '59' from tpcds.customer;

select count(*) as cnt
from debugdb.fact csd
left join (select *,
from_utc_timestamp(date_format(concat(string(dt),' ',hr,':',mins,':','00'),'yyyy-MM-dd HH:mm:ss.SSS'),'UTC') as ts
from debugdb.dim 
) tmp
on  csd.hr = tmp.hr
and csd.mins = tmp.mins
and csd.dt = tmp.dt
where unix_timestamp(tmp.ts) > unix_timestamp(CURRENT_TIMESTAMP) - 99999*3600 ;
```

Reproduced stacktrace:
```
Caused by: java.lang.NullPointerException
	at ai.rapids.cudf.HostColumnVectorCore.getStartListOffset(HostColumnVectorCore.java:275)
	at ai.rapids.cudf.HostColumnVectorCore.getUTF8(HostColumnVectorCore.java:365)
	at com.nvidia.spark.rapids.RapidsHostColumnVectorCore.getUTF8String(RapidsHostColumnVectorCore.java:183)
	at org.apache.spark.sql.vectorized.ColumnarBatchRow.getUTF8String(ColumnarBatch.java:220)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$5(GpuSubqueryBroadcastExec.scala:199)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuilder$ofRef.$plus$plus$eq(ArrayBuilder.scala:109)
	at scala.collection.mutable.ArrayBuilder$ofRef.$plus$plus$eq(ArrayBuilder.scala:66)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$3(GpuSubqueryBroadcastExec.scala:197)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:55)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:53)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.withResource(GpuSubqueryBroadcastExec.scala:142)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$2(GpuSubqueryBroadcastExec.scala:196)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:139)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:137)
	at org.apache.spark.sql.rapids.execution.GpuSubqueryBroadcastExec.$anonfun$relationFuture$1(GpuSubqueryBroadcastExec.scala:182)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

Note: This is a typical DPP feature. 
If I disable DPP, the GPU run works fine: ` set spark.sql.optimizer.dynamicPartitionPruning.enabled=false;`
