### ISSUE TITLE
[BUG] Reading the iceberg metadata failed with java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6269]
Reading the iceberg metadata failed with java.lang.ArrayIndexOutOfBoundsException.
Such as
```
spark-shell --packages org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.13.0 \
    --conf spark.sql.session.timeZone=UTC \
    --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
    --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
    --conf spark.sql.catalog.spark_catalog.type=hive

spark.sql("""CREATE TABLE spark_catalog.default.demo2 (id bigint, data string) USING iceberg;""")
spark.sql("""INSERT INTO spark_catalog.default.demo2 VALUES (1, 'a'), (2, 'b'), (3, 'c');""")

spark.read.format("iceberg").load("spark_catalog.default.demo2.files").count
```

Stacktrace:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
  at com.nvidia.spark.rapids.GpuRowToColumnConverter.$anonfun$convert$1(GpuRowToColumnarExec.scala:48)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
  at com.nvidia.spark.rapids.GpuRowToColumnConverter.convert(GpuRowToColumnarExec.scala:47)
  at com.nvidia.spark.rapids.RowToColumnarIterator.$anonfun$buildBatch$1(GpuRowToColumnarExec.scala:639)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.RowToColumnarIterator.withResource(GpuRowToColumnarExec.scala:588)
  at com.nvidia.spark.rapids.RowToColumnarIterator.buildBatch(GpuRowToColumnarExec.scala:615)
  at com.nvidia.spark.rapids.RowToColumnarIterator.next(GpuRowToColumnarExec.scala:611)
  at com.nvidia.spark.rapids.RowToColumnarIterator.next(GpuRowToColumnarExec.scala:588)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:283)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:238)
  at scala.Option.getOrElse(Option.scala:189)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.aggregateInputBatches(aggregate.scala:283)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$next$2(aggregate.scala:238)
  at scala.Option.getOrElse(Option.scala:189)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:235)
  at com.nvidia.spark.rapids.GpuHashAggregateIterator.next(aggregate.scala:181)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:241)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
  at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
  at org.apache.spark.scheduler.Task.run(Task.scala:131)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:750)
```

**Comment by viadea** [comment]
User's env is 
```
Spark 3.1.3 on Dataproc 2.0
iceberg-spark-runtime-3.1_2.12:0.13.1
```

**Comment by viadea** [comment]
Also tried below but could not workaround the issue
```
spark.conf.set("spark.rapids.sql.format.iceberg.enabled",false)
```

**Comment by jlowe** [comment]
> Also tried below but could not workaround the issue

This is not surprising, since the original plan is _not_ accelerating the Iceberg read on the GPU because it's a metadata read, not a normal data read.  Those types of reads are already not on the GPU, so setting configs to ensure the reads aren't on the GPU won't have any effect in this case.

The problem that's occurring is that Iceberg is returning a custom InternalRow object, StructInternalRow, that despite the plan schema stating it needs zero columns from the row, the row has many fields advertised.  In our tow-to-column code, it makes the assumption that the number of fields in a row matches the number of fields in the expected schema.  This custom row object violates that assumption and thus we get the index error.  I think the fix is to not assume the row object will have the same number of fields as the schema and instead always go off of what is expected in the read schema.
