### ISSUE TITLE
[SPARK-40121][PYTHON][SQL] Initialize projection used for Python UDF

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6382]
#### Context

- Spark 3.4: https://github.com/apache/spark/commit/336c9bc535
- Spark 3.3: https://github.com/apache/spark/commit/1a01a492c0

#### What changes were proposed in SPARK pull request?

proposes to initialize the projection so non-deterministic expressions can be evaluated with Python UDFs.

#### Why are the changes needed in Spark?

To make the Python UDF working with non-deterministic expressions.

#### Does this PR introduce _any_ user-facing change?

Yes.

  ```python
    from pyspark.sql.functions import udf, rand
    spark.range(10).select(udf(lambda x: x, "double")(rand())).show()
  ```

- Before
  ```
    java.lang.NullPointerException
    	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificMutableProjection.apply(Unknown Source)
    	at org.apache.spark.sql.execution.python.EvalPythonExec.$anonfun$doExecute$10(EvalPythonExec.scala:126)
    	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
    	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
    	at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:1161)
    	at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:1176)
    	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1213)
  ```

- After
  ```
    +----------------------------------+
    |<lambda>rand(-2507211707257730645)|
    +----------------------------------+
    |                0.7691724424045242|
    |               0.09602244075319044|
    |                0.3006471278112862|
    |                0.4182649571961977|
    |               0.29349096650900974|
    |                0.7987097908937618|
    |                0.5324802583101007|
    |                  0.72460930912789|
    |                0.1367749768412846|
    |               0.17277322931919348|
    +----------------------------------+
  ```

#### Why it might affect RAPIDS?

- Not significant impact.
- Plugin code could use that in code generations and udf tests.

#### Impact on Testing?

Yes

#### Requires Doc update?

No

**Comment by firestarman** [comment]
Tried the rand case with Pandas UDF which being supported by GPU, and it passed.
```
>>> my_udf = f.pandas_udf(add, returnType=DoubleType())
>>> 
>>> spark.range(10).select(my_udf(f.col('id'), f.rand())).show()
22/09/08 09:11:37 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> cast(add(id, rand(-1490390190885198594))#36 as string) AS add(id, rand(-1490390190885198594))#39 will run on GPU
    *Expression <Cast> cast(add(id, rand(-1490390190885198594))#36 as string) will run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> pythonUDF0#41 AS add(id, rand(-1490390190885198594))#36 will run on GPU
    *Exec <ArrowEvalPythonExec> will partially run on GPU
      *Expression <PythonUDF> add(id#33L, rand(-1490390190885198594))#35 will not block GPU acceleration
        *Expression <Rand> rand(-1490390190885198594) will run on GPU
      *Exec <RangeExec> will run on GPU

+-----------------------------------+
|add(id, rand(-1490390190885198594))|
+-----------------------------------+
|                        0.123114498|
|                         0.36419828|
|                        0.229748776|
|                         0.05551394|
|                        0.538371122|
|                        0.202647857|
|                        0.712122482|
|                        0.354099933|
|                        0.670545569|
|                        0.759819223|
+-----------------------------------+
```
