### ISSUE TITLE
[BUG] DMLC XGBoost train FAILED against rapids-4-spark 22.10.0-SNAPSHOT FAILED

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#6404]
**Describe the bug**
DMLC XGBoost train FAILED againt rapids-4-spark 22.10.0-SNAPSHOT FAILED with below error,

It PASS before commit `f2b6bd0f3724256831ace0041a64886824686553`, and failed after `49e0a85e930ec98635269a703069f631f6f7b419`

![image](https://user-images.githubusercontent.com/50287591/186374443-d446b73d-cae4-4caa-a168-aa87a32dace2.png)

`PASS` : [2022-08-17T06:59:23.132Z] 22/08/17 06:58:31 INFO RapidsPluginUtils: RAPIDS Accelerator build: {version=22.10.0-SNAPSHOT, user=, url=https://github.com/NVIDIA/spark-rapids.git, date=2022-08-16T17:31:42Z, revision=f2b6bd0f3724256831ace0041a64886824686553, cudf_version=22.10.0-SNAPSHOT, branch=HEAD}

`FAILED`:  [2022-08-18T06:42:32.397Z] 22/08/18 06:41:50 INFO RapidsPluginUtils: RAPIDS Accelerator build: {version=22.10.0-SNAPSHOT, user=, url=https://github.com/NVIDIA/spark-rapids.git, date=2022-08-17T16:31:58Z, revision=49e0a85e930ec98635269a703069f631f6f7b419, cudf_version=22.10.0-SNAPSHOT, branch=HEAD} (edited)

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 6) (10.233.85.56 executor 0): java.lang.NoClassDefFoundError: com/nvidia/spark/rapids/GpuColumnVector
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$$anon$1.$anonfun$loadNextBatch$2(GpuPreXGBoost.scala:334)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.withResource(GpuPreXGBoost.scala:596)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$$anon$1.loadNextBatch(GpuPreXGBoost.scala:319)
	at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$$anon$1.hasNext(GpuPreXGBoost.scala:357)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at org.apache.spark.sql.execution.columnar.DefaultCachedBatchSerializer$$anon$1.hasNext(InMemoryRelation.scala:118)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.sql.execution.SQLExecutionRDD.compute(SQLExecutionRDD.scala:55)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2258)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2207)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2206)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2206)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1079)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1079)
  at scala.Option.foreach(Option.scala:407)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1079)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2445)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2196)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2217)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2236)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2261)
  at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
  at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
  at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:2906)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:3676)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3674)
  at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:2906)
  at $anonfun$prediction$1(<console>:39)
  at Benchmark$.time(<console>:31)
  ... 37 elided
Caused by: java.lang.NoClassDefFoundError: com/nvidia/spark/rapids/GpuColumnVector
  at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$$anon$1.$anonfun$loadNextBatch$2(GpuPreXGBoost.scala:334)
  at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$.withResource(GpuPreXGBoost.scala:596)
  at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$$anon$1.loadNextBatch(GpuPreXGBoost.scala:319)
  at ml.dmlc.xgboost4j.scala.rapids.spark.GpuPreXGBoost$$anon$1.hasNext(GpuPreXGBoost.scala:357)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
  at org.apache.spark.sql.execution.columnar.DefaultCachedBatchSerializer$$anon$1.hasNext(InMemoryRelation.scala:118)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
  at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
  at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
  at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
  at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
  at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
  at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
  at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.sql.execution.SQLExecutionRDD.compute(SQLExecutionRDD.scala:55)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
  at org.apache.spark.scheduler.Task.run(Task.scala:131)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  ... 1 more

org.apache.spark.SparkException:  Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 6) (10.233.85.56 executor 0): java.lang.NoClassDefFoundError: com/nvidia/spark/rapids/GpuColumnVector
```

**Comment by NvTimLiu** [comment]
@gerashegalov Looks like it related to PR https://github.com/NVIDIA/spark-rapids/pull/5646

Could you please help to take a look?Thanks!

**Comment by gerashegalov** [comment]
Thanks for reporting the issue, @NvTimLiu. Please make sure to include steps to reproduce the failure.

**Comment by NvTimLiu** [comment]
please refer  https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.08/docs/get-started/xgboost-examples/notebook/toree.md to repro this issue

**Comment by NvTimLiu** [comment]
@gerashegalov 
Sorry, I did not catch it. Could you please help to explain how branch-22.10 removed GpuColumnVector's scala access  from `rapids-4-spark`, then aggregator jar restore it by transitive dependency?

Additional context
https://github.com/NVIDIA/spark-rapids/issues/6404 : xgboost4j-spark-gpu should fail to compile when the rapids-4-spark dependency is updated from 21.08 to 22.10.0-SNAPSHOT because GpuColumnVector is no longer accessible to scalac. Yet it worked because it was transitively including the aggregator jar.

**Comment by NvTimLiu** [comment]
@wbo4958  please take a look at DMLC XGboost build part, thanks

**Comment by wbo4958** [comment]
XGBoost explicitly depends on spark-rapids 21.08 and it calls some APIs of GpuColumnVector

**Comment by wbo4958** [comment]
so it seems we need to bring the access of GpuColumnVector back to be back-compatible?

**Comment by gerashegalov** [comment]
> XGBoost explicitly depends on spark-rapids 21.08 and it calls some APIs of GpuColumnVector

@wbo4958 How is explicit dependency 21.08 supposed to work when we then use rapids-4-spark later versions at run time? 
- We no longer support Spark 3.0.1 in rapids-4-spark 22.04 although it's used as a dependency https://github.com/dmlc/xgboost/blob/d6e2013c5f3df0fff702cf3bfbdbdbc911e566dc/jvm-packages/pom.xml#L37
- Source code relying on Spark are generally not binary-compatible,  it is to a certain extent source-compatible between versions https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/dev/shims.md

**Comment by gerashegalov** [comment]
> @gerashegalov Sorry, I did not catch it. Could you please help to explain how branch-22.10 removed GpuColumnVector's scala access from `rapids-4-spark`, then aggregator jar restore it by transitive dependency?

@NvTimLiu Take a look at https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/dev/shims.md

Our final (dist module) artifact's content is split in multiple areas. 

1/ 
Public classes with stable ABI that do not depend on supported Spark versions. It's placed at conventional locations at the top of the jar. These classes can loaded with any classloader. 
```bash
$ jar tvf dist/target/rapids-4-spark_2.12-22.10.0-SNAPSHOT-cuda11.jar | grep SQLPlugin
  4601 Mon Aug 29 14:39:26 PDT 2022 com/nvidia/spark/SQLPlugin.class
```

2/ 
And we have classes that we load only after figuring out the Spark version at run time. They are so-called "parallel worlds" that are not visible to a conventional classloader. It includes classes whose bytecode definitely differs across versions 
```bash
 $ jar tvf dist/target/rapids-4-spark_2.12-22.10.0-SNAPSHOT-cuda11.jar | grep 'spark320/com/nvidia' | grep '.class' | head -1
 12634 Mon Aug 29 14:39:00 PDT 2022 spark320/com/nvidia/spark/rapids/GpuUnaryExpression.class
```

3/
And classes that produce the same bytecode under all supported Spark versions under spark3xx-common.  They may be identical for all versions but may reference another class e.g. via method signature that is in a version-specific parallel world.

We try to keep 1/ small and GpuColumnVector is in 3/ under spark3xx-common. It now contains some code that is [version specific](https://github.com/NVIDIA/spark-rapids/blob/8a93d8a8ea2efe9a82e9d9ae967fb77664d9dde2/sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java#L467) and probably is not fully unshimmable to 1/
But we can see what we can do @wbo4958 regarding https://github.com/NVIDIA/spark-rapids/issues/6404#issuecomment-1229982315


In our build, the aggregator jars and all its dependencies are jars in a normal layout accessible to regular classloaders including compilers. So if by accident it gets onto the classpath because we end up using the full original pom before it has been reduced of its dependencies after `mvn install`, the XGBoost compilation succeeds since the compiler is still able to load GpuColumnVector from aggregator.

**Comment by NvTimLiu** [comment]
> > @gerashegalov Sorry, I did not catch it. Could you please help to explain how branch-22.10 removed GpuColumnVector's scala access from `rapids-4-spark`, then aggregator jar restore it by transitive dependency?
> 
> @NvTimLiu Take a look at https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/dev/shims.md
> 
> Our final (dist module) artifact's content is split in multiple areas.
> 
> 1/ Public classes with stable ABI that do not depend on supported Spark versions. It's placed at conventional locations at the top of the jar. These classes can loaded with any classloader.
> 
> ```shell
> $ jar tvf dist/target/rapids-4-spark_2.12-22.10.0-SNAPSHOT-cuda11.jar | grep SQLPlugin
>   4601 Mon Aug 29 14:39:26 PDT 2022 com/nvidia/spark/SQLPlugin.class
> ```
> 
> 2/ And we have classes that we load only after figuring out the Spark version at run time. They are so-called "parallel worlds" that are not visible to a conventional classloader. It includes classes whose bytecode definitely differs across versions
> 
> ```shell
>  $ jar tvf dist/target/rapids-4-spark_2.12-22.10.0-SNAPSHOT-cuda11.jar | grep 'spark320/com/nvidia' | grep '.class' | head -1
>  12634 Mon Aug 29 14:39:00 PDT 2022 spark320/com/nvidia/spark/rapids/GpuUnaryExpression.class
> ```
> 
> 3/ And classes that produce the same bytecode under all supported Spark versions under spark3xx-common. They may be identical for all versions but may reference another class e.g. via method signature that is in a version-specific parallel world.
> 
> We try to keep 1/ small and GpuColumnVector is in 3/ under spark3xx-common. It now contains some code that is [version specific](https://github.com/NVIDIA/spark-rapids/blob/8a93d8a8ea2efe9a82e9d9ae967fb77664d9dde2/sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java#L467) and probably is not fully unshimmable to 1/ But we can see what we can do @wbo4958 regarding [#6404 (comment)](https://github.com/NVIDIA/spark-rapids/issues/6404#issuecomment-1229982315)
> 
> In our build, the aggregator jars and all its dependencies are jars in a normal layout accessible to regular classloaders including compilers. So if by accident it gets onto the classpath because we end up using the full original pom before it has been reduced of its dependencies after `mvn install`, the XGBoost compilation succeeds since the compiler is still able to load GpuColumnVector from aggregator.


@gerashegalov  That's make sense, thanks a lot for your detailed explanation!

**Comment by NvTimLiu** [comment]
> Analysis with the repro in this notebook:
> 
> https://github.com/gerashegalov/spark-rapids-examples/blob/rero6404/examples/XGBoost-Examples/taxi/notebooks/scala/taxi-gpu.ipynb
> 
> Interestingly that xgboost4j does not seem to support the deployment option using --jars or --packages independently of the RAPIDS plugin issue.

Do you mean --jars does not work for the notebook env? 
I copied the rapids-4-spark jars into the spark/jars dir, the same issue existed in notebook.

**Comment by gerashegalov** [comment]
> Do you mean --jars does not work for the notebook env ?

yes, --jars does not work for xgboost4j in the spylon kernel even with the old spark-rapids 21.08. See this paragraph in the notebook.
```Python
%%init_spark
import os

m2dir = os.path.expanduser('~/.m2/repository')

xgboost_v = '1.6.1'
spark_rapids_v = '21.08.0'
cudf_v = '21.08.2'

launcher.jars = [
    f"{m2dir}/ml/dmlc/xgboost4j-gpu_2.12/{xgboost_v}/xgboost4j-gpu_2.12-{xgboost_v}.jar",
    f"{m2dir}/ml/dmlc/xgboost4j-spark-gpu_2.12/{xgboost_v}/xgboost4j-spark-gpu_2.12-{xgboost_v}.jar",
    f"{m2dir}/com/nvidia/rapids-4-spark_2.12/{spark_rapids_v}/rapids-4-spark_2.12-{spark_rapids_v}.jar",
    f"{m2dir}/ai/rapids/cudf/{cudf_v}/cudf-{cudf_v}-cuda11.jar"
]
launcher.conf.spark.plugins = "com.nvidia.spark.SQLPlugin"
``` 

> I copied the rapids-4-spark jars into the spark/jars dir, the same issue existed in notebook.

Copying the jar to `$SPARK_ HOME/jars` is merely a workaround of the issue, not a feature. It is the same as using extraClassPath in this paragraph (but it  is discouraged and should not be necessary to use extraClassPath).

```Python
%%init_spark
import os

m2dir = os.path.expanduser('~/.m2/repository')

xgboost_v = '1.6.1'
spark_rapids_v = '21.08.0'
cudf_v = '21.08.2'

launcher.conf.spark.driver.extraClassPath = [
    f"{m2dir}/ml/dmlc/xgboost4j-gpu_2.12/{xgboost_v}/xgboost4j-gpu_2.12-{xgboost_v}.jar",
    f"{m2dir}/ml/dmlc/xgboost4j-spark-gpu_2.12/{xgboost_v}/xgboost4j-spark-gpu_2.12-{xgboost_v}.jar",
    f"{m2dir}/com/nvidia/rapids-4-spark_2.12/{spark_rapids_v}/rapids-4-spark_2.12-{spark_rapids_v}.jar",
    f"{m2dir}/ai/rapids/cudf/{cudf_v}/cudf-{cudf_v}-cuda11.jar"
]
launcher.conf.spark.plugins = "com.nvidia.spark.SQLPlugin"
```
