### ISSUE TITLE
[BUG] window function of window function queries fail on Databricks 10.4

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#6531]
**Describe the bug**
When running specific window queries on Databricks environments, certain references to child expressions of the window function are actually not provided in the input window expressions when creating the GpuWindowExec. This is different from Apache Spark, as these references are usually provided. This causes the query to throw an exception in the Databricks environment.

This is because `GpuWindowExec.splitAndDedup` makes the following assumption which is not correct in Databricks:
```
This assumes that there is not a window function of another window function, like
`LAG(SUM(a), 2)` which appears to be something all distros split apart into separate
window operations, so we are good.
```

**Steps/Code to reproduce bug**
Python reproduce for Databricks 10.4

```python
from pyspark.sql.types import *

spark.conf.set("spark.rapids.sql.enabled", "true")
spark.conf.set("spark.sql.adaptive.enabled", "false")

data1 = [(1, 2), (2, 3), (3, 4)]
data2 = [(1, 3), (2, 4), (3, 5)]

schema1 = StructType()\
        .add("a_1", LongType())\
        .add("c", LongType())
    
schema2 = StructType()\
        .add("a_2", LongType())\
        .add("b", LongType())
    
spark.createDataFrame(spark.sparkContext.parallelize(data1), schema1).createOrReplaceTempView("agg")
spark.createDataFrame(spark.sparkContext.parallelize(data2), schema2).createOrReplaceTempView("part")

df = spark.sql("select b, sum(c) as sum_c, sum(c)/sum(sum(c)) over (partition by b) as r_c from agg, part where a_1 = a_2 group by b order by b, r_c")
df.collect()
```
Exception:

```
Py4JJavaError: An error occurred while calling o626.collectToPython.
: java.lang.RuntimeException: Couldn't find _w3#1123L in [b#1113L,sum_c#1116L,_gpu_w2#1143L]
	at scala.sys.package$.error(package.scala:30)
	at com.nvidia.spark.rapids.GpuBindReferences$$anonfun$1.applyOrElse(GpuBoundAttribute.scala:87)
	at com.nvidia.spark.rapids.GpuBindReferences$$anonfun$1.applyOrElse(GpuBoundAttribute.scala:81)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:228)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
	at com.nvidia.spark.rapids.GpuBindReferences$.transformNoRecursionOnReplacement(GpuBoundAttribute.scala:67)
	at com.nvidia.spark.rapids.GpuBindReferences$.$anonfun$transformNoRecursionOnReplacement$1(GpuBoundAttribute.scala:69)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1226)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1225)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.mapChildren(Expression.scala:607)
	at com.nvidia.spark.rapids.GpuBindReferences$.transformNoRecursionOnReplacement(GpuBoundAttribute.scala:69)
	at com.nvidia.spark.rapids.GpuBindReferences$.$anonfun$transformNoRecursionOnReplacement$1(GpuBoundAttribute.scala:69)
	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren(TreeNode.scala:1253)
	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren$(TreeNode.scala:1252)
	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.mapChildren(Expression.scala:699)
	at com.nvidia.spark.rapids.GpuBindReferences$.transformNoRecursionOnReplacement(GpuBoundAttribute.scala:69)
	at com.nvidia.spark.rapids.GpuBindReferences$.$anonfun$transformNoRecursionOnReplacement$1(GpuBoundAttribute.scala:69)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1226)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1225)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.mapChildren(Expression.scala:607)
	at com.nvidia.spark.rapids.GpuBindReferences$.transformNoRecursionOnReplacement(GpuBoundAttribute.scala:69)
	at com.nvidia.spark.rapids.GpuBindReferences$.bindRefInternal(GpuBoundAttribute.scala:93)
	at com.nvidia.spark.rapids.GpuBindReferences$.bindGpuReference(GpuBoundAttribute.scala:101)
	at com.nvidia.spark.rapids.GpuBindReferences$.$anonfun$bindGpuReferences$1(GpuBoundAttribute.scala:111)
	at scala.collection.immutable.List.map(List.scala:297)
	at com.nvidia.spark.rapids.GpuBindReferences$.bindGpuReferences(GpuBoundAttribute.scala:111)
	at com.nvidia.spark.rapids.GpuProjectExec.doExecuteColumnar(basicPhysicalOperators.scala:144)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:251)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:247)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.inputBatchRDD$lzycompute(GpuShuffleExchangeExecBase.scala:201)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.inputBatchRDD(GpuShuffleExchangeExecBase.scala:201)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.shuffleDependencyColumnar$lzycompute(GpuShuffleExchangeExecBase.scala:211)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.shuffleDependencyColumnar(GpuShuffleExchangeExecBase.scala:209)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.$anonfun$doExecuteColumnar$1(GpuShuffleExchangeExecBase.scala:235)
	at com.nvidia.spark.rapids.shims.Spark320PlusShims.attachTreeIfSupported(Spark320PlusShims.scala:291)
	at com.nvidia.spark.rapids.shims.Spark320PlusShims.attachTreeIfSupported$(Spark320PlusShims.scala:286)
	at com.nvidia.spark.rapids.shims.SparkShimImpl$.attachTreeIfSupported(SparkShims.scala:41)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.doExecuteColumnar(GpuShuffleExchangeExecBase.scala:232)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:251)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:247)
	at com.nvidia.spark.rapids.GpuShuffleCoalesceExec.doExecuteColumnar(GpuShuffleCoalesceExec.scala:66)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:251)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:247)
	at com.nvidia.spark.rapids.GpuSortExec.doExecuteColumnar(GpuSortExec.scala:128)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:251)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:247)
	at com.nvidia.spark.rapids.GpuColumnarToRowExec.doExecute(GpuColumnarToRowExec.scala:320)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:224)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:220)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:78)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:87)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)
	at org.apache.spark.sql.execution.ResultCacheManager.collectResult$1(ResultCacheManager.scala:575)
	at org.apache.spark.sql.execution.ResultCacheManager.computeResult(ResultCacheManager.scala:582)
	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:528)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:527)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:424)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:403)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:422)
	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3739)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3951)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:239)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:386)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:186)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:968)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:141)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:336)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3949)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3737)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by NVnavkumar** [comment]
Update:
The following SQL also fails on Databricks:
```
...
df = spark.sql("select b, sum(c) as sum_c, (b + c)/sum(sum(c)) over (partition by b) as r_c from agg, part where a_1 = a_2 group by b order by b, r_c")
df.collect()
```
