### ISSUE TITLE
[BUG] GpuKryoRegistrator fail on Rapids22.08

### ISSUE THREAD

**Issue by hailiang9615** [NVIDIA/spark-rapids#6533]
**Describe the bug**
When starting a SparkSQL window and formulating Kryo and GpuKryoRegistrator configuration items, has java.lang.NoClassDefFoundError appears on Rapids22.08: org/apache/spark/sql/rapids/execution/ SerializeConcatHostBuffersDeserializeBatch, but this problem did not occur in the previous version, Rapids22.06. Is this a problem with the configuration item settings or a bug in Rapids22.08?
**keyWord:**
Rapids22.08: SparkSQL has java.lang.NoClassDefFoundError: org/apache/spark/sql/rapids/execution/SerializeConcatHostBuffersDeserializeBatch issue using GpuKryoRegistrator.
**it reported:**

Caused by: java.lang.NoClassDefFoundError: org/apache/spark/sql/rapids/execution/SerializeConcatHostBuffersDeserializeBatch
        at com.nvidia.spark.rapids.GpuKryoRegistrator.registerClasses(GpuKryoRegistrator.scala:27)
        at org.apache.spark.serializer.KryoSerializer.$anonfun$newKryo$8(KryoSerializer.scala:170)
        at org.apache.spark.serializer.KryoSerializer.$anonfun$newKryo$8$adapted(KryoSerializer.scala:170)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.serializer.KryoSerializer.$anonfun$newKryo$5(KryoSerializer.scala:170)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:222)
        at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:161)
        at org.apache.spark.serializer.KryoSerializer$$anon$1.create(KryoSerializer.scala:102)
        at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.borrow(KryoPoolQueueImpl.java:48)
        at org.apache.spark.serializer.KryoSerializer$PoolWrapper.borrow(KryoSerializer.scala:109)
        at org.apache.spark.serializer.KryoSerializerInstance.borrowKryo(KryoSerializer.scala:336)
        at org.apache.spark.serializer.KryoSerializationStream.<init>(KryoSerializer.scala:256)
        at org.apache.spark.serializer.KryoSerializerInstance.serializeStream(KryoSerializer.scala:422)
        at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:317)
        at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:138)
        at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:91)
        at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:35)
        at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:77)
        at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1509)
        at org.apache.spark.scheduler.DAGScheduler.submitMissingTasks(DAGScheduler.scala:1388)
        at org.apache.spark.scheduler.DAGScheduler.submitStage(DAGScheduler.scala:1226)
        at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:1168)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2395)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
**Configuration items**
	./spark-sql --master spark://xxxx:7077 \
	--conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
	--conf spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistrator \

**Comment by tgravescs** [comment]
There are changes in 22.10 that fix this along with  https://github.com/NVIDIA/spark-rapids/issues/6442.

When you submit the application how are you specifying the rapids jar?  Is it in the spark jars directory or passing with --jars, --extraclasspath, or other?  If you can provide that information we can look if there is a workaround in 22.08.

**Comment by gerashegalov** [comment]
#6442 was about the issue introduced in the upcoming 22.10.0 release, which is fixed as @tgravescs points out. If the title is correct and 22.08 also had this issue, we should look more into this reproducer.

**Comment by sameerz** [comment]
Hi @hailiang9615, were you able to resolve this issue?  If not, can you please provide more information, as requested? 

> When you submit the application how are you specifying the rapids jar? Is it in the spark jars directory or passing with --jars, --extraclasspath, or other? If you can provide that information we can look if there is a workaround in 22.08.

**Comment by sameerz** [comment]
If you can provide more information about how to reproduce that would be helpful!  Closing for now until we get more feedback.  Please check 22.10 as well, which should be out by the end of October.
