### ISSUE TITLE
[BUG] UCX smoke tests can fail with OOM when initializing UCX

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6572]
There have been some intermittent failures when initializing UCX, most recently here: https://github.com/NVIDIA/spark-rapids/pull/6553#issuecomment-1251128025. 

```
[2022-09-19T07:13:29.517Z] 22/09/19 07:13:29 WARN TaskSetManager: Lost task 1.0 in stage 5.0 (TID 15) (10.233.91.25 executor 0): org.openucx.jucx.UcxException: No resources are available to initiate the operation
[2022-09-19T07:13:29.518Z]      at org.openucx.jucx.ucp.UcpWorker.createWorkerNative(Native Method)
[2022-09-19T07:13:29.518Z]      at org.openucx.jucx.ucp.UcpWorker.<init>(UcpWorker.java:45)
[2022-09-19T07:13:29.518Z]      at org.openucx.jucx.ucp.UcpContext.newWorker(UcpContext.java:59)
[2022-09-19T07:13:29.518Z]      at com.nvidia.spark.rapids.shuffle.ucx.UCX.init(UCX.scala:146)
```

After discussing with the UCX team, this is a known issue and is going to be fixed via: https://github.com/openucx/ucx/pull/8508. It seems that in some cases (as of late) we are getting VMs with too small `/dev/shm`.

For now, the workaround is to disable the `posix` transport, so that memory allocations fallback to the SystemV api (`shmget`), which looks to not be subject to the same limits.

**Comment by abellina** [comment]
I have tested this and it requires also an update to UCX 1.13.1, as I am getting segfaults with 1.12.1. It works with UCX 1.13.1 locally. 

My plan is to get a PR up with the change + move to UCX 1.13.1 for the build/smoke testing. I may need help on the databricks instance, I am not sure how that one is getting UCX at this rate.

**Comment by jlowe** [comment]
The test is being disabled in #6579 and needs to be re-enabled before this issue can be closed.

**Comment by abellina** [comment]
> I may need help on the databricks instance, I am not sure how that one is getting UCX at this rate.

Ok, looking back at the original report this didn't trigger in databricks at all, it is just our regular CI machine, so this change is unblocked. Thanks @GaryShen2008 for confirming.
