### ISSUE TITLE
[BUG] Delta Lake Deletes on Databricks broken with PERFILE parquet reader

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6592]
**Describe the bug**
I was testing on databricks 10.4 with delta tables using the PERFILE parquet reader and the deletes are erroring with:

```
Py4JJavaError: An error occurred while calling o349.sql.
: java.lang.IllegalStateException: File (s3a://XXX/YYYY) to be rewritten not found among candidate files:
s3a://XXX/YYYY/k1=false/part-00000-2374456e-e909-4f8d-9992-8b16f7f4b719.c000.snappy.parquet
```

It works fine with our multithreaded reader

**Comment by tgravescs** [comment]
Note this was using 22.10 snapshot jar rapids-4-spark_2.12-22.10.0-20220921.123827-31-cuda11.ja

**Comment by firestarman** [comment]
Hi Tom, can you share the repro steps ?

**Comment by firestarman** [comment]
I can also repro it when running `UPDATE` command and with even COALESCING and MULTITHREAD readers.
The error is just like
```
Py4JJavaError: An error occurred while calling o356.sql.
: java.lang.IllegalStateException: File (alluxio://ip:19998/xxxx/yyy/k1=false/part-00000-feb5071b-42c6-4a4b-9315-1117dea84412.c000.snappy.parquet) to be rewritten not found among candidate files:
s3a://xxxx/yyy/k1=false/part-00000-feb5071b-42c6-4a4b-9315-1117dea84412.c000.snappy.parquet
s3a://xxxx/yyy/k1=false/part-00000-21f3c931-533c-4a63-b3f1-c6a80f177878.c000.snappy.parquet
	at com.databricks.sql.transaction.tahoe.commands.DeltaCommand.$anonfun$getTouchedFile$1(DeltaCommand.scala:173)
	at scala.collection.immutable.Map$Map2.getOrElse(Map.scala:236)
	at com.databricks.sql.transaction.tahoe.commands.DeltaCommand.getTouchedFile(DeltaCommand.scala:172)
	at com.databricks.sql.transaction.tahoe.commands.DeltaCommand.getTouchedFile$(DeltaCommand.scala:166)
	at com.databricks.sql.transaction.tahoe.commands.UpdateCommandEdge.getTouchedFile(UpdateCommandEdge.scala:64)
	at com.databricks.sql.transaction.tahoe.commands.UpdateCommandEdge.$anonfun$performUpdate$7(UpdateCommandEdge.scala:194)
```

**Comment by tgravescs** [comment]
you are using alluvia there and I have a fix for that up as PR.  This issue is without alluvia, please don't use alluvia when trying to reproduce the issue

**Comment by firestarman** [comment]
I can repro it now. Here is the plan which is complaining of this error. 
```
22/09/26 02:19:17 WARN GpuOverrides: 
*Exec <HashAggregateExec> will run on GPU
  *Exec <ShuffleExchangeExec> will run on GPU
    *Partitioning <HashPartitioning> will run on GPU
    *Exec <HashAggregateExec> will run on GPU
      *Exec <ProjectExec> will run on GPU
        *Expression <Alias> input_file_name() AS input_file_name()#8385 will run on GPU
          *Expression <InputFileName> input_file_name() will run on GPU
        !Exec <FilterExec> cannot run on GPU because not all expressions can be replaced
          !Expression <ScalaUDF> UDF() cannot run on GPU because neither UDF implemented by class com.databricks.sql.transaction.tahoe.commands.DeleteCommandEdge$$Lambda$8354/1314591671 provides a GPU implementation, nor the conf `spark.rapids.sql.rowBasedUDF.enabled` is enabled
          *Exec <FilterExec> will run on GPU
            *Expression <And> (isnotnull(c1#8354) AND (c1#8354 = tom44)) will run on GPU
              *Expression <IsNotNull> isnotnull(c1#8354) will run on GPU
              *Expression <EqualTo> (c1#8354 = tom44) will run on GPU
            *Exec <FileSourceScanExec> will run on GPU
```
And the corresponding SQL is [here.](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala#L219)
But it can pass if having the upper `FilterExec ` run on GPU by setting `spark.rapids.sql.rowBasedUDF.enabled` to true.

Seems there are some incompatibilities about `input_file_name ` between the DB `FilterExec ` and GPU `FileSourceScanExec`.
