### ISSUE TITLE
[BUG] null pointer exception selecting single column from iceberg table

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6723]
**Describe the bug**
While I was investigating a test failure https://github.com/NVIDIA/spark-rapids/issues/6718. I did a select on iceberg table of just one column.  When I do this I get a null pointer exception:

`scala> spark.sql("select _c19 from ice11").show()
`
table was just created with spark.sql("CREATE TABLE ice11 USING ICEBERG AS SELECT * FROM ice")

I tried all the reader types, perfile, coalescing, and multithreaded and all failed.  If I select all columns then it works.

```
22/10/07 15:52:36 INFO DAGScheduler: Job 2 failed: show at <console>:23, took 0.033763 s
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2) (10.28.9.112 executor driver): java.lang.NullPointerE
xception
        at com.nvidia.spark.rapids.iceberg.parquet.GpuParquetReader$ReorderColumns.list(GpuParquetReader.java:314)
        at com.nvidia.spark.rapids.iceberg.parquet.GpuParquetReader$ReorderColumns.list(GpuParquetReader.java:284)
        at com.nvidia.spark.rapids.iceberg.parquet.TypeWithSchemaVisitor.visitThreeLevelList(TypeWithSchemaVisitor.java:158)
        at com.nvidia.spark.rapids.iceberg.parquet.TypeWithSchemaVisitor.visit(TypeWithSchemaVisitor.java:79)
        at com.nvidia.spark.rapids.iceberg.parquet.TypeWithSchemaVisitor.visitField(TypeWithSchemaVisitor.java:167)
        at com.nvidia.spark.rapids.iceberg.parquet.TypeWithSchemaVisitor.visitFields(TypeWithSchemaVisitor.java:181)
        at com.nvidia.spark.rapids.iceberg.parquet.TypeWithSchemaVisitor.visit(TypeWithSchemaVisitor.java:45)
        at com.nvidia.spark.rapids.iceberg.spark.source.GpuMultiFileBatchReader$MultiFileBatchReaderBase.filterParquetBlocks(GpuMultiFileBatchReader.java:282)
        at com.nvidia.spark.rapids.iceberg.spark.source.GpuMultiFileBatchReader$ParquetCoalescingBatchReader.lambda$createRapidsReader$1(GpuMultiFileBatchReader.java:367)
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at com.nvidia.spark.rapids.iceberg.spark.source.GpuMultiFileBatchReader$ParquetCoalescingBatchReader.createRapidsReader(GpuMultiFileBatchReader.java:366)
        at com.nvidia.spark.rapids.iceberg.spark.source.GpuMultiFileBatchReader$MultiFileBatchReaderBase.<init>(GpuMultiFileBatchReader.java:241)
        at com.nvidia.spark.rapids.iceberg.spark.source.GpuMultiFileBatchReader$ParquetCoalescingBatchReader.<init>(GpuMultiFileBatchReader.java:359)
        at com.nvidia.spark.rapids.iceberg.spark.source.GpuMultiFileBatchReader.ensureBatchReader(GpuMultiFileBatchReader.java:150)
        at com.nvidia.spark.rapids.iceberg.spark.source.GpuMultiFileBatchReader.next(GpuMultiFileBatchReader.java:117)
        at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
        at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:239)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by tgravescs** [comment]
also note disabling the plugin read of iceberg the select works fine.
