### ISSUE TITLE
[BUG] parquet_write_test is failing when reading on the CPU parquet that was written on the GPU

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6865]
I am getting some really weird failures in one of my PRs:

```
[2022-10-19T21:36:54.607Z] =========================== short test summary info ============================
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary]))]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Binary]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Array(Binary)]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Array(Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary])))]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary]))]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Binary]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Binary]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Array(Binary)]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Array(Array(Binary))]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Map(String(not_null),Binary)]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Array(Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary])))]]
[2022-10-19T21:36:54.607Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_round_trip[[Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary])]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary])]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Binary]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Array(Binary)]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Array(Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary])))]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Binary]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Array(Array(Binary))]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Map(String(not_null),Binary)]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Binary]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Array(Array(Binary))]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Map(String(not_null),Binary)]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_save_table[[Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary])]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_sql_save_table[[Array(Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Binary]))]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_empty_parquet_round_trip[[Binary]]
[2022-10-19T21:36:54.608Z] FAILED ../../src/main/python/parquet_write_test.py::test_write_empty_parquet_round_trip[[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Binary]]
```

It seems to be us reading code from the CPU that was previously written by the GPU (judging by the path for this parquet file and the assert code that is called.. `assert_gpu_and_cpu_writes_are_equal_collect`):

```
PARQUET_DATA/GPU/part-00000-e32cc610-d1d8-4821-8c15-fff270f6329d-c000.snappy.parquet
```

More info:

```
Caused by: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file file:.../PARQUET_DATA/GPU/part-00000-e32cc610-d1d8-4821-8c15-fff270f6329d-c000.snappy.parquet^[[0m
  at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:251)^[[0m
  at org.apache.parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:207)^[[0m
  at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:37)^[[0m
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)^[[0m
  at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:93)^[[0m
  at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:173)^[[0m
  ... 16 more^[[0m
Caused by: java.lang.ClassCastException: Expected instance of group converter but got "org.apache.spark.sql.execution.datasources.parquet.ParquetPrimitiveConverter"^[[0m
  at org.apache.parquet.io.api.Converter.asGroupConverter(Converter.java:34)^[[0m
  at org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:267)^[[0m
  at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:147)^[[0m
  at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:109)^[[0m
  at org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:165)^[[0m
  at org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:109)^[[0m
  at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:137)^[[0m
  at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:222)^[[0m
  ... 21 more^[[0m
```

**Comment by firestarman** [comment]
Getting the same error in my PR #6823

**Comment by ttnghia** [comment]
Can you try to reverse this and run integration tests:
 * https://github.com/rapidsai/cudf/pull/11539

**Comment by hyperbolic2346** [comment]
@rwlee is looking into this now. These integration tests passed before commit, so it is possibly a merge conflict.

**Comment by rwlee** [comment]
Untagging myself after looking into it. It's unrelated to https://github.com/rapidsai/cudf/pull/11539 -- reverted the changes and tested locally and ended up with the same errors. The commit that the revert conflicted with was all test changes and did not touch any of the core parquet code.

**Comment by abellina** [comment]
I am getting a different result than @rwlee. I am able to reproduce with https://github.com/rapidsai/cudf/pull/11539. When I revert that the failure goes away. I think the plugin needs to be changed to reflect the removal of `INT8` from cuDF.

**Comment by abellina** [comment]
Trying to change a few things in the plugin after talking to @revans2. If that works I'll PR it, but else I may need more help from cuDF if I am not able to get it to work.
