### ISSUE TITLE
[BUG] integration test fail in CDH env due us trying to change permissions on /tmp/hive

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6883]
**Describe the bug**
I was trying to run integration tests on a CDH cluster (which have a real hive deploy) but it failed due to https://github.com/NVIDIA/spark-rapids/pull/6726

```
2022-10-21 17:48:07 INFO     Creating directory /tmp/hive with permissions 0o777
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 267, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/cloudera/2212/integration_tests/src/main/python/spark_init_internal.py", line 100, in pytest_sessionstart
INTERNALERROR>     global_init()
INTERNALERROR>   File "/home/cloudera/2212/integration_tests/src/main/python/spark_init_internal.py", line 87, in global_init
INTERNALERROR>     create_tmp_hive()
INTERNALERROR>   File "/home/cloudera/2212/integration_tests/src/main/python/spark_init_internal.py", line 94, in create_tmp_hive
INTERNALERROR>     os.chmod(path, mode)
INTERNALERROR> PermissionError: [Errno 1] Operation not permitted: '/tmp/hive'
22/10/21 17:48:07 INFO util.ShutdownHookManager: Shutdown hook called

```

**Comment by tgravescs** [comment]
Note, I was manually running the tests in this case

**Comment by gerashegalov** [comment]
looks like we should catch an exception from this log it as a warning without allowing it to fail. 

@tgravescs Were you overriding this default https://github.com/NVIDIA/spark-rapids/blob/cad2a2690c2e7a00682a95ab5d1bd6e0e7b76d92/integration_tests/run_pyspark_from_build.sh#L232 ?

**Comment by tgravescs** [comment]
I wasn't using run_pyspark_from_build.sh, spark-submit with runtests.py... just because that is what we originally ran there.

**Comment by tgravescs** [comment]
going to close this for now since not using run script and our official tests change dto use run script. I'll reopen if it becomes issue again
