### ISSUE TITLE
[BUG] Parquet of a binary decimal is not supported

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#6915]
**Describe the bug**
In the parquet spec it is allowed to store a decimal value as a binary physical type.  We currently run into a number of errors when we try to read data in this type.

**Steps/Code to reproduce bug**
See https://github.com/NVIDIA/spark-rapids/pull/6914

The tests in particular are "binary Decimal" and "binary Decimal2" There are two tests because they each show a different error.

The first one throws an exception like.

```
 org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 15.0 failed 1 times, most recent failure: Lost task 0.0 in stage 15.0 (TID 15) (10.28.9.123 executor driver): org.apache.spark.sql.execution.QueryExecutionException: Parquet column cannot be converted in file .../BINARY_DEC_TEST.parquet. Column: int_test, Expected: decimal(9,2), Found: required binary int_test (DECIMAL(9,2))
	at com.nvidia.spark.rapids.GpuParquetFileFilterHandler.throwTypeIncompatibleError(GpuParquetScan.scala:883)
	at com.nvidia.spark.rapids.GpuParquetFileFilterHandler.$anonfun$filterBlocks$14(GpuParquetScan.scala:705)
	at com.nvidia.spark.rapids.GpuParquetFileFilterHandler.$anonfun$filterBlocks$14$adapted(GpuParquet
```

The second one gets all the way down to CUDF and throws an exception there.

```
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 17.0 failed 1 times, most recent failure: Lost task 0.0 in stage 17.0 (TID 17) (10.28.9.123 executor driver): ai.rapids.cudf.CudfException: cuDF failure at: .../cudf/cpp/src/io/parquet/reader_impl_helpers.cu:124: Invalid representation of decimal type
	at ai.rapids.cudf.Table.readParquet(Native Method)
	at ai.rapids.cudf.Table.readParquet(Table.java:1047)
	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.$anonfun$readBufferToTable$1(GpuParquetScan.scala:1668)
```

**Expected behavior**
The tests read the correct data like they do on the CPU.

I will file and link an issue against CUDF.

**Comment by revans2** [comment]
I filed https://github.com/rapidsai/cudf/issues/11993 in CUDF to help fix the CUDF side of this.
