### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: com.nvidia.spark.rapids.jni.ParquetFooter.readAndFilter

### ISSUE THREAD

**Issue by njalan** [NVIDIA/spark-rapids#6921]
I faced below errors when running spark etl jobs:
 
2022-10-26 20:59:58,820 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 50.0 (TID 417) (10.120.39.27 executor 0): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: com.nvidia.spark.rapids.jni.ParquetFooter.readAndFilter(JJJJ[Ljava/lang/String;[I[IIZ)J
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:467)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:278)
        at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.next(GpuMultiFileReader.scala:440)
        at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
        at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:442)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1(GpuExec.scala:193)
        at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1$adapted(GpuExec.scala:192)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.RebaseHelper$.withResource(RebaseHelper.scala:26)
        at com.nvidia.spark.rapids.CollectTimeIterator.hasNext(GpuExec.scala:192)
        at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:288)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at com.nvidia.spark.rapids.GpuHashAggregateIterator.$anonfun$hasNext$2(aggregate.scala:232)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at scala.Option.getOrElse(Option.scala:189)
        at com.nvidia.spark.rapids.GpuHashAggregateIterator.hasNext(aggregate.scala:232)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:312)
        at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:335)
        at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:179)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)

Spark is standalone cluster with one worker for testing. Spark version is spark3.2.2 and rapid  jars are rapids-4-spark_2.12-22.10.0.jar and cudf-22.10.0-cuda11.jar

**Comment by tgravescs** [comment]
Hello, 
It looks like its not finding the com.nvidia.spark.rapids.jni.ParquetFooter.readAndFilter function.
You should not  specify a separate cudf jar, the rapids-4-spark_2.12-22.10.0.jar contains the cudf jar and other jni functions it needs.  
Please remove that and try again and let us know if that works.

**Comment by njalan** [comment]
@tgravescs Thanks for your reply. it is working fine.  Actually performance is not hat good and I am running some lots of sql joining query by spark sql.

**Comment by tgravescs** [comment]
@njalan we would be happy to look at your results and configs to see if we can recommend something that may perform better.

If you can tell us a little about your setup and workload and what configs you have tried and what performance you are seeing vs the cpu that would help.  

  There is the qualification tool that is to help to see if your application is one that is a good fit for the GPU: https://nvidia.github.io/spark-rapids/docs/spark-qualification-tool.html

**Comment by njalan** [comment]
@tgravescs  
I put all the config on below link
 https://github.com/NVIDIA/spark-rapids/discussions/6942
kindly check it once you have time
