### ISSUE TITLE
[BUG] AQE on Databricks failed the query with error "UnsupportedOperationException: ColumnarToRow does not implement doExecuteBroadcast"

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#7037]
**Env:**
Databricks 10.4
Latest 22.12 snapshot jar 
(With AQE on, DPP does not matter here)

**Mini repro**
```
import org.apache.spark.sql.Row
import org.apache.spark.sql.types._
import spark.sqlContext.implicits._
import org.apache.spark.sql.functions._

val data = Seq(
    Row(Row("Adam ","","Green"),"1","M",1000),
    Row(Row("Bob ","Middle","Green"),"2","M",2000),
    Row(Row("Cathy ","","Green"),"3","F",3000)
)

val schema = (new StructType()
  .add("name",new StructType()
    .add("firstname",StringType)
    .add("middlename",StringType)
    .add("lastname",StringType)) 
  .add("id",StringType)
  .add("gender",StringType)
  .add("salary",IntegerType))

val df = spark.createDataFrame(spark.sparkContext.parallelize(data),schema)
val df2 = df.withColumn("dt",current_date().as("dt")).withColumn("ts",current_timestamp().as("ts"))

df2.printSchema
df2.write.format("parquet").mode("overwrite").save("/tmp/testparquet")
val newdf2 = spark.read.parquet("/tmp/testparquet")
newdf2.createOrReplaceTempView("df2")
```

Then run below SQL:
```
%sql
set spark.sql.adaptive.enabled=true;

Select *
from
(
   select distinct a.salary
   from df2 a inner join (select max(date(ts)) as state_start from df2) b
   on date(a.ts) > b.state_start - 2 
)
where salary in (
   select salary from (select a.salary
   from df2 a inner join (select max(date(ts)) as state_start from df2) b on date(a.ts) > b.state_start - 2
   limit 1
 )
)
```

Error:
```
com.databricks.backend.common.rpc.DatabricksExceptions$SQLExecutionException: java.lang.UnsupportedOperationException: ColumnarToRow does not implement doExecuteBroadcast
	at org.apache.spark.sql.errors.QueryExecutionErrors$.doExecuteBroadcastNotImplementedError(QueryExecutionErrors.scala:1903)
	at org.apache.spark.sql.execution.SparkPlan.doExecuteBroadcast(SparkPlan.scala:356)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:237)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
	at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:233)
	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.prepareBroadcast(BroadcastNestedLoopJoinExec.scala:444)
	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.codegenLeftExistence(BroadcastNestedLoopJoinExec.scala:522)
	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.doConsume(BroadcastNestedLoopJoinExec.scala:430)
	at org.apache.spark.sql.execution.CodegenSupport.consume(WholeStageCodegenExec.scala:197)
	at org.apache.spark.sql.execution.CodegenSupport.consume$(WholeStageCodegenExec.scala:152)
	at org.apache.spark.sql.execution.InputAdapter.consume(WholeStageCodegenExec.scala:499)
	at org.apache.spark.sql.execution.InputRDDCodegen.doProduce(WholeStageCodegenExec.scala:486)
	at org.apache.spark.sql.execution.InputRDDCodegen.doProduce$(WholeStageCodegenExec.scala:459)
	at org.apache.spark.sql.execution.InputAdapter.doProduce(WholeStageCodegenExec.scala:499)
	at org.apache.spark.sql.execution.CodegenSupport.$anonfun$produce$1(WholeStageCodegenExec.scala:98)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
	at org.apache.spark.sql.execution.CodegenSupport.produce(WholeStageCodegenExec.scala:93)
	at org.apache.spark.sql.execution.CodegenSupport.produce$(WholeStageCodegenExec.scala:93)
	at org.apache.spark.sql.execution.InputAdapter.produce(WholeStageCodegenExec.scala:499)
	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.doProduce(BroadcastNestedLoopJoinExec.scala:423)
	at org.apache.spark.sql.execution.CodegenSupport.$anonfun$produce$1(WholeStageCodegenExec.scala:98)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
```

Note: if we disable AQE, then this query works fine.

**Comment by viadea** [comment]
BTW, this issue does not happen on my on-prem cluster.

**Comment by NVnavkumar** [comment]
It looks like on Databricks, one of the inner joins actually becomes a left semi join when AQE is enabled on Databricks, therefore, this becomes a version of issue seen in #7030

**Comment by jlowe** [comment]
Inner join and left semi join should be equally supported wrt. being on the CPU vs. GPU, so I'm not following how changing the join type leads to the behavior reported in this issue. Is there a non-equality condition being added when the join transform takes place?

**Comment by NVnavkumar** [comment]
The issue is that BroadcastNestedLoopJoin falls back to the CPU because the date expressions are not AST (the expressions are also using date_sub and cast_as_date in this example as is the example in #7030, and the same not supported error messages are reported). On Apache Spark, this is fine since both joins are inner joins, and the plugin can convert these conditions to GpuFilter with no issues.  But for some reason, the plan from Databricks when AQE is enabled has one of these joins as a left semi join (which probably makes sense as an optimization). The issue that causes the exception thrown here though is because when the BNLJ falls back to CPU, both sides need to be converted to row. There is a complication here, one side of the join contains a `BroadcastQueryStage` which has a child that is a `ReusedExchange` and in this case it's reusing a `GpuBroadcastExchange` from earlier, which makes this side columnar.

That's why a ColumnarToRow is here complaining about not being able to do a broadcast since it was added to handle this and this side needs to be able to broadcast.

One option here is to convert this ColumnarToRow to GpuColumnarToRow and implement doExecuteBroadcast. 

The note here is that if  #7030 is implemented then this would be automatically handled by that (probably more optimally).

**Comment by NVnavkumar** [comment]
And I just realized why this optimization is happening. The query is using a `select distinct` and `inner join`, so that becomes somewhat effectively a `left semi join` in this case.

**Comment by jlowe** [comment]
> There is a complication here, one side of the join contains a BroadcastQueryStage which has a child that is a ReusedExchange and in this case it's reusing a GpuBroadcastExchange from earlier, which makes this side columnar.

We've hit something like this before in Apache Spark, and I thought this case should have been covered by our handling of the SubqueryBroadcastExec (see #4440).  Wondering if we need to set the AdaptiveSparkPlan to be columnar (if it's not already?), fetch the subquery result via GpuSubqueryBroadcast then GpuColumnarToRow from there to the rest of the plan.

**Comment by jlowe** [comment]
It would be interesting to see if we can replicate this on Apache Spark (e.g.: explicitly change the query to use a left semi join rather than an inner join), see if we can get it to reuse a GPU exchange on a portion of the plan that is on the CPU.  There's also tests in this area in dpp_test.py where we should be testing GPU broadcasts being read by plans on the CPU.

Bottom line is we should already be handling GPU exchange reuse by CPU plans on Apache Spark, so it would be good to study how that's working to provide insight into why it might not be working for the Databricks case and what it should be doing to fix it.

**Comment by NVnavkumar** [comment]
I have tried changing the `select distinct...inner join` to a `select ...left semi join`, and ran the test in Apache Spark, it works, and I get the following GPU plan  (output when setting `logTransformations` to true): 
```
GpuColumnarToRow false
+- GpuProject [salary#80]
   +- GpuRowToColumnar targetsize(104857600)
      +- BroadcastNestedLoopJoin BuildRight, LeftSemi, (cast(ts#82 as date) > date_sub(state_start#89, 2))
         :- GpuColumnarToRow false
         :  +- GpuBroadcastHashJoin [salary#80], [salary#109], LeftSemi, GpuBuildRight
         :     :- GpuCoalesceBatches targetsize(104857600)
         :     :  +- GpuFilter gpuisnotnull(ts#82), true
         :     :     +- GpuFileGpuScan parquet [salary#80,ts#82] Batched: true, DataFilters: [isnotnull(ts#82)], Format: Parquet, Location: InMemoryFileIndex[file:/tmp/pyspark_tests/7f588d3-lcedt-gw0-2580342-1512304418/PARQUET_DATA], PartitionFilters: [], PushedFilters: [IsNotNull(ts)], ReadSchema: struct<salary:int,ts:timestamp>
         :     +- BroadcastQueryStage 6
         :        +- GpuBroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, true] as bigint)),false), [id=#2039]
         :           +- GpuGlobalLimit 1, 0
         :              +- GpuShuffleCoalesce 104857600
         :                 +- ShuffleQueryStage 5
         :                    +- GpuColumnarExchange gpusinglepartitioning$(), ENSURE_REQUIREMENTS, [id=#1948]
         :                       +- GpuLocalLimit 1
         :                          +- GpuProject [salary#109]
         :                             +- GpuFilter (cast(ts#111 as date) > date_sub(state_start#90, 2)), false
         :                                +- GpuBroadcastNestedLoopJoin Inner, GpuBuildRight, 104857600
         :                                   :- GpuCoalesceBatches targetsize(104857600)
         :                                   :  +- GpuFilter gpuisnotnull(ts#111), true
         :                                   :     +- GpuFileGpuScan parquet [salary#109,ts#111] Batched: true, DataFilters: [isnotnull(ts#111)], Format: Parquet, Location: InMemoryFileIndex[file:/tmp/pyspark_tests/7f588d3-lcedt-gw0-2580342-1512304418/PARQUET_DATA], PartitionFilters: [], PushedFilters: [IsNotNull(ts)], ReadSchema: struct<salary:int,ts:timestamp>
         :                                   +- BroadcastQueryStage 3
         :                                      +- GpuBroadcastExchange IdentityBroadcastMode, [id=#1573]
         :                                         +- GpuCoalesceBatches targetsize(104857600)
         :                                            +- GpuFilter gpuisnotnull(state_start#90), true
         :                                               +- GpuHashAggregate(keys=[], functions=[gpubasicmax(cast(ts#104 as date))], output=[state_start#90])
         :                                                  +- GpuShuffleCoalesce 104857600
         :                                                     +- ShuffleQueryStage 0
         :                                                        +- GpuColumnarExchange gpusinglepartitioning$(), ENSURE_REQUIREMENTS, [id=#1354]
         :                                                           +- GpuHashAggregate(keys=[], functions=[partial_gpubasicmax(cast(ts#104 as date))], output=[max#114])
         :                                                              +- GpuFileGpuScan parquet [ts#104] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[file:/tmp/pyspark_tests/7f588d3-lcedt-gw0-2580342-1512304418/PARQUET_DATA], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<ts:timestamp>
         +- BroadcastQueryStage 4
            +- BroadcastExchange IdentityBroadcastMode, [id=#1622]
               +- GpuColumnarToRow false
                  +- GpuFilter gpuisnotnull(state_start#89), true
                     +- GpuHashAggregate(keys=[], functions=[gpubasicmax(cast(ts#97 as date))], output=[state_start#89])
                        +- GpuShuffleCoalesce 104857600
                           +- ShuffleQueryStage 2
                              +- ReusedExchange [max#116], GpuColumnarExchange gpusinglepartitioning$(), ENSURE_REQUIREMENTS, [id=#1354]```

**Comment by NVnavkumar** [comment]
Btw, when running the test in Databricks, it fails with some missing references (looks similar to the exception in the window issue here #6531) :

```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o531.collectToPython.
E                   : java.lang.RuntimeException: Couldn't find state_start#99 in [salary#90,ts#92]
E                   	at scala.sys.package$.error(package.scala:30)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$$anonfun$1.applyOrElse(GpuBoundAttribute.scala:87)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$$anonfun$1.applyOrElse(GpuBoundAttribute.scala:81)
E                   	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
E                   	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:228)
E                   	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$.transformNoRecursionOnReplacement(GpuBoundAttribute.scala:67)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$.$anonfun$transformNoRecursionOnReplacement$1(GpuBoundAttribute.scala:69)
E                   	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren(TreeNode.scala:1253)
E                   	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren$(TreeNode.scala:1252)
E                   	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.mapChildren(Expression.scala:699)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$.transformNoRecursionOnReplacement(GpuBoundAttribute.scala:69)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$.$anonfun$transformNoRecursionOnReplacement$1(GpuBoundAttribute.scala:69)
E                   	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren(TreeNode.scala:1255)
E                   	at org.apache.spark.sql.catalyst.trees.BinaryLike.mapChildren$(TreeNode.scala:1252)
E                   	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.mapChildren(Expression.scala:699)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$.transformNoRecursionOnReplacement(GpuBoundAttribute.scala:69)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$.bindRefInternal(GpuBoundAttribute.scala:93)
E                   	at com.nvidia.spark.rapids.GpuBindReferences$.bindReference(GpuBoundAttribute.scala:117)
E                   	at com.nvidia.spark.rapids.GpuFilterExec.doExecuteColumnar(basicPhysicalOperators.scala:454)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:251)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:247)
E                   	at com.nvidia.spark.rapids.GpuProjectExec.doExecuteColumnar(basicPhysicalOperators.scala:151)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:251)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:247)
E                   	at com.nvidia.spark.rapids.GpuColumnarToRowExec.doExecute(GpuColumnarToRowExec.scala:316)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:224)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:268)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:264)
E                   	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:220)
E                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:78)
E                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:87)
E                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)
E                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)
E                   	at org.apache.spark.sql.execution.ResultCacheManager.collectResult$1(ResultCacheManager.scala:575)
E                   	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$computeResult$1(ResultCacheManager.scala:580)
E                   	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:503)
E                   	at org.apache.spark.sql.execution.ResultCacheManager.computeResult(ResultCacheManager.scala:580)
E                   	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:528)
E                   	at scala.Option.getOrElse(Option.scala:189)
E                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:527)
E                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:424)
E                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:403)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:422)
E                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3739)
E                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3951)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:239)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:386)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:186)
E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:968)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:141)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:336)
E                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3949)
E                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3737)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
E                   	at py4j.Gateway.invoke(Gateway.java:295)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
E                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
E                   	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jlowe** [comment]
> ran the test in Apache Spark, it works, and I get the following GPU plan

Was this with AQE on?  I don't see evidence of AQE anywhere in the plan.  It looks like the plugin was able to plan the entire query at once and make sure the output of the broadcast feeding the BNLJ was already on the CPU when broadcasted.  We need AQE to "hide" parts of the plan so we don't know ahead of time whether the broadcast receiver will be on the GPU or not.

Also I don't see a reused exchange being fed into a CPU exec as was described earlier (it's going into a GPU aggregate instead), so maybe the tweak to the plan is making a significantly different plan that it was before?

**Comment by NVnavkumar** [comment]
Judging from this, it looks like Databricks is reusing the GpuBroadcastExchange, but Apache Spark is actually reusing the GpuColumnarExchange

**Comment by jlowe** [comment]
Hmm, looks like we need an explicit check in the transition overrides looking for:
   Non GPU exec --> BroadcastQueryStageExec --> ReusedExchangeExec --> GpuBroadcastExchange
and then fix it up by injecting a GpuSubqueryBroadcastExec to fetch the GPU broadcast results back to the CPU.  I _think_ the plan would work if there was a GpuSubqueryBroadcastExec between the BNLJ and the BroadcastQueryStage.

It looks like GpuSubqueryBroadcastExec is triggered off of SubqueryBroadcastExec, but I didn't see that in the CPU plan.  Maybe that's the difference that keeps this from working as intended on Databricks?
