### ISSUE TITLE
[BUG] Qualification tool skips applications due to failure in expression parsing

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#7044]
**Describe the bug**
When running Qualification tool on Spark2.x eventlogs, it was found that the Qualification tool skips the application analysis when expression parser triggers an exception.
This means that all applications with usupported format won't be processed by the tool which is inconvenient for users who are willing to migrate from Spark2.x to Spark3.x

**Expected behavior**
I suggest that parser skips the expression that triggers the exception, then continue processing the app normally after displaying a warning/error messages to the log file.

Although we cannot reproduce the same failure on our side, the Qualification tool should not skip the entire application due an error in one of the expressions because:
- It is expected that different spark releases might change the expression format in the log.
- It is possible that the parser does not fully cover the expression formats.

**Additional context**

the error below is due to a missing match-case for “||” in [SQLPlanParser-line-436](https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala#L436) ; but the parser checks for  “OR”.

```
22/11/09 17:16:39 WARN com.nvidia.spark.rapids.tool.qualification.Qualification: Unexpected exception processing log gs://gcp_bucket_path/logss/application_1667271647355_0001_1.lz4, skipping!
scala.MatchError: || (of class java.lang.String)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.$anonfun$parseFilterExpressions$7(SQLPlanParser.scala:436)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parseFilterExpressions(SQLPlanParser.scala:413)
	at com.nvidia.spark.rapids.tool.planparser.FilterExecParser.parse(FilterExecParser.scala:34)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parsePlanNode(SQLPlanParser.scala:140)
	at com.nvidia.spark.rapids.tool.planparser.WholeStageExecParser.$anonfun$parse$3(WholeStageExecParser.scala:43)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.nvidia.spark.rapids.tool.planparser.WholeStageExecParser.parse(WholeStageExecParser.scala:42)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parsePlanNode(SQLPlanParser.scala:103)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.$anonfun$parseSQLPlan$1(SQLPlanParser.scala:80)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parseSQLPlan(SQLPlanParser.scala:79)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.$anonfun$aggregateStats$6(QualificationAppInfo.scala:354)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.$anonfun$aggregateStats$1(QualificationAppInfo.scala:352)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.aggregateStats(QualificationAppInfo.scala:332)
	at com.nvidia.spark.rapids.tool.qualification.Qualification.com$nvidia$spark$rapids$tool$qualification$Qualification$$qualifyApp(Qualification.scala:126)
	at com.nvidia.spark.rapids.tool.qualification.Qualification$QualifyThread.run(Qualification.scala:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by amahussein** [comment]
The following evenlog generated by spark2.x looks different compared to spark3.x
At least I can see "||" in the spark2.x version.
```
$SPARK_HOME/bin/spark-shell \
       --conf spark.eventLog.enabled=true 
       
val dfTN = Seq(("Smith",45),("Andy",77)).toDF("Name","Marks");
dfTN.filter('Name ===  "Andy").show
dfTN.filter('Name === "Andy" || 'Marks > "50").show      
```

```
{"Event":"org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionStart","executionId":1,"description":"show at <console>:26","details":"org.apache.spark.sql.Dataset.show(Dataset.scala:719)\n$line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:26)\n$line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:30)\n$line16.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:32)\n$line16.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:34)\n$line16.$read$$iw$$iw$$iw$$iw.<init>(<console>:36)\n$line16.$read$$iw$$iw$$iw.<init>(<console>:38)\n$line16.$read$$iw$$iw.<init>(<console>:40)\n$line16.$read$$iw.<init>(<console>:42)\n$line16.$read.<init>(<console>:44)\n$line16.$read$.<init>(<console>:48)\n$line16.$read$.<clinit>(<console>)\n$line16.$eval$.$print$lzycompute(<console>:7)\n$line16.$eval$.$print(<console>:6)\n$line16.$eval.$print(<console>)\nsun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\nsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\nsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.lang.reflect.Method.invoke(Method.java:498)\nscala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)","physicalPlanDescription":"== Parsed Logical Plan ==\nGlobalLimit 21\n+- LocalLimit 21\n   +- Project [cast(Name#5 as string) AS Name#18, cast(Marks#6 as string) AS Marks#19]\n      +- Filter ((Name#5 = Andy) || (Marks#6 > cast(50 as int)))\n         +- Project [_1#2 AS Name#5, _2#3 AS Marks#6]\n            +- LocalRelation [_1#2, _2#3]\n\n== Analyzed Logical Plan ==\nName: string, Marks: string\nGlobalLimit 21\n+- LocalLimit 21\n   +- Project [cast(Name#5 as string) AS Name#18, cast(Marks#6 as string) AS Marks#19]\n      +- Filter ((Name#5 = Andy) || (Marks#6 > cast(50 as int)))\n         +- Project [_1#2 AS Name#5, _2#3 AS Marks#6]\n            +- LocalRelation [_1#2, _2#3]\n\n== Optimized Logical Plan ==\nLocalRelation [Name#18, Marks#19]\n\n== Physical Plan ==\nLocalTableScan [Name#18, Marks#19]","sparkPlanInfo":{"nodeName":"LocalTableScan","simpleString":"LocalTableScan [Name#18, Marks#19]","children":[],"metadata":{},"metrics":[{"name":"number of output rows","accumulatorId":1,"metricType":"sum"}]},"time":1668019769484}
{"Event":"org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionEnd","executionId":1,"time":1668019769493}
```
