### ISSUE TITLE
[BUG] Some tests in the `AdaptiveQueryExecSuite` fail on Spark 340

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7054]
**Describe the bug**
```scala
- Plugin should translate child plan of GPU DataWritingCommandExec to GPU *** FAILED ***
  java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:529)
  at scala.None$.get(Option.scala:527)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.$anonfun$new$20(AdaptiveQueryExecSuite.scala:259)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:134)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:189)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession$(SparkQueryCompareTestSuite.scala:184)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.withGpuSparkSession(AdaptiveQueryExecSuite.scala:37)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.$anonfun$new$19(AdaptiveQueryExecSuite.scala:264)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  ...
- Plugin should translate child plan of CPU DataWritingCommandExec to GPU *** FAILED ***
  java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:529)
  at scala.None$.get(Option.scala:527)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.$anonfun$new$25(AdaptiveQueryExecSuite.scala:302)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:134)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:189)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession$(SparkQueryCompareTestSuite.scala:184)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.withGpuSparkSession(AdaptiveQueryExecSuite.scala:37)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.$anonfun$new$24(AdaptiveQueryExecSuite.scala:309)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  ...
- Avoid transitions to row when writing to Parquet *** FAILED ***
  java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:529)
  at scala.None$.get(Option.scala:527)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.$anonfun$new$31(AdaptiveQueryExecSuite.scala:348)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:134)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:189)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession$(SparkQueryCompareTestSuite.scala:184)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.withGpuSparkSession(AdaptiveQueryExecSuite.scala:37)
  at com.nvidia.spark.rapids.AdaptiveQueryExecSuite.$anonfun$new$29(AdaptiveQueryExecSuite.scala:366)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
```
mvn clean package -DwildcardSuites=com.nvidia.spark.rapids.AdaptiveQueryExecSuite -Dbuildver=340 -Dsurefire.useFile=false
```

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by HaoYang670** [comment]
cc @andygrove , could you please take a look?

**Comment by andygrove** [comment]
I looked at the failures and see that these plans are different in Spark 3.4.0.

## Spark 3.2.1

```
CommandResult <empty>
   +- GpuColumnarToRow false
      +- Execute GpuInsertIntoHadoopFsRelationCommand ...
         +- AdaptiveSparkPlan isFinalPlan=true
            +- == Final Plan ==
               GpuFileGpuScan parquet ...
            +- == Initial Plan ==
               FileScan parquet ...
```

## Spark 3.4.0

```
CommandResult <empty>
   +- AdaptiveSparkPlan isFinalPlan=true
      +- == Final Plan ==
         GpuColumnarToRow false
         +- Execute GpuInsertIntoHadoopFsRelationCommand ...
            +- GpuFileGpuScan parquet ...
      +- == Initial Plan ==
         Execute InsertIntoHadoopFsRelationCommand ...
         +- FileScan parquet ...
```

I will create a PR to update the tests to support this.
