### ISSUE TITLE
[BUG]  JUnit and ScalaTest not runnable on Databricks instances

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#7098]
**Describe the bug**
Running JUnit, ScalaTest on Databricks throws CNF, probably missing a bunch of `install-file` in `jenkins/databricks/build.sh`:
```
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Filter
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.getConstructor(Class.java:1825)
        at org.apache.maven.surefire.junit.PojoAndJUnit3Checker.isPojoTest(PojoAndJUnit3Checker.java:51)
        at org.apache.maven.surefire.junit.PojoAndJUnit3Checker.accept(PojoAndJUnit3Checker.java:43)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:97)
        at org.apache.maven.surefire.junit.JUnit3Provider.scanClassPath(JUnit3Provider.java:128)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:79)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.Filter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 18 more
```

**Steps/Code to reproduce bug**
```
SPARK_BASE_VERSION=3.X.Y ./jenkins/databricks/build.sh
mvn install -pl tests -am -DskipTests -Dskip -Dmaven.javadoc.skip -Dmaven.scalastyle.skip -Ddatabricks -Dbuildver=3XYdb
mvn test -pl tests -Ddatabricks  -Dbuildver=3XYdb
```

**Expected behavior**
We should be able to verify Databricks Shims using Java/Scala Unit Tests 

**Environment details (please complete the following information)**
 - Environment location: Databricks

**Additional context**
N/A

**Comment by tgravescs** [comment]
Note the unit tests have never run on Databricks.

**Comment by tgravescs** [comment]
https://github.com/NVIDIA/spark-rapids/issues/1320

**Comment by gerashegalov** [comment]
closing, since as it's a duplicate of #1320
