### ISSUE TITLE
[BUG] GpuBroadcastHashJoinExec ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#718]
**Describe the bug**

When performing a join of two tables created with a `PARTITIONED BY` clause using the following code, a GPU projection fails with `ArrayIndexOutOfBoundsException` due to receiving a broadcast batch with zero columns. The same code works fine on CPU, indicating that there is a bug in the plugin.

The query works if the `PARTITIONED BY` clause is removed from the `CREATE TABLE` statement for t1.

The failure happens with AQE on or off.

**Steps/Code to reproduce bug**

Run the following unit test.

```scala
test("Join partitioned tables") {

  withGpuSparkSession(spark => {
    import spark.implicits._

    val path = new File(TEST_FILES_ROOT, "test.parquet").getAbsolutePath
    (0 until 100)
        .map(i => (i,i*5))
        .toDF("a", "b")
        .write
        .mode(SaveMode.Overwrite)
        .parquet(path)
    spark.read.parquet(path).createOrReplaceTempView("testData")

    spark.sql("DROP TABLE IF EXISTS t1").collect()
    spark.sql("DROP TABLE IF EXISTS t2").collect()

    spark.sql("CREATE TABLE t1 (a INT, b INT) USING parquet PARTITIONED BY (a)").collect()
    spark.sql("CREATE TABLE t2 (a INT, b INT) USING parquet PARTITIONED BY (a)").collect()

    spark.sql("INSERT INTO TABLE t1 SELECT a, b FROM testData").collect()
    spark.sql("INSERT INTO TABLE t2 SELECT a, b FROM testData").collect()

    val df3 = spark.sql(
        "SELECT t1.a, t2.b " +
        "FROM t1 " +
        "JOIN t2 " +
        "ON t1.a = t2.a "
        )
    df3.collect()

  })
}

```

Stack trace:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.vectorized.ColumnarBatch.column(ColumnarBatch.java:102)
	at com.nvidia.spark.rapids.GpuBoundReference.columnarEval(GpuBoundAttribute.scala:95)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35)
	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:50)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:160)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:157)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:157)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:192)
	at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:49)
	at com.nvidia.spark.rapids.shims.spark301.GpuBroadcastHashJoinExec.builtTable$lzycompute$1(GpuBroadcastHashJoinExec.scala:147)
	at com.nvidia.spark.rapids.shims.spark301.GpuBroadcastHashJoinExec.builtTable$1(GpuBroadcastHashJoinExec.scala:145)
	at com.nvidia.spark.rapids.shims.spark301.GpuBroadcastHashJoinExec.$anonfun$doExecuteColumnar$5(GpuBroadcastHashJoinExec.scala:162)
```

**Expected behavior**
The code should work when on GPU. Changing `withGpuSparkSession` to `withCpuSparkSession` makes the test pass.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by jlowe** [comment]
@revans2  @sameerz this seems like it could be pretty serious.  From the exception it looks like we tried to address a column index off the end of a batch, implying we're mismatching inputs and outputs between operators in the query.

**Comment by revans2** [comment]
This looks like it is a bug in the parquet reader for partitioned data.

The plan asks to read only the column that the data is partitioned by (The following is the CPU version).
```
FileScan parquet default.t1[a#32] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[file:/tmp/spark-warehouse8378085594252186462/t1/a=235, file:/tmp/spark-warehous..., PartitionFilters: [isnotnull(a#32)], PushedFilters: [], ReadSchema: struct<>
```

The GPU version is the same.  I'll see what I can do to trace it down in the parquet reader, but I suspect it is the same for all of the readers that we have.

**Comment by revans2** [comment]
If I set

```
spark.conf.set("spark.rapids.sql.format.parquet.multiThreadedRead.enabled", "false")
```

The test now passes. So it appears to be related to the small file work done for parquet.

**Comment by revans2** [comment]
Big thanks to @tgravescs who pointed me at the right code.  I have a patch that works, but I need to clean it up and add in a test.  Should hopefully not be too long.
