### ISSUE TITLE
[BUG] Parquet unsigned int scan test failure

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7213]
Have seen the following failure in premerge and nightly builds of 23.02 where one of the tests in ParquetScanSuite fails:
```
[2022-11-30T17:37:00.861Z] [31m- Test Parquet nested unsigned int: uint8, uint16, uint32 *** FAILED ***[0m
[2022-11-30T17:37:00.861Z] [31m  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 251.0 failed 1 times, most recent failure: Lost task 0.0 in stage 251.0 (TID 1125) (nightly-work2-690-q0bgr-jdx4z executor driver): java.lang.IllegalArgumentException: Cannot grow BufferHolder by size -8 because the size is negative[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder.grow(BufferHolder.java:67)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeArrayWriter.initialize(UnsafeArrayWriter.java:61)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_3$(Unknown Source)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)[0m
[2022-11-30T17:37:00.861Z] [31m	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:365)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.scheduler.Task.run(Task.scala:136)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)[0m
[2022-11-30T17:37:00.861Z] [31m	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)[0m
[2022-11-30T17:37:00.861Z] [31m	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2022-11-30T17:37:00.861Z] [31m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[2022-11-30T17:37:00.861Z] [31m	at java.lang.Thread.run(Thread.java:750)[0m
[2022-11-30T17:37:00.861Z] [31m[0m
[2022-11-30T17:37:00.861Z] [31mDriver stacktrace:[0m
[2022-11-30T17:37:00.861Z] [31m  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)[0m
[2022-11-30T17:37:00.862Z] [31m  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)[0m
[2022-11-30T17:37:00.862Z] [31m  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)[0m
[2022-11-30T17:37:00.862Z] [31m  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)[0m
[2022-11-30T17:37:00.862Z] [31m  at scala.Option.foreach(Option.scala:407)[0m
[2022-11-30T17:37:00.862Z] [31m  ...[0m
[2022-11-30T17:37:00.862Z] [31m  Cause: java.lang.IllegalArgumentException: Cannot grow BufferHolder by size -8 because the size is negative[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder.grow(BufferHolder.java:67)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeArrayWriter.initialize(UnsafeArrayWriter.java:61)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_3$(Unknown Source)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)[0m
[2022-11-30T17:37:00.862Z] [31m  at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:365)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)[0m
[2022-11-30T17:37:00.862Z] [31m  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)[0m
[2022-11-30T17:37:00.862Z] [31m  ...[0m
```

**Comment by jlowe** [comment]
Tracked this down to some bad offsets for a LIST column being generated from the chunked Parquet reader.  @nvdbaranec was able to reproduce the problem in pure C++ code for libcudf.

**Comment by nvdbaranec** [comment]
Triaged this.  It turns out this is another case of a malformed (but plausible in the wild) parquet file.  Essentially, we have a table with 2 rows in it.  However, 3 of the columns (members of a struct) contain 4 values which we translate as 4 rows.  This throws the figure-out-chunks code to blow up quietly.   We had a similar issue a while back that got fixed in the reader itself but it looks like it has re-appeared in this new code path. 

The filename jogged my memory too.  nested-unsigned.parquet.  It turns out this was the same file that cause the earlier issue
https://github.com/rapidsai/cudf/pull/11353
https://github.com/NVIDIA/spark-rapids/pull/6147
