### ISSUE TITLE
[BUG]  Test Parquet nested unsigned int: uint8, uint16, uint32 *** FAILED

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7318]
**Describe the bug**
 Test Parquet nested unsigned int: uint8, uint16, uint32 *** FAILED tested failed the nightly build on Spark 3.2.1

```
[2022-12-09T12:37:13.624Z] ^[[31m- Test Parquet nested unsigned int: uint8, uint16, uint32 *** FAILED ***^[[0m
[2022-12-09T12:37:13.624Z] ^[[31m  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 250.0 failed 1 times, most recent failure: Lost task 0.0 in stage 250.0 (TID 1124) (nightly-work1-698-nn8wd-c1hlv executor driver): java.lang.IllegalStateException: Partition row number <2> does not match that of the read batch <4>.^[[0m
[2022-12-09T12:37:13.624Z] ^[[31m       at com.nvidia.spark.rapids.GpuColumnarBatchWithPartitionValuesIterator.computeValuesAndRowNumsForBatch(GpuColumnarBatchIterator.scala:157)^[[0m
[2022-12-09T12:37:13.624Z] ^[[31m       at com.nvidia.spark.rapids.GpuColumnarBatchWithPartitionValuesIterator.$anonfun$next$1(GpuColumnarBatchIterator.scala:111)^[[0m
```

**Comment by jlowe** [comment]
This is the same issue as #7213.  The exact failure message changed after the sanity checks added in #7304.
