### ISSUE TITLE
[BUG] test_delta_write_encryption_runtimeconfig_fallback failed

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7320]
Saw the following failure in a nightly run against 3.3.x-SNAPSHOT.  It appears the attempt to capture the plan to examine it for fallback accidentally captured a Delta Lake metadata plan rather than the plan performing the write.
```
[2022-12-09T19:49:51.276Z] =================================== FAILURES ===================================
[2022-12-09T19:49:51.276Z] ______ test_delta_write_encryption_runtimeconfig_fallback[write_options2] ______
[2022-12-09T19:49:51.276Z] [gw4] linux -- Python 3.8.15 /opt/conda/bin/python
[2022-12-09T19:49:51.276Z] 
[2022-12-09T19:49:51.276Z] spark_tmp_path = '/tmp/pyspark_tests//it-test-33x-158-gm00d-vrgmx-gw4-29144-4535688/'
[2022-12-09T19:49:51.276Z] write_options = {'parquet.encryption.column.keys': 'k2:a', 'parquet.encryption.footer.key': 'k1'}
[2022-12-09T19:49:51.277Z] 
[2022-12-09T19:49:51.277Z]     @allow_non_gpu(*delta_meta_allow, "ExecutedCommandExec")
[2022-12-09T19:49:51.277Z]     @delta_lake
[2022-12-09T19:49:51.277Z]     @ignore_order
[2022-12-09T19:49:51.277Z]     @pytest.mark.parametrize("write_options", [{"parquet.encryption.footer.key": "k1"},
[2022-12-09T19:49:51.277Z]                                                {"parquet.encryption.column.keys": "k2:a"},
[2022-12-09T19:49:51.277Z]                                                {"parquet.encryption.footer.key": "k1", "parquet.encryption.column.keys": "k2:a"}])
[2022-12-09T19:49:51.277Z]     @pytest.mark.skipif(is_before_spark_320(), reason="Delta Lake writes are not supported before Spark 3.2.x")
[2022-12-09T19:49:51.277Z]     def test_delta_write_encryption_runtimeconfig_fallback(spark_tmp_path, write_options):
[2022-12-09T19:49:51.277Z]         data_path = spark_tmp_path + "/DELTA_DATA"
[2022-12-09T19:49:51.277Z] >       assert_gpu_fallback_write(
[2022-12-09T19:49:51.277Z]             lambda spark, path: unary_op_df(spark, int_gen).coalesce(1).write.format("delta").save(path),
[2022-12-09T19:49:51.277Z]             lambda spark, path: spark.read.format("delta").load(path),
[2022-12-09T19:49:51.277Z]             data_path,
[2022-12-09T19:49:51.277Z]             "ExecutedCommandExec",
[2022-12-09T19:49:51.277Z]             conf=copy_and_update(write_options, delta_writes_enabled_conf))
[2022-12-09T19:49:51.277Z] 
[2022-12-09T19:49:51.277Z] ../../src/main/python/delta_lake_write_test.py:325: 
[2022-12-09T19:49:51.277Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-12-09T19:49:51.277Z] ../../src/main/python/asserts.py:338: in assert_gpu_fallback_write
[2022-12-09T19:49:51.277Z]     jvm.com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertCapturedAndGpuFellBack(cpu_fallback_class_name, 2000)
[2022-12-09T19:49:51.277Z] /home/jenkins/agent/workspace/jenkins-rapids_it-3.3.x-SNAPSHOT-dev-github-158/jars/spark-3.3.2-SNAPSHOT-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321: in __call__
[2022-12-09T19:49:51.277Z]     return_value = get_return_value(
[2022-12-09T19:49:51.277Z] ../../../spark-3.3.2-SNAPSHOT-bin-hadoop3.2/python/pyspark/sql/utils.py:190: in deco
[2022-12-09T19:49:51.277Z]     return f(*a, **kw)
[2022-12-09T19:49:51.277Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2022-12-09T19:49:51.277Z] 
[2022-12-09T19:49:51.277Z] answer = 'xro8331'
[2022-12-09T19:49:51.277Z] gateway_client = <py4j.clientserver.JavaClient object at 0x7f0afacedeb0>
[2022-12-09T19:49:51.277Z] target_id = 'z:com.nvidia.spark.rapids.ExecutionPlanCaptureCallback'
[2022-12-09T19:49:51.277Z] name = 'assertCapturedAndGpuFellBack'
[2022-12-09T19:49:51.277Z] 
[2022-12-09T19:49:51.277Z]     def get_return_value(answer, gateway_client, target_id=None, name=None):
[2022-12-09T19:49:51.277Z]         """Converts an answer received from the Java gateway into a Python object.
[2022-12-09T19:49:51.277Z]     
[2022-12-09T19:49:51.277Z]         For example, string representation of integers are converted to Python
[2022-12-09T19:49:51.277Z]         integer, string representation of objects are converted to JavaObject
[2022-12-09T19:49:51.277Z]         instances, etc.
[2022-12-09T19:49:51.277Z]     
[2022-12-09T19:49:51.277Z]         :param answer: the string returned by the Java gateway
[2022-12-09T19:49:51.277Z]         :param gateway_client: the gateway client used to communicate with the Java
[2022-12-09T19:49:51.277Z]             Gateway. Only necessary if the answer is a reference (e.g., object,
[2022-12-09T19:49:51.277Z]             list, map)
[2022-12-09T19:49:51.277Z]         :param target_id: the name of the object from which the answer comes from
[2022-12-09T19:49:51.277Z]             (e.g., *object1* in `object1.hello()`). Optional.
[2022-12-09T19:49:51.277Z]         :param name: the name of the member from which the answer comes from
[2022-12-09T19:49:51.277Z]             (e.g., *hello* in `object1.hello()`). Optional.
[2022-12-09T19:49:51.277Z]         """
[2022-12-09T19:49:51.277Z]         if is_error(answer)[0]:
[2022-12-09T19:49:51.277Z]             if len(answer) > 1:
[2022-12-09T19:49:51.277Z]                 type = answer[1]
[2022-12-09T19:49:51.277Z]                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
[2022-12-09T19:49:51.277Z]                 if answer[1] == REFERENCE_TYPE:
[2022-12-09T19:49:51.277Z] >                   raise Py4JJavaError(
[2022-12-09T19:49:51.277Z]                         "An error occurred while calling {0}{1}{2}.\n".
[2022-12-09T19:49:51.277Z]                         format(target_id, ".", name), value)
[2022-12-09T19:49:51.277Z] E                   py4j.protocol.Py4JJavaError: An error occurred while calling z:com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertCapturedAndGpuFellBack.
[2022-12-09T19:49:51.277Z] E                   : java.lang.AssertionError: assertion failed: Could not find ExecutedCommandExec in the GPU plan
[2022-12-09T19:49:51.277Z] E                   ObjectHashAggregate(keys=[], functions=[collect_set(txn#12872, 0, 0), count(protocol#12876), sum(add#12873.size), last(metaData#12875, true), count(metaData#12875), last(protocol#12876, true), count(remove#12874), count(add#12873), count(txn#12872)], output=[fileSizeHistogram#12735, setTransactions#12736, numOfProtocol#12737L, sizeInBytes#12738L, metadata#12739, numOfMetadata#12740L, protocol#12741, numOfRemoves#12742L, numOfFiles#12743L, numOfSetTransactions#12744L])
[2022-12-09T19:49:51.277Z] E                   +- Exchange SinglePartition, ENSURE_REQUIREMENTS, [plan_id=7519]
[2022-12-09T19:49:51.277Z] E                      +- ObjectHashAggregate(keys=[], functions=[partial_collect_set(txn#12872, 0, 0), partial_count(protocol#12876), partial_sum(add#12873.size), partial_last(metaData#12875, true), partial_count(metaData#12875), partial_last(protocol#12876, true), partial_count(remove#12874), partial_count(add#12873), partial_count(txn#12872)], output=[buf#12959, count#12960L, sum#12961L, last#12962, valueSet#12963, count#12964L, last#12965, valueSet#12966, count#12967L, count#12968L, count#12969L])
[2022-12-09T19:49:51.277Z] E                         +- *(1) Project [txn#12872, add#12873, remove#12874, metaData#12875, protocol#12876]
[2022-12-09T19:49:51.277Z] E                            +- *(1) Scan ExistingRDD Delta Table State #0 - file:///tmp/pyspark_tests/it-test-33x-158-gm00d-vrgmx-gw4-29144-4535688/DELTA_DATA/GPU/_delta_log[txn#12872,add#12873,remove#12874,metaData#12875,protocol#12876,cdc#12877,commitInfo#12878]
[2022-12-09T19:49:51.277Z] E                   
[2022-12-09T19:49:51.277Z] E                   	at scala.Predef$.assert(Predef.scala:223)
[2022-12-09T19:49:51.277Z] E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertDidFallBack(Plugin.scala:483)
[2022-12-09T19:49:51.277Z] E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertCapturedAndGpuFellBack(Plugin.scala:477)
[2022-12-09T19:49:51.277Z] E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertCapturedAndGpuFellBack(Plugin.scala)
[2022-12-09T19:49:51.277Z] E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-12-09T19:49:51.277Z] E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-12-09T19:49:51.277Z] E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-12-09T19:49:51.277Z] E                   	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-12-09T19:49:51.277Z] E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2022-12-09T19:49:51.277Z] E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2022-12-09T19:49:51.278Z] E                   	at py4j.Gateway.invoke(Gateway.java:282)
[2022-12-09T19:49:51.278Z] E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2022-12-09T19:49:51.278Z] E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2022-12-09T19:49:51.278Z] E                   	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2022-12-09T19:49:51.278Z] E                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2022-12-09T19:49:51.278Z] E                   	at java.lang.Thread.run(Thread.java:750)
[2022-12-09T19:49:51.278Z] 
[2022-12-09T19:49:51.278Z] /home/jenkins/agent/workspace/jenkins-rapids_it-3.3.x-SNAPSHOT-dev-github-158/jars/spark-3.3.2-SNAPSHOT-bin-hadoop3.2/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326: Py4JJavaError
```

**Comment by jlowe** [comment]
Duplicate of #7329
