### ISSUE TITLE
[BUG] Update Exception to fix Assertion error in Databricks-11.3 integration tests.

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7327]
**Describe the bug**
Below tests are failing due as the exception type is different in Databricks-11.3. 

- [x] test_array_element_at_zero_index_fail - Possibly Related to https://github.com/NVIDIA/spark-rapids/pull/7075
- [x] test_day_time_interval_divided_by_zero 
- [x] test_day_time_interval_divided_by_zero_scalar 
- [x] test_day_time_interval_division_overflow  
- [x] test_day_time_interval_scalar_divided_by_zero  
- [x] test_div_by_zero_ansi
- [x] test_div_overflow_exception_when_ansi
- [x] test_mod_pmod_by_zero  
- [x] test_multiplication_ansi_overflow

Failure Reason:
```
org.apache.spark.SparkArithmeticException: [INTERVAL_DIVIDED_BY_ZERO] Division by zero. Use `try_divide` to tolerate divisor being 0 and return NULL instead.
org.apache.spark.SparkArithmeticException: [ARITHMETIC_OVERFLOW] Overflow in integral divide. Use 'try_divide' to tolerate overflow and return NULL instead. If necessary set spark.sql.ansi.enabled to "false" to bypass this error.
org.apache.spark.SparkArithmeticException: [DIVIDE_BY_ZERO] Division by zero. Use `try_divide` to tolerate divisor being 0 and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
org.apache.spark.SparkArithmeticException: [NUMERIC_VALUE_OUT_OF_RANGE] 577694938495380589068894346762519873590000000000000000000000000000000000000 cannot be represented as Decimal(38, 0). If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
```

**Steps/Code to reproduce bug**
Build and run integration tests on Databricks-11.3 environment.
Build  steps - Pull in this PR locally if not merged - https://github.com/NVIDIA/spark-rapids/pull/7152 
                      /home/ubuntu/spark-rapids$ ./jenkins/databricks/build.sh

Test steps:  Modify the test.sh under jenkins/databrikcs to run a specific test.
                Example: Comment all lines starting from `export TEST_PARALLEL=${TEST_PARALLEL:-4}` in the file and add below lines:
                ```
                export TEST_PARALLEL=${TEST_PARALLEL:-1}
                TEST_NAME=$1
                bash /home/ubuntu/spark-rapids/integration_tests/run_pyspark_from_build.sh -k $TEST_NAME
               ```

Run Test -  `./jenkins/databricks/test.sh test_array_element_at_zero_index_fail  `

**Expected behavior**
All above tests should pass on Databricks-11.3 shim

**Environment details (please complete the following information)**
Databricks-11.3 runtime.

**Additional context**

**Comment by rwlee** [comment]
#7388 should close this issue. `test_multiplication_ansi_overflow` is the only remaining test and the GPU portion of the test is failing rather than not matching the error message of the CPU test.

```
22/12/18 06:20:37 WARN GpuOverrides:
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#4 could run on GPU 

22/12/18 06:20:37 ERROR GpuOverrideUtil: Encountered an exception applying GPU overrides java.lang.IllegalStateException: Decimal Multiply should be converted in Ch
eckOverflow
java.lang.IllegalStateException: Decimal Multiply should be converted in CheckOverflow
        at com.nvidia.spark.rapids.GpuOverrides$$anon$87.convertToGpu(GpuOverrides.scala:1832)
        at com.nvidia.spark.rapids.BinaryExprMeta.convertToGpu(RapidsMeta.scala:1251)
        at com.nvidia.spark.rapids.BinaryExprMeta.convertToGpu(RapidsMeta.scala:1242)
        at com.nvidia.spark.rapids.UnaryExprMeta.convertToGpu(RapidsMeta.scala:1127)
        at com.nvidia.spark.rapids.UnaryExprMeta.convertToGpu(RapidsMeta.scala:1119)
        at com.nvidia.spark.rapids.GpuProjectExecMeta.$anonfun$convertToGpu$1(basicPhysicalOperators.scala:49)
        at scala.collection.immutable.Stream.map(Stream.scala:418)
        at com.nvidia.spark.rapids.GpuProjectExecMeta.convertToGpu(basicPhysicalOperators.scala:49)
        at com.nvidia.spark.rapids.GpuProjectExecMeta.convertToGpu(basicPhysicalOperators.scala:41)
        at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:748)
        at com.nvidia.spark.rapids.GpuOverrides$.com$nvidia$spark$rapids$GpuOverrides$$doConvertPlan(GpuOverrides.scala:4130)
        at com.nvidia.spark.rapids.GpuOverrides.applyOverrides(GpuOverrides.scala:4469)
        at com.nvidia.spark.rapids.GpuOverrides.$anonfun$applyWithContext$3(GpuOverrides.scala:4335)
        at com.nvidia.spark.rapids.GpuOverrides$.logDuration(GpuOverrides.scala:500)
        at com.nvidia.spark.rapids.GpuOverrides.$anonfun$applyWithContext$1(GpuOverrides.scala:4332)
        at com.nvidia.spark.rapids.GpuOverrideUtil$.$anonfun$tryOverride$1(GpuOverrides.scala:4298)
        at com.nvidia.spark.rapids.GpuOverrides.applyWithContext(GpuOverrides.scala:4352)
        at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:4325)
        at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:4321)
        at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1(Columnar.scala:569)
        at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1$adapted(Columnar.scala:569)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:569)
        at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:523)
        at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$2(QueryExecution.scala:704)
        at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
        at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:704)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:703)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$2(QueryExecution.scala:314)
        at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:319)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$3(QueryExecution.scala:349)
        at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:777)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:349)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
        at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:346)
        at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:310)
        at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:304)
        at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:394)
        at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:463)
        at org.apache.spark.sql.execution.QueryExecution.explainStringLocal(QueryExecution.scala:425)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:205)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:392)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:188)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
        at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:142)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:342)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4288)
        at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:4048)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
        at py4j.Gateway.invoke(Gateway.java:306)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
        at java.lang.Thread.run(Thread.java:750)
``

**Comment by nartal1** [comment]
All tests in this issue are passing. Closing.
