### ISSUE TITLE
[BUG] intermittently could not find ExecutedCommandExec in the GPU plan in delta_lake_write test

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#7329]
**Describe the bug**
this is introduced in #7288, 
initially this was found in nightly integrations tests CI which only failed in one spark ver (320) and pass all others.
This is hard to be reproduced (5% reproducible in local test)

found `could not find ExecutedCommandExec in the GPU plan` intermittently in fallback cases
test_delta_write_disabled_fallback
test_delta_write_encryption_option_fallback
test_delta_write_encryption_hadoopconfig_fallback

FAILED ../../src/main/python/delta_lake_write_test.py::test_delta_write_disabled_fallback[{'spark.rapids.sql.format.parquet.write.enabled': 'false'}][IGNORE_ORDER, ALLOW_NON_GPU(ExecutedCommandExec,DeserializeToObjectExec,ShuffleExchangeExec,FileSourceScanExec,FilterExec,MapPartitionsExec,MapElementsExec,ObjectHashAggregateExec,ProjectExec,SerializeFromObjectExec,SortExec)]
```
[2022-12-12T01:06:35.032Z] [1m[31mE                   : java.lang.AssertionError: assertion failed: Could not find ExecutedCommandExec in the GPU plan[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   ObjectHashAggregate(keys=[], functions=[collect_set(txn#470, 0, 0), count(protocol#474), sum(add#471.size), last(metaData#473, true), count(metaData#473), last(protocol#474, true), count(remove#472), count(add#471), count(txn#470)], output=[fileSizeHistogram#334, setTransactions#335, numOfProtocol#336L, sizeInBytes#337L, metadata#338, numOfMetadata#339L, protocol#340, numOfRemoves#341L, numOfFiles#342L, numOfSetTransactions#343L])[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   +- Exchange SinglePartition, ENSURE_REQUIREMENTS, [id=#295][0m
[2022-12-12T01:06:35.032Z] [1m[31mE                      +- ObjectHashAggregate(keys=[], functions=[partial_collect_set(txn#470, 0, 0), partial_count(protocol#474), partial_sum(add#471.size), partial_last(metaData#473, true), partial_count(metaData#473), partial_last(protocol#474, true), partial_count(remove#472), partial_count(add#471), partial_count(txn#470)], output=[buf#557, count#558L, sum#559L, last#560, valueSet#561, count#562L, last#563, valueSet#564, count#565L, count#566L, count#567L])[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                         +- *(1) Project [txn#470, add#471, remove#472, metaData#473, protocol#474][0m
[2022-12-12T01:06:35.032Z] [1m[31mE                            +- *(1) Scan ExistingRDD Delta Table State #0 - file:///tmp/pyspark_tests/it-test-320-591-gxvdc-cgf5x-gw0-31646-344327987/DELTA_DATA/GPU/_delta_log[txn#470,add#471,remove#472,metaData#473,protocol#474,cdc#475,commitInfo#476][0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   [0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at scala.Predef$.assert(Predef.scala:223)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertDidFallBack(Plugin.scala:483)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertCapturedAndGpuFellBack(Plugin.scala:477)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertCapturedAndGpuFellBack(Plugin.scala)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at java.lang.reflect.Method.invoke(Method.java:498)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at py4j.Gateway.invoke(Gateway.java:282)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)[0m
[2022-12-12T01:06:35.032Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:750)[0m
```

FAILED ../../src/main/python/delta_lake_write_test.py::test_delta_write_encryption_hadoopconfig_fallback[write_options2][IGNORE_ORDER, ALLOW_NON_GPU(DeserializeToObjectExec,ShuffleExchangeExec,FileSourceScanExec,FilterExec,MapPartitionsExec,MapElementsExec,ObjectHashAggregateExec,ProjectExec,SerializeFromObjectExec,SortExec,ExecutedCommandExec)]
```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling z:com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertCapturedAndGpuFellBack.
E                   : java.lang.AssertionError: assertion failed: Could not find ExecutedCommandExec in the GPU plan
E                   GpuColumnarToRow false
E                   +- GpuCoalesce 1
E                      +- GpuRowToColumnar targetsize(104857600)
E                         +- *(1) Scan ExistingRDD[a#25622]
E
E                   	at scala.Predef$.assert(Predef.scala:223)
E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertDidFallBack(Plugin.scala:483)
E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.assertCapturedAndGpuFellBack(Plugin.scala:477)
E                   	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertCapturedAndGpuFellBack(Plugin.scala)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
E                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
E                   	at java.lang.Thread.run(Thread.java:750)
```

**Steps/Code to reproduce bug**
```
mvn clean package -pl '!tools' -Dbuildver=320 -DskipTests=true -Dskip.rat=true

# need to re-run multiple times to get a reproduce
# if SPARK_HOME=<spark 32X>, delta 2.0.1/2.0.0
PYSP_TEST_spark_jars_packages="io.delta:delta-core_2.12:2.0.1" \
      PYSP_TEST_spark_sql_extensions="io.delta.sql.DeltaSparkSessionExtension" \
      PYSP_TEST_spark_sql_catalog_spark__catalog="org.apache.spark.sql.delta.catalog.DeltaCatalog" \
      integration_tests/run_pyspark_from_build.sh -m delta_lake --delta_lake
```

**Expected behavior**
Always pass the tests

**Comment by pxLi** [comment]
move this to 23.02, xfail all fallback cases for now
