### ISSUE TITLE
[BUG] test_conditional_with_side_effects_case_when fails

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7350]
**Describe the bug**
```
5:27:54  [31mFAILED[0m ../../src/main/python/conditionals_test.py::[1mtest_conditional_with_side_effects_case_when[String][0m - py4j.protocol.Py4JJavaError: An error occurred while calling o398652.collec...
05:27:54  [31mFAILED[0m ../../src/main/python/conditionals_test.py::[1mtest_conditional_with_side_effects_map_key_not_found[true-data_gen0-map_gen0][0m - py4j.protocol.Py4JJavaError: An error occurred while calling o399729.collec...
05:27:54  [31m= [31m[1m2 failed[0m, [32m14842 passed[0m, [33m827 skipped[0m, [33m544 xfailed[0m, [33m223 xpassed[0m, [33m802 warnings[0m[31m in 6918.14s (1:55:18)[0m[31m =[0m
05:27:59  + cd spark-rapids
```

Part of stack:
```

[2022-12-13T10:01:52.543Z] 22/12/13 10:01:52 ERROR Executor: Exception in task 2.0 in stage 1889.0 (TID 7558)
[2022-12-13T10:01:52.543Z] java.lang.ArithmeticException: One or more rows overflow for Add operation.
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.shims.RapidsErrorUtils$.arithmeticOverflowError(RapidsErrorUtils.scala:55)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$6(arithmetic.scala:204)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$6$adapted(arithmetic.scala:202)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd$.withResource(arithmetic.scala:184)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$5(arithmetic.scala:202)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$5$adapted(arithmetic.scala:201)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd$.withResource(arithmetic.scala:184)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd$.basicOpOverflowCheck(arithmetic.scala:201)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd.$anonfun$doColumnar$7(arithmetic.scala:280)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.CudfBinaryOperator.withResource(GpuExpressions.scala:336)
[2022-12-13T10:01:52.543Z]      at org.apache.spark.sql.rapids.GpuAdd.doColumnar(arithmetic.scala:273)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:317)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:316)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.CudfBinaryOperator.doColumnar(GpuExpressions.scala:336)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$3(GpuExpressions.scala:261)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:254)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEval(GpuExpressions.scala:336)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$filterEvaluateWhenThen$1(conditionalExpressions.scala:466)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2022-12-13T10:01:52.543Z]      at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
                                                                                  
```

**Comment by jlowe** [comment]
I can reproduce this easily outside of Databricks on Spark 3.2.1.  I'm also seeing unit test failures in Scala on Spark 3.2.1 in ConditionalsSuite, e.g.:
```
ConditionalsSuite:
- CASE WHEN test all branches *** FAILED ***
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 102.0 failed 1 times, most recent failure: Lost task 0.0 in stage 102.0 (TID 153) (10.28.9.126 executor driver): java.lang.ArithmeticException: One or more rows overflow for Add operation.
	at org.apache.spark.sql.rapids.shims.RapidsErrorUtils$.arithmeticOverflowError(RapidsErrorUtils.scala:55)
	at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$6(arithmetic.scala:204)
	at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$6$adapted(arithmetic.scala:202)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at org.apache.spark.sql.rapids.GpuAdd$.withResource(arithmetic.scala:184)
	at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$5(arithmetic.scala:202)
	at org.apache.spark.sql.rapids.GpuAdd$.$anonfun$basicOpOverflowCheck$5$adapted(arithmetic.scala:201)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at org.apache.spark.sql.rapids.GpuAdd$.withResource(arithmetic.scala:184)
	at org.apache.spark.sql.rapids.GpuAdd$.basicOpOverflowCheck(arithmetic.scala:201)
	at org.apache.spark.sql.rapids.GpuAdd.$anonfun$doColumnar$7(arithmetic.scala:280)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.CudfBinaryOperator.withResource(GpuExpressions.scala:336)
	at org.apache.spark.sql.rapids.GpuAdd.doColumnar(arithmetic.scala:273)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:317)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:316)
	at com.nvidia.spark.rapids.CudfBinaryOperator.doColumnar(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$3(GpuExpressions.scala:261)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
	at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:254)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
	at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
	at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEval(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$filterEvaluateWhenThen$1(conditionalExpressions.scala:466)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuCaseWhen.withResource(conditionalExpressions.scala:314)
	at com.nvidia.spark.rapids.GpuCaseWhen.filterEvaluateWhenThen(conditionalExpressions.scala:465)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEvalWithSideEffects$4(conditionalExpressions.scala:405)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEvalWithSideEffects$4$adapted(conditionalExpressions.scala:398)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuCaseWhen.withResource(conditionalExpressions.scala:314)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEvalWithSideEffects$3(conditionalExpressions.scala:398)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEvalWithSideEffects$3$adapted(conditionalExpressions.scala:394)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuCaseWhen.withResource(conditionalExpressions.scala:314)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEvalWithSideEffects$2(conditionalExpressions.scala:394)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEvalWithSideEffects$2$adapted(conditionalExpressions.scala:391)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.nvidia.spark.rapids.GpuCaseWhen.$anonfun$columnarEvalWithSideEffects$1(conditionalExpressions.scala:391)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuCaseWhen.withResource(conditionalExpressions.scala:314)
	at com.nvidia.spark.rapids.GpuCaseWhen.columnarEvalWithSideEffects(conditionalExpressions.scala:388)
	at com.nvidia.spark.rapids.GpuCaseWhen.columnarEval(conditionalExpressions.scala:359)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:109)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
	at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:108)
	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:115)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:216)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:213)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:213)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:248)
	at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:115)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$tieredProject$1(basicPhysicalOperators.scala:335)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuTieredProject.withResource(basicPhysicalOperators.scala:286)
	at com.nvidia.spark.rapids.GpuTieredProject.recurse$1(basicPhysicalOperators.scala:334)
	at com.nvidia.spark.rapids.GpuTieredProject.tieredProject(basicPhysicalOperators.scala:354)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$tieredProjectAndClose$2(basicPhysicalOperators.scala:360)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuTieredProject.withResource(basicPhysicalOperators.scala:286)
	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$tieredProjectAndClose$1(basicPhysicalOperators.scala:359)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuTieredProject.withResource(basicPhysicalOperators.scala:286)
	at com.nvidia.spark.rapids.GpuTieredProject.tieredProjectAndClose(basicPhysicalOperators.scala:358)
	at com.nvidia.spark.rapids.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:161)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:241)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by jlowe** [comment]
These failures all appear to be related to a recent change, see rapidsai/cudf#12279.  The issue is that `any` and `all` are returning flipped results for empty columns.  Filed rapidsai/cudf#12373.
