### ISSUE TITLE
[BUG] shuffle smoke test hash_aggregate_test.py::test_hash_grpby_sum failed OOM intermittently in premerge

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#7397]
**Describe the bug**
We saw several intermittent cuda oom failures in pre-merge intermittently when doing the ucx shuffle smoke test,
https://github.com/NVIDIA/spark-rapids/actions/runs/3730854860/jobs/6328391314
https://github.com/NVIDIA/spark-rapids/actions/runs/3735203778/jobs/6338169927

hash_aggregate_test.py::test_hash_grpby_sum in https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/jenkins/spark-premerge-build.sh#L91 failed `java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: CUDA error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-305-cuda11/target/libcudf-install/include/rmm/mr/device/cuda_memory_resource.hpp:70: cudaErrorMemoryAllocation out of memory`

```
[2022-12-19T11:09:28.506Z]     def get_return_value(answer, gateway_client, target_id=None, name=None):
[2022-12-19T11:09:28.506Z]         """Converts an answer received from the Java gateway into a Python object.
[2022-12-19T11:09:28.506Z]     
[2022-12-19T11:09:28.506Z]         For example, string representation of integers are converted to Python
[2022-12-19T11:09:28.506Z]         integer, string representation of objects are converted to JavaObject
[2022-12-19T11:09:28.506Z]         instances, etc.
[2022-12-19T11:09:28.506Z]     
[2022-12-19T11:09:28.506Z]         :param answer: the string returned by the Java gateway
[2022-12-19T11:09:28.506Z]         :param gateway_client: the gateway client used to communicate with the Java
[2022-12-19T11:09:28.506Z]             Gateway. Only necessary if the answer is a reference (e.g., object,
[2022-12-19T11:09:28.506Z]             list, map)
[2022-12-19T11:09:28.506Z]         :param target_id: the name of the object from which the answer comes from
[2022-12-19T11:09:28.506Z]             (e.g., *object1* in `object1.hello()`). Optional.
[2022-12-19T11:09:28.506Z]         :param name: the name of the member from which the answer comes from
[2022-12-19T11:09:28.506Z]             (e.g., *hello* in `object1.hello()`). Optional.
[2022-12-19T11:09:28.506Z]         """
[2022-12-19T11:09:28.506Z]         if is_error(answer)[0]:
[2022-12-19T11:09:28.506Z]             if len(answer) > 1:
[2022-12-19T11:09:28.506Z]                 type = answer[1]
[2022-12-19T11:09:28.506Z]                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
[2022-12-19T11:09:28.506Z]                 if answer[1] == REFERENCE_TYPE:
[2022-12-19T11:09:28.506Z] >                   raise Py4JJavaError(
[2022-12-19T11:09:28.506Z]                         "An error occurred while calling {0}{1}{2}.\n".
[2022-12-19T11:09:28.506Z]                         format(target_id, ".", name), value)
[2022-12-19T11:09:28.506Z] [1m[31mE                   py4j.protocol.Py4JJavaError: An error occurred while calling o586.collectToPython.[0m
[2022-12-19T11:09:28.506Z] [1m[31mE                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 5.0 failed 1 times, most recent failure: Lost task 1.0 in stage 5.0 (TID 15) (10.233.106.38 executor 0): java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: CUDA error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-305-cuda11/target/libcudf-install/include/rmm/mr/device/cuda_memory_resource.hpp:70: cudaErrorMemoryAllocation out of memory[0m
[2022-12-19T11:09:28.506Z] [1m[31mE                   	at ai.rapids.cudf.Rmm.allocCudaInternal(Native Method)[0m
[2022-12-19T11:09:28.506Z] [1m[31mE                   	at ai.rapids.cudf.Rmm.allocCuda(Rmm.java:351)[0m
[2022-12-19T11:09:28.506Z] [1m[31mE                   	at ai.rapids.cudf.CudaMemoryBuffer.allocate(CudaMemoryBuffer.java:107)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at ai.rapids.cudf.CudaMemoryBuffer.allocate(CudaMemoryBuffer.java:97)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.$anonfun$initBounceBufferPools$1(UCXShuffleTransport.scala:135)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.$anonfun$initBounceBufferPools$1$adapted(UCXShuffleTransport.scala:132)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.BounceBufferManager.<init>(BounceBufferManager.scala:96)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.initBounceBufferPools(UCXShuffleTransport.scala:146)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.ucx$lzycompute(UCXShuffleTransport.scala:75)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.ucx(UCXShuffleTransport.scala:69)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.makeServer(UCXShuffleTransport.scala:310)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.server$lzycompute(RapidsShuffleInternalManagerBase.scala:1142)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.server(RapidsShuffleInternalManagerBase.scala:1127)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.getWriter(RapidsShuffleInternalManagerBase.scala:1204)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.sql.rapids.ProxyRapidsShuffleInternalManagerBase.getWriter(RapidsShuffleInternalManagerBase.scala:1410)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.run(Task.scala:131)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:750)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   [0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   Driver stacktrace:[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2253)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2202)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2201)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2201)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1078)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1078)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at scala.Option.foreach(Option.scala:407)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1078)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2440)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2382)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2371)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:868)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2202)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2223)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2242)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2267)[0m
[2022-12-19T11:09:28.507Z] [1m[31mE                   	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDD.collect(RDD.scala:1029)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuRangePartitioner$.sketch(GpuRangePartitioner.scala:49)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuRangePartitioner$.createRangeBounds(GpuRangePartitioner.scala:134)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$.getPartitioner(GpuShuffleExchangeExecBase.scala:386)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$.prepareBatchShuffleDependency(GpuShuffleExchangeExecBase.scala:295)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.shuffleDependencyColumnar$lzycompute(GpuShuffleExchangeExecBase.scala:235)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.shuffleDependencyColumnar(GpuShuffleExchangeExecBase.scala:224)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.$anonfun$doExecuteColumnar$1(GpuShuffleExchangeExecBase.scala:250)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at com.nvidia.spark.rapids.shims.Spark31XShims.attachTreeIfSupported(Spark31XShims.scala:411)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase.doExecuteColumnar(GpuShuffleExchangeExecBase.scala:247)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:207)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:203)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuCoalesceBatches.doExecuteColumnar(GpuCoalesceBatches.scala:715)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:207)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:203)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuSortExec.doExecuteColumnar(GpuSortExec.scala:142)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeColumnar$1(SparkPlan.scala:207)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeColumnar(SparkPlan.scala:203)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at com.nvidia.spark.rapids.GpuColumnarToRowExec.doExecute(GpuColumnarToRowExec.scala:316)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:321)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:387)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3519)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)[0m
[2022-12-19T11:09:28.508Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3516)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at java.lang.reflect.Method.invoke(Method.java:498)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at py4j.Gateway.invoke(Gateway.java:282)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:750)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   Caused by: java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: CUDA error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-305-cuda11/target/libcudf-install/include/rmm/mr/device/cuda_memory_resource.hpp:70: cudaErrorMemoryAllocation out of memory[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at ai.rapids.cudf.Rmm.allocCudaInternal(Native Method)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at ai.rapids.cudf.Rmm.allocCuda(Rmm.java:351)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at ai.rapids.cudf.CudaMemoryBuffer.allocate(CudaMemoryBuffer.java:107)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at ai.rapids.cudf.CudaMemoryBuffer.allocate(CudaMemoryBuffer.java:97)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.$anonfun$initBounceBufferPools$1(UCXShuffleTransport.scala:135)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.$anonfun$initBounceBufferPools$1$adapted(UCXShuffleTransport.scala:132)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.BounceBufferManager.<init>(BounceBufferManager.scala:96)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.initBounceBufferPools(UCXShuffleTransport.scala:146)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.ucx$lzycompute(UCXShuffleTransport.scala:75)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.ucx(UCXShuffleTransport.scala:69)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at com.nvidia.spark.rapids.shuffle.ucx.UCXShuffleTransport.makeServer(UCXShuffleTransport.scala:310)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.server$lzycompute(RapidsShuffleInternalManagerBase.scala:1142)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.server(RapidsShuffleInternalManagerBase.scala:1127)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.getWriter(RapidsShuffleInternalManagerBase.scala:1204)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.sql.rapids.ProxyRapidsShuffleInternalManagerBase.getWriter(RapidsShuffleInternalManagerBase.scala:1410)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.run(Task.scala:131)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2022-12-19T11:09:28.509Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
```

**Comment by pxLi** [comment]
not seeing this recently. close this for now and will reopen if show up again
