### ISSUE TITLE
[BUG] test_dynamic_partition_write_round_trip failed in CDH tests

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7403]
So this is a test I added to touch the dynamic partition overwrite because of this bug: https://github.com/NVIDIA/spark-rapids/issues/7378

It looks like the CDH environment (perhaps they have a different Orc version?) does not support this feature.

```
238426 [2022-12-20T18:02:21.577Z] ^[[31m^[[1m____________ test_dynamic_partition_write_round_trip[hive-Integer] _____________^[[0m
238427 [2022-12-20T18:02:21.577Z]
238428 [2022-12-20T18:02:21.577Z] spark_tmp_path = '/tmp/pyspark_tests//rl-r7525-d32-u35.raplab.nvidia.com-main-120005-1084154900/'
238429 [2022-12-20T18:02:21.577Z] orc_gen = Integer, orc_impl = 'hive'
238430 [2022-12-20T18:02:21.577Z]
238431 [2022-12-20T18:02:21.577Z]     @ignore_order(local=True)
238432 [2022-12-20T18:02:21.577Z]     @pytest.mark.parametrize('orc_gen', [int_gen], ids=idfn)
238433 [2022-12-20T18:02:21.577Z]     @pytest.mark.parametrize('orc_impl', ["native", "hive"])
238434 [2022-12-20T18:02:21.577Z]     def test_dynamic_partition_write_round_trip(spark_tmp_path, orc_gen, orc_impl):
238435 [2022-12-20T18:02:21.577Z]         gen_list = [('_c0', orc_gen)]
238436 [2022-12-20T18:02:21.577Z]         data_path = spark_tmp_path + '/ORC_DATA'
238437 [2022-12-20T18:02:21.577Z]         def do_writes(spark, path):
238438 [2022-12-20T18:02:21.577Z]             df = gen_df(spark, gen_list).withColumn("my_partition", lit("PART"))
238439 [2022-12-20T18:02:21.577Z]             # first write finds no partitions, it skips the dynamic partition
238440 [2022-12-20T18:02:21.577Z]             # overwrite code
238441 [2022-12-20T18:02:21.577Z]             df.write.mode("overwrite").partitionBy("my_partition").orc(path)
238442 [2022-12-20T18:02:21.577Z]             # second write actually triggers dynamic partition overwrite
238443 [2022-12-20T18:02:21.577Z]             df.write.mode("overwrite").partitionBy("my_partition").orc(path)
238444 [2022-12-20T18:02:21.577Z]         assert_gpu_and_cpu_writes_are_equal_collect(
238445 [2022-12-20T18:02:21.577Z]                 lambda spark, path: do_writes(spark, path),
238446 [2022-12-20T18:02:21.577Z]                 lambda spark, path: spark.read.orc(path),
238447 [2022-12-20T18:02:21.577Z]                 data_path,
238448 [2022-12-20T18:02:21.577Z]                 conf={
238449 [2022-12-20T18:02:21.577Z]                     'spark.sql.orc.impl': orc_impl,
238450 [2022-12-20T18:02:21.577Z]                     'spark.rapids.sql.format.orc.write.enabled': True,
238451 [2022-12-20T18:02:21.577Z] >                   'spark.sql.sources.partitionOverwriteMode': 'DYNAMIC'
238452 [2022-12-20T18:02:21.577Z]                 })
238453 [2022-12-20T18:02:21.577Z]
238454 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/orc_write_test.py^[[0m:115:
238455 [2022-12-20T18:02:21.577Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
238456 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/asserts.py^[[0m:268: in assert_gpu_and_cpu_writes_are_equal_collect
238457 [2022-12-20T18:02:21.577Z]     _assert_gpu_and_cpu_writes_are_equal(write_func, read_func, base_path, 'COLLECT', conf=conf)
238458 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/asserts.py^[[0m:238: in _assert_gpu_and_cpu_writes_are_equal
238459 [2022-12-20T18:02:21.577Z]     with_cpu_session(lambda spark : write_func(spark, cpu_path), conf=conf)
238460 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/spark_session.py^[[0m:113: in with_cpu_session
238461 [2022-12-20T18:02:21.577Z]     return with_spark_session(func, conf=copy)
238462 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/spark_session.py^[[0m:97: in with_spark_session
238463 [2022-12-20T18:02:21.577Z]     ret = func(_spark)
238464 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/asserts.py^[[0m:238: in <lambda>
238465 [2022-12-20T18:02:21.577Z]     with_cpu_session(lambda spark : write_func(spark, cpu_path), conf=conf)
238466 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/orc_write_test.py^[[0m:109: in <lambda>
238467 [2022-12-20T18:02:21.577Z]     lambda spark, path: do_writes(spark, path),
238468 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m../../src/main/python/orc_write_test.py^[[0m:105: in do_writes
238469 [2022-12-20T18:02:21.577Z]     df.write.mode("overwrite").partitionBy("my_partition").orc(path)
238470 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m/opt/cloudera/parcels/SPARK3-3.2.1.3.2.7171000.1-1-1.p0.25570994/lib/spark3/python/lib/pyspark.zip/pyspark/sql/readwriter.py^[[0m:995: in orc
238471 [2022-12-20T18:02:21.577Z]     self._jwrite.orc(path)
238472 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m/opt/cloudera/parcels/SPARK3-3.2.1.3.2.7171000.1-1-1.p0.25570994/lib/spark3/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py^[[0m:1322: in __call__
238473 [2022-12-20T18:02:21.577Z]     answer, self.gateway_client, self.target_id, self.name)
238474 [2022-12-20T18:02:21.577Z] ^[[1m^[[31m/opt/cloudera/parcels/SPARK3-3.2.1.3.2.7171000.1-1-1.p0.25570994/lib/spark3/python/lib/pyspark.zip/pyspark/sql/utils.py^[[0m:111: in deco
238475 [2022-12-20T18:02:21.577Z]     return f(*a, **kw)
238476 [2022-12-20T18:02:21.577Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
238477 [2022-12-20T18:02:21.577Z]
238478 [2022-12-20T18:02:21.577Z] answer = 'xro12457'
238479 [2022-12-20T18:02:21.577Z] gateway_client = <py4j.clientserver.JavaClient object at 0x7f7e3bdba320>
238480 [2022-12-20T18:02:21.577Z] target_id = 'o12456', name = 'orc'
238481 [2022-12-20T18:02:21.577Z]
238482 [2022-12-20T18:02:21.577Z]     def get_return_value(answer, gateway_client, target_id=None, name=None):
238483 [2022-12-20T18:02:21.577Z]         """Converts an answer received from the Java gateway into a Python object.
238484 [2022-12-20T18:02:21.577Z]
238485 [2022-12-20T18:02:21.577Z]         For example, string representation of integers are converted to Python
238486 [2022-12-20T18:02:21.577Z]         integer, string representation of objects are converted to JavaObject
238487 [2022-12-20T18:02:21.577Z]         instances, etc.
238488 [2022-12-20T18:02:21.577Z]
238489 [2022-12-20T18:02:21.577Z]         :param answer: the string returned by the Java gateway
238490 [2022-12-20T18:02:21.577Z]         :param gateway_client: the gateway client used to communicate with the Java
238491 [2022-12-20T18:02:21.577Z]             Gateway. Only necessary if the answer is a reference (e.g., object,
238492 [2022-12-20T18:02:21.577Z]             list, map)
238493 [2022-12-20T18:02:21.577Z]         :param target_id: the name of the object from which the answer comes from
238494 [2022-12-20T18:02:21.577Z]             (e.g., *object1* in `object1.hello()`). Optional.
238495 [2022-12-20T18:02:21.577Z]         :param name: the name of the member from which the answer comes from
238496 [2022-12-20T18:02:21.577Z]             (e.g., *hello* in `object1.hello()`). Optional.
238497 [2022-12-20T18:02:21.577Z]         """
238498 [2022-12-20T18:02:21.577Z]         if is_error(answer)[0]:
238499 [2022-12-20T18:02:21.577Z]             if len(answer) > 1:
238500 [2022-12-20T18:02:21.577Z]                 type = answer[1]
238501 [2022-12-20T18:02:21.577Z]                 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
238502 [2022-12-20T18:02:21.577Z]                 if answer[1] == REFERENCE_TYPE:
238503 [2022-12-20T18:02:21.577Z]                     raise Py4JJavaError(
238504 [2022-12-20T18:02:21.577Z]                         "An error occurred while calling {0}{1}{2}.\n".
238505 [2022-12-20T18:02:21.577Z] >                       format(target_id, ".", name), value)
238506 [2022-12-20T18:02:21.577Z] ^[[1m^[[31mE                   py4j.protocol.Py4JJavaError: An error occurred while calling o12456.orc.^[[0m
238507 [2022-12-20T18:02:21.577Z] ^[[1m^[[31mE                   : java.io.IOException: PathOutputCommitProtocol does not support dynamicPartitionOverwrite^[[0m
238508 [2022-12-20T18:02:21.577Z] ^[[1m^[[31mE                     at org.apache.spark.internal.io.cloud.PathOutputCommitProtocol.<init>(PathOutputCommitProtocol.scala:59)^[[0m
238509 [2022-12-20T18:02:21.577Z] ^[[1m^[[31mE                     at sun.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)^[[0m
238510 [2022-12-20T18:02:21.577Z] ^[[1m^[[31mE                     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)^[[0m
238511 [2022-12-20T18:02:21.577Z] ^[[1m^[[31mE                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)^[[0m
238512 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.internal.io.FileCommitProtocol$.instantiate(FileCommitProtocol.scala:218)^[[0m
238513 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:112)^[[0m
238514 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)^[[0m
238515 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)^[[0m
238516 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)^[[0m
238517 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:111)^[[0m
238518 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)^[[0m
238519 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)^[[0m
238520 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)^[[0m
238521 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)^[[0m
238522 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)^[[0m
238523 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:111)^[[0m
238524 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)^[[0m
238525 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)^[[0m
238526 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)^[[0m
238527 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)^[[0m
238528 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)^[[0m
238529 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)^[[0m
238530 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)^[[0m
238531 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)^[[0m
238532 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)^[[0m
238533 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)^[[0m
238534 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)^[[0m
238535 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)^[[0m
238536 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)^[[0m
238537 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:129)^[[0m
238538 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:856)^[[0m
238539 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:382)^[[0m
238540 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:355)^[[0m
238541 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)^[[0m
238542 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at org.apache.spark.sql.DataFrameWriter.orc(DataFrameWriter.scala:807)^[[0m
238543 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)^[[0m
238544 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)^[[0m
238545 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at java.lang.reflect.Method.invoke(Method.java:498)^[[0m
238546 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)^[[0m
238547 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)^[[0m
238548 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at py4j.Gateway.invoke(Gateway.java:282)^[[0m
238549 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)^[[0m
238550 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at py4j.commands.CallCommand.execute(CallCommand.java:79)^[[0m
238551 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)^[[0m
238552 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at py4j.ClientServerConnection.run(ClientServerConnection.java:106)^[[0m
238553 [2022-12-20T18:02:21.578Z] ^[[1m^[[31mE                     at java.lang.Thread.run(Thread.java:748)^[[0m
238554 [2022-12-20T18:02:21.578Z]
```

**Comment by abellina** [comment]
Note that this test fails in 321cdh but not in 330cdh. I am going to disable for 321cdh but leave it enabled for the later one since it seems to be a feature that is not there in 3.2.1. Note this is a feature that is being requested that isn't implemented yet, and so I don't think a shim is appropriate here.

**Comment by abellina** [comment]
Please note this error happens on the CPU, so we are moving forward with `skipif`.
```
../../src/main/python/asserts.py:268: in assert_gpu_and_cpu_writes_are_equal_collect
    _assert_gpu_and_cpu_writes_are_equal(write_func, read_func, base_path, 'COLLECT', conf=conf)
../../src/main/python/asserts.py:238: in _assert_gpu_and_cpu_writes_are_equal
    with_cpu_session(lambda spark : write_func(spark, cpu_path), conf=conf)
../../src/main/python/spark_session.py:113: in with_cpu_session
    return with_spark_session(func, conf=copy)
../../src/main/python/spark_session.py:97: in with_spark_session
    ret = func(_spark)
../../src/main/python/asserts.py:238: in <lambda>
    with_cpu_session(lambda spark : write_func(spark, cpu_path), conf=conf)
../../src/main/python/orc_write_test.py:110: in <lambda>
    lambda spark, path: do_writes(spark, path),
../../src/main/python/orc_write_test.py:106: in do_writes
    df.write.mode("overwrite").partitionBy("my_partition").orc(path)
/opt/cloudera/parcels/SPARK3-3.2.1.3.2.7171000.1-1-1.p0.25570994/lib/spark3/python/lib/pyspark.zip/pyspark/sql/readwriter.py:995: in orc
    self._jwrite.orc(path)
/opt/cloudera/parcels/SPARK3-3.2.1.3.2.7171000.1-1-1.p0.25570994/lib/spark3/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py:1322: in __call__
    answer, self.gateway_client, self.target_id, self.name)
/opt/cloudera/parcels/SPARK3-3.2.1.3.2.7171000.1-1-1.p0.25570994/lib/spark3/python/lib/pyspark.zip/pyspark/sql/utils.py:111: in deco
    return f(*a, **kw)
```
