### ISSUE TITLE
[BUG] Investigate binaryop.cpp:205: Unsupported operator for these types on Databricks 11.3

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#7454]
**Describe the bug**
NDS queries 40, 47, 53, 57, 63, 80, 89 failed with
```
binaryop.cpp:205: Unsupported operator for these types
```
<details>
<summary> sample stack trace</summary>
<pre>
Job aborted due to stage failure: Task 0 in stage 3621.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3621.0 (TID 209299) (10.59.180.205 executor 23): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:333)
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$write$15(GpuFileFormatWriter.scala:246)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:169)
	at org.apache.spark.scheduler.Task.$anonfun$run$4(Task.scala:137)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:104)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:137)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:96)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:902)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1696)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:905)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:760)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ai.rapids.cudf.CudfException: CUDF failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-314-cuda11/thirdparty/cudf/cpp/src/binaryop/binaryop.cpp:205: Unsupported operator for these types
	at ai.rapids.cudf.ColumnView.binaryOpVV(Native Method)
	at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1249)
	at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1242)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:296)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:290)
	at org.apache.spark.sql.rapids.GpuSubtractBase.doColumnar(arithmetic.scala:367)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:309)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:308)
	at com.nvidia.spark.rapids.CudfBinaryOperator.doColumnar(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$3(GpuExpressions.scala:257)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
	at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:254)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
	at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
	at org.apache.spark.sql.rapids.GpuSubtract.org$apache$spark$sql$rapids$GpuAddSub$$super$columnarEval(arithmetic.scala:150)
	at org.apache.spark.sql.rapids.GpuAddSub.columnarEval(arithmetic.scala:68)
	at org.apache.spark.sql.rapids.GpuAddSub.columnarEval$(arithmetic.scala:62)
	at org.apache.spark.sql.rapids.GpuSubtract.columnarEval(arithmetic.scala:150)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
	at com.nvidia.spark.rapids.GpuUnaryExpression.columnarEval(GpuExpressions.scala:203)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
	at org.apache.spark.sql.rapids.GpuDecimalDivideBase.longDivide(arithmetic.scala:884)
	at org.apache.spark.sql.rapids.GpuDecimalDivideBase.longDivide$(arithmetic.scala:883)
	at org.apache.spark.sql.rapids.GpuDecimalDivide.longDivide(arithmetic.scala:209)
	at org.apache.spark.sql.rapids.GpuDecimalDivideBase.columnarEval(arithmetic.scala:923)
	at org.apache.spark.sql.rapids.GpuDecimalDivideBase.columnarEval$(arithmetic.scala:921)
	at org.apache.spark.sql.rapids.GpuDecimalDivide.columnarEval(arithmetic.scala:209)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
	at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEval(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:254)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
	at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
	at org.apache.spark.sql.rapids.CudfBinaryPredicateWithSideEffect.columnarEval(predicates.scala:112)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:254)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
	at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
	at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
	at org.apache.spark.sql.rapids.CudfBinaryPredicateWithSideEffect.columnarEval(predicates.scala:112)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
	at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:108)
	at com.nvidia.spark.rapids.GpuFilter$.$anonfun$apply$2(basicPhysicalOperators.scala:398)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuFilter$.withResource(basicPhysicalOperators.scala:369)
	at com.nvidia.spark.rapids.GpuFilter$.apply(basicPhysicalOperators.scala:396)
	at com.nvidia.spark.rapids.GpuFilter$.$anonfun$apply$1(basicPhysicalOperators.scala:377)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuFilter$.withResource(basicPhysicalOperators.scala:369)
	at com.nvidia.spark.rapids.GpuFilter$.apply(basicPhysicalOperators.scala:376)
	at com.nvidia.spark.rapids.GpuFilterExec.$anonfun$doExecuteColumnar$4(basicPhysicalOperators.scala:468)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$next$1(GpuExec.scala:199)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.RebaseHelper$.withResource(RebaseHelper.scala:26)
	at com.nvidia.spark.rapids.CollectTimeIterator.next(GpuExec.scala:198)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:292)
	at com.nvidia.spark.rapids.GpuTopN$$anon$2.hasNext(limit.scala:241)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.writeWithIterator(GpuFileFormatDataWriter.scala:86)
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$executeTask$1(GpuFileFormatWriter.scala:320)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1730)
	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:327)
	... 21 more
	Suppressed: com.databricks.s3a.ClosedStreamException: Filesystem WriteOperationHelper {bucket=rapidsai-databricks} closed
		at shaded.databricks.org.apache.hadoop.fs.s3a.S3ABlockOutputStream.checkOpen(S3ABlockOutputStream.java:248)
		at shaded.databricks.org.apache.hadoop.fs.s3a.S3ABlockOutputStream.write(S3ABlockOutputStream.java:299)
		at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:62)
		at java.io.DataOutputStream.write(DataOutputStream.java:107)
		at com.nvidia.spark.rapids.ColumnarOutputWriter$.$anonfun$writeBufferedData$2(ColumnarOutputWriter.scala:200)
		at com.nvidia.spark.rapids.ColumnarOutputWriter$.$anonfun$writeBufferedData$2$adapted(ColumnarOutputWriter.scala:194)
		at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
		at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
		at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
		at com.nvidia.spark.rapids.ColumnarOutputWriter$.writeBufferedData(ColumnarOutputWriter.scala:194)
		at com.nvidia.spark.rapids.ColumnarOutputWriter.writeBufferedData(ColumnarOutputWriter.scala:84)
		at com.nvidia.spark.rapids.ColumnarOutputWriter.close(ColumnarOutputWriter.scala:178)
		at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.releaseCurrentWriter(GpuFileFormatDataWriter.scala:70)
		at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.releaseResources(GpuFileFormatDataWriter.scala:81)
		at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.abort(GpuFileFormatDataWriter.scala:113)
		at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$executeTask$2(GpuFileFormatWriter.scala:324)
		at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1741)
		... 22 more
</pre>
</details>

**Steps/Code to reproduce bug**
Run NDS on Databricks with multiple worker nodes

**Expected behavior**
All queries should succeed

**Environment details (please complete the following information)**
 - Environment location: Databricks 11.3
 - Spark configuration settings related to the issue: N/A

**Additional context**
N/A

**Comment by gerashegalov** [comment]
It appears to be the bug with + and - on decimal with different precision. After adding more instrumentation  found the simplest repro not requiring  NDS
```Python
>>> spark.createDataFrame([('1.12', '2.12')], 'a STRING, b STRING').selectExpr("CAST(a AS DECIMAL(7,2)) - CAST(b AS DECIMAL(12,2)) AS C1").collect()

ai.rapids.cudf.CudfException: CUDF failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-318-cuda11/thirdparty/cudf/cpp/src/binaryop/binaryop.cpp:205: Unsupported operator for these types
```

Multiplication works:
```Python
>>> spark.createDataFrame([('1.12', '2.12')], 'a STRING, b STRING').selectExpr("CAST(a AS DECIMAL(7,2)) * CAST(b AS DECIMAL(12,2)) AS C1").collect()

[Row(C1=Decimal('2.3744'))]
```

**Comment by gerashegalov** [comment]
testing with 3.4 as of https://github.com/apache/spark/commit/bbbacfb2e971fb74b5ec1da4fd4db9652f1683d6 that still compiles with the current spark-rapids reproduces the bug as well:

**Comment by gerashegalov** [comment]
looks like the same Spark commit causing #6691 is responsible for this because the difference between 3.3.1 plan working and 3.4 not working is that we no longer apply precision promotion before sending the op to GPU
