### ISSUE TITLE
[BUG] q67 appears to run out of system memory and also GPU memory using multi-threaded shuffle in Databricks

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7496]
@mattahrens ran some NDS @ 3TB benchmarks using T4s in Databricks with 8 g4dn.2xlarge workers.

It is worth mentioning that a bigger node (g4dn.4xlarge) works. This bigger machine has 64GB of RAM, as opposed to the 32GB available to the one with the issues. When looking at the Environment tab in the Spark UI, Xmx for the executors was ~20GB, and we are using the following configs (other than to turn on the shuffle):

```
"spark.task.resource.gpu.amount": ".01",
"spark.plugins": "com.nvidia.spark.SQLPlugin",
"spark.rapids.memory.pinnedPool.size": "4G",
"spark.sql.files.maxPartitionBytes": "1G",
"spark.rapids.sql.multiThreadedRead.numThreads": "100",
"spark.rapids.sql.concurrentGpuTasks": "2"
```

So we have 5GB (4GB pinned + 1GB pageable), and that would put the process at ~25GB baseline, leaving us ~7GB free for other things, including direct byte buffers and HostMemoryBuffer instances. It seems that this was not enough.

First, a task was interrupted with the exception below:

```
23/01/10 17:13:52 ERROR TaskContextImpl: Error in TaskCompletionListener
org.apache.spark.TaskKilledException
	at org.apache.spark.TaskContextImpl.killTaskIfInterrupted(TaskContextImpl.scala:246)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:36)
	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:469)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1(GpuExec.scala:193)
	at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1$adapted(GpuExec.scala:192)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.RebaseHelper$.withResource(RebaseHelper.scala:26)
	at com.nvidia.spark.rapids.CollectTimeIterator.hasNext(GpuExec.scala:192)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:291)
	at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1(GpuExec.scala:193)
	at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$hasNext$1$adapted(GpuExec.scala:192)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.RebaseHelper$.withResource(RebaseHelper.scala:26)
	at com.nvidia.spark.rapids.CollectTimeIterator.hasNext(GpuExec.scala:192)
	at scala.collection.Iterator$$anon$22.hasNext(Iterator.scala:1089)
	at scala.collection.BufferedIterator.headOption(BufferedIterator.scala:32)
	at scala.collection.BufferedIterator.headOption$(BufferedIterator.scala:32)
	at scala.collection.Iterator$$anon$22.headOption(Iterator.scala:1076)
	at com.nvidia.spark.rapids.CloseableBufferedIterator.headOption(CloseableBufferedIterator.scala:36)
	at com.nvidia.spark.rapids.CloseableBufferedIterator.close(CloseableBufferedIterator.scala:41)
	at com.nvidia.spark.rapids.CloseableBufferedIterator.$anonfun$new$2(CloseableBufferedIterator.scala:32)
	at com.nvidia.spark.rapids.CloseableBufferedIterator.$anonfun$new$2$adapted(CloseableBufferedIterator.scala:32)
	at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:162)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1(TaskContextImpl.scala:169)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1$adapted(TaskContextImpl.scala:169)
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:224)
	at org.apache.spark.TaskContextImpl.invokeTaskCompletionListeners(TaskContextImpl.scala:169)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:162)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:166)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:95)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:832)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:835)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:690)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Then ~30 seconds later we OOM on the GPU as well (we tried to spill then oom).

I do not know why a task was interrupted, or why we kept going. It seems we need to dig a bit deeper here to figure out what could be going on in this environment, we probably want to add some heap dumps to figure out the number of HostMemoryBuffers and direct buffers that are in flight.

**Comment by tgravescs** [comment]
just a note a few things of interest:
1) CPU job fails with executors lost
2) Seeing a job failure that is really a job cancelled due to replanning on the GPU runs.  This isn't actually a failure though.  
3) with gpu run and g4dn.xlarge I do see some executors lost but doesn't fail job, just a couple task failures.  Likely possible to fail entire job like CPU did.

**Comment by abellina** [comment]
So this is still an issue where @tgravescs has seen executors killed, but it is unclear what the reason is. It requires further investigation.
