### ISSUE TITLE
[BUG] simple json_tuple test failing with cudf error

### ISSUE THREAD

**Issue by jbrennan333** [NVIDIA/spark-rapids#7574]
**Describe the bug**
Running a simple json_tuple that works on CPU causes my spark shell to hit a CUDF ERROR when I run it on the GPU:
```
23/01/24 21:50:08 ERROR Executor: Exception in task 0.0 in stage 24.0 (TID 24)
ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-pre_release-100-cuda11/thirdparty/cudf/cpp/src/strings/strings_column_view.cpp:24: strings_column_view only supports strings
	at ai.rapids.cudf.ColumnView.getJSONObject(Native Method)
	at ai.rapids.cudf.ColumnView.getJSONObject(ColumnView.java:2814)
	at com.nvidia.spark.rapids.GpuJsonTuple.$anonfun$generate$6(GpuJsonTuple.scala:73)
```
**Steps/Code to reproduce bug**
I created a 1 row df with a json string column, and tried a simple json_tuple.   It works on the CPU:
```
scala> df.printSchema
root
 |-- id: integer (nullable = false)
 |-- value: string (nullable = true)

scala> spark.conf.set("spark.rapids.sql.enabled", false)
scala> df.show(false)
+---+----------------------------------------------------------------------------+
|id |value                                                                       |
+---+----------------------------------------------------------------------------+
|1  |{"Zipcode":"abc","ZipCodeType":"STANDARD","City":"PARC PARQUE","State":"PR"}|
+---+----------------------------------------------------------------------------+

scala> df.select(col("id"),json_tuple(col("value"),"Zipcode","ZipCodeType","City","State")).show(false)
...
+---+---+--------+-----------+---+
|id |c0 |c1      |c2         |c3 |
+---+---+--------+-----------+---+
|1  |abc|STANDARD|PARC PARQUE|PR |
+---+---+--------+-----------+---+
```
It fails on the GPU:
```
scala> spark.conf.set("spark.rapids.sql.enabled", true)

scala> df.select(col("id"),json_tuple(col("value"),"Zipcode","ZipCodeType","City","State")).show(false)
23/01/24 21:50:08 WARN GpuOverrides: 
!Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
  @Partitioning <SinglePartition$> could run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> cast(id#556 as string) AS id#820 will run on GPU
      *Expression <Cast> cast(id#556 as string) will run on GPU
    *Exec <GenerateExec> will run on GPU
      *Expression <JsonTuple> json_tuple(value#557, Zipcode, ZipCodeType, City, State) will run on GPU
      ! <LocalTableScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.LocalTableScanExec
        @Expression <AttributeReference> id#556 could run on GPU
        @Expression <AttributeReference> value#557 could run on GPU
...
23/01/24 21:50:08 ERROR Executor: Exception in task 0.0 in stage 24.0 (TID 24)
ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-pre_release-100-cuda11/thirdparty/cudf/cpp/src/strings/strings_column_view.cpp:24: strings_column_view only supports strings
	at ai.rapids.cudf.ColumnView.getJSONObject(Native Method)
	at ai.rapids.cudf.ColumnView.getJSONObject(ColumnView.java:2814)
	at com.nvidia.spark.rapids.GpuJsonTuple.$anonfun$generate$6(GpuJsonTuple.scala:73)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:216)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:213)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:213)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:248)
	at com.nvidia.spark.rapids.GpuJsonTuple.$anonfun$generate$5(GpuJsonTuple.scala:73)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:46)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:44)
	at com.nvidia.spark.rapids.GpuJsonTuple.withResource(GpuJsonTuple.scala:29)
	at com.nvidia.spark.rapids.GpuJsonTuple.$anonfun$generate$2(GpuJsonTuple.scala:72)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuJsonTuple.withResource(GpuJsonTuple.scala:29)
	at com.nvidia.spark.rapids.GpuJsonTuple.generate(GpuJsonTuple.scala:61)
	at com.nvidia.spark.rapids.GpuGenerateExec.$anonfun$doGenerate$4(GpuGenerateExec.scala:747)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuGenerateExec.withResource(GpuGenerateExec.scala:658)
	at com.nvidia.spark.rapids.GpuGenerateExec.$anonfun$doGenerate$3(GpuGenerateExec.scala:745)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:496)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:241)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Expected behavior**
The GPU should produce the same results as the CPU.

**Environment details (please complete the following information)**
I ran this on my desktop system (RTX4000) in a spark-shell using this jar:
rapids-4-spark_2.12-23.02.0-20230122.152330-55-cuda11.jar

**Comment by jlowe** [comment]
@cindyyuanjiang could you look into this?

**Comment by cindyyuanjiang** [comment]
@jlowe Yes, taking a look now.

**Comment by cindyyuanjiang** [comment]
I tried the following and so far it works for me.

```
scala> spark.conf.set("spark.rapids.sql.enabled", true)

scala> df.select(col("id"),json_tuple(col("value"),"Zipcode","ZipCodeType","City","State")).show(false)
+---+---+--------+-----------+---+
|id |c0 |c1      |c2         |c3 |
+---+---+--------+-----------+---+
|1  |abc|STANDARD|PARC PARQUE|PR |
+---+---+--------+-----------+---+


scala> val data = Seq((1, "{\"Zipcode\":\"abc\",\"ZipCodeType\":\"STANDARD\",\"City\":\"PARC PARQUE\",\"State\":\"PR\"}"))
data: Seq[(Int, String)] = List((1,{"Zipcode":"abc","ZipCodeType":"STANDARD","City":"PARC PARQUE","State":"PR"}))

scala> val df = data.toDF("id", "value")
df: org.apache.spark.sql.DataFrame = [id: int, value: string]

scala> df.show(false)
+---+----------------------------------------------------------------------------+
|id |value                                                                       |
+---+----------------------------------------------------------------------------+
|1  |{"Zipcode":"abc","ZipCodeType":"STANDARD","City":"PARC PARQUE","State":"PR"}|
+---+----------------------------------------------------------------------------+


scala> spark.conf.set("spark.rapids.sql.enabled", true)

scala> df.select(col("id"),json_tuple(col("value"),"Zipcode","ZipCodeType","City","State")).show(false)
+---+---+--------+-----------+---+
|id |c0 |c1      |c2         |c3 |
+---+---+--------+-----------+---+
|1  |abc|STANDARD|PARC PARQUE|PR |
+---+---+--------+-----------+---+
```

**Comment by jbrennan333** [comment]
If I change the select to this (removed the col("id")):
```
df.select(json_tuple(col("value"),"Zipcode","ZipCodeType","City","State")).show(false)
```
I do not hit the failure.

**Comment by cindyyuanjiang** [comment]
@jbrennan333 Thank you! I found the issue was due to the json expression evaluating to the wrong column in the inputBatch. I am working on fixing this now.
