### ISSUE TITLE
[BUG] arithmetic_ops_test failed in databricks 11.3 runtime

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#7614]
**Describe the bug**
The test error is only found in db 11.3 runtime

```
[2023-01-28T11:59:43.295Z] E                   Caused by: java.lang.IllegalArgumentException: Both columns must be of the same fixed_point type

[2023-01-28T11:59:43.295Z] E                   	at ai.rapids.cudf.BinaryOperable.implicitConversion(BinaryOperable.java:84)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryExpression.outputType(GpuExpressions.scala:284)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryExpression.outputType$(GpuExpressions.scala:281)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryOperator.outputType(GpuExpressions.scala:336)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:294)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:290)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryOperator.doColumnar(GpuExpressions.scala:336)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:309)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:308)

[2023-01-28T11:59:43.295Z] E                   	at org.apache.spark.sql.rapids.GpuRemainderBase.org$apache$spark$sql$rapids$GpuDivModLike$$super$doColumnar(arithmetic.scala:1057)

[2023-01-28T11:59:43.295Z] E                   	at org.apache.spark.sql.rapids.GpuDivModLike.$anonfun$doColumnar$10(arithmetic.scala:763)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.CudfBinaryOperator.withResource(GpuExpressions.scala:336)

[2023-01-28T11:59:43.295Z] E                   	at org.apache.spark.sql.rapids.GpuDivModLike.doColumnar(arithmetic.scala:762)

[2023-01-28T11:59:43.295Z] E                   	at org.apache.spark.sql.rapids.GpuDivModLike.doColumnar$(arithmetic.scala:747)

[2023-01-28T11:59:43.295Z] E                   	at org.apache.spark.sql.rapids.GpuRemainderBase.doColumnar(arithmetic.scala:1057)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$3(GpuExpressions.scala:257)

[2023-01-28T11:59:43.295Z] E                   	at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
```

failed cases list
```
[2023-01-28T11:59:43.310Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Byte-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o234449.collec...

[2023-01-28T11:59:43.310Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Byte-Decimal(19,0)] - py4j.protocol.Py4JJavaError: An error occurred while calling o234630.collec...

[2023-01-28T11:59:43.310Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Byte-Decimal(30,10)] - py4j.protocol.Py4JJavaError: An error occurred while calling o234811.collec...

[2023-01-28T11:59:43.310Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Short-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o236782.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Short-Decimal(19,0)] - py4j.protocol.Py4JJavaError: An error occurred while calling o236963.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Short-Decimal(30,10)] - py4j.protocol.Py4JJavaError: An error occurred while calling o237144.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(6,5)] - py4j.protocol.Py4JJavaError: An error occurred while calling o238041.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(6,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o238222.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(5,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o238403.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(5,3)] - py4j.protocol.Py4JJavaError: An error occurred while calling o238584.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(4,2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o238765.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(3,-2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o238946.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(19,0)] - py4j.protocol.Py4JJavaError: An error occurred while calling o239306.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Integer-Decimal(30,10)] - py4j.protocol.Py4JJavaError: An error occurred while calling o239487.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Long-Decimal(6,5)] - py4j.protocol.Py4JJavaError: An error occurred while calling o240384.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Long-Decimal(6,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o240565.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Long-Decimal(5,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o240746.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Long-Decimal(5,3)] - py4j.protocol.Py4JJavaError: An error occurred while calling o240927.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Long-Decimal(4,2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o241108.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Long-Decimal(3,-2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o241289.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Long-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o241470.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(6,3)-Integer] - py4j.protocol.Py4JJavaError: An error occurred while calling o242367.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(6,3)-Long] - py4j.protocol.Py4JJavaError: An error occurred while calling o242548.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(6,3)-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o243803.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(6,3)-Decimal(19,0)] - py4j.protocol.Py4JJavaError: An error occurred while calling o243984.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(6,3)-Decimal(30,10)] - py4j.protocol.Py4JJavaError: An error occurred while calling o244165.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Byte] - py4j.protocol.Py4JJavaError: An error occurred while calling o244346.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Short] - py4j.protocol.Py4JJavaError: An error occurred while calling o244527.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Long] - py4j.protocol.Py4JJavaError: An error occurred while calling o244887.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(6,5)] - py4j.protocol.Py4JJavaError: An error occurred while calling o245068.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(6,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o245249.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(5,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o245430.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(5,3)] - py4j.protocol.Py4JJavaError: An error occurred while calling o245611.collec...

[2023-01-28T11:59:43.311Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(4,2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o245792.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(3,-2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o245973.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(19,0)] - py4j.protocol.Py4JJavaError: An error occurred while calling o246333.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(10,-2)-Decimal(30,10)] - py4j.protocol.Py4JJavaError: An error occurred while calling o246514.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Byte] - py4j.protocol.Py4JJavaError: An error occurred while calling o246695.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Short] - py4j.protocol.Py4JJavaError: An error occurred while calling o246876.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Long] - py4j.protocol.Py4JJavaError: An error occurred while calling o247236.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(6,5)] - py4j.protocol.Py4JJavaError: An error occurred while calling o247417.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(6,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o247598.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(5,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o247779.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(5,3)] - py4j.protocol.Py4JJavaError: An error occurred while calling o247960.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(4,2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o248141.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(3,-2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o248322.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(19,0)] - py4j.protocol.Py4JJavaError: An error occurred while calling o248682.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(15,3)-Decimal(30,10)] - py4j.protocol.Py4JJavaError: An error occurred while calling o248863.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Byte] - py4j.protocol.Py4JJavaError: An error occurred while calling o249044.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Short] - py4j.protocol.Py4JJavaError: An error occurred while calling o249225.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Integer] - py4j.protocol.Py4JJavaError: An error occurred while calling o249406.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Decimal(6,5)] - py4j.protocol.Py4JJavaError: An error occurred while calling o249766.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Decimal(6,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o249947.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Decimal(5,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o250128.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Decimal(5,3)] - py4j.protocol.Py4JJavaError: An error occurred while calling o250309.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Decimal(4,2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o250490.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Decimal(3,-2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o250671.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(30,12)-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o250852.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Integer] - py4j.protocol.Py4JJavaError: An error occurred while calling o251749.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Long] - py4j.protocol.Py4JJavaError: An error occurred while calling o251930.collec...

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Decimal(6,5)] - AssertionError: GPU and CPU decimal values are different at [1149, '(a % b)']

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Decimal(6,4)] - AssertionError: GPU and CPU decimal values are different at [137, '(a % b)']

[2023-01-28T11:59:43.312Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Decimal(5,4)] - AssertionError: GPU and CPU decimal values are different at [568, '(a % b)']

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o253185.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Decimal(19,0)] - py4j.protocol.Py4JJavaError: An error occurred while calling o253366.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(3,-3)-Decimal(30,10)] - py4j.protocol.Py4JJavaError: An error occurred while calling o253547.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Byte] - py4j.protocol.Py4JJavaError: An error occurred while calling o253728.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Short] - py4j.protocol.Py4JJavaError: An error occurred while calling o253909.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Integer] - py4j.protocol.Py4JJavaError: An error occurred while calling o254090.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Decimal(6,5)] - py4j.protocol.Py4JJavaError: An error occurred while calling o254450.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Decimal(6,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o254631.collec...

[2023-01-28T11:59:43.313Z] 2023-01-28 09:52:06 INFO     Executing global initialization tasks before test launches

[2023-01-28T11:59:43.313Z] 2023-01-28 09:52:06 INFO     Creating directory /home/ubuntu/spark-rapids/integration_tests/target/run_dir-20230128095206-a1C8/hive with permissions 0o777

[2023-01-28T11:59:43.313Z] 2023-01-28 09:52:06 INFO     Skipping findspark init because on xdist master

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Decimal(5,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o254812.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Decimal(5,3)] - py4j.protocol.Py4JJavaError: An error occurred while calling o254993.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Decimal(4,2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o255174.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Decimal(3,-2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o255355.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(27,7)-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o255536.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Byte] - py4j.protocol.Py4JJavaError: An error occurred while calling o256075.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Short] - py4j.protocol.Py4JJavaError: An error occurred while calling o256256.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Integer] - py4j.protocol.Py4JJavaError: An error occurred while calling o256437.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Decimal(6,5)] - py4j.protocol.Py4JJavaError: An error occurred while calling o256797.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Decimal(6,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o256978.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Decimal(5,4)] - py4j.protocol.Py4JJavaError: An error occurred while calling o257159.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Decimal(5,3)] - py4j.protocol.Py4JJavaError: An error occurred while calling o257340.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Decimal(4,2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o257521.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Decimal(3,-2)] - py4j.protocol.Py4JJavaError: An error occurred while calling o257702.collec...

[2023-01-28T11:59:43.313Z] FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_mixed[Decimal(20,-3)-Decimal(16,7)] - py4j.protocol.Py4JJavaError: An error occurred while calling o257883.collec...

[2023-01-28T11:59:43.313Z] = 86 failed, 15827 passed, 495 skipped, 915 xfailed, 277 xpassed, 795 warnings in 7656.16s (2:07:36) =
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**
Pass the test

**Comment by pxLi** [comment]
oops, dup of https://github.com/NVIDIA/spark-rapids/issues/7595
