### ISSUE TITLE
[BUG] GpuBroadcastNestedLoopJoinExec:  Close called too many times

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7637]
**Describe the bug**
A customers job on Databricks failed with:
`
java.lang.IllegalStateException: Close called too many times ColumnVector{rows=1, type=TIMESTAMP_MICROSECONDS, nullCount=Optional.empty, offHeap=(ID: 1517118 0)}`

The stack trace:

```
java.lang.IllegalStateException: Close called too many times ColumnVector{rows=1, type=TIMESTAMP_MICROSECONDS, nullCount=Optional.empty, offHeap=(ID: 1647243 0)}
        at ai.rapids.cudf.ColumnVector.close(ColumnVector.java:224)
        at com.nvidia.spark.rapids.GpuColumnVector.close(GpuColumnVector.java:1120)
        at org.apache.spark.sql.vectorized.ColumnarBatch.close(ColumnarBatch.java:44)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableColumn.safeClose(implicits.scala:56)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:30)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at org.apache.spark.sql.rapids.execution.GpuBroadcastNestedLoopJoinExec.withResource(GpuBroadcastNestedLoopJoinExec.scala:380)
        at org.apache.spark.sql.rapids.execution.GpuBroadcastNestedLoopJoinExec.$anonfun$doConditionalJoin$1(GpuBroadcastNestedLoopJoinExec.scala:635)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:868)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:868)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:380)

```

It looks like this might be happening after a prior stage was cancelled so a hunch might be our broadcast is getting cleaned up when it shouldn't be but need to investigate further

**Comment by abellina** [comment]
I may have a fix for this. Putting up a patch shortly, but I will need some help to test in this environment.
