### ISSUE TITLE
[BUG] GPU OOM using GpuRegExpExtract

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7640]
**Describe the bug**

User applications OOM on GpuRegExpExtract using 512M batch size.  Decreasing it to 256M works around the issue.

```
23/02/01 20:33:02 ERROR Executor: Exception in task 49.0 in stage 15.0 (TID 124)
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: RMM failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-307-cuda11/thirdparty/cudf/cpp/build/_deps/rmm-src/include/rmm/mr/device/arena_memory_resource.hpp:159: Maximum pool size exceeded
        at ai.rapids.cudf.ColumnView.extractRe(Native Method)
        at ai.rapids.cudf.ColumnView.extractRe(ColumnView.java:3272)
        at org.apache.spark.sql.rapids.GpuRegExpExtract.doColumnar(stringFunctions.scala:1302)
        at com.nvidia.spark.rapids.GpuTernaryExpression.$anonfun$columnarEval$8(GpuExpressions.scala:415)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.GpuRegExpTernaryBase.withResourceIfAllowed(stringFunctions.scala:1072)
        at com.nvidia.spark.rapids.GpuTernaryExpression.$anonfun$columnarEval$7(GpuExpressions.scala:400)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.GpuRegExpTernaryBase.withResourceIfAllowed(stringFunctions.scala:1072)

```

**Comment by NVnavkumar** [comment]
After fix from #7854, I've tested in the customer environment. Looks like the query is now working with default 512M batch size.
