### ISSUE TITLE
[BUG] Multi-threaded shuffle bails with division-by-zero ArithmeticException

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#7675]
**Describe the bug**
Shuffle integration tests (such as test_hash_grpby_sum) crash for multi-threaded shuffle  in the `local` mode (default)
   
```
WARN TaskSetManager: Lost task 3.0 in stage 89.0 (TID 256) (10.0.0.132 executor driver): java.lang.ArithmeticException: / by zero
```
<details><summary>stack trace</summary>
<pre>
	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase$.queueWriteTask(RapidsShuffleInternalManagerBase.scala:166)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$2(RapidsShuffleInternalManagerBase.scala:323)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$2$adapted(RapidsShuffleInternalManagerBase.scala:268)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.withResource(RapidsShuffleInternalManagerBase.scala:228)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$1(RapidsShuffleInternalManagerBase.scala:268)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.$anonfun$write$1$adapted(RapidsShuffleInternalManagerBase.scala:267)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.withResource(RapidsShuffleInternalManagerBase.scala:228)
	at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterBase.write(RapidsShuffleInternalManagerBase.scala:267)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
</pre>
</details>

**Steps/Code to reproduce bug**
To reproduce:
```
SPARK_HOME=~/dist/spark-3.1.1-bin-hadoop3.2 \
  PYSP_TEST_spark_rapids_shuffle_mode=MULTITHREADED \
  PYSP_TEST_spark_rapids_shuffle_multiThreaded_writer_threads=2 \
  PYSP_TEST_spark_rapids_shuffle_multiThreaded_reader_threads=2 \
  PYSP_TEST_spark_shuffle_manager=com.nvidia.spark.rapids.spark311.RapidsShuffleManager \
  PYSP_TEST_spark_rapids_memory_gpu_minAllocFraction=0 \
  PYSP_TEST_spark_rapids_memory_gpu_maxAllocFraction=0.1 \
  PYSP_TEST_spark_rapids_memory_gpu_allocFraction=0.1 \
  ./integration_tests/run_pyspark_from_build.sh -k test_hash_grpby_sum
```

The test succeeds after enabling a test standalone `local-cluster` mode  by adding NUM_LOCAL_EXECS  > 0 to the environment boiling down to using `--master local-cluster[NUM_LOCAL_EXECS,1,1024]`
Tested with values 1, 2, 4

**Expected behavior**
Tests queries should succeed 

**Environment details (please complete the following information)**
 - Environment location: Standalone, Databricks
 - Spark configuration settings related to the issue: 
 spark.rapids.shuffle.mode=MULTITHREADED, spark.master=local, etc see repro

**Additional context**
_Originally posted by @nartal1 in https://github.com/NVIDIA/spark-rapids/issues/7610#issuecomment-1414614584_

**Comment by abellina** [comment]
I worked with Niranjan to patch the local mode MT shuffle. This issue will be fixed by https://github.com/NVIDIA/spark-rapids/pull/7610.

**Comment by abellina** [comment]
https://github.com/NVIDIA/spark-rapids/pull/7610 merged, closing.
