### ISSUE TITLE
[BUG] GpuParquetScan fails with NullPointerException - Delta CDF query

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7688]
**Describe the bug**

User got the following exception using Databricks with a query using change data feed functionality.  It looks like the number of rows is > 0 but the read schema is null. This is something we didn't ever expect to happen. We handle an empty ReadSchema but not a null one. This Exec this was on was a **Scan DeltaCDFRelation**   Reference: https://docs.delta.io/2.0.0/delta-change-data-feed.html

```
Caused by: java.lang.NullPointerException
	at com.nvidia.spark.rapids.MultiFileCloudParquetPartitionReader.readBatches(GpuParquetScan.scala:2224)
	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.liftedTree1$1(GpuMultiFileReader.scala:584)
	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.readBuffersToBatch(GpuMultiFileReader.scala:583)
	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1(GpuMultiFileReader.scala:776)
	at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$next$1$adapted(GpuMultiFileReader.scala:731)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
```

Need to investigate a bit more what its doing.

**Comment by tgravescs** [comment]
closed via pr above
