### ISSUE TITLE
[BUG]IT test failure: udf_test.py::test_window_aggregate_udf

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7741]
**Describe the bug**
UCX EGX YARN integration test failed:

 FAILED integration_tests/src/main/python/udf_test.py::test_window_aggregate_udf[Lower_Upper-Integer][IGNORE_ORDER]

stack trace:
```
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                   Caused by: java.util.NoSuchElementException: Cannot locate buffers associated with ID: ShuffleBufferId(shuffle_130_27962_3,1946726)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at com.nvidia.****.rapids.RapidsBufferCatalog.$anonfun$acquireBuffer$1(RapidsBufferCatalog.scala:232)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at com.nvidia.****.rapids.RapidsBufferCatalog.acquireBuffer(RapidsBufferCatalog.scala:229)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at com.nvidia.****.rapids.RapidsBufferCatalog.com$nvidia$****$rapids$RapidsBufferCatalog$$updateUnderlyingRapidsBuffer(RapidsBufferCatalog.scala:210)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at com.nvidia.****.rapids.RapidsBufferCatalog$RapidsBufferHandleImpl.setSpillPriority(RapidsBufferCatalog.scala:77)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at com.nvidia.****.rapids.ShuffleBufferCatalog.updateSpillPriorityForLocalRead(ShuffleBufferCatalog.scala:289)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.RapidsCachingReader.$anonfun$read$5(RapidsCachingReader.scala:96)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.RapidsCachingReader.$anonfun$read$5$adapted(RapidsCachingReader.scala:96)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)^[[0m
[2023-02-10T22:15:46.473Z] ^[[1m^[[31mE                         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.RapidsCachingReader.$anonfun$read$3(RapidsCachingReader.scala:96)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.RapidsCachingReader.$anonfun$read$3$adapted(RapidsCachingReader.scala:76)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at scala.collection.immutable.List.foreach(List.scala:392)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.RapidsCachingReader.$anonfun$read$1(RapidsCachingReader.scala:76)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.RapidsCachingReader.$anonfun$read$1$adapted(RapidsCachingReader.scala:68)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at scala.collection.Iterator.foreach(Iterator.scala:941)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at scala.collection.Iterator.foreach$(Iterator.scala:941)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.RapidsCachingReader.read(RapidsCachingReader.scala:68)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at org.apache.****.sql.rapids.execution.ShuffledBatchRDD.compute(ShuffledBatchRDD.scala:152)^[[0m
[2023-02-10T22:15:46.474Z] ^[[1m^[[31mE                         at org.apache.****.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)^[[0m
```

**Comment by tgravescs** [comment]
Alessandro looked and we think the exception happened because executor OOM'd, need more investigation.
