### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7744]
We have a test that runs under Yarn with UCX (UCX-EGX-Yarn) where we run ~100 tests from our CI. The following test failed once, and then succeeded the next two attempts. It hasn't failed before, not according to the history. This is with 23.02

```
FAILED integration_tests/src/main/python/udf_test.py::test_window_aggregate_udf[Lower_Upper-Integer][IGNORE_ORDER]
```

This seems to indicate that either we are likely close to the overhead limit of 22GB. We set aside: 4GB for pinned memory, 1GB for the pageable pool (and didn't set `spark.rapids.memory.host.spillStorageSize` so our max on the host should be 5GB).

Nonetheless we are using more host memory than I anticipated here. I think it would be worth using this test to figure out what is all this host memory.

```
23/02/10 20:35:04 ERROR YarnClusterScheduler: Lost executor 1 on spark-egx-10.nvidia.com: Container killed by YARN for exceeding physical memory limits. 22.3 GB of 22 GB physical memory used. Consider boosting spark.executor.memoryOverhead.
```

The error above causes fetch failures:

```
23/02/10 20:35:04 WARN TaskSetManager: Lost task 104.0 in stage 350.0 (TID 28281) (spark-egx-02.nvidia.com executor 2): FetchFailed(BlockManagerId(1, spark-egx-10.nvidia.com, 38899, Some(rapids=62688)), shuffleId=130, mapIndex=2, mapId=27963, reduceId=104, message=
org.apache.spark.shuffle.rapids.RapidsShuffleFetchFailedException: Transfer error detected by shuffle iterator, failing task. Connection to 1 closed
	at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.next(RapidsShuffleIterator.scala:378)
	at com.nvidia.spark.rapids.shuffle.RapidsShuffleIterator.next(RapidsShuffleIterator.scala:49)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator$ConcatIterator.next(Iterator.scala:230)
	at org.apache.spark.util.CompletionIterator.next(CompletionIterator.scala:29)
	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at com.nvidia.spark.rapids.CollectTimeIterator.$anonfun$next$1(GpuExec.scala:199)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.RebaseHelper$.withResource(RebaseHelper.scala:26)
	at com.nvidia.spark.rapids.CollectTimeIterator.next(GpuExec.scala:198)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$next$1(GpuCoalesceBatches.scala:385)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.withResource(GpuCoalesceBatches.scala:237)
```

We also see this, but executor 2 didn't seem to get shot, so either that didn't get logged or it was coming, or something really bad happened. I am thinking that what we really want is a flag in the shuffle catalog that says "we have been told to shutdown, so no buffers can be accessed". This is going to be filed separately.

```
23/02/10 20:35:05 WARN TaskSetManager: Lost task 88.1 in stage 350.0 (TID 28288) (spark-egx-02.nvidia.com executor 2): java.util.NoSuchElementException: Cannot locate buffers associated with ID: ShuffleBufferId(shuffle_130_27962_88,1947246)
	at com.nvidia.spark.rapids.RapidsBufferCatalog.$anonfun$acquireBuffer$1(RapidsBufferCatalog.scala:232)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at com.nvidia.spark.rapids.RapidsBufferCatalog.acquireBuffer(RapidsBufferCatalog.scala:229)
	at com.nvidia.spark.rapids.RapidsBufferCatalog.com$nvidia$spark$rapids$RapidsBufferCatalog$$updateUnderlyingRapidsBuffer(RapidsBufferCatalog.scala:210)
	at com.nvidia.spark.rapids.RapidsBufferCatalog$RapidsBufferHandleImpl.setSpillPriority(RapidsBufferCatalog.scala:77)
	at com.nvidia.spark.rapids.ShuffleBufferCatalog.updateSpillPriorityForLocalRead(ShuffleBufferCatalog.scala:289)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$5(RapidsCachingReader.scala:96)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$5$adapted(RapidsCachingReader.scala:96)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$3(RapidsCachingReader.scala:96)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$3$adapted(RapidsCachingReader.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$1(RapidsCachingReader.scala:76)
	at org.apache.spark.sql.rapids.RapidsCachingReader.$anonfun$read$1$adapted(RapidsCachingReader.scala:68)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)
	at org.apache.spark.sql.rapids.RapidsCachingReader.read(RapidsCachingReader.scala:68)
	at org.apache.spark.sql.rapids.execution.ShuffledBatchRDD.compute(ShuffledBatchRDD.scala:152)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tgravescs** [comment]
I assume this is dup of https://github.com/NVIDIA/spark-rapids/issues/7741

**Comment by abellina** [comment]
Yeah, closed 7741 since I think this one had just a tad more info.
