### ISSUE TITLE
[BUG] Unit tests  failures in WindowFunctionSuite and CostBasedOptimizerSuite on Spark-3.4

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7755]
**Describe the bug**
Some of the  unit tests are failing in WindowFunctionSuite and CostBasedOptimizerSuite on Spark-3.4  with similar error:
```
- [Window] [RANGE] [ASC] [Long Type] *** FAILED ***
  org.apache.spark.SparkException: [INTERNAL_ERROR] The operation `dataType` is not supported.
  at org.apache.spark.SparkException$.internalError(SparkException.scala:77)
  at org.apache.spark.SparkException$.internalError(SparkException.scala:81)
  at org.apache.spark.sql.errors.QueryCompilationErrors$.dataTypeOperationUnsupportedError(QueryCompilationErrors.scala:3457)
  at org.apache.spark.sql.catalyst.expressions.WindowFrame.dataType(windowExpressions.scala:185)
  at org.apache.spark.sql.catalyst.expressions.WindowFrame.dataType$(windowExpressions.scala:185)
  at org.apache.spark.sql.catalyst.expressions.SpecifiedWindowFrame.dataType(windowExpressions.scala:196)
  at com.nvidia.spark.rapids.DataTypeMeta$.apply(RapidsMeta.scala:991)
  at com.nvidia.spark.rapids.BaseExprMeta.typeMeta(RapidsMeta.scala:1035)
  at com.nvidia.spark.rapids.ContextChecks.tagBase(TypeChecks.scala:884)
  at com.nvidia.spark.rapids.ContextChecks.tag(TypeChecks.scala:878)

```

Tests failing in **WindowFunctionSuite  -  28**
Tests failing in **CostBasedOptimizerSuite  - 1**

**Steps/Code to reproduce bug**
```
mvn clean install -pl tests -am -DskipTests
mvn test -Dbuildver=340  -pl tests -Dsuites='com.nvidia.spark.rapids.WindowFunctionSuite'

mvn test -Dbuildver=340  -pl tests -Dsuites='com.nvidia.spark.rapids.CostBasedOptimizerSuite '

```
**Expected behavior**
All tests in above test suite should pass

**Comment by nartal1** [comment]
All tests in WindowFunctionSuite and CostBasedOptimizerSuite on latest Spark-3.4 now. Closing  this issue
