### ISSUE TITLE
[BUG] Unit tests failure in AnsiCastOpSuite on Spark-3.4

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7757]
**Describe the bug**
Couple of tests are failing in AnsiCastOpSuite  on Spark-3.4 with below error:

```
- Copy ints to long *** FAILED ***
  java.lang.IllegalStateException: Expected 1 ansi_cast expressions, found 0
  at com.nvidia.spark.rapids.AnsiCastOpSuite.assertContainsAnsiCast(AnsiCastOpSuite.scala:895)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.doTableCopy(AnsiCastOpSuite.scala:771)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.$anonfun$new$179(AnsiCastOpSuite.scala:730)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect(SparkQueryCompareTestSuite.scala:492)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect$(SparkQueryCompareTestSuite.scala:488)
  at com.nvidia.spark.rapids.GpuExpressionTestSuite.collect(GpuExpressionTestSuite.scala:21)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.$anonfun$runOnCpuAndGpu$1(SparkQueryCompareTestSuite.scala:424)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:135)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession$(SparkQueryCompareTestSuite.scala:193)
  ...
- Copy long to float *** FAILED ***
  java.lang.IllegalStateException: Expected 1 ansi_cast expressions, found 0
  at com.nvidia.spark.rapids.AnsiCastOpSuite.assertContainsAnsiCast(AnsiCastOpSuite.scala:895)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.doTableCopy(AnsiCastOpSuite.scala:771)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.$anonfun$new$180(AnsiCastOpSuite.scala:734)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect(SparkQueryCompareTestSuite.scala:492)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect$(SparkQueryCompareTestSuite.scala:488)
  at com.nvidia.spark.rapids.GpuExpressionTestSuite.collect(GpuExpressionTestSuite.scala:21)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.$anonfun$runOnCpuAndGpu$1(SparkQueryCompareTestSuite.scala:424)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:135)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession$(SparkQueryCompareTestSuite.scala:193)
  ...

```

**Steps/Code to reproduce bug**
```
mvn clean install -pl tests -am -DskipTests
mvn test -Dbuildver=340  -pl tests -Dsuites='com.nvidia.spark.rapids.AnsiCastOpSuite '
```
**Expected behavior**
All tests should pass in AnsiCastOpSuite

**Comment by andygrove** [comment]
Running against 3.3.0 produces this plan:

```
CommandResult <empty>
   +- GpuColumnarToRow false
      +- Execute GpuInsertIntoHadoopFsRelationCommand ......
         +- GpuProject [cast(c0#1709 as int) AS c0#1723], true
            +- GpuShuffleCoalesce 2147483647
               +- GpuColumnarExchange gpusinglepartitioning$(), REPARTITION_BY_NUM, [id=#11615]
                  +- GpuRowToColumnar targetsize(2147483647)
                     +- LocalTableScan [c0#1709]
```                     

The test is looking for the projection with the `cast`.

In 3.4.0 we see this plan:

```
CommandResult <empty>
   +- Execute InsertIntoHadoopFsRelationCommand .....
      +- WriteFiles
         +- Exchange SinglePartition, REPARTITION_BY_NUM, [plan_id=12271]
            +- LocalTableScan [c0#1685]
```

There is no cast here. Also, the query is not running on GPU.

**Comment by andygrove** [comment]
I am +1 for moving more of these tests to Python. I will try that out for this issue,
