### ISSUE TITLE
[Spark-Rapids][Out of Memory]

### ISSUE THREAD

**Issue by obaid1922** [NVIDIA/spark-rapids#7774]
I am using spark-rapids in my spark application. My dataset consists of around 175 columns. I am getting an "Out of Memory" error whenever I increase the dataset size above 500000 rows. My cluster consists of 2 executor nodes with one Tesla T4 each. I am quite new to rapids. I require some guidance regarding what configurations could be useful to mitigate this issue.

**Comment by revans2** [comment]
I don't think we have enough information to be able to answer your question right now.

There are a number of reasons that you could run out of memory, and a lot of that can depend on where the OOM happened, configuration settings, and some times details of your query.  If you don't feel comfortable sharing those publicly you can send things to [spark-rapids-support@nvidia.com](mailto:spark-rapids-support@nvidia.com).

So first off what version of Spark and what version of the plugin are you using? This can help us know if fixes have gone in that could help you with your issue.

Second if you can share a stack trace with us we can hopefully help to understand what is happening.

The following are a few common causes that we have seen with OOMs.

We often see issues when reading compressed columnar data (parquet and ORC). In some cases the amount of data produced does not correspond to the amount of data read from disk. If you tend to see the OOM happen inside the parquet or ORC reader you can try to adjust [spark.sql.files.maxPartitionBytes](https://spark.apache.org/docs/latest/sql-performance-tuning.html#other-configuration-options) or [spark.rapids.sql.reader.batchSizeRows](https://nvidia.github.io/spark-rapids/docs/configs.html#sql.reader.batchSizeRows).  This only works up to a single row group in parquet or stripe in ORC.  In some newer versions of the plugin we have a chunked reader for parquet that can break apart a single batch.

There are some skewed joins that can cause OOMs because our current join implementation requires the entire build side to be in GPU memory at once. If you are seeing OOM errors while trying to do a join. You can try to increase your shuffle partitions. We are working on a fix for this, but it is not done yet.

If you are seeing OOM errors in window operations this can happen with very large windows. Spark on the CPU requires an entire window to be held in memory while performing the operations. For many cases we also require this, but CPU memory size is usually larger than GPU memory size. Especially for a T4 that only has 16 GiB of memory. There are optimizations that we can do for window operations, but they have not been a high priority until a customer starts to run into them.

If it is for other operators you can often try to adjust your target batch size https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#columnar-batch-size and your GPU concurrency https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#number-of-tasks-per-executor

**Comment by obaid1922** [comment]
Thank you so much for the response.
I am using spark 3.1.1 and rapids 22.06. I am using following configurations:

--conf spark.kubernetes.executor.request.cores=2
--conf spark.executor.cores=2
--conf spark.executor.instances=2 
--conf spark.executor.memory=250G 
--conf spark.scheduler.mode=FAIR 
--conf spark.scheduler.allocation.file=/opt/spark/bin/fair_example.xml 
--conf spark.dynamicAllocation.enabled=false 
--conf spark.executor.heartbeatInterval=3600s 
--conf spark.network.timeout=36000s 
--conf spark.sql.broadcastTimeout=36000 
--conf spark.driver.memory=70G 
--conf spark.kubernetes.namespace=default 
--conf spark.driver.maxResultSize=150g 
--conf spark.kubernetes.container.image.pullPolicy=Always 
--conf spark.pyspark.driver.python=python3.8 
--conf spark.pyspark.python=python3.8 
--conf spark.kubernetes.authenticate.driver.serviceAccountName=spark 
--conf spark.kubernetes.container.image=itopscm/fraud_engine:rapid_212 
--conf spark.kubernetes.driver.label.driver=driver 
--conf spark.kubernetes.spec.driver.dnsConfig=default-subdomain  
--conf spark.kubernetes.driverEnv.env_server=QA 
--conf spark.executorEnv.env_server=QA 
--conf spark.sql.adaptive.enabled=false 
--conf spark.executor.extraJavaOptions=-Duser.timezone=UTC 
--conf spark.driver.extraJavaOptions=-Duser.timezone=UTC 
--conf spark.plugins=com.nvidia.spark.SQLPlugin 
--conf spark.kubernetes.executor.podTemplateFile=/tmp/templates/gpu-template.yaml 
--conf spark.sql.cache.serializer=com.nvidia.spark.ParquetCachedBatchSerializer 
--conf spark.executor.resource.gpu.amount=1 
--conf spark.task.resource.gpu.amount=0.5
--conf spark.rapids.sql.concurrentGpuTasks=2 
--conf spark.executor.resource.gpu.vendor=nvidia.com 
--conf spark.rapids.memory.gpu.oomDumpDir=/y/mcpdata 
--conf spark.rapids.memory.pinnedPool.size=20g 
--conf spark.executor.memoryOverhead=4g 
--conf spark.executor.resource.gpu.discoveryScript=/getGpusResources.sh

and here is the traceback:

[2023-02-16 14:11:47,548] [INFO] [CacheDataReaderImpl:get-28] - Going to fetch data from cache for node_id: preprocess_op_config_params instance id: FMI key_value: preprocess_op_id|8|
[2023-02-16 14:11:47,548] [INFO] [PreprocessingHandlerImpl:preprocess-188] - Going to perform preprocess op: 8 for attribute id : 515 for model code : 5422
[2023-02-16 14:11:47,549] [DEBUG] [CacheIntermediateDataHandler:perform_preprocessing_operation-24] - Function: caching intermediate results, Class: CacheIntermediateDataHandler
2023-02-16 14:11:47 WARN  WindowExec:69 - No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
2023-02-16 14:11:48 WARN  DAGScheduler:69 - Broadcasting large task binary with size 1651.4 KiB
2023-02-16 14:12:06 WARN  DAGScheduler:69 - Broadcasting large task binary with size 1690.3 KiB
2023-02-16 14:16:06 WARN  TaskSetManager:69 - Lost task 0.0 in stage 348.0 (TID 15381) (10.84.179.9 executor 2): java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: RMM failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni-release-1-cuda11/thirdparty/cudf/cpp/build/_deps/rmm-src/include/rmm/mr/device/limiting_resource_adaptor.hpp:143: Exceeded memory limit
	at ai.rapids.cudf.Table.merge(Native Method)
	at ai.rapids.cudf.Table.merge(Table.java:1931)
	at com.nvidia.spark.rapids.GpuSorter.$anonfun$mergeSort$2(SortUtils.scala:254)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:64)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:62)
	at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:66)
	at com.nvidia.spark.rapids.GpuSorter.$anonfun$mergeSort$1(SortUtils.scala:240)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:66)
	at com.nvidia.spark.rapids.GpuSorter.mergeSort(SortUtils.scala:236)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.$anonfun$mergeSortEnoughToOutput$2(GpuSortExec.scala:429)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:64)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:62)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.withResource(GpuSortExec.scala:234)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.$anonfun$mergeSortEnoughToOutput$1(GpuSortExec.scala:419)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:64)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:62)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.withResource(GpuSortExec.scala:234)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.mergeSortEnoughToOutput(GpuSortExec.scala:412)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.$anonfun$next$3(GpuSortExec.scala:519)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.withResource(GpuSortExec.scala:234)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.next(GpuSortExec.scala:518)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.next(GpuSortExec.scala:234)
	at com.nvidia.spark.rapids.GpuRunningWindowIterator.cacheBatchIfNeeded(GpuWindowExec.scala:1306)
	at com.nvidia.spark.rapids.GpuRunningWindowIterator.hasNext(GpuWindowExec.scala:1326)
	at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.hasNext(GpuSortExec.scala:261)
	at com.nvidia.spark.rapids.GpuKeyBatchingIterator.hasNext(GpuKeyBatchingIterator.scala:59)
	at com.nvidia.spark.rapids.GpuWindowIterator.hasNext(GpuWindowExec.scala:1090)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1423)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1350)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1414)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1237)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:384)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:335)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by revans2** [comment]
Sorry about the slow response. I have been heads down on a few other OOM issues that we have been trying to come up with a better general purpose solutions to deal with them.

This is the first time that I am seeing an OOM on sort after we put in the out of core sort algorithm.  T4s have 16 GiB of memory, you are running with 2 concurrent tasks, and the default target batch size is 2 GiB.  That means each of the tasks should have access to the full 8 GiB of memory and have up to 4 batches in flight at any one point in time. But sort itself is not using a crazy amount of memory.  It will sort the input batch (a little over 2x the input batch size because we need to hold the input, output and the order we want the output to be in).  Then we close the input and split it into fairly evenly sized chunks. This should be 2x the input batch size because we need to hold the sorted input and the data split into smaller batches.  Those smaller batches are then stored away so that they can be spilled to host memory or even disk.  Once all of the input data has been processed, then the algorithm will start to take some of those smaller chunks and merge sort them together. This is where the OOM happened.  That merge sort should be similar to the original sort that we did. 2x the target batch size. In this case 2 GiB. So it should be taking 4 GiB at most. The only thing that I can think of is that we some how have a fragmentation problem or there is a bug in the code that we have missed.

Please try to reduce your target batch size to 1 GiB.  `spark.rapids.sql.batchSizeBytes=1g`  Hopefully this will reduce the memory pressure you are seeing without impacting performance too much.

**Comment by mattahrens** [comment]
Please let us know if you have any other questions.  Closing for now.
