### ISSUE TITLE
[BUG] Parquet chunked reader size of output exceeds column size limit

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7796]
**Describe the bug**

User job seeing the following. 

```
ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-346-cuda11/thirdparty/cudf/cpp/include/cudf/detail/sizes_to_offsets_iterator.cuh:318: Size of output exceeds column size limit
	at ai.rapids.cudf.ParquetChunkedReader.readChunk(Native Method)
	at ai.rapids.cudf.ParquetChunkedReader.readChunk(ParquetChunkedReader.java:111)
	at com.nvidia.spark.rapids.ParquetTableReader.$anonfun$next$1(GpuParquetScan.scala:2400)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.ParquetTableReader.withResource(GpuParquetScan.scala:2376)
```

**Comment by ttnghia** [comment]
CC @nvdbaranec.

**Comment by nvdbaranec** [comment]
I have this repro'd locally.
