### ISSUE TITLE
[BUG] Subquery broadcast issue on Databricks

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7805]
**Describe the bug**
Customer query on databricks 10.4 failed with the following stack trace.  Looking at the actual plan it looks like we possibly changed a subquery broadcast into a GPU version but then didn't remove the CPU equivalent subquery broadcast, which ending up running and results in this exception.

```
	at scala.Predef$.assert(Predef.scala:208)
	at org.apache.spark.sql.execution.FileSourceScanExec.doExecute(DataSourceScanExec.scala:986)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:226)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:270)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:266)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:222)
	at org.apache.spark.sql.execution.FilterExec.doExecute(basicPhysicalOperators.scala:361)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:226)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:270)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:266)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:222)
	at org.apache.spark.sql.execution.ProjectExec.doExecute(basicPhysicalOperators.scala:86)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:226)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execuQuery$1(SparkPlan.scala:270)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:266)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:222)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:78)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:87)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)
	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)
	at org.apache.spark.sql.execution.ResultCacheManager.collectResult$1(ResultCacheManager.scala:575)
	at org.apache.spark.sql.execution.ResultCacheManager.computeResult(ResultCacheManager.scala:582)
	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:528)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:527)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:424)
	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:403)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:424)
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec.$anonfun$relationFuture$1(BroadcastExchangeExec.scala:146)
```

**Comment by tgravescs** [comment]
![Screenshot from 2023-02-22 15-38-38](https://user-images.githubusercontent.com/4563792/220765191-93ef4aff-d26d-42ba-ab39-b946bb540d29.png)

**Comment by tgravescs** [comment]
this was using a 22.10 release version, I tested this with latest 23.04 snapshot and it appears fixed.  I'll test a few more jobs to make sure and then close this
