### ISSUE TITLE
[BUG] Issue reading parquet: child columns must have the same number of rows as the Struct column

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7837]
This was seen by a customer. Posting to document for now, and will update with more info when we get it.

```
cudf/cpp/src/structs/structs_column_factories.cu:40: Child columns must have the same number of rows as the Struct column.
  at ai.rapids.cudf.ParquetChunkedReader.readChunk(Native Method)
  at ai.rapids.cudf.ParquetChunkedReader.readChunk(ParquetChunkedReader.java:111)
  at com.nvidia.spark.rapids.ParquetTableReader.$anonfun$next$1(GpuParquetScan.scala:2396)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.ParquetTableReader.withResource(GpuParquetScan.scala:2372)
  at com.nvidia.spark.rapids.ParquetTableReader.next(GpuParquetScan.scala:2395)
  at com.nvidia.spark.rapids.ParquetTableReader.next(GpuParquetScan.scala:2372)
  at com.nvidia.spark.rapids.CachedGpuBatchIterator$.$anonfun$apply$1(GpuDataProducer.scala:163)
  at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  at com.nvidia.spark.rapids.CachedGpuBatchIterator$.withResource(GpuDataProducer.scala:146)
  at com.nvidia.spark.rapids.CachedGpuBatchIterator$.apply(GpuDataProducer.scala:160)
  at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$1(GpuMultiFileReader.scala:1146)
```

**Comment by abellina** [comment]
We believe this is already addressed by: https://github.com/rapidsai/cudf/pull/12698

**Comment by abellina** [comment]
The error is no longer present in 23.04, closing this.
