### ISSUE TITLE
[BUG] require minimum xdist version or inline xdist.is_xdist_worker

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#7875]
**Describe the bug**
The code detecting whether the test is running in an xdist worker can fails with the older xdist versions

```bash
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/user/miniconda3/lib/python3.9/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/user/miniconda3/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/user/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/user/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/user/miniconda3/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/user/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/user/gits/NVIDIA/spark-rapids/integration_tests/src/main/python/spark_init_internal.py", line 102, in pytest_sessionstart
INTERNALERROR>     if not running_with_xdist(session, is_worker=True):
INTERNALERROR>   File "/home/user/gits/NVIDIA/spark-rapids/integration_tests/src/main/python/spark_init_internal.py", line 71, in running_with_xdist
INTERNALERROR>     return xdist.is_xdist_worker(session) if is_worker\
INTERNALERROR> AttributeError: module 'xdist' has no attribute 'is_xdist_worker'
```

**Steps/Code to reproduce bug**
Run any integration test with xdist prior to version 2.0.0 https://github.com/pytest-dev/pytest-xdist/commit/ba8398478e66b6f2897ad10857e61064a7f2ed56

**Expected behavior**
It should just work :) Probably not worth it imposing version constraints because of this simple method, thus, we could inline its definition because it's a simple syntactic sugar 

**Environment details (please complete the following information)**
 wherever

**Additional context**
Broken by 
https://github.com/NVIDIA/spark-rapids/pull/6358/files#diff-a23faf040f93cb83b21faa5ed0dec137a638de89ee1a8c4bdeae5f575d2cf01dR70

**Comment by gerashegalov** [comment]
consider closing as at least it's now documented in #7884
