### ISSUE TITLE
[BUG] Issue when loading spark-rapids plugin

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids#8008]
When loading the spark-rapids plugin using the provided jar (https://nvidia.github.io/spark-rapids/docs/download.html#download-v23020) and provided command (https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#local-mode), I encountered this issue:
```
spark-shell \
       --master local \
       --num-executors 1 \
       --conf spark.executor.cores=1 \
       --conf spark.rapids.sql.concurrentGpuTasks=1 \
       --driver-memory 10g \
       --conf spark.rapids.memory.pinnedPool.size=2G \
       --conf spark.sql.files.maxPartitionBytes=512m \
       --conf spark.plugins=com.nvidia.spark.SQLPlugin \
       --jars ${SPARK_RAPIDS_PLUGIN_JAR}

23/04/03 17:13:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/04/03 17:13:16 WARN RapidsPluginUtils: RAPIDS Accelerator 23.02.0 using cudf 23.02.0.
23/04/03 17:13:16 WARN RapidsPluginUtils: spark.rapids.sql.multiThreadedRead.numThreads is set to 20.
23/04/03 17:13:16 WARN RapidsPluginUtils: RAPIDS Accelerator is enabled, to disable GPU support set `spark.rapids.sql.enabled` to false.
23/04/03 17:13:16 WARN RapidsPluginUtils: spark.rapids.sql.explain is set to `NOT_ON_GPU`. Set it to 'NONE' to suppress the diagnostics logging about the query placement on the GPU.
23/04/03 17:13:31 ERROR Inbox: Ignoring error
java.lang.NullPointerException
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:524)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:116)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
23/04/03 17:13:31 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:103)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:87)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:78)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:589)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1000)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:212)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1996)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:524)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:116)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

The pair of 
```
Executor: Issue communicating with driver in heartbeater
```
and
```
Caused by: java.lang.NullPointerException
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:524)
```
repeats forever.

Note that without loading the plugin (i.e., without specifying `--conf spark.plugins=com.nvidia.spark.SQLPlugin`) then I didn't have any issue with running `spark-shell`.

**Comment by ttnghia** [comment]
I restarted the machine and the issue is gone. The issue occurs after I tried to load the plugin with async allocator, which should fail to initialize on a machine with vGPU.

So probably after failed to initialize, the cuda driver is hung up and prevents any subsequent initialization. I guess this is related to:
 * https://github.com/NVIDIA/spark-rapids/issues/7834.

**Comment by tgravescs** [comment]
There was likely a failure with executor coming up, if you don't know that error and can't reproduce there is nothing else to do. Sometimes local mode doesn't log everything and it easier to see errors on a standalone type setup.  Since nothing further for us to take action on closing this.

**Comment by willianzhong007** [comment]
I ran into the same issue, but it seems to not affect the use of RAPIDS acceleration for Spark. But I don't know why? @tgravescs @mattahrens @ttnghia 
my envs have 6*T4 GPU, I got the error：

export CUDA_VISIBLE_DEVICES=0
spark-shell \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.master=local[*] \
  --conf spark.driver.host=127.0.0.1 \
  --conf spark.driver.bindAddress=127.0.0.1 \
  --conf spark.logConf=true \
  --conf spark.rapids.sql.debug=true \
  --jars /opt/spark-3.4.1-bin-hadoop3/jars/rapids-4-spark_2.12-25.08.0.jar 

<img width="1615" height="825" alt="Image" src="https://github.com/user-attachments/assets/fae4f98f-f360-43e6-814b-ff1db5dbfdf4" />

<img width="1045" height="870" alt="Image" src="https://github.com/user-attachments/assets/09561ffe-2b75-43ee-ac16-6674fb993506" />
