### ISSUE TITLE
[BUG] Integration tests against JDK17 FAILED on "cannot access class sun.nio.ch.DirectBuffer"

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#8056]
**Describe the bug**

Install Java JDK17 and run integration tests against JDK17, got below error:

Note : JDK17 Java runtime requires maven 3.8+ if build spark-rapids jar(mvn package) or download dependency jars via mvn CLI (mvn dependency:get rapids-4-spark_2.12:23.06.0-SNAPSHOT) 

```
--> java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

--------------------------------------------------------------------------------------------------------------------------------
--> export PLUGIN_VER=${1:-'23.06.0-SNAPSHOT'}
--> export SPARK_VER=${2:-'3.2.0'}
--> export SPARK_SHIM=spark${SPARK_VER//./}
--> # Download spark-rapids jars and spark binaries.
--> LOCAL_JAR_PATH=`pwd` SPARK_HOME=$SPARK_HOME bash integration_tests/run_pyspark_from_build.sh

INTERNALERROR> E               File "/test/spark-3.2.0-bin-hadoop3.2/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 326, in get_return_value
INTERNALERROR> E                 raise Py4JJavaError(
INTERNALERROR> E             py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
INTERNALERROR> E             : java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x336eb6ed) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x336eb6ed
INTERNALERROR> E                at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:213)
INTERNALERROR> E                at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
INTERNALERROR> E                at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:110)
INTERNALERROR> E                at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:348)
INTERNALERROR> E                at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:287)
INTERNALERROR> E                at org.apache.spark.SparkEnv$.create(SparkEnv.scala:336)
INTERNALERROR> E                at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:191)
INTERNALERROR> E                at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
INTERNALERROR> E                at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
INTERNALERROR> E                at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
INTERNALERROR> E                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INTERNALERROR> E                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
INTERNALERROR> E                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

**Comment by revans2** [comment]
Spark 3.2 does not support JDK 17.  It looks like 3.3.0+ does support JDK 17.

**Comment by gerashegalov** [comment]
More recent versions of Spark may do it automatically in the submit but we should be able to work it around by adding conditionally based on JDK version to extraJavaOptions for any versions

https://github.com/apache/spark/blob/30029c90c77ca1ddbedc4e692fdaa7b66b0c43c3/pom.xml#L309-L325

**Comment by NvTimLiu** [comment]
Close as we will run JDK17 with  spark-3.3.0+
