### ISSUE TITLE
[BUG] test_parquet_read_nano_as_longs_31x failed on Dataproc

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8074]
test_parquet_read_nano_as_longs_31x failed in the Dataproc nightly test with:
```
[2023-04-11T17:58:30.590Z] E                   Caused by: java.lang.AssertionError: Type conversion is not allowed from Table{columns=[ColumnVector{rows=3, type=INT64, nullCount=Optional.empty, offHeap=(ID: 200365 7fee00811c40)}, ColumnVector{rows=3, type=STRING, nullCount=Optional.empty, offHeap=(ID: 200366 7fee006c2620)}, ColumnVector{rows=3, type=TIMESTAMP_MICROSECONDS, nullCount=Optional.empty, offHeap=(ID: 200367 7fee0013e580)}], cudfTable=140660195200544, rows=3} to [LongType, StringType, LongType] columns 0 to 3
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:789)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:670)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.CachedGpuBatchIterator$.$anonfun$apply$2(GpuDataProducer.scala:163)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:87)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:85)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.CachedGpuBatchIterator$.closeOnExcept(GpuDataProducer.scala:146)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.CachedGpuBatchIterator$.$anonfun$apply$1(GpuDataProducer.scala:160)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.CachedGpuBatchIterator$.withResource(GpuDataProducer.scala:146)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.CachedGpuBatchIterator$.apply(GpuDataProducer.scala:157)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$4(GpuMultiFileReader.scala:1169)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.next(RmmRapidsRetryIterator.scala:425)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:531)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:460)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.drainSingleWithVerification(RmmRapidsRetryIterator.scala:274)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$.withRetryNoSplit(RmmRapidsRetryIterator.scala:127)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$1(GpuMultiFileReader.scala:1162)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:375)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.readBatch(GpuMultiFileReader.scala:1136)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.next(GpuMultiFileReader.scala:1121)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:469)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:255)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:197)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:254)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:227)
[2023-04-11T17:58:30.590Z] E                   	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:271)
[2023-04-11T17:58:30.590Z] E                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:505)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2023-04-11T17:58:30.590Z] E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:508)
[2023-04-11T17:58:30.590Z] E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-04-11T17:58:30.590Z] E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-04-11T17:58:30.590Z] E                   	... 1 more
```

**Comment by andygrove** [comment]
This test is now being skipped on dataproc, so closing this issue.

```
[2023-04-14T15:07:34.171Z] ../../src/main/python/parquet_test.py::test_parquet_read_nano_as_longs_31x[INJECT_OOM] SKIPPED [ 85%]
```

There is a follow-on issue https://github.com/NVIDIA/spark-rapids/issues/8086 to discuss supporting this in the future on dataproc.
