### ISSUE TITLE
[BUG] Arithmetic_ops_test failure for Spark 3.4

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#8160]
**Describe the bug**
When running arithmetic_ops_test, there are 3 tests that are failing 

```
FAILED ../../src/main/python/arithmetic_ops_test.py::test_cast_neg_to_decimal_err - pyspark.errors.exceptions.captured.ArithmeticExce...
FAILED ../../src/main/python/arithmetic_ops_test.py::test_div_by_zero_ansi[1/0] - pyspark.errors.exceptions.captured.ArithmeticExcept...
FAILED ../../src/main/python/arithmetic_ops_test.py::test_div_overflow_exception_when_ansi[true-CAST(-9223372036854775808L as LONG) DIV -1][INJECT_OOM]

```

**Steps/Code to reproduce bug**
Run integration tests for failing tests
```
cd $SPARK_RAPIDS_HOME/integration_tests/
./run_pyspark_from_build.sh -k test_cast_neg_to_decimal_err
```

**Comment by jlowe** [comment]
-12 cannot be represented as decimal(7, 7), since that decimal can only represent values -1 < x < 1.  I get a similar exception on Spark 3.2.1 as well:
```
$ ~/src/spark321/bin/pyspark --conf spark.sql.ansi.enabled=true
Python 3.9.1 (default, Dec 11 2020, 14:32:07) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
23/04/26 10:31:32 WARN Utils: Your hostname, jlowe-ldt resolves to a loopback address: 127.0.1.1; using 10.28.9.126 instead (on interface eno1)
23/04/26 10:31:32 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/04/26 10:31:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
23/04/26 10:31:36 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.2.1
      /_/

Using Python version 3.9.1 (default, Dec 11 2020 14:32:07)
Spark context Web UI available at http://10.28.9.126:4041
Spark context available as 'sc' (master = local[*], app id = local-1682523096560).
SparkSession available as 'spark'.
>>> spark.sql("select cast(-12 as decimal(7, 7))").collect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlowe/src/spark321/python/pyspark/sql/dataframe.py", line 693, in collect
    sock_info = self._jdf.collectToPython()
  File "/home/jlowe/src/spark321/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/home/jlowe/src/spark321/python/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/home/jlowe/src/spark321/python/lib/py4j-0.10.9.3-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o33.collectToPython.
: java.lang.ArithmeticException: Decimal(compact,-120000000,20,0}) cannot be represented as Decimal(7, 7).
	at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotChangeDecimalPrecisionError(QueryExecutionErrors.scala:97)
	at org.apache.spark.sql.catalyst.expressions.CastBase.changePrecision(Cast.scala:744)
	at org.apache.spark.sql.catalyst.expressions.CastBase.$anonfun$castToDecimal$12(Cast.scala:777)
	at org.apache.spark.sql.catalyst.expressions.CastBase.nullSafeEval(Cast.scala:923)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:481)
```

**Comment by razajafri** [comment]
You can see in Spark-3.2.1 as you have shown, you are getting a Py4JJavaError but if you do the same thing in Spark-3.4.0 you will not get the same exception.

```
$ bin/pyspark 
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
23/04/26 09:01:19 WARN Utils: Your hostname, raza-linux-2 resolves to a loopback address: 127.0.1.1; using 192.168.1.78 instead (on interface enp13s0)
23/04/26 09:01:19 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/04/26 09:01:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.4.0
      /_/

Using Python version 3.8.10 (default, May 11 2021 07:01:05)
Spark context Web UI available at http://192.168.1.78:4040
Spark context available as 'sc' (master = local[*], app id = local-1682524881638).
SparkSession available as 'spark'.
>>> spark.conf.set('spark.sql.ansi.enabled', 'true')
>>> spark.sql("select cast(-12 as decimal(7, 7))").collect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rjafri/spark-3.4.0-bin-hadoop3/python/pyspark/sql/dataframe.py", line 1216, in collect
    sock_info = self._jdf.collectToPython()
  File "/home/rjafri/spark-3.4.0-bin-hadoop3/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/home/rjafri/spark-3.4.0-bin-hadoop3/python/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ArithmeticException: [NUMERIC_VALUE_OUT_OF_RANGE] -12 cannot be represented as Decimal(7, 7). If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error, and return NULL instead.
== SQL(line 1, position 8) ==
select cast(-12 as decimal(7, 7))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by razajafri** [comment]
OK, so this is a change in Spark that was introduced to avoid throwing `Py4JJavaError` as part of [this](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-42911?filter=allissues). 

This means that we will see more of these types of errors in the future as Spark is moving away from throwing a generic `Py4JJavaError` to a more Spark exception, similar to how they are moving away from throwing generic Java exceptions and wrapping them in their own versions

**Comment by jlowe** [comment]
Yes, we should have the tests special-case for this new exception path/type.  Would be awesome if we could do this generically through the existing assert error methods so it "just works" regardless of how Spark wants to throw the exception.  If not, then we can add an assert utility for pyspark exceptions separate from the py4j error exception assert.
