### ISSUE TITLE
[AUDIT][SPARK-38324][SQL] The second range is not [0, 59] in the day time ANSI interval

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#8206]
Spark added error checking in ansi mode when the minutes in `day(hour, minute)` are out of range:

> Throw an error when the second value in day(hour, minute) to second interval out of range [0, 59]

https://github.com/apache/spark/pull/40033

Since we have `GpuIntervalUtils` this looks like something we may need to adapt to.

**Comment by razajafri** [comment]
I can't find a way for us to use this function 

```
scala> val df = Seq("10 01:01:39", "10 01:49:01").toDF
df: org.apache.spark.sql.DataFrame = [value: string]

scala> df.printSchema
root
 |-- value: string (nullable = true)


scala> df.selectExpr("""interval value day to second""").show
org.apache.spark.sql.catalyst.parser.ParseException:
mismatched input 'day' expecting {<EOF>, '-'}(line 1, pos 15)

== SQL ==
interval value day to second
---------------^^^

  at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:255)
  at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:124)
  at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:49)
  at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseExpression(ParseDriver.scala:43)
  at org.apache.spark.sql.Dataset.$anonfun$selectExpr$1(Dataset.scala:1497)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
  at scala.collection.TraversableLike.map(TraversableLike.scala:238)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at org.apache.spark.sql.Dataset.selectExpr(Dataset.scala:1496)
  ... 47 elided

```

**Comment by revans2** [comment]
```
df.selectExpr("cast(value as INTERVAL day to second) as i")
```

If you look at what code is calling into our GpuIntervalUtils it is cast and CSV parsing. There may be more too, but that is all I traced out easily.

**Comment by andygrove** [comment]
Here is some code to test this issue:

```scala
val df = Seq("10 01:01:99", "10 01:49:01").toDF.repartition(2)
df.createOrReplaceTempView("t")
spark.sql("SELECT CAST(value AS INTERVAL DAY TO SECOND) from t;").show()
```

When running against Spark 3.4.1 with the plugin, it fails with:

```
Caused by: java.lang.IllegalArgumentException: Cast string to day time interval failed, may be the format is invalid, range check failed or overflow
  at com.nvidia.spark.rapids.shims.GpuIntervalUtils$.$anonfun$castStringToDayTimeIntervalWithThrow$1(GpuIntervalUtils.scala:167)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
  at com.nvidia.spark.rapids.shims.GpuIntervalUtils$.castStringToDayTimeIntervalWithThrow(GpuIntervalUtils.scala:165)
  at com.nvidia.spark.rapids.shims.GpuIntervalUtils$.castStringToDayTimeIntervalWithThrow(GpuIntervalUtils.scala:153)
  at com.nvidia.spark.rapids.GpuCast$.doCast(GpuCast.scala:495)
```

However, when running against 3.5.0-rc3, we fall back to CPU because we do not support the expression `ToPrettyString`. I just saw that @razajafri has already filed an [issue](https://github.com/NVIDIA/spark-rapids/issues/9171) for this.

```
23/09/01 19:59:22 WARN GpuOverrides: 
!Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced
  @Expression <Alias> toprettystring(cast(value#41 as interval day to second), Some(UTC)) AS toprettystring(value)#59 could run on GPU
    ! <ToPrettyString> toprettystring(cast(value#41 as interval day to second), Some(UTC)) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.ToPrettyString
      @Expression <Cast> cast(value#41 as interval day to second) could run on GPU
        @Expression <AttributeReference> value#41 could run on GPU
```

**Comment by andygrove** [comment]
Note that `ToPrettyString` is specific to calling `show()`. If we `collect()` instead then we see this failure against 3.5.0:

```
Caused by: java.lang.IllegalArgumentException: Cast string to day time interval failed, may be the format is invalid, range check failed or overflow
  at com.nvidia.spark.rapids.shims.GpuIntervalUtils$.$anonfun$castStringToDayTimeIntervalWithThrow$1(GpuIntervalUtils.scala:167)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
  at com.nvidia.spark.rapids.shims.GpuIntervalUtils$.castStringToDayTimeIntervalWithThrow(GpuIntervalUtils.scala:165)
  at com.nvidia.spark.rapids.shims.GpuIntervalUtils$.castStringToDayTimeIntervalWithThrow(GpuIntervalUtils.scala:153)
  at com.nvidia.spark.rapids.GpuCast$.doCast(GpuCast.scala:495)

```
