### ISSUE TITLE
[BUG] NDS query 16 fails on EMR 6.10 with java.lang.ClassCastException

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#8268]
Running NDS SF3K on EMR 6.10 fails on query 16 with this exception:
```
====== Run query16 ======
TaskFailureListener is registered.
An error occurred while calling o12516.collectToPython.
: java.lang.ClassCastException: [Lscala.runtime.Nothing$; cannot be cast to org.apache.spark.sql.execution.joins.HashedRelation
        at org.apache.spark.sql.execution.SubqueryBroadcastExec.doExecuteCollect(SubqueryBroadcastExec.scala:77)
        at org.apache.spark.sql.execution.AsyncSubqueryExec$$anon$2.doCompute(basicPhysicalOperators.scala:931)
        at org.apache.spark.sql.execution.AsyncSubqueryExec$$anon$2.doCompute(basicPhysicalOperators.scala:928)
        at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$compute$1(AsyncDriverOperation.scala:73)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:216)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:199)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:245)
        at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:196)
        at org.apache.spark.sql.execution.AsyncDriverOperation.compute(AsyncDriverOperation.scala:67)
        at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$computeFuture$1(AsyncDriverOperation.scala:53)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$1(SQLExecution.scala:267)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
        at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.checkNoFailures(AdaptiveExecutor.scala:154)
        at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.doRun(AdaptiveExecutor.scala:88)
        at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.tryRunningAndGetFuture(AdaptiveExecutor.scala:66)
        at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.execute(AdaptiveExecutor.scala:57)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:249)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:248)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:521)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:483)
        at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3756)
        at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:3922)
        at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:554)
        at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3920)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
        at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:114)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$7(SQLExecution.scala:139)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:139)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:245)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:138)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3920)
        at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3753)
        at sun.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by NVnavkumar** [comment]
This error seems to be easier to reproduce when running the full benchmark

**Comment by NVnavkumar** [comment]
This is a regression from the fix made for https://github.com/NVIDIA/spark-rapids/issues/6978, so something in EMR 6.10 might have been updated to perform things differently from EMR 6.8

**Comment by kevnzhao** [comment]
Updates from EMR Spark team:

EMR Spark team checked if there is any difference in SubqueryBroadcastExec and there is no change in emr-6.10 when compared to emr-6.8.
SubqueryBroadcastExec is expecting HashedRelation with child.executeBroadcast. (but got Lscala.runtime.Nothing$)

Looks like something similar to earlier issue fixed in RAPIDS - https://github.com/NVIDIA/spark-rapids/issues/6978
Like earlier can RAPIDS team get more details from Spark History server - Like Plan? did anything change in RAPIDS where child.executeBroadcast will give diff results other than HashedRelation?

**Comment by jlowe** [comment]
This is also failing on emr-6.12.

**Comment by mattahrens** [comment]
This is failing intemittently on EMR 7.2.0.

**Comment by mattahrens** [comment]
This is also failing intermittently on EMR 7.3.0.

**Comment by revans2** [comment]
I think I found the bug.

query16 some times can match no data for the date and customer address tables. When this happens there is now a race between AQE trying to replan the query and stages that have already been planned, but are not needed, executing.

If AQE wins this race then the query passes and everything is fine. If the main query stage starts to run, then we expose a bug in GpuBroadcastRowExec, which does not properly handle empty relation for a HashedRelation BroadcastMode.

https://github.com/NVIDIA/spark-rapids/blob/823dd1d2365f5eb04258e29395525654d1b7ad8f/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuBroadcastToRowExec.scala#L67

I will put up a PR with the fix.
