### ISSUE TITLE
[BUG] GpuTimeAdd throws UnsupportedOperationException takes column and interval as an argument only

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#8293]
**Describe the bug**
customer running on Databricks 10.4 (3.2.1 based) reported a query failing due to the task throwing exception:
```
23/05/15 18:18:10 WARN TaskSetManager: Lost task 4.0 in stage 6751.0 (TID 58109) (10.13.2.116 executor 3): java.lang.UnsupportedOperationException: GpuTimeAdd takes column and interval as an argument only
        at org.apache.spark.sql.rapids.shims.GpuTimeAdd.$anonfun$columnarEval$2(datetimeExpressions.scala:119)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.shims.GpuTimeAdd.withResourceIfAllowed(datetimeExpressions.scala:45)
        at org.apache.spark.sql.rapids.shims.GpuTimeAdd.$anonfun$columnarEval$1(datetimeExpressions.scala:75)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.shims.GpuTimeAdd.withResourceIfAllowed(datetimeExpressions.scala:45)
        at org.apache.spark.sql.rapids.shims.GpuTimeAdd.columnarEval(datetimeExpressions.scala:74)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
        at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:254)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
        at com.nvidia.spark.rapids.CudfBinaryOperator.columnarEval(GpuExpressions.scala:336)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
        at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:254)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at com.nvidia.spark.rapids.CudfBinaryOperator.withResourceIfAllowed(GpuExpressions.scala:336)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:253)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:252)
        at org.apache.spark.sql.rapids.CudfBinaryPredicateWithSideEffect.columnarEval(predicates.scala:112)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
        at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
        at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:102)
        at com.nvidia.spark.rapids.GpuFilter$.computeCheckedFilterMask(basicPhysicalOperators.scala:465)
        at com.nvidia.spark.rapids.GpuFilter$.apply(basicPhysicalOperators.scala:495)
        at com.nvidia.spark.rapids.GpuFilter$.$anonfun$filterAndClose$4(basicPhysicalOperators.scala:487)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuFilter$.withResource(basicPhysicalOperators.scala:406)
       
at com.nvidia.spark.rapids.GpuFilter$.$anonfun$filterAndClose$3(basicPhysicalOperators.scala:486)
```

Not sure why this is a runtime exception and not a CPU fallback. 

I'm trying to find out what types customer was using here, it does looks like it hit:

https://github.com/NVIDIA/spark-rapids/blame/branch-23.04/sql-plugin/src/main/spark320/scala/org/apache/spark/sql/rapids/shims/datetimeExpressions.scala#L119

which looks very unexpected.

**Comment by tgravescs** [comment]
this error is happening because we are getting 2 GPUScalars as input. It looks like its being called as part of a ReuseExchange

**Comment by tgravescs** [comment]
example plan:

```
 GpuFilter
Input [3]: [datetime#1943, name#1945, uuid#1946]
Arguments: (((((gpuisnotnull(datetime#1943) AND gpuisnotnull(name#1945)) AND gpuisnotnull(uuid#1946)) AND (datetime#1943 <= Subquery subquery#1735, [id=#4892535])) AND (datetime#1943 >= Subquery subquery#1736, [id=#4892620] + -86400000000)) AND gpuisnotnull(gpuconcat(name#1945, |, uuid#1946)))
```
The subquery here must be returning a GPUScalar and then doing GpuTimeAdd with GpuScalar(-86400000000)
