### ISSUE TITLE
[BUG] Filter on dates with subquery results in ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#8331]
**Describe the bug**

I was writing some test code and ran into this failure:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
  at ai.rapids.cudf.Table.<init>(Table.java:58)
  at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:638)
  at com.nvidia.spark.rapids.GpuFilter$.$anonfun$doFilter$2(basicPhysicalOperators.scala:505)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
  at com.nvidia.spark.rapids.GpuFilter$.$anonfun$doFilter$1(basicPhysicalOperators.scala:503)
  at scala.Option.map(Option.scala:230)
  at com.nvidia.spark.rapids.GpuFilter$.doFilter(basicPhysicalOperators.scala:502)
  at com.nvidia.spark.rapids.GpuFilter$.apply(basicPhysicalOperators.scala:554)
  at com.nvidia.spark.rapids.GpuFilter$.$anonfun$filterAndCloseWithRetry$3(basicPhysicalOperators.scala:479)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
  at com.nvidia.spark.rapids.GpuFilter$.$anonfun$filterAndCloseWithRetry$2(basicPhysicalOperators.scala:478)
  at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
  at com.nvidia.spark.rapids.GpuFilter$.$anonfun$filterAndCloseWithRetry$1(basicPhysicalOperators.scala:477)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.next(RmmRapidsRetryIterator.scala:424)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:528)
  at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:458)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:496)
  at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
  at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
  at scala.collection.TraversableOnce.sum(TraversableOnce.scala:262)
  at scala.collection.TraversableOnce.sum$(TraversableOnce.scala:262)
  at scala.collection.AbstractIterator.sum(Iterator.scala:1431)
  at com.nvidia.spark.rapids.GpuCoalesceBatches.$anonfun$internalDoExecuteColumnar$1(GpuCoalesceBatches.scala:872)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
```

To reproduce in scala:

```
val df = Seq((1)).toDF("seq")
df.write.parquet("testsubquery")
val df = spark.read.parquet("testsubquery")
val curDate = df.withColumn("current_date",current_date().as("current_date"))
curDate.createOrReplaceTempView("curDate")
spark.sql("select current_date, ((select last(current_date) from curDate) + interval 1 day) as test from curDate").createOrReplaceTempView("test2")
spark.sql("select * from test2 where test < current_date").show()
```

This works fine on CPU side and it works fine with > because there is an actual row there.

Result on CPU:
```
scala> spark.sql("select * from test2 where test < current_date").show()
+------------+----+
|current_date|test|
+------------+----+
+------------+----+
```

**Comment by tgravescs** [comment]
note this also happens with timestamps after fix for https://github.com/NVIDIA/spark-rapids/issues/8293, likely other datatypes as well.

**Comment by revans2** [comment]
This indicates that we are trying to filter a batch with no columns in it. And yet we were able to come up with the column to filter on. I really would like to understand better how that is happening....

**Comment by revans2** [comment]
Yup that is exactly what the code is doing. We made the assumption it would never happen, but it did, so we can make a quick fix for this special case...
