### ISSUE TITLE
[BUG] ORC reader NullPointerExecption

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#8363]
**Describe the bug**
Customer his null pointer exception reader orc file:

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.$anonfun$close$1(GpuMultiFileReader.scala:835) ~[spark3xx-common/:?]
        at scala.collection.Iterator.foreach(Iterator.scala:943) ~[scala-library-2.12.14.jar:?]
        at scala.collection.Iterator.foreach$(Iterator.scala:943) ~[scala-library-2.12.14.jar:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) ~[scala-library-2.12.14.jar:?]
        at scala.collection.IterableLike.foreach(IterableLike.scala:74) ~[scala-library-2.12.14.jar:?]
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73) ~[scala-library-2.12.14.jar:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56) ~[scala-library-2.12.14.jar:?]
        at com.nvidia.spark.rapids.MultiFileCloudPartitionReaderBase.close(GpuMultiFileReader.scala:833) ~[spark3xx-common/:?]
        at com.nvidia.spark.rapids.shims.GpuDataSourceRDD$$anon$1.$anonfun$advanceToNextIter$1(GpuDataSourceRDD.scala:75) ~[spark3xx-common/:?]  
        at com.nvidia.spark.rapids.shims.GpuDataSourceRDD$$anon$1.$anonfun$advanceToNextIter$1$adapted(GpuDataSourceRDD.scala:74) ~[spark3xx-common/:?]
        at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:131) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1(TaskContextImpl.scala:143) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1$adapted(TaskContextImpl.scala:143) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:198) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.TaskContextImpl.invokeTaskCompletionListeners(TaskContextImpl.scala:143) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:136) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.scheduler.Task.run(Task.scala:146) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) ~[spark-core_2.12-3.3.0.jar:3.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException
        at com.nvidia.spark.rapids.MultiFileCloudOrcPartitionReader$ReadBatchRunner.doRead(GpuOrcScan.scala:1657) ~[spark3xx-common/:?]
        at com.nvidia.spark.rapids.MultiFileCloudOrcPartitionReader$ReadBatchRunner.call(GpuOrcScan.scala:1627) ~[spark3xx-common/:?]
        at com.nvidia.spark.rapids.MultiFileCloudOrcPartitionReader$ReadBatchRunner.call(GpuOrcScan.scala:1616) ~[spark3xx-common/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        ... 3 more

```

The line number that should match up with the 23.02.20221221 jar they are using:
https://github.com/NVIDIA/spark-rapids/blob/2737942ade2703f975bcb5a5944b52620476ef9b/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOrcScan.scala#L1657

I'm guessing the issue here is that this if checks to see if ctx == null but then it references ctx.updatedReadSchema in side of that.

**Comment by tgravescs** [comment]
filed https://github.com/NVIDIA/spark-rapids/issues/8367 to add test
