### ISSUE TITLE
[BUG] cache_test:test_batch_no_cols test FAILED on spark-3.3.0+

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#8548]
**Describe the bug**

cache_test:`test_batch_no_cols` test FAILED on spark-3.3.0+, also FAILED on spark-3.2.1+ `databricks` clusters, while it PASS on spark-3.1.x and spark-3.2.x, 

Related PR https://github.com/NVIDIA/spark-rapids/pull/8507/

logs:

```
=================================== FAILURES ===================================
_____________________ test_batch_no_cols[with_cpu_session] _____________________
[gw1] linux -- Python 3.9.16 /opt/conda/bin/python

with_x_session = <function with_cpu_session at 0x7ff5dff58310>

    @pytest.mark.parametrize('with_x_session', [with_gpu_session, with_cpu_session])
    def test_batch_no_cols(with_x_session):
>       function_to_test_on_df(with_x_session, lambda spark: unary_op_df(spark, int_gen).drop("a"), lambda df: df.count(), test_conf={})

../../src/main/python/cache_test.py:358: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../src/main/python/cache_test.py:271: in function_to_test_on_df
    cached_result = with_x_session(with_cache(True), test_conf)
../../src/main/python/spark_session.py:116: in with_cpu_session
    return with_spark_session(func, conf=copy)
../../src/main/python/spark_session.py:100: in with_spark_session
    ret = func(_spark)
../../src/main/python/cache_test.py:266: in helper
    _df.cache().count()
../../../spark-3.3.0-bin-hadoop3/python/pyspark/sql/dataframe.py:804: in count
    return int(self._jdf.count())
/home/jenkins/agent/workspace/jenkins-rapids_integration-pre_release-github-582-330/jars/spark-3.3.0-bin-hadoop3/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321: in __call__
    return_value = get_return_value(
../../../spark-3.3.0-bin-hadoop3/python/pyspark/sql/utils.py:190: in deco
    return f(*a, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

answer = 'xro31151'
gateway_client = <py4j.clientserver.JavaClient object at 0x7ff4d800de80>
target_id = 'o31149', name = 'count'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.
    
        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.
    
        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
>                   raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
                        format(target_id, ".", name), value)
                   py4j.protocol.Py4JJavaError: An error occurred while calling o31149.count.
                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1362.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1362.0 (TID 2523) (100.101.238.121 executor 0): java.lang.RuntimeException: com.nvidia.spark.rapids.ByteArrayInputFile@3d42dbc4 is not a Parquet file (length is too low: 0)
                         at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:539)
                         at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:776)
                         at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:657)
                         at com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.convertCachedBatchToInternalRowIter(ParquetCachedBatchSerializer.scala:747)
                         at com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.hasNext(ParquetCachedBatchSerializer.scala:727)
                         at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.hashAgg_doAggregateWithoutKey_0$(Unknown Source)
                         at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
                         at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
                         at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
                         at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
                         at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
                         at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
                         at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
                         at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
                         at org.apache.spark.scheduler.Task.run(Task.scala:136)
                         at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
                         at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
                         at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                         at java.lang.Thread.run(Thread.java:750)
                   
                   Driver stacktrace:
                         at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)
                         at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)
                         at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)
                         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
                         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
                         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
                         at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)
                         at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)
                         at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)
                         at scala.Option.foreach(Option.scala:407)
                         at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1182)
                         at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2860)
                         at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2802)
                         at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2791)
                         at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
                         at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952)
                         at org.apache.spark.SparkContext.runJob(SparkContext.scala:2228)
                         at org.apache.spark.SparkContext.runJob(SparkContext.scala:2249)
                         at org.apache.spark.SparkContext.runJob(SparkContext.scala:2268)
                         at org.apache.spark.SparkContext.runJob(SparkContext.scala:2293)
                         at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1021)
                         at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
                         at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
                         at org.apache.spark.rdd.RDD.withScope(RDD.scala:406)
                         at org.apache.spark.rdd.RDD.collect(RDD.scala:1020)
                         at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:424)
                         at org.apache.spark.sql.Dataset.$anonfun$count$1(Dataset.scala:3161)
                         at org.apache.spark.sql.Dataset.$anonfun$count$1$adapted(Dataset.scala:3160)
                         at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:3858)
                         at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
                         at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3856)
                         at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
                         at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
                         at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
                         at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
                         at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
                         at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3856)
                         at org.apache.spark.sql.Dataset.count(Dataset.scala:3160)
                         at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
                         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                         at java.lang.reflect.Method.invoke(Method.java:498)
                         at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
                         at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
                         at py4j.Gateway.invoke(Gateway.java:282)
                         at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
                         at py4j.commands.CallCommand.execute(CallCommand.java:79)
                         at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
                         at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
                         at java.lang.Thread.run(Thread.java:750)
                   Caused by: java.lang.RuntimeException: com.nvidia.spark.rapids.ByteArrayInputFile@3d42dbc4 is not a Parquet file (length is too low: 0)
                         at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:539)
                         at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:776)
                         at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:657)
                         at com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.convertCachedBatchToInternalRowIter(ParquetCachedBatchSerializer.scala:747)
                         at com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.hasNext(ParquetCachedBatchSerializer.scala:727)
                         at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.hashAgg_doAggregateWithoutKey_0$(Unknown Source)
                         at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
                         at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
                         at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
                         at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
                         at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
                         at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
                         at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
                         at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
                         at org.apache.spark.scheduler.Task.run(Task.scala:136)
                         at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
                         at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
                         at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                         ... 1 more

/home/jenkins/agent/workspace/jenkins-rapids_integration-pre_release-github-582-330/jars/spark-3.3.0-bin-hadoop3/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326: Py4JJavaError
=============================== warnings summary ===============================
../../../spark-3.3.0-bin-hadoop3/python/pyspark/sql/pandas/utils.py:37: 24 warnings
  /home/jenkins/agent/workspace/jenkins-rapids_integration-pre_release-github-582-330/jars/spark-3.3.0-bin-hadoop3/python/pyspark/sql/pandas/utils.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
 =========================== short test summary info ============================
FAILED ../../src/main/python/cache_test.py::test_batch_no_cols[with_cpu_session][INJECT_OOM]

```

**Comment by NvTimLiu** [comment]
@razajafri  Can you help to take a look, thanks!

**Comment by pxLi** [comment]
failed also DB runtimes (321db + 330db + 332db)

**Comment by NvTimLiu** [comment]
@razajafri  can we close this issue as the PR https://github.com/NVIDIA/spark-rapids/pull/8553/ got merged?
