### ISSUE TITLE
[BUG] SerializeConcatHostBuffersDeserializeBatch.writeObject fails with ArrayIndexOutOfBoundsException on rows-only table

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#8603]
When the executor wants to spill a broadcast from host to disk it invokes `SerializeConcatHostBuffersDeserializeBatch.writeObject`, and this method is also called from the driver. The driver side of this method is invoked often and works well, where with a series of `HostMemoryBuffer` it is able to serialize them using `JCudfSerialization`. If the executor wants to spill I have seen a failure for a rows-only batch (see below).

I found this while looking at https://github.com/NVIDIA/spark-rapids/issues/8602.  believe there is no reason why we would want to serialize this in the executor, so we should try and make this call a noop or write some dummy value. 

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at ai.rapids.cudf.Table.(Table.java:58)
	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:640)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.$anonfun$writeObject$3(GpuBroadcastExchangeExec.scala:239)
	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.$anonfun$writeObject$2(GpuBroadcastExchangeExec.scala:238)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.$anonfun$writeObject$2$adapted(GpuBroadcastExchangeExec.scala:237)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.rapids.execution.SerializeConcatHostBuffersDeserializeBatch.writeObject(GpuBroadcastExchangeExec.scala:237)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1154)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:44)
	at org.apache.spark.serializer.SerializationStream.writeAll(Serializer.scala:168)
	at org.apache.spark.serializer.SerializerManager.dataSerializeStream(SerializerManager.scala:188)
	at org.apache.spark.storage.BlockManager.$anonfun$dropFromMemory$3(BlockManager.scala:1853)
	at org.apache.spark.storage.BlockManager.$anonfun$dropFromMemory$3$adapted(BlockManager.scala:1848)
	at org.apache.spark.storage.DiskStore.put(DiskStore.scala:70)
	at org.apache.spark.storage.BlockManager.dropFromMemory(BlockManager.scala:1848)
	at org.apache.spark.storage.memory.MemoryStore.dropBlock$1(MemoryStore.scala:490)
	at org.apache.spark.storage.memory.MemoryStore.$anonfun$evictBlocksToFreeSpace$4(MemoryStore.scala:516)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at org.apache.spark.storage.memory.MemoryStore.evictBlocksToFreeSpace(MemoryStore.scala:507)
	at org.apache.spark.memory.StorageMemoryPool.acquireMemory(StorageMemoryPool.scala:92)
	at org.apache.spark.memory.StorageMemoryPool.acquireMemory(StorageMemoryPool.scala:73)
	at org.apache.spark.memory.UnifiedMemoryManager.acquireStorageMemory(UnifiedMemoryManager.scala:181)
	at org.apache.spark.storage.memory.MemoryStore.putBytes(MemoryStore.scala:151)
	at org.apache.spark.storage.BlockManager.maybeCacheDiskBytesInMemory(BlockManager.scala:1590)
	at org.apache.spark.storage.BlockManager.doGetLocalBytes(BlockManager.scala:994)
	at org.apache.spark.storage.BlockManager.$anonfun$getLocalBytes$3(BlockManager.scala:960)
```

**Comment by abellina** [comment]
I think we should not write/read data if `batchInternal` is defined, otherwise we should fix this because in theory we could spill before `batchInternal` is created...
