### ISSUE TITLE
[BUG] ai.rapids.cudf.CudfException: CUDA_ERROR_INVALID_PTX

### ISSUE THREAD

**Issue by PerkzZheng** [NVIDIA/spark-rapids#861]
**Describe the bug**

The preprocessing steps shown below acts normal in CPUs setting. However, when it was executed on GPUs, there turns out to be `ai.rapids.cudf.CudfException: CUDA_ERROR_INVALID_PTX`, which is not easy to debug. 

```python
def get_column_counts_with_frequency_limit(df, frequency_limit = None):
    cols = ['_c%d' % i for i in ALL_COLS]
    df = (df
        .select(posexplode(array(*cols)))
        .withColumnRenamed('pos', 'column_id')
        .withColumnRenamed('col', 'data')
        .filter('data is not null')
        .groupBy('column_id', 'data')
        .count())

    if frequency_limit:
        df = df.filter((col('count') >= frequency_limit))
    return df

def assign_id_with_window(df):
    windowed = Window.partitionBy('column_id').orderBy(desc('count'))
    return (df
            .withColumn('id', row_number().over(windowed))
            .withColumnRenamed('count', 'model_count'))

df = spark.read.schema(schema).option('sep', '\t').csv('file:/data/train.txt',header=True)

col_counts = get_column_counts_with_frequency_limit(df,6)
col_counts_id = assign_id_with_window(col_counts)

for i in ALL_COLS:
    model = (col_counts_id .filter('column_id == %d' % (i)).drop('column_id'))
    col_name = '_c%d'%i
    model = (model.drop('model_count').withColumnRenamed('data', col_name))
    df = (df.join(model, col_name, how='left').drop(col_name).withColumnRenamed('id', col_name))

df = df.na.fill(0)
```
Then, 
```python
df.show(100)
```
I have met `ai.rapids.cudf.CudfException: CUDA_ERROR_INVALID_PTX` several times. 

```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-27-59ff38af73d1> in <module>
----> 1 df.show(100)

~/spark/python/pyspark/sql/dataframe.py in show(self, n, truncate, vertical)
    438         """
    439         if isinstance(truncate, bool) and truncate:
--> 440             print(self._jdf.showString(n, 20, vertical))
    441         else:
    442             print(self._jdf.showString(n, int(truncate), vertical))

~/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

~/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    129     def deco(*a, **kw):
    130         try:
--> 131             return f(*a, **kw)
    132         except py4j.protocol.Py4JJavaError as e:
    133             converted = convert_exception(e.java_exception)

~/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o2685.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 521.0 failed 4 times, most recent failure: Lost task 0.3 in stage 521.0 (TID 2989, 10.23.137.25, executor 1): ai.rapids.cudf.CudfException: CUDA_ERROR_INVALID_PTX
	at ai.rapids.cudf.ColumnVector.binaryOpVV(Native Method)
	at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1032)
	at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1021)
	at ai.rapids.spark.CudfBinaryExpression.doColumnar(GpuExpressions.scala:222)
	at ai.rapids.spark.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:218)
	at ai.rapids.spark.CudfBinaryOperator.doColumnar(GpuExpressions.scala:238)
	at ai.rapids.spark.GpuBinaryExpression.columnarEval(GpuExpressions.scala:174)
	at ai.rapids.spark.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:166)
	at ai.rapids.spark.CudfBinaryOperator.columnarEval(GpuExpressions.scala:238)
	at ai.rapids.spark.GpuUnaryExpression.columnarEval(GpuExpressions.scala:123)
	at ai.rapids.spark.GpuAlias.columnarEval(namedExpressions.scala:90)
	at ai.rapids.spark.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:48)
	at ai.rapids.spark.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:156)
	at ai.rapids.spark.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:153)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at ai.rapids.spark.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:153)
	at ai.rapids.spark.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:188)
	at ai.rapids.spark.GpuProjectExec$.project(basicPhysicalOperators.scala:47)
	at ai.rapids.spark.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:38)
	at ai.rapids.spark.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:87)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at ai.rapids.spark.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:169)
	at ai.rapids.spark.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:185)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2023)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1972)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1971)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1971)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:950)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:950)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:950)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2203)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2152)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2141)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:752)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2093)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2133)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2158)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:385)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3625)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2695)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3616)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:763)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3614)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2695)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2902)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:300)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:337)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ai.rapids.cudf.CudfException: CUDA_ERROR_INVALID_PTX
	at ai.rapids.cudf.ColumnVector.binaryOpVV(Native Method)
	at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1032)
	at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1021)
	at ai.rapids.spark.CudfBinaryExpression.doColumnar(GpuExpressions.scala:222)
	at ai.rapids.spark.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:218)
	at ai.rapids.spark.CudfBinaryOperator.doColumnar(GpuExpressions.scala:238)
	at ai.rapids.spark.GpuBinaryExpression.columnarEval(GpuExpressions.scala:174)
	at ai.rapids.spark.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:166)
	at ai.rapids.spark.CudfBinaryOperator.columnarEval(GpuExpressions.scala:238)
	at ai.rapids.spark.GpuUnaryExpression.columnarEval(GpuExpressions.scala:123)
	at ai.rapids.spark.GpuAlias.columnarEval(namedExpressions.scala:90)
	at ai.rapids.spark.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:48)
	at ai.rapids.spark.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:156)
	at ai.rapids.spark.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:153)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at ai.rapids.spark.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:153)
	at ai.rapids.spark.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:188)
	at ai.rapids.spark.GpuProjectExec$.project(basicPhysicalOperators.scala:47)
	at ai.rapids.spark.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:38)
	at ai.rapids.spark.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:87)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at ai.rapids.spark.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:169)
	at ai.rapids.spark.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:185)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Environment details (please complete the following information)**
 - Environment location: Standalone
- Spark Version: 3.0.0
cudf-0.14-cuda10-2.jar   rapids-4-spark_2.12-0.3.0-SNAPSHOT.jar
 - Spark configuration settings related to the issue
```
$SPARK_HOME/bin/pyspark \
       --master spark://10.23.137.25:7077\
       --conf spark.rapids.sql.enabled=true\
       --conf spark.rapids.sql.incompatibleOps.enabled=true\
       --conf spark.worker.resource.gpu.discoveryScript=/home/perkz/GetGpusResources.sh\
       --conf spark.plugins=ai.rapids.spark.SQLPlugin\
       --conf spark.rapids.sql.castFloatToString.enabled=true\
       --conf spark.rapids.sql.castStringToInteger.enabled=true\
       --conf spark.rapids.sql.explain=true\
       --driver-memory 60G \
       --conf spark.executor.memory=30G\
       --conf spark.executor.cores=4\
       --conf spark.task.cpus=1 \
       --conf spark.executor.resource.gpu.amount=1\
       --conf spark.rapids.memory.pinnedPool.size=4G\
       --conf spark.rapids.memory.gpu.pooling.enabled=true\
       --conf spark.rapids.memory.gpu.allocFraction=0.25\
       --conf spark.task.resource.gpu.amount=0.25\
       --conf spark.rapids.sql.concurrentGpuTasks=2\
       --conf spark.locality.wait=0s\
       --conf spark.sql.files.maxPartitionBytes=512m\
       --conf spark.sql.autoBroadcastJoinThreshold=1GB \
       --conf spark.driver.maxResultSize=2G \
       --conf spark.network.timeout=1800s \
       --conf spark.sql.shuffle.partitions=10
```

**Additional context**

**Comment by tgravescs** [comment]
> cudf-0.14-cuda10-2.jar rapids-4-spark_2.12-0.3.0-SNAPSHOT.jar

You should be using cudf 0.16-snapshot with the 0.3.0-SNAPSHOT version.  see https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/pom.xml#L152

Please give that a try and see if it works

**Comment by sameerz** [comment]
Please reopen if you still have questions.
