### ISSUE TITLE
[BUG] EGX nightly tests fail to detect Spark version on startup

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8665]
Recently EGX nightly test have been failing to determine the Spark version with this error:
```
08:27:37  ++ PYTHONPATH=/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python:/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip
08:27:37  ++ python -c 'import py****, re; print(re.sub('\''\.dev0?$'\'', '\'''\'', py****.__version__))'
08:27:37  Traceback (most recent call last):
08:27:37    File "<string>", line 1, in <module>
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/__init__.py", line 53, in <module>
08:27:37      from py****.rdd import RDD, RDDBarrier
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/rdd.py", line 40, in <module>
08:27:37      from py****.statcounter import StatCounter
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/statcounter.py", line 24, in <module>
08:27:37      from numpy import maximum, minimum, sqrt
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
08:27:37      from . import core
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 24, in <module>
08:27:37      from . import multiarray
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.py", line 14, in <module>
08:27:37      from . import overrides
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/core/overrides.py", line 69, in <module>
08:27:37      ArgSpec = collections.namedtuple('ArgSpec', 'args varargs keywords defaults')
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/serializers.py", line 390, in namedtuple
08:27:37      for k, v in _old_namedtuple_kwdefaults.items():
08:27:37  AttributeError: 'NoneType' object has no attribute 'items'
08:27:37  Error in sys.excepthook:
08:27:37  Traceback (most recent call last):
08:27:37    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
08:27:37      from apport.fileutils import likely_packaged, get_recent_crashes
08:27:37    File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
08:27:37      from apport.report import Report
08:27:37    File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
08:27:37      from urllib.request import urlopen
08:27:37    File "/usr/lib/python3.5/urllib/request.py", line 88, in <module>
08:27:37      import http.client
08:27:37    File "/usr/lib/python3.5/http/client.py", line 1262, in <module>
08:27:37      import ssl
08:27:37    File "/usr/lib/python3.5/ssl.py", line 308, in <module>
08:27:37      "cafile capath openssl_cafile_env openssl_cafile openssl_capath_env "
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/serializers.py", line 390, in namedtuple
08:27:37      for k, v in _old_namedtuple_kwdefaults.items():
08:27:37  AttributeError: 'NoneType' object has no attribute 'items'
08:27:37  
08:27:37  Original exception was:
08:27:37  Traceback (most recent call last):
08:27:37    File "<string>", line 1, in <module>
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/__init__.py", line 53, in <module>
08:27:37      from py****.rdd import RDD, RDDBarrier
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/rdd.py", line 40, in <module>
08:27:37      from py****.statcounter import StatCounter
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/statcounter.py", line 24, in <module>
08:27:37      from numpy import maximum, minimum, sqrt
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
08:27:37      from . import core
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 24, in <module>
08:27:37      from . import multiarray
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.py", line 14, in <module>
08:27:37      from . import overrides
08:27:37    File "/usr/local/lib/python3.5/dist-packages/numpy/core/overrides.py", line 69, in <module>
08:27:37      ArgSpec = collections.namedtuple('ArgSpec', 'args varargs keywords defaults')
08:27:37    File "/home/****/rapids_it-EGX-Yarn/****-3.1.2-bin-hadoop3.2/python/py****/serializers.py", line 390, in namedtuple
08:27:37      for k, v in _old_namedtuple_kwdefaults.items():
08:27:37  AttributeError: 'NoneType' object has no attribute 'items'
08:27:37  + VERSION_STRING=
08:29:43  + '[' 1 '!=' 0 ']'
08:29:43  + exit 1
```

**Comment by NvTimLiu** [comment]
Spark-3.x requires python3.6+, 

Someone changed the python3.6 bin pointing to 3.5 on EGX-03 yarn, yuk. 

Let me fix it again.

Looks like some one was testing on EGX3 host, and changed the python env

A week ago someone changed the default python from 3.6 to 2.7, causing the nightly CI failure. I just fixed it. Now he soft-linked 3.6 to 3.5
```
lrwxrwxrwx 1 root root       7 Jul  5 06:02 /usr/bin/python3.6 -> python3*

lrwxrwxrwx 1 root root      18 Aug 23  2022 /usr/bin/python3 -> /usr/bin/python3.5*

```
