### ISSUE TITLE
[BUG] cannot disable Sort by itself

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#881]
**Describe the bug**
This is related to #880 

When I tried to work around the issue by disabling sort, some how sort still tried to replaced and resulted in an exception.

```
java.lang.IllegalStateException: Cannot be converted to GPU
	at com.nvidia.spark.rapids.RuleNotFoundExprMeta.convertToGpu(RapidsMeta.scala:831)
	at com.nvidia.spark.rapids.RuleNotFoundExprMeta.convertToGpu(RapidsMeta.scala:821)
	at com.nvidia.spark.rapids.GpuOverrides$$anon$95.$anonfun$convertToGpu$8(GpuOverrides.scala:1221)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at com.nvidia.spark.rapids.GpuOverrides$$anon$95.convertToGpu(GpuOverrides.scala:1221)
	at com.nvidia.spark.rapids.GpuOverrides$$anon$95.convertToGpu(GpuOverrides.scala:1218)
	at com.nvidia.spark.rapids.GpuSortMeta.$anonfun$convertToGpu$1(GpuSortExec.scala:39)
	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
	at scala.collection.immutable.Stream.force(Stream.scala:269)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$withNewChildren$2(TreeNode.scala:274)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
	at org.apache.spark.sql.catalyst.trees.TreeNode.withNewChildren(TreeNode.scala:269)

```

**Comment by revans2** [comment]
I started to look at this and it is rather complicated.  Some how when we disable the sort a `GpuLiteral` is showing up in the `SortOrder` before we try to translate it to run on the GPU which is resulting in it getting really confused, even though we think we can run it on the GPU.

There is also an issue with `GpuWindowExec` not requiring a single batch for it's input.  with all of these things I would rather wait on this until #850 is in.

**Comment by revans2** [comment]
OK So I have tracked it down a bit more.  It looks like there is an issue with `addSortsIfNeeded` in `GpuOverrides`.  Essentially what appears to happen is that we need to insert a `SortExec`, but the `SortExec` we insert can end up with a `GpuExpression` in it which is bad to start out with and really confuses the `GpuOverrides` when it tries to convert it back to the GPU.

I'm not 100% sure how to fix it at this point though.
