### ISSUE TITLE
[BUG] databricks cudf_udf night build failing with pool size exceeded errors

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8827]
**Describe the bug**
The night build failed again last night with cudf-udf tests.  Specifically 

```
[2023-07-27T12:25:43.469Z] DEBUG: Pooled memory, pool size: 755.4873046875 MiB, max size: 8796093022208.0 MiB
[2023-07-27T12:25:43.469Z] Traceback (most recent call last):
[2023-07-27T12:25:43.469Z]   File "/home/ubuntu/rapids-4-spark_2.12-23.08.0-SNAPSHOT-cuda11.jar/rapids/daemon_databricks.py", line 132, in manager
[2023-07-27T12:25:43.469Z]   File "/home/ubuntu/rapids-4-spark_2.12-23.08.0-SNAPSHOT-cuda11.jar/rapids/worker.py", line 61, in initialize_gpu_mem
[2023-07-27T12:25:43.469Z]     rmm.mr.set_current_device_resource(rmm.mr.PoolMemoryResource(base_t(), pool_size, pool_max_size))
[2023-07-27T12:25:43.469Z]   File "memory_resource.pyx", line 348, in rmm._lib.memory_resource.PoolMemoryResource.__cinit__
[2023-07-27T12:25:43.469Z] MemoryError: std::bad_alloc: out_of_memory: RMM failure at:/databricks/conda/envs/cudf-udf/include/rmm/mr/device/pool_memory_resource.hpp:196: Maximum pool size exceeded
[2023-07-27T12:25:43.469Z] 23/07/27 12:25:42 WARN PythonWorkerFactory: Failed to open socket to Python daemon:
[2023-07-27T12:25:43.469Z] java.net.SocketException: Connection reset
[2023-07-27T12:25:43.469Z] 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
[2023-07-27T12:25:43.469Z] 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[2023-07-27T12:25:43.469Z] 	at java.net.SocketInputStream.read(SocketInputStream.java:224)
```

Not sure what changed but for some reason we think that the maximum pool size is 8192 PiB. But that didn't change. The runs that passed also had similar debug messages.

```
[2023-07-25T12:25:22.234Z] INFO: Process 4813 found CUDA visible device(s): 0
[2023-07-25T12:25:32.141Z] DEBUG: Pooled memory, pool size: 755.4873046875 MiB, max size: 8796093022208.0 MiB
[2023-07-25T12:25:32.697Z] INFO: Process 4856 found CUDA visible device(s): 0
[2023-07-25T12:25:42.603Z] DEBUG: Pooled memory, pool size: 755.4873046875 MiB, max size: 8796093022208.0 MiB
[2023-07-25T12:25:42.603Z] PASSED [  9%]
[2023-07-25T12:25:43.158Z] ../../src/main/python/udf_cudf_test.py::test_with_column[large data] 23/07/25 12:25:43 WARN GpuOverrides: 
[2023-07-25T12:25:43.158Z]     ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
[2023-07-25T12:25:43.158Z]       @Expression <AttributeReference> id#30L could run on GPU
```

But the message did change. `Process XXXX` was printed for the passing version, but not the failed ones. I am going to have to debug some things to understand what is happening.

**Comment by revans2** [comment]
hmm the file that prints out the log messages has not changed since 2020, and the max is essentially long max value, because that is the default if it is not set with an environment variable.

**Comment by revans2** [comment]
Not the other lines are in there too, just in a different order...

**Comment by NvTimLiu** [comment]
Checking

Another cudf-udf nightly test got PASS against 23.10.0 on blossom hosts
I saw there was an maintenance yestoday, not sure if it related to 27th Databricks update, let me check
