### ISSUE TITLE
[BUG] Possible failure to push down pruned read schema to ORC reader

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#8906]
When reading an ORC file with numerous rows (N > 100M), one might expect to see failures in reading a `STRING` column via `spark-rapids` if the total number of characters across the column exceeds the range of `cudf::size_type`. This is a known defect, and expected:
```sql
SELECT * FROM my_large_table
```
```
Caused by: ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-pre_release-164-cuda11/thirdparty/cudf/cpp/include/cudf/strings/detail/strings_children.cuh:82: Size of output exceeds the column size limit
  at ai.rapids.cudf.ColumnView.stringConcatenationListElementsSepCol(Native Method)
  at ai.rapids.cudf.ColumnView.stringConcatenateListElements(ColumnView.java:2900)
  at ai.rapids.cudf.ColumnView.stringConcatenateListElements(ColumnView.java:2867)
  at com.nvidia.spark.rapids.GpuCast$.$anonfun$concatenateStringArrayElements$11(GpuCast.scala:720)
```
However, it is unexpected that the operation would fail if the output projection excludes the `STRINGS` column, like:
```sql
SELECT my_array FROM my_large_table; -- my_strings column is not selected.
```
It would appear that the `STRINGS` column is being deserialized, even though it's not in the output projection.

**Comment by mythrocks** [comment]
cc @razajafri. Just FYI, since this is one of the items we're testing in #8666.

**Comment by mythrocks** [comment]
Sorry, no. This is not a problem. Or rather, not the problem I thought this was.

This is not the result of reading the `STRINGS` column, in hindsight. This is the result of calling `.show`, which converts the table into a `LIST<STRING>`, which then fails the size check.
