### ISSUE TITLE
[BUG] java.lang.ClassCastException: com.nvidia.spark.rapids.RuleNotFoundExprMeta cannot be cast to com.nvidia.spark.rapids.GeneratorExprMeta

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9034]
**Describe the bug**
Customer reported 23.06 issue got exception:
```

23/08/14 14:58:34 ERROR GpuOverrideUtil: Encountered an exception applying GPU overrides java.lang.ClassCastException: com.nvidia.spark.rapids.RuleNotFoundExprMeta cannot be cast to com.nvidia.spark.rapids.GeneratorExprMeta
java.lang.ClassCastException: com.nvidia.spark.rapids.RuleNotFoundExprMeta cannot be cast to com.nvidia.spark.rapids.GeneratorExprMeta
	at com.nvidia.spark.rapids.GpuGenerateExecSparkPlanMeta.tagPlanForGpu(GpuGenerateExec.scala:50)
	at com.nvidia.spark.rapids.SparkPlanMeta.tagSelfForGpu(RapidsMeta.scala:756)
	at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:318)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$6(RapidsMeta.scala:297)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$6$adapted(RapidsMeta.scala:297)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at com.nvidia.spark.rapids.RapidsMeta.tagForGpu(RapidsMeta.scala:297)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$6(RapidsMeta.scala:297)
	at com.nvidia.spark.rapids.RapidsMeta.$anonfun$tagForGpu$6$adapted(RapidsMeta.scala:297)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
```

It looks like our code is assuming anything for GpuGenerateExec will be a GeneratorExprMeta when we shouldn't be

**Comment by pxLi** [comment]
fixed by #9036
