### ISSUE TITLE
[BUG] ParquetFormatScanSuite does not pass locally

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#9069]
NOTE: this is on my linux laptop (mobile RTX 3070 8GB and driver 525.105.17).

I am running the `ParquetFormatScanSuite`  like this using branch-23.10 HEAD:

```
mvn package -Dbuildver=321 -pl '!integration_tests' -DwildcardSuites=org.apache.spark.sql.rapids.ParquetFormatScanSuit
```

In my linux laptop and I can consistently repro these test failures. Filing for visibility:

```
ParquetFormatScanSuite:
- STRING NATIVE
- ENUM NATIVE
- JSON NATIVE
- BINARY NATIVE
- BSON NATIVE
- int32 NATIVE
- int32 - unsigned NATIVE
- int32 - int8 OVERFLOW NATIVE
- int64 NATIVE
- int64 - unsigned NATIVE
- int32 Decimal NATIVE
- int64 Decimal NATIVE
- FIXED_LEN_BYTE_ARRAY(16) Decimal NATIVE
- FIXED_LEN_BYTE_ARRAY(15) Decimal NATIVE
- binary Decimal NATIVE
- binary Decimal2 NATIVE
- Date NATIVE
- Timestamp (MILLIS AND MICROS) NATIVE
- nz timestamp (MILLIS AND MICROS) NATIVE !!! CANCELED !!!
  SparkQueryCompareTestSuite.this.isSpark330OrLater was false Spark version not 3.3.0+ (SparkQueryCompareTestSuite.scala:2147)
- nz timestamp spark enabled (MILLIS AND MICROS) NATIVE !!! IGNORED !!!
- BASIC LIST NATIVE
- NO GROUP LIST NATIVE *** FAILED ***
  ai.rapids.cudf.CudfException: cuFile error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-511-cuda11/thirdparty/cudf/cpp/build/_deps/kvikio-src/cpp/include/kvikio/file_handle.hpp:176: internal error
  at ai.rapids.cudf.Table.readParquet(Native Method)
  at ai.rapids.cudf.Table.readParquet(Table.java:1117)
  at ai.rapids.cudf.Table.readParquet(Table.java:1107)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$221(ParquetFormatScanSuite.scala:1134)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$221$adapted(ParquetFormatScanSuite.scala:1120)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.withTempDir(ParquetFormatScanSuite.scala:88)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$220(ParquetFormatScanSuite.scala:1120)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$220$adapted(ParquetFormatScanSuite.scala:1112)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:138)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  ...
- SINGLE GROUP LIST NATIVE *** FAILED ***
  ai.rapids.cudf.CudfException: cuFile error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-511-cuda11/thirdparty/cudf/cpp/build/_deps/kvikio-src/cpp/include/kvikio/file_handle.hpp:176: internal error
  at ai.rapids.cudf.Table.readParquet(Native Method)
  at ai.rapids.cudf.Table.readParquet(Table.java:1117)
  at ai.rapids.cudf.Table.readParquet(Table.java:1107)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$229(ParquetFormatScanSuite.scala:1170)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$229$adapted(ParquetFormatScanSuite.scala:1155)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.withTempDir(ParquetFormatScanSuite.scala:88)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$228(ParquetFormatScanSuite.scala:1155)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$228$adapted(ParquetFormatScanSuite.scala:1146)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:138)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  ...
- SINGLE GROUP TUPLE LIST NATIVE *** FAILED ***
  ai.rapids.cudf.CudfException: cuFile error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-511-cuda11/thirdparty/cudf/cpp/build/_deps/kvikio-src/cpp/include/kvikio/file_handle.hpp:176: internal error
  at ai.rapids.cudf.Table.readParquet(Native Method)
  at ai.rapids.cudf.Table.readParquet(Table.java:1117)
  at ai.rapids.cudf.Table.readParquet(Table.java:1107)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$238(ParquetFormatScanSuite.scala:1213)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$238$adapted(ParquetFormatScanSuite.scala:1194)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.withTempDir(ParquetFormatScanSuite.scala:88)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$237(ParquetFormatScanSuite.scala:1194)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$237$adapted(ParquetFormatScanSuite.scala:1182)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:138)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  ...
- SPECIAL ARRAY LIST NATIVE !!! IGNORED !!!
- SPECIAL _TUPLE LIST NATIVE !!! IGNORED !!!
- BASIC MAP NATIVE
- DUPLICATE KEY MAP NATIVE
- MAP_KEY_VALUE NATIVE !!! IGNORED !!!
- STRING JAVA
- ENUM JAVA
- JSON JAVA
- BINARY JAVA
- BSON JAVA
- int32 JAVA
- int32 - unsigned JAVA
- int32 - int8 OVERFLOW JAVA
- int64 JAVA
- int64 - unsigned JAVA
- int32 Decimal JAVA
- int64 Decimal JAVA
- FIXED_LEN_BYTE_ARRAY(16) Decimal JAVA
- FIXED_LEN_BYTE_ARRAY(15) Decimal JAVA
- binary Decimal JAVA
- binary Decimal2 JAVA
- Date JAVA
- Timestamp (MILLIS AND MICROS) JAVA
- nz timestamp (MILLIS AND MICROS) JAVA !!! CANCELED !!!
  SparkQueryCompareTestSuite.this.isSpark330OrLater was false Spark version not 3.3.0+ (SparkQueryCompareTestSuite.scala:2147)
- nz timestamp spark enabled (MILLIS AND MICROS) JAVA !!! IGNORED !!!
- BASIC LIST JAVA
- NO GROUP LIST JAVA *** FAILED ***
  ai.rapids.cudf.CudfException: cuFile error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-511-cuda11/thirdparty/cudf/cpp/build/_deps/kvikio-src/cpp/include/kvikio/file_handle.hpp:176: internal error
  at ai.rapids.cudf.Table.readParquet(Native Method)
  at ai.rapids.cudf.Table.readParquet(Table.java:1117)
  at ai.rapids.cudf.Table.readParquet(Table.java:1107)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$221(ParquetFormatScanSuite.scala:1134)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$221$adapted(ParquetFormatScanSuite.scala:1120)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.withTempDir(ParquetFormatScanSuite.scala:88)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$220(ParquetFormatScanSuite.scala:1120)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$220$adapted(ParquetFormatScanSuite.scala:1112)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:138)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  ...
- SINGLE GROUP LIST JAVA *** FAILED ***
  ai.rapids.cudf.CudfException: cuFile error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-511-cuda11/thirdparty/cudf/cpp/build/_deps/kvikio-src/cpp/include/kvikio/file_handle.hpp:176: internal error
  at ai.rapids.cudf.Table.readParquet(Native Method)
  at ai.rapids.cudf.Table.readParquet(Table.java:1117)
  at ai.rapids.cudf.Table.readParquet(Table.java:1107)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$229(ParquetFormatScanSuite.scala:1170)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$229$adapted(ParquetFormatScanSuite.scala:1155)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.withTempDir(ParquetFormatScanSuite.scala:88)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$228(ParquetFormatScanSuite.scala:1155)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$228$adapted(ParquetFormatScanSuite.scala:1146)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:138)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  ...
- SINGLE GROUP TUPLE LIST JAVA *** FAILED ***
  ai.rapids.cudf.CudfException: cuFile error at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-511-cuda11/thirdparty/cudf/cpp/build/_deps/kvikio-src/cpp/include/kvikio/file_handle.hpp:176: internal error
  at ai.rapids.cudf.Table.readParquet(Native Method)
  at ai.rapids.cudf.Table.readParquet(Table.java:1117)
  at ai.rapids.cudf.Table.readParquet(Table.java:1107)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$238(ParquetFormatScanSuite.scala:1213)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$238$adapted(ParquetFormatScanSuite.scala:1194)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.withTempDir(ParquetFormatScanSuite.scala:88)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$237(ParquetFormatScanSuite.scala:1194)
  at org.apache.spark.sql.rapids.ParquetFormatScanSuite.$anonfun$new$237$adapted(ParquetFormatScanSuite.scala:1182)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:138)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withGpuSparkSession(SparkQueryCompareTestSuite.scala:198)
  ...
- SPECIAL ARRAY LIST JAVA !!! IGNORED !!!
- SPECIAL _TUPLE LIST JAVA !!! IGNORED !!!
- BASIC MAP JAVA
- DUPLICATE KEY MAP JAVA
- MAP_KEY_VALUE JAVA !!! IGNORED !!!
Run completed in 18 seconds, 534 milliseconds.
Total number of tests run: 48
Suites: completed 2, aborted 0
Tests: succeeded 42, failed 6, canceled 2, ignored 8, pending 0
*** 6 TESTS FAILED ***
```

**Comment by abellina** [comment]
Note I see the same for 23.08. I bet I have a missing library or incompatibility. It looks like an issue with kvikio.

**Comment by sameerz** [comment]
Comment during bug scrub: ParquetFormatScanSuite should not call `ai.rapids.cudf.Table.readParquet`, the test needs to be updated.

**Comment by revans2** [comment]
@abellina is https://github.com/NVIDIA/spark-rapids/pull/9093 good enough to fix this? Or do you want someone to dig into what is happening because there may be some issues with cufile/kvikio?

**Comment by abellina** [comment]
Locally the tests pass with your patch. I think this is good enough to close as the plugin doesn't use this api directly, and this is likely just my laptop not configured well.
