### ISSUE TITLE
Unable to parse spark event log in txt format for profiling 

### ISSUE THREAD

**Issue by pratik4891** [NVIDIA/spark-rapids#9087]
Got into below error while trying to parse spark event log in txt format - 

```
java -cp "rapids-4-spark-tools_2.12-22.04.0.jar:/opt/spark/jars/*" com.nvidia.spark.rapids.tool.profiling
.ProfileMain  /opt/spark/spark-kubernetes-drivershs.log
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
23/08/21 13:03:40 WARN EventLogPathProcessor: File: spark-kubernetes-drivershs.log it not a supported file type. Supported compression types are: lzf, lz4, gz,
 snappy, zstd. Skipping this file.
23/08/21 13:03:40 WARN ProfileMain: No event logs to process after checking paths, exiting!


```
When tried to zip the file and pass it as a parameter then also it failed 

```
java -cp "rapids-4-spark-tools_2.12-22.04.0.jar:/opt/spark/jars/*" com.nvidia.spark.rapids.tool.profiling
.ProfileMain eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.zip
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
23/08/21 13:05:45 WARN EventLogPathProcessor: File: eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.zip it not a supported file type. Supported compression ty
pes are: lzf, lz4, gz, snappy, zstd. Skipping this file.
23/08/21 13:05:45 WARN ProfileMain: No event logs to process after checking paths, exiting!
185@spark-sts-deltaservice-32d1c7899375e654-driver:~$ cp eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.zip eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.
gz
185@spark-sts-deltaservice-32d1c7899375e654-driver:~$ java -cp "rapids-4-spark-tools_2.12-22.04.0.jar:/opt/spark/jars/*" com.nvidia.spark.rapids.tool.profiling
.ProfileMain eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.gz
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
23/08/21 13:08:46 INFO Profiler: Threadpool size is 4
23/08/21 13:08:46 INFO ApplicationInfo: Parsing Event Log: file:/opt/spark/eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.gz
23/08/21 13:08:47 WARN Profiler: Got unexpected exception processing file: ApacheSparkEventLog(file:/opt/spark/eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb
.gz)
java.util.zip.ZipException: Not in GZIP format
        at java.base/java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
        at java.base/java.util.zip.GZIPInputStream.<init>(Unknown Source)
        at org.apache.spark.sql.rapids.tool.AppBase.openEventLogInternal(AppBase.scala:58)
        at org.apache.spark.sql.rapids.tool.AppBase.$anonfun$processEvents$4(AppBase.scala:91)
        at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2763)
        at org.apache.spark.sql.rapids.tool.AppBase.$anonfun$processEvents$3(AppBase.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.rapids.tool.AppBase.processEvents(AppBase.scala:90)
        at org.apache.spark.sql.rapids.tool.profiling.ApplicationInfo.<init>(ApplicationInfo.scala:239)
        at com.nvidia.spark.rapids.tool.profiling.Profiler.com$nvidia$spark$rapids$tool$profiling$Profiler$$createApp(Profiler.scala:249)
        at com.nvidia.spark.rapids.tool.profiling.Profiler$ProfileProcessThread$1.run(Profiler.scala:212)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
23/08/21 13:08:47 INFO Profiler: No application to process. Exiting
185@spark-sts-deltaservice-32d1c7899375e654-driver:~$ java -cp "rapids-4-spark-tools_2.12-22.04.0.jar:/opt/spark/jars/*" com.nvidia.spark.rapids.tool.profiling
.ProfileMain eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.zip
```

Is there any way to profile in case we have the spark event logs in txt format

**Comment by tgravescs** [comment]
The error message is saying that the profiling tool doesn't support the .zip format (eventLogs-spark-d77b4d7368654c8f90ccfe574562a9eb.zip).  Can you just unzip it and pass it in?  It does support just plain text format that you would get from Spark when compression is not enabled.

**Comment by tgravescs** [comment]
Also note it looks like you are using a fairly old version of the jar (rapids-4-spark-tools_2.12-22.04.0).  I would recommend updating to a newer version if you can.

**Comment by tgravescs** [comment]
Sorry I missed, the first part of the issue: 

```
23/08/21 13:03:40 WARN EventLogPathProcessor: File: spark-kubernetes-drivershs.log it not a supported file type. Supported compression types are: lzf, lz4, gz,
 snappy, zstd. Skipping this file.
 
```
 We do support plaintext but it shouldn't have any suffix at all. It expects the filename to be one Spark generates, which is either no suffix or the compression specific suffix.  Can you rename the file to just be spark-kubernetes-drivershs and try again.

I'll file a separate issue for us to improve our error messages.

**Comment by pratik4891** [comment]
Thanks Thomas , it is working now after keeping the spark log file name intact , command being used - 

java -cp rapids-4-spark-tools_2.12-23.08.0.jar:/opt/spark/jars/* com.nvidia.spark.rapids.tool.profiling.P
rofileMain  /opt/spark/spark-e239a2f4dd5d40d48c85c00d0180fcdd

It would be nice if we can get a Json output as well so it can be parsed and stored in some DB

**Comment by tgravescs** [comment]
the tool supports outputing CSV, you should be able to read that with Spark or other tools to store and process afterwards.
