### ISSUE TITLE
[BUG] ConcurrentModificationException in ScalableTaskCompletion

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#9131]
I saw the following error when running NDS in our performance cluster. We had task failures, and so this is hard to reproduce, but overall I think it makes sense why it is happening, so I don't think a bug fix needs to reproduce it.

The issue looks to be that while we are invoking callbacks, a callback may want to register a new user callback (e.g. I see calls to `onTaskCompletion` from within a user callback, and this ends up calling `ScalableTaskCompletion.add` and `TopLevelTaskCompletion.add` which modifies its `pending` collection while we are iterating on it:

```
Executor task launch worker for task 132.0 in stage 1740.0 (TID 306588) 23/08/28 23:39:11:862 ERROR TaskContextImpl: Error in TaskCompletionListener
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1493)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.callAllCallbacks(ScalableTaskCompletion.scala:93)
	at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.apply(ScalableTaskCompletion.scala:115)
	at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.apply(ScalableTaskCompletion.scala:87)
	at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:130)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1(TaskContextImpl.scala:142)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1$adapted(TaskContextImpl.scala:142)
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:197)
	at org.apache.spark.TaskContextImpl.invokeTaskCompletionListeners(TaskContextImpl.scala:142)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:135)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
I was able to repro this and find the root cause. We can add callbacks while we are calling a callback as seen below. 

In this example, Spark is marking a task as having failed. In doing so, we call the callbacks for this task. We eventually reach the `CloseableBufferedIterator` and its `close` method. This `close` method is going to close `headOption` if it exists, but that delegated to the underlying iterator's `headOption`. In this case, the underlying iterator is a shuffle reader, and we are asking it to populate a value here so we can turn around and close it. Because of this, we instantiate a `SerializedBatchIterator` and the first thing it does is register a callback. We registered a callback while calling the callbacks.

I think one bug is `CloseableBufferedIterator` needs to find a way not to call to its parent during a close. That seems like a big waste of time. The second issue is we may need to add code in the `ScalableTaskCompletion` code to detect these "loops" and so something about it. I think if, after calling the callbacks we know about, we get new callbacks, we may want to do error out loudly, rather than rely on the `HashSet.forEach` method detecting the modification.


```
        at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.add(ScalableTaskCompletion.scala:180)
        at com.nvidia.spark.rapids.ScalableTaskCompletion$.add(ScalableTaskCompletion.scala:231)
        at com.nvidia.spark.rapids.ScalableTaskCompletion$.onTaskCompletion(ScalableTaskCompletion.scala:242)
        at com.nvidia.spark.rapids.SerializedBatchIterator.$anonfun$new$1(GpuColumnarBatchSerializer.scala:44)
        at scala.Option.foreach(Option.scala:407)
        at com.nvidia.spark.rapids.SerializedBatchIterator.<init>(GpuColumnarBatchSerializer.scala:43)
        at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$2.asKeyValueIterator(GpuColumnarBatchSerializer.scala:223)
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedReaderBase$RapidsShuffleThreadedBlockIterator.$anonfun$popFetchedIfAvailable$1(RapidsShuffleInternalManagerBase.scala:805)
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedReaderBase$RapidsShuffleThreadedBlockIterator.$anonfun$popFetchedIfAvailable$1$adapted(RapidsShuffleInternalManagerBase.scala:782)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedReaderBase$RapidsShuffleThreadedBlockIterator.popFetchedIfAvailable(RapidsShuffleInternalManagerBase.scala:782)
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedReaderBase$RapidsShuffleThreadedBlockIterator.$anonfun$next$5(RapidsShuffleInternalManagerBase.scala:690)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedReaderBase$RapidsShuffleThreadedBlockIterator.next(RapidsShuffleInternalManagerBase.scala:684)
        at org.apache.spark.sql.rapids.RapidsShuffleThreadedReaderBase$RapidsShuffleThreadedBlockIterator.next(RapidsShuffleInternalManagerBase.scala:610)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at org.apache.spark.util.CompletionIterator.next(CompletionIterator.scala:29)
        at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at scala.collection.Iterator$$anon$22.next(Iterator.scala:1095)
        at scala.collection.Iterator$$anon$22.head(Iterator.scala:1082)
        at scala.collection.BufferedIterator.headOption(BufferedIterator.scala:32)
        at scala.collection.BufferedIterator.headOption$(BufferedIterator.scala:32)
        at scala.collection.Iterator$$anon$22.headOption(Iterator.scala:1076)
        at com.nvidia.spark.rapids.CloseableBufferedIterator.headOption(CloseableBufferedIterator.scala:42)
        at com.nvidia.spark.rapids.CloseableBufferedIterator.close(CloseableBufferedIterator.scala:47)
        at com.nvidia.spark.rapids.CloseableBufferedIterator.$anonfun$new$2(CloseableBufferedIterator.scala:36)
        at com.nvidia.spark.rapids.ScalableTaskCompletion$UserTaskCompletion.apply(ScalableTaskCompletion.scala:74)
        at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.$anonfun$callAllCallbacks$1(ScalableTaskCompletion.scala:120)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.callAllCallbacks(ScalableTaskCompletion.scala:113)
        at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.apply(ScalableTaskCompletion.scala:161)
        at com.nvidia.spark.rapids.ScalableTaskCompletion$TopLevelTaskCompletion.apply(ScalableTaskCompletion.scala:99)
        at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:130)
        at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1(TaskContextImpl.scala:142)
        at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1$adapted(TaskContextImpl.scala:142)
        at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:197)
        at org.apache.spark.TaskContextImpl.invokeTaskCompletionListeners(TaskContextImpl.scala:142)
        at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:135)
        at org.apache.spark.scheduler.Task.run(Task.scala:141)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
Unfortunately, when we use `.buffered` we get an instance of `BufferedIterator` that cannot be closed cleanly. It has a method, `headOption` that will always buffer if called the first time. So if we are closing a task and we haven't actually buffered anything we would be forced to buffer in order to close (e.g. there isn't a `hasBufferedCached` method...)

So I think we should instead pass a regular Iterator to `CloseableBufferedIterator` and have it perform smarter buffering, so we don't do unnecessary work on close.
