### ISSUE TITLE
[BUG] GC/OOM on `parquet_test.py::test_small_file_memory` on CDH

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#9135]
The `parquet_test.py::test_small_file_memory` test runs out of memory on CDH (at least on the equivalent of Spark 3.3):
```
$ SPARK_HOME=$SPARK_HOME ./run_pyspark_from_build.sh -k test_small_file_memory
```
```
...
23/08/29 21:17:50 ERROR executor.Executor: [Executor task launch worker for task 2.0 in stage 5.0 (TID 2015)]: Exception in task 2.0 in stage 5.0 (TID 2015)
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_322]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_322]
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readPartFiles$7(GpuMultiFileReader.scala:1216) ~[spark3xx-common/:?]
	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readPartFiles$7$adapted(GpuMultiFileReader.scala:1215) ~[spark3xx-common/:?]
	at scala.collection.Iterator.foreach(Iterator.scala:943) ~[scala-library-2.12.15.jar:?]
	at scala.collection.Iterator.foreach$(Iterator.scala:943) ~[scala-library-2.12.15.jar:?]
...
```

As indicated above, this test was run manually on CDH.  As a control group, I was able to run the `window_function_test.py` on the same setup, without failures.
Additionally, `parquet_test.py::test_small_file_memory` runs properly on Apache Spark 3.2.x:
```
$ SPARK_HOME=$SPARK_HOME ./run_pyspark_from_build.sh -k test_small_file_memory
...
../../src/main/python/parquet_test.py::test_small_file_memory[] 23/08/29 21:20:32 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.datetimeRebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.datetimeRebaseModeInWrite' instead.
23/08/29 21:20:32 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.int96RebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.int96RebaseModeInWrite' instead.
23/08/29 21:20:42 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.int96RebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.int96RebaseModeInWrite' instead.
23/08/29 21:20:42 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.datetimeRebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.datetimeRebaseModeInWrite' instead.
PASSED   [ 50%]
../../src/main/python/parquet_test.py::test_small_file_memory[parquet] 23/08/29 21:20:45 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.datetimeRebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.datetimeRebaseModeInWrite' instead.
23/08/29 21:20:45 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.int96RebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.int96RebaseModeInWrite' instead.
23/08/29 21:20:53 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.int96RebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.int96RebaseModeInWrite' instead.
23/08/29 21:20:53 WARN SQLConf: The SQL config 'spark.sql.legacy.parquet.datetimeRebaseModeInWrite' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.parquet.datetimeRebaseModeInWrite' instead.
PASSED [100%]
```

**Comment by mythrocks** [comment]
I should point out that this is a pre-existing test (to stress-test coalesced reads in Parquet). Literally 3 years ago: 7ac919b4eea9a40c39bbf583a10bd8f6b19648bb.

**Comment by mythrocks** [comment]
I'm wondering if this message has anything to do with the problem:
```
23/08/29 22:00:16 WARN  rapids.MultiFileReaderThreadPool: [Executor task launch worker for task 2.0 in stage 5.0 (TID 2015)]: Configuring the file reader thread pool with a max of 128 threads instead of spark.rapids.sql.multiThreadedRead.numThreads = 20
23/08/29 22:00:16 WARN  rapids.MultiFileReaderThreadPool: [Executor task launch worker for task 3.0 in stage 5.0 (TID 2016)]: Configuring the file reader thread pool with a max of 128 threads instead of spark.rapids.sql.multiThreadedRead.numThreads = 20
23/08/29 22:00:16 WARN  rapids.MultiFileReaderThreadPool: [Executor task launch worker for task 0.0 in stage 5.0 (TID 2013)]: Configuring the file reader thread pool with a max of 128 threads instead of spark.rapids.sql.multiThreadedRead.numThreads = 20
23/08/29 22:00:16 WARN  rapids.MultiFileReaderThreadPool: [Executor task launch worker for task 1.0 in stage 5.0 (TID 2014)]: Configuring the file reader thread pool with a max of 128 threads instead of spark.rapids.sql.multiThreadedRead.numThreads = 20
```

**Comment by mythrocks** [comment]
I've done some more digging. I think this might have to do with resetting the thread pool size or something.

Here is an easy repro:
```
spark-shell --jars /home/cloudera/mithunr/spark-rapids/dist/target/rapids-4-spark_2.12-23.10.0-SNAPSHOT-cuda11.jar --conf sparns=com.nvidia.spark.SQLPlugin --conf spark.rapids.sql.explain=ALL --conf spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistrator --conf fs.defaultFS="file:///" --conf spark.rapids.sql.format.parquet.reader.type=COALESCING --conf spark.sql.sources.useV1SourceList="" --conf spark.sql.files.maxPartitionBytes=1g --master local[1]
```
```scala
// Write corpus.
spark.conf.set("spark.rapids.sql.enabled", false)
(0 to 2048).toDF.repartition(2000).write.mode("overwrite").parquet("file:///tmp/myth_parq_ints")

// Read for boom.
spark.conf.set("spark.rapids.sql.enabled", true)
spark.read.parquet("file:///tmp/myth_parq_ints").show
```
It does not matter if the data resides on HDFS or local disk.

**Comment by mythrocks** [comment]
More experiments:  
1. Same node, with Apache Spark 3.3.0: It didn't look like the coalesced Parquet reader had any logic specific to CDH.
On the same large (CPU-count) node, I ran the `COALESCING` reader test against Apache Spark 3.3.0 instead of CDH. The result was identical: OOM crash. 
2. The read succeeds if Spark is started up with `PERFILE` reader, and then changed to `COALESCING`.

**Comment by jlowe** [comment]
What is the executor core count set to on the cluster?  Is the test running in local mode or in cluster mode?

**Comment by jlowe** [comment]
I think this is related to #9051.  I suspect we were using the incorrect driver core count instead of the (I suspect larger) executor core count when setting up the multithreaded reader pool.  Easiest fix is to give the executors more heap space on the cloudera cluster setup if that's possible.  Long-term fix is budgeting host memory usage.  This initiative is underway for off-heap memory, but this is a heap OOM.  Would be interesting to get a heap dump on OOM to see what's taking up all the heap space.

**Comment by mythrocks** [comment]
> What is the executor core count set to on the cluster? Is the test running in local mode or in cluster mode?

I've run it in local mode, for both CDH and Apache Spark. I have set `--master local[1]`.  That should imply a single core, no? 

I've captured a heap-dump on OOM. Analyzing it now.

**Comment by mythrocks** [comment]
Heap dump indicates that there are 128 `java.lang.Thread`s, each holding about 8MB Java local `byte[]`. That exhausts the default 1GB heap in my runs.  IMO this implies that the large core count might be part of the problem.

I see that the `COALESCING` multi-threaded Parquet reader decides to use `128` threads in its memory pool, thereby exhausting the heap.
```
23/08/30 22:09:33 WARN MultiFileReaderThreadPool: Configuring the file reader thread pool with a max of 128 threads instead of spark.rapids.sql.multiThreadedRead.numThreads = 20
```
This is with `spark.executor.cores` not set to anything, probably causing the pool to consume all available CPUs.

There might be a couple of ways around the OOM:
1. As @jlowe suggested already, we could bump the heap for the test. (In my run, `--driver-memory 8g` worked, even with 128 threads.)
2. We could set `spark.executor.cores` to a specific, smaller value.

I'm inclined to try the latter. I'll update here with results.

**Comment by jlowe** [comment]
We may want to revisit the 8MB heap buffer that is being used.  This was copied from some existing Parquet reading code and could make sense to produce large, chunky reads, especially for cloud applications, but asking for 8MB when there are hundreds of threads is...problematic.  We may want to automatically scale that buffer size based on the number of threads or simply use a smaller value for the temporary buffer.

**Comment by mythrocks** [comment]
Ah, it turns out that one can't simply set `spark.executor.cores` for a specific test (`test_small_file_memory`). The Spark application is already up by that point.

One option is to set `spark.executor.cores` in `run_pyspark_from_build.sh`. I don't know if that would be acceptable.

**Comment by mythrocks** [comment]
There is a tentative workaround to get this test to run on the large CDH nodes here:
https://github.com/NVIDIA/spark-rapids/pull/9177.

The more robust fix (to size the Parquet reader's buffers "appropriately") may be tackled later on.

**Comment by mythrocks** [comment]
I have raised #9269 and #9271 to mitigate this problem.

**Comment by pxLi** [comment]
We also saw this case failed OOM constantly while testing in arm environment (GPU: A30)

**Comment by mythrocks** [comment]
It stands to reason that it fails.  :/ High core count, with low heap allocation.
