### ISSUE TITLE
[BUG]Range window-functions with non-timestamp order-by expressions not falling back to CPU

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#925]
**Describe the bug**
We have a user trying to do an orderby on a non-timestamp column over a range and its throwing an exception at the CUDF level:

Caused by: ai.rapids.cudf.CudfException: cuDF failure at: /ansible-managed/jenkins-slave/slave2/workspace/spark/cudf_release/cpp/src/rolling/rolling.cu:1157: Unsupported data-type for `timestamp`-based rolling window operation!
	at ai.rapids.cudf.Table.timeRangeRollingWindowAggregate(Native Method)
	at ai.rapids.cudf.Table.access$2800(Table.java:35)
	at ai.rapids.cudf.Table$AggregateOperation.aggregateWindowsOverTimeRanges(Table.java:1906)
	at com.nvidia.spark.rapids.GpuWindowExpression.evaluateRangeBasedWindowExpression(GpuWindowExpression.scala:211)
	at com.nvidia.spark.rapids.GpuWindowExpression.columnarEval(GpuWindowExpression.scala:119)

This should have ideally fell back to the CPU.

**Comment by tgravescs** [comment]
this was partially fixed by the lead/lag feature. I found one issue with the handling of nullable columns so will fix that under this issue
