### ISSUE TITLE
[BUG] close called too many times ColumnVector

### ISSUE THREAD

**Issue by rongou** [NVIDIA/spark-rapids#936]
**Describe the bug**
Got this while running TPCxBB query 22. It seems to happen for both legacy and per-thread default stream. Shuffle manager is enabled.

**Steps/Code to reproduce bug**
Run TPCxBB query 22 on a 12GB Titan V, the exception is thrown fairly reliably.

**Expected behavior**
Should not throw exception.

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark configuration settings related to the issue
```bash
 --conf spark.shuffle.manager=com.nvidia.spark.rapids.spark301.RapidsShuffleManager\
 --conf spark.rapids.sql.concurrentGpuTasks=6\
 --conf spark.sql.shuffle.partitions=6\
 --conf spark.sql.files.maxPartitionBytes=168m
```

**Additional context**
Here is the stack trace:
```console
20/10/13 14:13:38 WARN TaskSetManager: Lost task 3.0 in stage 22.0 (TID 30, 127.0.0.1, executor 0): java.lang.IllegalStateException: Close called too many times ColumnVector{rows=31671561, type=INT64, nullCount=Optional.empty, offHeap=(ID: 589 0)}
	at ai.rapids.cudf.ColumnVector.close(ColumnVector.java:271)
	at com.nvidia.spark.rapids.GpuColumnVector.close(GpuColumnVector.java:389)
	at org.apache.spark.sql.vectorized.ColumnarBatch.close(ColumnarBatch.java:48)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableColumn.safeClose(implicits.scala:56)
	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:58)
	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:53)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.closeOnExcept(GpuCoalesceBatches.scala:115)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1(GpuCoalesceBatches.scala:172)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1$adapted(GpuCoalesceBatches.scala:170)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.withResource(GpuCoalesceBatches.scala:115)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:170)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:206)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:206)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:206)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$doExecuteColumnar$1(aggregate.scala:420)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abellina** [comment]
@rongou, I think this was called as a response to an exception. `closeOnExcept` calls `safeClose` if the function body blows up.  Was there another exception also thrown here?

Not saying that there isn't a bug that is causing is to close too much.

**Comment by jlowe** [comment]
`safeClose` is not supposed to clobber the exception but instead add any exception as a suppressed exception on the current exception.  Looks like that is busted.  I'll post a PR to fix it shortly.

**Comment by jlowe** [comment]
@rongou it would be good to try the patch in #940 which should expose the underlying exception that was trying to be thrown.  I agree with @abellina that there's still a double-close to fix here for proper exception handling independent of the error that triggered it.

**Comment by rongou** [comment]
Patched it in and seems to be doing the right thing now:
```console
20/10/14 19:22:32 WARN TaskSetManager: Lost task 3.0 in stage 32.0 (TID 118, 127.0.0.1, executor 0): java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: CUDA error at: /home/rou/miniconda3/envs/cudf_dev/include/rmm/mr/device/cuda_memory_resource.hpp:68: cudaErrorMemoryAllocation out of memory
	at ai.rapids.cudf.Table.contiguousSplit(Native Method)
	at ai.rapids.cudf.Table.contiguousSplit(Table.java:1584)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$5(SpillableColumnarBatch.scala:158)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$5$adapted(SpillableColumnarBatch.scala:157)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.withResource(SpillableColumnarBatch.scala:115)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$4(SpillableColumnarBatch.scala:157)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.$anonfun$addBatch$4$adapted(SpillableColumnarBatch.scala:156)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.withResource(SpillableColumnarBatch.scala:115)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.addBatch(SpillableColumnarBatch.scala:156)
	at com.nvidia.spark.rapids.SpillableColumnarBatch$.apply(SpillableColumnarBatch.scala:128)
	at com.nvidia.spark.rapids.GpuCoalesceIterator.saveOnDeck(GpuCoalesceBatches.scala:461)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$2(GpuCoalesceBatches.scala:177)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$2$adapted(GpuCoalesceBatches.scala:172)
	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:55)
	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:53)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.closeOnExcept(GpuCoalesceBatches.scala:115)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1(GpuCoalesceBatches.scala:172)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.$anonfun$hasNext$1$adapted(GpuCoalesceBatches.scala:170)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.withResource(GpuCoalesceBatches.scala:115)
	at com.nvidia.spark.rapids.AbstractGpuCoalesceIterator.hasNext(GpuCoalesceBatches.scala:170)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:206)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:206)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.shims.spark300.GpuHashJoin$$anon$1.hasNext(GpuHashJoin.scala:206)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at com.nvidia.spark.rapids.GpuHashAggregateExec.$anonfun$doExecuteColumnar$1(aggregate.scala:420)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: Close called too many times ColumnVector{rows=30927211, type=INT64, nullCount=Optional.empty, offHeap=(ID: 8181 0)}
		at ai.rapids.cudf.ColumnVector.close(ColumnVector.java:267)
		at com.nvidia.spark.rapids.GpuColumnVector.close(GpuColumnVector.java:389)
		at org.apache.spark.sql.vectorized.ColumnarBatch.close(ColumnarBatch.java:48)
		at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableColumn.safeClose(implicits.scala:51)
		at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:58)
		... 34 more
```

**Comment by rongou** [comment]
This was just an OOM error
