### ISSUE TITLE
[QST] Couldn't start UcpListener

### ISSUE THREAD

**Issue by Nikhilpa1** [NVIDIA/spark-rapids#9386]
While running the TPC-DS benchmark with the Spark Rapids project, I encountered a warning in the logs indicating a problem related to the UcpListener and port range. Here's the specific error message:
`WARN TaskSetManager: Lost task 0.0 in stage 45.0 (TID 12171) (10.1.1.10 executor 2): java.net.BindException: Couldn't start UcpListener on port range 52897-52913
	at com.nvidia.spark.rapids.shuffle.ucx.UCX$UcpEndpointManager.startListener(UCX.scala:985)
	...
`
Here's the Spark configuration:
`export SPARK_CONF=(
    "--master" "spark://${SPARK_MASTER}:7077"
    "--deploy-mode" "client"
    "--conf" "spark.executor.resource.gpu.amount=1"
    "--conf" "spark.executor.extraClassPath=${SPARK_RAPIDS_PLUGIN_JAR}"
    "--conf" "spark.driver.extraClassPath=${SPARK_RAPIDS_PLUGIN_JAR}"
    "--conf" "spark.rapids.sql.concurrentGpuTasks=1"
    "--conf" "spark.driver.memory=1G"
    "--conf" "spark.executor.memory=1G"
    "--conf" "spark.executor.cores=1"
    "--conf" "spark.task.cpus=1"
    "--conf" "spark.executor.resource.gpu.amount=1"
    "--conf" "spark.task.resource.gpu.amount=0.25"
    "--conf" "spark.rapids.memory.pinnedPool.size=1G"
    "--conf" "spark.sql.files.maxPartitionBytes=128m"
    "--conf" "spark.plugins=com.nvidia.spark.SQLPlugin"
    "--conf" "spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh"
    "--files" "/home/kanaka.3/spark-rapids-project/sparkRapidsPlugin/getGpusResources.sh"
    "--conf" "spark.shuffle.manager=com.nvidia.spark.rapids.spark330.RapidsShuffleManager"
    "--conf" "spark.rapids.shuffle.mode=UCX"
    "--conf" "spark.shuffle.service.enabled=false"
    "--conf" "spark.dynamicAllocation.enabled=false"
    "--conf" "spark.executorEnv.UCX_ERROR_SIGNALS="
    "--conf" "spark.executorEnv.UCX_MEMTYPE_CACHE=n"
    "--conf" "spark.executorEnv.UCX_IB_RX_QUEUE_LEN=1024"
    "--conf" "spark.executorEnv.UCX_RNDV_SCHEME=put_zcopy"
    "--conf" "spark.executorEnv.UCX_MAX_RNDV_RAILS=1"
    "--conf" "spark.executorEnv.UCX_TLS=tcp,cuda_copy,cuda_ipc,rc"
    "--conf" "spark.executorEnv.UCX_NET_DEVICES=en0,mlx5_0:1"
)
`
UCX was configured with the following options:
--build=x86_64-redhat-linux-gnu
--host=x86_64-redhat-linux-gnu
--enable-mt
--disable-params-check
--enable-cma
--with-cuda=/opt/cuda/11.8
--with-gdrcopy=/opt/gdrcopy/2.3
--with-verbs
--without-cm
--with-rdmacm
--with-rocm
--without-xpmem
--without-ugni

**Comment by abellina** [comment]
Hello @Nikhilpa1!

It seems that the TCP ports in the range logged are failing to be bound by our socket.

You can set the starting port we will attempt using `spark.rapids.shuffle.ucx.listenerStartPort`. By default we will try 16 times (`spark.port.maxRetries`) by starting at a port and going up by one in case a retry is needed. 

If you don't set `listenerStartPort` we start trying at a random port above 1024.

**Comment by Nikhilpa1** [comment]
I tried mentioning the listener start port(through `spark.rapids.shuffle.ucx.listenerStartPort`) that I used when running the perf_test, and even then, I am encountering the same error. Do you have any suggestions?

**Comment by abellina** [comment]
@Nikhilpa1 for some reason the executors are not able to bind to the tcp ports and I am not sure why. Is this running under a container by any chance?

One thing we can try is looking at the UCX logs (`spark.executorEnv.UCX_LOG_LEVEL=info`, then `spark.executorEnv.UCX_LOG_FILE=/tmp/ucx_%h_%p.log`) should give us some UCX-level logs.

Also, I'd try without:
```
"--conf" "spark.executorEnv.UCX_TLS=tcp,cuda_copy,cuda_ipc,rc"
"--conf" "spark.executorEnv.UCX_NET_DEVICES=en0,mlx5_0:1"
```
to see if UCX will pick the right interfaces to use.

**Comment by Nikhilpa1** [comment]
No, it is not running on a container. 
Trying without 
`"--conf" "spark.executorEnv.UCX_TLS=tcp,cuda_copy,cuda_ipc,rc"
"--conf" "spark.executorEnv.UCX_NET_DEVICES=en0,mlx5_0:1"`
didn't help. Please let me know if you need more info about the system or on the run.

Additionally, Can I get the details of the configuration specifics that were used to compare ucx on vs off performance.

**Comment by abellina** [comment]
> One thing we can try is looking at the UCX logs (spark.executorEnv.UCX_LOG_LEVEL=info, then spark.executorEnv.UCX_LOG_FILE=/tmp/ucx_%h_%p.log) should give us some UCX-level logs.

@Nikhilpa1 were you able to generate a log file with the above? This would be helpful.

> Additionally, Can I get the details of the configuration specifics that were used to compare ucx on vs off performance.

Please take a look a this GTC presentation for results we have presented in the past: https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s31822/.

**Comment by Nikhilpa1** [comment]
> Were you able to generate a log file with the above? This would be helpful.
Yes.
[1697552387.833492] [gpu11:19890:0]          parser.c:2000 UCX  INFO  UCX_* env variables: UCX_MEMTYPE_CACHE=n UCX_MAX_RNDV_RAILS=1 UCX_LOG_FILE=/home/kanaka.3/tmp/ucx_with_only_net.log UCX_RNDV_SCHEME=put_zcopy UCX_NET_DEVICES=en0,mlx5_0:1 UCX_LOG_LEVEL=info UCX_ERROR_SIGNALS= UCX_IB_RX_QUEUE_LEN=1024
[1697552387.850624] [gpu11:19890:0] rdmacm_listener.c:83   UCX  DIAG  rdma_bind_addr(addr=10.1.1.11:50956) failed: No such device
[1697552387.850642] [gpu11:19890:0]    ucp_listener.c:245  UCX  DIAG  failed to create UCT listener on CM 0x2ac175ab25b0 (component rdmacm) with address 10.1.1.11:50956 status No such device
[1697552387.871581] [gpu11:19890:a]       rdmacm_cm.c:712  UCX  DIAG  [cep 0x2ac1bc029990 <invalid>->10.1.1.10:8368 client Success] got error event RDMA_CM_EVENT_ADDR_ERROR, event status No such device (-19)
[1697552387.871606] [gpu11:19890:a]          uct_cm.c:100  UCX  DIAG  resolve callback failed with error: Destination is unreachable
[1697552387.871939] [gpu11:19890:1]       wireup_cm.c:91   UCX  DIAG  ep 0x2abe4ffa20b0: client switching from rdmacm to tcp in attempt to connect to the server
[1697552387.872051] [gpu11:19890:a]       rdmacm_cm.c:712  UCX  DIAG  [cep 0x2ac1bc02a040 <invalid>->10.1.1.12:23238 client Success] got error event RDMA_CM_EVENT_ADDR_ERROR, event status No such device (-19)
[1697552387.872061] [gpu11:19890:a]          uct_cm.c:100  UCX  DIAG  resolve callback failed with error: Destination is unreachable
[1697552387.872078] [gpu11:19890:1]       wireup_cm.c:91   UCX  DIAG  ep 0x2abe4ffa2108: client switching from rdmacm to tcp in attempt to connect to the server
[1697552387.872843] [gpu11:19890:1]      ucp_worker.c:1783 UCX  INFO  ep_cfg[2]: tag(tcp/en0) am(tcp/en0)
[1697552387.876788] [gpu11:19890:1]      ucp_worker.c:1783 UCX  INFO      ep_cfg[3]: tag(tcp/en0) am(tcp/en0)
[1697552387.877323] [gpu11:19890:1]      ucp_worker.c:1783 UCX  INFO    ep_cfg[4]: tag(rc_mlx5/mlx5_0:1) am(rc_mlx5/mlx5_0:1) ka(ud_mlx5/mlx5_0:1)

**Comment by abellina** [comment]
@yosefe @petro-rudenko any ideas on what is happening with this?
```
[1697552387.850624] [gpu11:19890:0] rdmacm_listener.c:83 UCX DIAG rdma_bind_addr(addr=10.1.1.11:50956) failed: No such device
[1697552387.850642] [gpu11:19890:0] ucp_listener.c:245 UCX DIAG failed to create UCT listener on CM 0x2ac175ab25b0 (component rdmacm) with address 10.1.1.11:50956 status No such device
```

It looks like the NIC with IP address 10.1.1.11 doesn't support RDMACM but we are attempting it? 

@Nikhilpa1 one attempt you can make is disabling RDMACM, as a test:

Please set `spark.executorEnv.UCX_SOCKADDR_TLS_PRIORITY=tcp,sockcm`. Also please share logs when you run with ths environment variable. And thanks!!!

**Comment by Nikhilpa1** [comment]
Thanks for the response.
Disabling rdma with `spark.executorEnv.UCX_SOCKADDR_TLS_PRIORITY=tcp,sockcm` worked fine..
[1697557791.108393] [gpu12:8008 :0]          parser.c:2000 UCX  INFO  UCX_* env variables: UCX_MEMTYPE_CACHE=n UCX_MAX_RNDV_RAILS=1 UCX_RNDV_SCHEME=put_zcopy UCX_SOCKADDR_TLS_PRIORITY=tcp,sockcm UCX_NET_DEVICES=en0,mlx5_0:1 UCX_LOG_LEVEL=info UCX_ERROR_SIGNALS= UCX_IB_RX_QUEUE_LEN=1024
[1697557791.174517] [gpu12:8008 :1]      ucp_worker.c:1783 UCX  INFO  ep_cfg[2]: tag(tcp/en0) am(tcp/en0)
[1697557791.178327] [gpu12:8008 :1]      ucp_worker.c:1783 UCX  INFO      ep_cfg[3]: tag(tcp/en0) am(tcp/en0)
[1697557791.178942] [gpu12:8008 :1]      ucp_worker.c:1783 UCX  INFO    ep_cfg[4]: tag(rc_mlx5/mlx5_0:1) am(rc_mlx5/mlx5_0:1) ka(ud_mlx5/mlx5_0:1)
But, I am still facing
23/10/17 11:48:02 ERROR TaskSchedulerImpl: Lost executor 11 on 10.1.1.12: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.

**Comment by Nikhilpa1** [comment]
In executor logs,

ERROR BlockManagerStorageEndpoint: Error in removing shuffle 109
java.lang.IllegalStateException: An executor with RapidsShuffleManager is trying to use a ShuffleBufferCatalog that isn't initialized.
        at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.resolver$lzycompute(RapidsShuffleInternalManagerBase.scala:1152)
        at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.resolver(RapidsShuffleInternalManagerBase.scala:1136)
        at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.shuffleBlockResolver(RapidsShuffleInternalManagerBase.scala:1409)
        at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.unregisterShuffle(RapidsShuffleInternalManagerBase.scala:1393)
        at org.apache.spark.sql.rapids.ProxyRapidsShuffleInternalManagerBase.unregisterShuffle(RapidsShuffleInternalManagerBase.scala:1486)
        at org.apache.spark.storage.BlockManagerStorageEndpoint$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$3(BlockManagerStorageEndpoint.scala:61)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.spark.storage.BlockManagerStorageEndpoint.$anonfun$doAsync$1(BlockManagerStorageEndpoint.scala:89)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by abellina** [comment]
Ok, mind providing the beginning of the executor log? (Up until when you start getting assigned tasks). 

We should see us start to get memory for the GPU and what seems to be happening is that we are not fully initializing. This could happen if the version of Spark running in the executors is somehow different than the one running on the driver as we are looking to match that the classname provided under `spark.shuffle.manager` is the one that would match our shim (for Spark 3.3.0 in this case).

**Comment by Nikhilpa1** [comment]
I've double-checked the version of Spark with the shim, and it is 3.3.0.
I have the executor logs here. Please use it for your reference.
[stdout.zip](https://github.com/NVIDIA/spark-rapids/files/12936525/stdout.zip)

**Comment by abellina** [comment]
The log here shows that executorId 2 died had an issue, so we stopped the connection. I don't see the exception you are seeing above.

I think we should try `UCX_TLS=tcp,cuda_copy,cuda_ipc` to remove RDMA alltogether, and I'll try to repro this on my side.

**Comment by Nikhilpa1** [comment]
Using `UCX_TLS=tcp,cuda_copy,cuda_ipc` fixed the issue of lost executors, but the performance improvement with UCX is minimal.

**Comment by abellina** [comment]
Ok, that's good and bad :) 

At least we know there's some sort of issue with the RDMA part and that it is inside of UCX. Can you remove the UCX_TLS setting and share the UCX logs for all executors? That will help triage what is happening there.

In terms of the improvement: how much are you shuffling? Do you spend a lot of time blocked in shuffle before?

One of the big benefits we get with UCX is in the writes: because we are caching all the GPU blocks instead of writing them to files. That said, if the size of shuffle is rather large and causes us to spill, we will copy those raw bytes to disk on the spill (it doesn't go through the regular Spark compression/encryption (if enabled) pipe).

That said, if you are spending enough time writing shuffle before and all the bytes were to fit in GPU memory, I'd expect some performance improvement here because we are not writing to disk.

On the read, there seems to be an issue in your setup where RDMA isn't 100% there. Could you share the output of `ucx_info -d`? That would help the UCX team tell us what is missing.

**Comment by Nikhilpa1** [comment]
>Can you remove the UCX_TLS setting and share the UCX logs for all executors?
When run without UCX_TLS setting, facing lost executor,
[Archive.zip](https://github.com/NVIDIA/spark-rapids/files/12940505/Archive.zip)

>Could you share the output of ucx_info -d?
Please find it here: [ucx_info_d.txt](https://github.com/NVIDIA/spark-rapids/files/12941147/ucx_info_d.txt)

**Comment by abellina** [comment]
It seems you have 3 machines: 10.1.1.10, 10.1.1.11, 10.1.1.12. I see 1 executor in .10, 3 executors in .11, and 3 executors in .12. 

Could you please run ucx_info -d in each machine?

Could you also, please capture the UCX log for each machine? 

For the` ucx_info -d` you provided, it seems to be OK. I see both en0 and mlx5_0:1. @yosefe @petro-rudenko fyi.

**Comment by Nikhilpa1** [comment]
> Could you please run ucx_info -d in each machine?

[ucx_info.zip](https://github.com/NVIDIA/spark-rapids/files/12946785/ucx_info.zip)

> Could you also, please capture the UCX log for each machine?
[ucx_logs_all_executors.log](https://github.com/NVIDIA/spark-rapids/files/12947513/ucx_logs_all_executors.log)

**Comment by abellina** [comment]
Thanks @Nikhilpa1 I meant without UCX_TLS or UCX_SOCKADDR_TLS_PRIORITY changes, so it would fail. I just want to see what each executor is seeing... thank you!

**Comment by abellina** [comment]
This is great @Nikhilpa1 !

```
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[gpu12:2007 :1:2106]     ib_mlx5.c:1114 Assertion `(num_bb > 0) && (num_bb <= 4)' failed: num_bb=6

/home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/ib/mlx5/ib_mlx5.c: [ uct_ib_mlx5_txwq_validate_always() ]
      ...
     1110     uint16_t hw_ci;
     1111 
     1112     /* num_bb must be non-zero and not larger than MAX_BB */
==>  1113     ucs_assertv((num_bb > 0) && (num_bb <= UCT_IB_MLX5_MAX_BB), "num_bb=%u",
     1114                 num_bb);
     1115 
     1116     /* bb_max must be smaller than the full QP length */

==== backtrace (tid:   2106) ====
 0 0x000000000002af1a uct_ib_mlx5_txwq_validate_always()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/ib/mlx5/ib_mlx5.c:1113
 1 0x000000000003f024 uct_ib_mlx5_txwq_validate()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/ib/mlx5/ib_mlx5.inl:193
 2 0x000000000003f024 uct_rc_mlx5_common_post_send()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/ib/rc/accel/rc_mlx5.inl:462
 3 0x000000000003f024 uct_rc_mlx5_txqp_inline_iov_post()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/ib/rc/accel/rc_mlx5.inl:499
 4 0x000000000003f024 uct_rc_mlx5_ep_am_short_iov_inline()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/ib/rc/accel/rc_mlx5_ep.c:111
 5 0x000000000003f024 uct_rc_mlx5_ep_am_short_iov()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/ib/rc/accel/rc_mlx5_ep.c:309
 6 0x000000000002cd78 uct_ep_am_short_iov()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/api/uct.h:3008
 7 0x000000000002cd78 ucp_am_contig_short()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucp/core/ucp_am.c:582
 8 0x00000000000ec2b5 ucp_request_try_send()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucp/core/ucp_request.inl:334
 9 0x00000000000ec2b5 ucp_request_send()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucp/core/ucp_request.inl:357
10 0x00000000000ec2b5 ucp_wireup_replay_pending_request()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucp/wireup/wireup.c:984
11 0x00000000000ec2b5 ucp_wireup_replay_pending_requests()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucp/wireup/wireup.c:996
12 0x00000000000ec78d ucp_wireup_eps_progress()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucp/wireup/wireup.c:503
13 0x0000000000055593 ucs_callbackq_slow_proxy()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucs/datastruct/callbackq.c:404
14 0x000000000005ba5a ucs_callbackq_dispatch()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucs/datastruct/callbackq.h:211
15 0x000000000005ba5a uct_worker_progress()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/uct/api/uct.h:2768
16 0x000000000005ba5a ucp_worker_progress()  /home/kanaka.3/projects/sources/ucx-1.14.0/src/ucp/core/ucp_worker.c:2807
=================================
```
^^^^ @petro-rudenko @yosefe @sameerz  FYI. I need some help from the UCX team to figure out what is wrong in this scenario, but @Nikhilpa1's environment is triggering asserts and we are seeing this stack trace in several executors. Please see logs provided.
