### ISSUE TITLE
Fix Integration Test Failures related to udf_test.py

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#9493]

**Comment by razajafri** [comment]
This is the exception that I see when I run either of the tests above. 

```
23/10/27 03:12:01 ERROR SQLUsageLogging: Exception while logging query profile
org.apache.spark.SparkException: [INTERNAL_ERROR] UnevaluableAggregateFunc.aggBufferSchema should not be called.
        at org.apache.spark.SparkException$.internalError(SparkException.scala:85)
        at org.apache.spark.SparkException$.internalError(SparkException.scala:89)
        at org.apache.spark.sql.catalyst.expressions.UnevaluableAggregateFunc.aggBufferSchema(PythonUDF.scala:109)
        at org.apache.spark.sql.catalyst.expressions.aggregate.AggregateFunction.hasFixedSizeBuffer(interfaces.scala:359)
        at com.databricks.sql.serialization.marshalling.FallbackAggregateFunctionMarshaller$.tryToProto(ExpressionMarshaller.scala:231)
        at com.databricks.sql.serialization.marshalling.FallbackAggregateFunctionMarshaller$.tryToProto(ExpressionMarshaller.scala:220)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.$anonfun$tryToProto$1(interfaces.scala:154)
        at scala.Option.orElse(Option.scala:447)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$2.toProto(interfaces.scala:173)
        at com.databricks.sql.serialization.marshalling.ExpressionMarshaller$.toProto(ExpressionMarshaller.scala:57)
        at com.databricks.sql.serialization.marshalling.MarshallingContextImpl.toProto(interfaces.scala:96)
        at com.databricks.sql.serialization.marshalling.ExpressionChildWriter.writeExpression(childUtils.scala:300)
        at com.databricks.sql.serialization.marshalling.AggregateExpressionMarshaller$.buildProto(singleExpressionTypeMarshallers.scala:249)
        at com.databricks.sql.serialization.marshalling.AggregateExpressionMarshaller$.buildProto(singleExpressionTypeMarshallers.scala:245)
        at com.databricks.sql.serialization.marshalling.SingleTagExpressionMarshaller.toProto(ExpressionMarshaller.scala:111)
        at com.databricks.sql.serialization.marshalling.SingleTagExpressionMarshaller.toProto$(ExpressionMarshaller.scala:72)
        at com.databricks.sql.serialization.marshalling.SingleExpressionTypeMarshaller.toProto(ExpressionMarshaller.scala:280)
        at com.databricks.sql.serialization.marshalling.SingleExpressionTypeMarshaller.toProto(ExpressionMarshaller.scala:280)
        at com.databricks.sql.serialization.marshalling.SingleTypeMarshallerRegistry.$anonfun$tryToProto$1(singleTypeMarshallers.scala:100)
        at scala.Option.map(Option.scala:230)
        at com.databricks.sql.serialization.marshalling.SingleTypeMarshallerRegistry.tryToProto(singleTypeMarshallers.scala:100)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$2.toProto(interfaces.scala:173)
        at com.databricks.sql.serialization.marshalling.ExpressionMarshaller$.toProto(ExpressionMarshaller.scala:57)
        at com.databricks.sql.serialization.marshalling.MarshallingContextImpl.toProto(interfaces.scala:96)
        at com.databricks.sql.serialization.marshalling.ExpressionChildWriter.$anonfun$writeExpressions$1(childUtils.scala:313)
        at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
        at scala.collection.immutable.StreamIterator.$anonfun$next$1(Stream.scala:1061)
        at scala.collection.immutable.StreamIterator$LazyCell.v$lzycompute(Stream.scala:1050)
        at scala.collection.immutable.StreamIterator$LazyCell.v(Stream.scala:1050)
        at scala.collection.immutable.StreamIterator.hasNext(Stream.scala:1055)
        at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:32)
        at com.google.protobuf.AbstractMessageLite$Builder.checkForNullValues(AbstractMessageLite.java:348)
        at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:335)
        at com.databricks.sql.serialization.protobuf.ChildExpressionList$Builder.addAllExpressions(ChildExpressionList.java:1047)
        at com.databricks.sql.serialization.marshalling.ExpressionChildWriter.writeExpressions(childUtils.scala:313)
        at com.databricks.sql.serialization.marshalling.UnknownSparkPlanMarshaller.buildProto(UnknownSparkPlanMarshaller.scala:38)
        at com.databricks.sql.serialization.marshalling.UnknownSparkPlanMarshaller.buildProto$(UnknownSparkPlanMarshaller.scala:33)
        at com.databricks.sql.serialization.marshalling.FallbackSparkPlanMarshaller$.buildProto(SparkPlanMarshaller.scala:603)
        at com.databricks.sql.serialization.marshalling.FallbackSparkPlanMarshaller$.toProto(SparkPlanMarshaller.scala:612)
        at com.databricks.sql.serialization.marshalling.FallbackSparkPlanMarshaller$.toProto(SparkPlanMarshaller.scala:603)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$2.$anonfun$toProto$1(interfaces.scala:173)
        at scala.Option.getOrElse(Option.scala:189)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$2.toProto(interfaces.scala:173)
        at com.databricks.sql.serialization.marshalling.SparkPlanMarshaller$.toProto(SparkPlanMarshaller.scala:55)
        at com.databricks.sql.serialization.marshalling.MarshallingContextImpl.toProto(interfaces.scala:94)
        at com.databricks.sql.serialization.marshalling.SparkPlanChildWriter.writePlan(childUtils.scala:339)
        at com.databricks.sql.serialization.marshalling.ShuffleExchangeExecMarshaller$.buildProto(singleSparkPlanTypeMarshallers.scala:941)
        at com.databricks.sql.serialization.marshalling.ShuffleExchangeExecMarshaller$.buildProto(singleSparkPlanTypeMarshallers.scala:932)
        at com.databricks.sql.serialization.marshalling.SingleSparkPlanTypeMarshaller.toProto(SparkPlanMarshaller.scala:670)
        at com.databricks.sql.serialization.marshalling.SingleSparkPlanTypeMarshaller.toProto(SparkPlanMarshaller.scala:662)
        at com.databricks.sql.serialization.marshalling.SingleTypeMarshallerRegistry.$anonfun$tryToProto$1(singleTypeMarshallers.scala:100)
        at scala.Option.map(Option.scala:230)
        at com.databricks.sql.serialization.marshalling.SingleTypeMarshallerRegistry.tryToProto(singleTypeMarshallers.scala:100)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$2.toProto(interfaces.scala:173)
        at com.databricks.sql.serialization.marshalling.SparkPlanMarshaller$.toProto(SparkPlanMarshaller.scala:55)
        at com.databricks.sql.serialization.marshalling.MarshallingContextImpl.toProto(interfaces.scala:94)
        at com.databricks.sql.serialization.marshalling.SparkPlanChildWriter.writePlan(childUtils.scala:339)
        at com.databricks.sql.serialization.marshalling.SortExecMarshaller$.buildProto(singleSparkPlanTypeMarshallers.scala:244)
        at com.databricks.sql.serialization.marshalling.SortExecMarshaller$.buildProto(singleSparkPlanTypeMarshallers.scala:239)
        at com.databricks.sql.serialization.marshalling.SingleSparkPlanTypeMarshaller.toProto(SparkPlanMarshaller.scala:670)
        at com.databricks.sql.serialization.marshalling.SingleSparkPlanTypeMarshaller.toProto(SparkPlanMarshaller.scala:662)
        at com.databricks.sql.serialization.marshalling.SingleTypeMarshallerRegistry.$anonfun$tryToProto$1(singleTypeMarshallers.scala:100)
        at scala.Option.map(Option.scala:230)
        at com.databricks.sql.serialization.marshalling.SingleTypeMarshallerRegistry.tryToProto(singleTypeMarshallers.scala:100)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$1.tryToProto(interfaces.scala:154)
        at com.databricks.sql.serialization.marshalling.PartialMarshaller$$anon$2.toProto(interfaces.scala:173)
        at com.databricks.sql.serialization.marshalling.SparkPlanMarshaller$.toProto(SparkPlanMarshaller.scala:55)
        at com.databricks.sql.serialization.marshalling.MarshallingContextImpl.toProto(interfaces.scala:94)
        at com.databricks.sql.logging.QueryProfile$.toProto(QueryProfile.scala:570)
        at com.databricks.sql.logging.QueryProfile$.toProtoBase64(QueryProfile.scala:702)
        at com.databricks.sql.logging.SQLUsageLogging$.logQueryProfile(SQLUsageLogging.scala:251)
        at com.databricks.sql.logging.SQLUsageLogging$.tryLogQueryProfile(SQLUsageLogging.scala:301)
        at com.databricks.sql.logging.SQLUsageLogging$.$anonfun$tryLogQueryProfileWrapper$1(SQLUsageLogging.scala:384)
        at org.apache.spark.util.threads.SparkThreadLocalCapturingRunnable.$anonfun$run$1(SparkThreadLocalForwardingThreadPoolExecutor.scala:118)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at com.databricks.spark.util.IdentityClaim$.withClaim(IdentityClaim.scala:48)
        at org.apache.spark.util.threads.SparkThreadLocalCapturingHelper.$anonfun$runWithCaptured$4(SparkThreadLocalForwardingThreadPoolExecutor.scala:81)
        at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:41)
        at org.apache.spark.util.threads.SparkThreadLocalCapturingHelper.runWithCaptured(SparkThreadLocalForwardingThreadPoolExecutor.scala:80)
        at org.apache.spark.util.threads.SparkThreadLocalCapturingHelper.runWithCaptured$(SparkThreadLocalForwardingThreadPoolExecutor.scala:66)
        at org.apache.spark.util.threads.SparkThreadLocalCapturingRunnable.runWithCaptured(SparkThreadLocalForwardingThreadPoolExecutor.scala:115)
        at org.apache.spark.util.threads.SparkThreadLocalCapturingRunnable.run(SparkThreadLocalForwardingThreadPoolExecutor.scala:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)


```

**Comment by jlowe** [comment]
I was not able to reproduce the exception listed in the description, but I did see hangs.  It appears Databricks 13.3 has pulled in [SPARK-44705](https://issues.apache.org/jira/browse/SPARK-44705) which changes the Python worker handling to use a single thread rather than separate reader and writer threads.  That leads to hangs in UDF tests because our support assumes there are reader and writer threads.

**Comment by firestarman** [comment]
I have fixed the hangs, but there are still some failing tests. Will continue debugging.
