### ISSUE TITLE
[FEA] Build Spark snapshot versions 3.3 and greater for both scala 2.12 and 2.13

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9564]
**Is your feature request related to a problem? Please describe.**
We build spark snapshots and push for testing purposes.  I think we only build the scala 2.12, we should probably build for both scala versions (2.12 and 2.13)

**Comment by tgravescs** [comment]
@pxLi

**Comment by pxLi** [comment]
> @pxLi

ACK. Please help check if we could simply update internal profiles to support 2.13 build, 
we will try provide more pipelines when we have time

Before it, we would only test against release spark 2.13 versions

**Comment by tgravescs** [comment]
to change scala versions for anything < 4.0  the instructions are here:

https://spark.apache.org/docs/latest/building-spark.html#change-scala-version

> ./dev/change-scala-version.sh 2.13
> ./build/mvn -Pscala-2.13 ......

**Comment by NvTimLiu** [comment]
Checking, will create pipelines to build scala 2.13 SNAPSHOT spark artifacts

**Comment by NvTimLiu** [comment]
@tgravescs  Will we only build 3.3 SNAPSHOT against 2.13 binaries,

 or all the spark3.3+/3.4+/3.5+/4.0+ ?

**Comment by NvTimLiu** [comment]
Updated CI scripts, and uploaded 2.13 spark-3.5 artifacts onto internal maven repo.

**Comment by NvTimLiu** [comment]
Got an `StackOverflowError` error when build `spark3.4+ SNPASHPT` against scala2.13

Other spark SNPASHOT versions(3.3/3.5/4.0) seem have no such issue, not sure if this is a spark issue? 

cc @tgravescs  can you help to take a look (NGCC/spark3.4_deploy/286-288)? Thx~



```
[ERROR] ## Exception when compiling 608 sources to /ansible-managed/jenkins-slave/slave1/workspace/spark/spark3.4_deploy/sql/catalyst/target/scala-2.13/classes
 Exception in thread "main" java.lang.StackOverflowError
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
 	at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
 	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
 	at scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
 	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
 	at scala.reflect.internal.Trees$Select.transform(Trees.scala:852)
 	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
 	at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
 	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
 	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
 	at scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
```

**Comment by NvTimLiu** [comment]
> Got an `StackOverflowError` error when build `spark3.4+ SNPASHPT` against scala2.13
> 
> Other spark SNPASHOT versions(3.3/3.5/4.0) seem have no such issue, not sure if this is a spark issue?
> 
> cc @tgravescs can you help to take a look (NGCC/spark3.4_deploy/286-288)? Thx~
> 
> ```
> [ERROR] ## Exception when compiling 608 sources to /ansible-managed/jenkins-slave/slave1/workspace/spark/spark3.4_deploy/sql/catalyst/target/scala-2.13/classes
>  Exception in thread "main" java.lang.StackOverflowError
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
>  	at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
>  	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
>  	at scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
>  	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
>  	at scala.reflect.internal.Trees$Select.transform(Trees.scala:852)
>  	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
>  	at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
>  	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1489)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:712)
>  	at scala.tools.nsc.transform.CleanUp$CleanUpTransformer.transform(CleanUp.scala:37)
>  	at scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
> ```

The JDK8 StackOverFlow Error on spark-3.4 scala-2.13 is due to overwriting JVM ThreadStackSize with env MAVEN_OPTS to the default value -Xss1m from -Xss128m when building in the docker container by setting env `MAVEN_OPTS=-Xmx20g -XX:ReservedCodeCacheSize=2g`

Fixed by suffix MAVEN_OPTS with `-Xss128m`

**Comment by NvTimLiu** [comment]
Enabled internal CI to built Spark snapshot versions 3.3+  for both scala 2.12 and 2.13
