### ISSUE TITLE
[BUG] parquet_test.py::test_parquet_column_name_with_dots failing nightly build

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9629]
**Describe the bug**
`[2023-11-03T17:27:39.514Z] FAILED ../../src/main/python/parquet_test.py::test_parquet_column_name_with_dots[{'spark.rapids.sql.format.parquet.reader.type': 'COALESCING'}][INJECT_OOM, IGNORE_ORDER] - `

```
2023-11-03T17:27:39.514Z] : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 26613.0 failed 1 times, most recent failure: Lost task 0.0 in stage 26613.0 (TID 77942) (verify-rapids-nightly-dev-github-arm64-fd6n9-zsts8 executor driver): java.lang.NullPointerException

[2023-11-03T17:27:39.514Z] 	at sun.reflect.GeneratedMethodAccessor554.invoke(Unknown Source)

[2023-11-03T17:27:39.514Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2023-11-03T17:27:39.514Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2023-11-03T17:27:39.514Z] 	at org.apache.parquet.hadoop.util.ContextUtil.getConfiguration(ContextUtil.java:269)

[2023-11-03T17:27:39.514Z] 	at org.apache.parquet.hadoop.util.counters.mapreduce.MapReduceCounterLoader.getCounterByNameAndFlag(MapReduceCounterLoader.java:41)

[2023-11-03T17:27:39.514Z] 	at org.apache.parquet.hadoop.util.counters.BenchmarkCounter.getCounterWhenFlagIsSet(BenchmarkCounter.java:72)

[2023-11-03T17:27:39.514Z] 	at org.apache.parquet.hadoop.util.counters.BenchmarkCounter.loadCounters(BenchmarkCounter.java:66)

[2023-11-03T17:27:39.514Z] 	at org.apache.parquet.hadoop.util.counters.BenchmarkCounter.initCounterFromContext(BenchmarkCounter.java:51)

[2023-11-03T17:27:39.514Z] 	at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:133)

[2023-11-03T17:27:39.514Z] 	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.$anonfun$buildReaderWithPartitionValues$2(ParquetFileFormat.scala:355)

[2023-11-03T17:27:39.514Z] 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:116)

[2023-11-03T17:27:39.514Z] 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:169)

[2023-11-03T17:27:39.514Z] 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:93)

[2023-11-03T17:27:39.515Z] 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)

[2023-11-03T17:27:39.515Z] 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)

[2023-11-03T17:27:39.515Z] 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.util.random.SamplingUtils$.reservoirSampleAndCount(SamplingUtils.scala:41)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.RangePartitioner$.$anonfun$sketch$1(Partitioner.scala:306)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.RangePartitioner$.$anonfun$sketch$1$adapted(Partitioner.scala:304)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:915)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:915)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)

[2023-11-03T17:27:39.515Z] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)

```

**Comment by jlowe** [comment]
We can see from the Python stacktrace that this occurred within a CPU session, so there should be no RAPIDS Accelerator code involved here.  The stacktrace also shows no RAPIDS Accelerator classes in the call chain. On the surface, this looks like something unrelated to the RAPIDS Accelerator.

<details>
<summary>Python stacktrace for reference</summary>

```
[2023-11-03T17:27:39.511Z] ../../src/main/python/parquet_test.py:1528: 
[2023-11-03T17:27:39.511Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2023-11-03T17:27:39.511Z] ../../src/main/python/asserts.py:581: in assert_gpu_and_cpu_are_equal_collect
[2023-11-03T17:27:39.511Z]     _assert_gpu_and_cpu_are_equal(func, 'COLLECT', conf=conf, is_cpu_first=is_cpu_first, result_canonicalize_func_before_compare=result_canonicalize_func_before_compare)
[2023-11-03T17:27:39.511Z] ../../src/main/python/asserts.py:486: in _assert_gpu_and_cpu_are_equal
[2023-11-03T17:27:39.511Z]     from_cpu = run_on_cpu()
[2023-11-03T17:27:39.511Z] ../../src/main/python/asserts.py:471: in run_on_cpu
[2023-11-03T17:27:39.511Z]     from_cpu = with_cpu_session(bring_back, conf=conf)
[2023-11-03T17:27:39.511Z] ../../src/main/python/spark_session.py:116: in with_cpu_session
[2023-11-03T17:27:39.511Z]     return with_spark_session(func, conf=copy)
[2023-11-03T17:27:39.511Z] ../../src/main/python/spark_session.py:100: in with_spark_session
[2023-11-03T17:27:39.511Z]     ret = func(_spark)
[2023-11-03T17:27:39.511Z] ../../src/main/python/asserts.py:205: in <lambda>
[2023-11-03T17:27:39.511Z]     bring_back = lambda spark: limit_func(spark).collect()
[2023-11-03T17:27:39.511Z] /spark-3.1.1-bin-hadoop3.2/python/pyspark/sql/dataframe.py:677: in collect
[2023-11-03T17:27:39.511Z]     sock_info = self._jdf.collectToPython()
[2023-11-03T17:27:39.511Z] /spark-3.1.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py:1304: in __call__
[2023-11-03T17:27:39.511Z]     return_value = get_return_value(
[2023-11-03T17:27:39.511Z] /spark-3.1.1-bin-hadoop3.2/python/pyspark/sql/utils.py:111: in deco
[2023-11-03T17:27:39.511Z]     return f(*a, **kw)
```
</details>

**Comment by pxLi** [comment]
this failed in arm64 build, but passed in following 2 runs. lets keep monitoring
