### ISSUE TITLE
[BUG] 3.1.0 tests failing with errors where shuffle gets a CompressedBatch

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#967]
Something has changed in 3.1.0 and tests are now failing with errors like

```
- NOT ON GPU[FileSourceScanExec,FilterExec,CollectLimitExec,GreaterThan,Length,StringTrim,LocalTableScanExec,DeserializeToObjectExec,Invoke,AttributeReference,Literal]: Test CSV inferred schema *** FAILED ***
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 454.0 failed 1 times, most recent failure: Lost task 0.0 in stage 454.0 (TID 749) (192.168.50.62 executor driver): scala.MatchError: com.nvidia.spark.rapids.GpuCompressedColumnVector@2feeb4f0 (of class com.nvidia.spark.rapids.GpuCompressedColumnVector)
	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.$anonfun$writeValue$2(GpuColumnarBatchSerializer.scala:68)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.writeValue(GpuColumnarBatchSerializer.scala:67)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:249)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:158)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:484)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1426)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:487)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2211)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2160)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2159)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2159)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1076)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1076)
  at scala.Option.foreach(Option.scala:274)
  ...
  Cause: scala.MatchError: com.nvidia.spark.rapids.GpuCompressedColumnVector@2feeb4f0 (of class com.nvidia.spark.rapids.GpuCompressedColumnVector)
  at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.$anonfun$writeValue$2(GpuColumnarBatchSerializer.scala:68)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
  at com.nvidia.spark.rapids.GpuColumnarBatchSerializerInstance$$anon$1.writeValue(GpuColumnarBatchSerializer.scala:67)
  at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:249)
  at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:158)
  at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
  at org.apache.spark.scheduler.Task.run(Task.scala:131)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:484)

```

**Comment by revans2** [comment]
Looks like @jlowe is working on something related to this.  I'll let him take a first crack at this.
