### ISSUE TITLE
[BUG] Complex AST expressions can crash with non-matching operand type error

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9733]
Related to rapidsai/cudf#14409.  Some expressions can cause the AST to produce a non-matching operand type failure, e.g.:
```
scala> spark.conf.set("spark.rapids.sql.projectAstEnabled", "true")
scala> spark.range(10).withColumn("x", col("id")).repartition(1).selectExpr("(id < x) == (id < (id + x))").collect
23/11/15 21:30:31 ERROR Executor: Exception in task 0.0 in stage 5.0 (TID 3)
ai.rapids.cudf.CudfException: CUDF failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-pre_release-203-cuda11/thirdparty/cudf/cpp/src/ast/expression_parser.cpp:149: An AST expression was provided non-matching operand types.
	at ai.rapids.cudf.ast.CompiledExpression.computeColumn(Native Method)
	at ai.rapids.cudf.ast.CompiledExpression.computeColumn(CompiledExpression.java:88)
	at com.nvidia.spark.rapids.GpuProjectAstExec$$anon$1.$anonfun$next$15(basicPhysicalOperators.scala:452)
[...]
```

We may need to consider analyzing the Spark expression tree and falling back to the CPU for cases that will trigger the bug reported in rapidsai/cudf#14409 until that is fixed.

**Comment by sameerz** [comment]
Jason will add a test to see whether the cudf change fixed this.
