### ISSUE TITLE
[BUG] Java OOM when testing non-UTC time zone with lots of cases fallback.

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#9829]
**Describe the bug**

Premerge reports OOM when running CI.
Refer to:  https://github.com/NVIDIA/spark-rapids/pull/9773

Errors are:
```
[2023-11-21T12:23:14.166Z] ----------------------------- Captured stderr call -----------------------------
[2023-11-21T12:23:14.166Z] 2023-11-21 15:50:18 INFO     Error while receiving.
[2023-11-21T12:23:14.166Z] Traceback (most recent call last):
[2023-11-21T12:23:14.166Z]   File "/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-8481-ci-2/.download/spark-3.1.1-bin-hadoop3.2/python/pyspark/sql/utils.py", line 111, in deco
[2023-11-21T12:23:14.166Z]     return f(*a, **kw)
[2023-11-21T12:23:14.166Z]   File "/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-8481-ci-2/.download/spark-3.1.1-bin-hadoop3.2/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
[2023-11-21T12:23:14.166Z]     raise Py4JJavaError(
[2023-11-21T12:23:14.166Z] py4j.protocol.Py4JJavaError: An error occurred while calling o650151.collectToPython.
[2023-11-21T12:23:14.166Z] : java.lang.OutOfMemoryError: Java heap space
[2023-11-21T12:23:14.166Z] 

```

**Steps/Code to reproduce bug**
Based on this PR https://github.com/NVIDIA/spark-rapids/pull/9773.

```
export TEST_PARALLEL=1
export TZ=Iran
./integration_tests/run_pyspark_from_build.sh -s
```

**Additional context**
Locally I set TEST_PARALLEL to 1 on Spark 341, it also fails.  

Changes in https://github.com/NVIDIA/spark-rapids/pull/9652
- user.timezone=$TZ
- PYSP_TEST_spark_sql_session_timeZone=$TZ

Changes in [#9773](https://github.com/NVIDIA/spark-rapids/pull/9773):  
- Set TZ=non-UTC

**Comment by winningsix** [comment]
There're more contexts here. One point may be related is the way we run those test cases. When we set to non-UTC case, most cases will be fallback onto CPU. It may lead to higher memory demand for Java heap. If that's the case, it's more likely a test setting problem other than Rapids plugin's bug.

**Comment by res-life** [comment]
More error, GPU OutOfMemory even when the GPU memory is 40G.

PYSP_TEST_spark_rapids_memory_gpu_allocSize=40000m

```
2454832 23/11/23 12:17:01 ERROR Executor: Exception in task 0.0 in stage 71540.0 (TID 265099)
2454833 com.nvidia.spark.rapids.jni.SplitAndRetryOOM: GPU OutOfMemory: could not split input target batch size to less than 10 MiB
2454834   at com.nvidia.spark.rapids.GpuParquetScan$.splitTargetBatchSize(GpuParquetScan.scala:266)
2454835   at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.chunkedSplit(GpuParquetScan.scala:1968)
2454836   at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$4(GpuMultiFileReader.scala:1068)
2454837   at com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.split(RmmRapidsRetryIterator.scala:442)
2454838   at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:557)
2454839   at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:495)
2454840   at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
2454841   at scala.collection.TraversableOnce$FlattenOps$$anon$2.hasNext(TraversableOnce.scala:469)
2454842   at com.nvidia.spark.rapids.GpuColumnarBatchWithPartitionValuesIterator.hasNext(GpuColumnarBatchIterator.scala:114)
2454843   at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
2454844   at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.next(GpuMultiFileReader.scala:1025)
2454845   at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
2454846   at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
2454847   at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
2454848   at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:474)
2454849   at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$3(GpuColumnarToRowExec.scala:285)
2454850   at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
2454851   at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:284)
2454852   at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:257)
2454853   at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:301)
2454854   at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
2454855   at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
2454856   at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
2454857   at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
2454858   at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
2454859   at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
2454860   at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
2454861   at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
```

**Comment by res-life** [comment]
About the Gpu OOM, I checked the passed CIs for UTC time zone, it also reports OOM:
```
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 1] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 2] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: Device store exhausted, unable to allocate 2147483712 bytes. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 1] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 2] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: Device store exhausted, unable to allocate 2147483712 bytes. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 1] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 2] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: Device store exhausted, unable to allocate 2147483712 bytes. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 1] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: [RETRY 2] Retrying allocation of 2147483712 after a synchronize. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 WARN DeviceMemoryEventHandler: Device store exhausted, unable to allocate 2147483712 bytes. Total RMM allocated is 137038848 bytes.
[2023-11-24T02:28:23.045Z] 23/11/24 02:28:22 ERROR Executor: Exception in task 0.0 in stage 22016.0 (TID 65075)
[2023-11-24T02:28:23.045Z] com.nvidia.spark.rapids.jni.SplitAndRetryOOM: GPU OutOfMemory: could not split input target batch size to less than 10 MiB
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.GpuParquetScan$.splitTargetBatchSize(GpuParquetScan.scala:266)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.MultiFileParquetPartitionReader.chunkedSplit(GpuParquetScan.scala:1968)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.$anonfun$readBatch$4(GpuMultiFileReader.scala:1068)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.split(RmmRapidsRetryIterator.scala:442)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:557)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:495)
[2023-11-24T02:28:23.045Z] 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
[2023-11-24T02:28:23.045Z] 	at scala.collection.TraversableOnce$FlattenOps$$anon$2.hasNext(TraversableOnce.scala:469)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.GpuColumnarBatchWithPartitionValuesIterator.hasNext(GpuColumnarBatchIterator.scala:114)
[2023-11-24T02:28:23.045Z] 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.MultiFileCoalescingPartitionReaderBase.next(GpuMultiFileReader.scala:1025)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.PartitionIterator.hasNext(dataSourceUtil.scala:29)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.MetricsBatchIterator.hasNext(dataSourceUtil.scala:46)
[2023-11-24T02:28:23.045Z] 	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2023-11-24T02:28:23.045Z] 	at org.apache.spark.sql.rapids.GpuFileSourceScanExec$$anon$1.hasNext(GpuFileSourceScanExec.scala:474)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$3(GpuColumnarToRowExec.scala:285)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:284)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:257)
[2023-11-24T02:28:23.045Z] 	at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:301)
[2023-11-24T02:28:23.045Z] 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
[2023-11-24T02:28:23.045Z] 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2023-11-24T02:28:23.046Z] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2023-11-24T02:28:23.046Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-11-24T02:28:23.046Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-11-24T02:28:23.046Z] 	at java.lang.Thread.run(Thread.java:750)

```
Refer to CI 8525, 8527, select Blue Ocean, select Premerge CI 2.

@revans2  Is this a issue?

**Comment by winningsix** [comment]
From the log, Parquet is trying to split its batch to a "< 10MB" batch. It's reasonable for ```GpuParquetScan``` to reject further split on a small batch. Most likely this is an issue for other parts. It seems there're other outstanding allocations consuming the memory here even we configured it at a higher size.

Is there any err msg about memory leak like below?
```
DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED
```

**Comment by winningsix** [comment]
Per offline discussion, a few further information:
In local environment (using 1 process(es) TEST_PARALLEL = 1), each process CPU core = 16, Mem = 32 GB, Gpu Mem = 50 GB
CI (with 5 process(es)  TEST_PARALLEL = 5), each process CPU core = TBA, Mem = 2 GB, Gpu Mem = 1.2 GB
- CI passed in local environment using configuration above while failed in CI.

A few follow-ups as below needed to further narrow down the issue:
- Understand the needed peak GPU memory for non-UTC test environment. A suspected difference against UTC case is we will have much more fallbacks there with more c2r operators.
- Update CI with updated configurations to pass our new pipeline.

cc @pxLi

**Comment by res-life** [comment]
Tested after this [commit](https://github.com/NVIDIA/spark-rapids/pull/9719), then the OOM will disappear.
Because this commit will convert lots of fallback to regular passed case.
We can close this after this commit merged.

**Comment by res-life** [comment]
Separated this to 2 other issues:
- https://github.com/NVIDIA/spark-rapids/issues/9914
- https://github.com/NVIDIA/spark-rapids/issues/9915

**Comment by wjxiz1992** [comment]
Updates:

1. I can stably reproduce the OOM at one single test case `test_explode_array_data[Array(Array(String))][DATAGEN_SEED=1701258438, INJECT_OOM, IGNORE_ORDER({'local': True})] `
2. Firstly I did heapdump at two places, one is `when the OOM occurs`, the other is `right before the OOM test case started`. Both of them are using large memory.

When OOM:
![image](https://github.com/NVIDIA/spark-rapids/assets/20476954/f576330d-08b2-4e75-9f53-7dc4348a3933)
Right before OOM test case:
![image](https://github.com/NVIDIA/spark-rapids/assets/20476954/a573175b-4a85-4223-b84a-5d946996cb64)

3. By checking the large size objects, we found top comsumers are 
![image](https://github.com/NVIDIA/spark-rapids/assets/20476954/47800b48-00e5-408a-b8a6-189e86fe48e3)
the `...execution.joins....` are not related to the `test_explode_array_data` test case, but still there, which leads the suspections for memory leak. 
4. By checking the incoming reference of the largest `MutableURLClassLoader`, we found `ExecutionPlanCaptureCallBack` seems to have so many self reference
![image](https://github.com/NVIDIA/spark-rapids/assets/20476954/fc950b43-33c6-44d2-abb7-c97ed5e722ca)
5. I comment out all `jvm.org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback.assert...` in `asserts.py`, then no OOM, and the heap dump at the test case is like below6. 
![image](https://github.com/NVIDIA/spark-rapids/assets/20476954/13f3d7ad-f063-48ff-973b-1afbf6604af7)

No MutableURLClassLoad and other large size in the heap this time:
![image](https://github.com/NVIDIA/spark-rapids/assets/20476954/1816a623-2a79-49b7-bcfe-b33ccf02568a)

**Comment by revans2** [comment]
It sounds like ExecutionPlanCaptureCallback has a memory leak in it.

**Comment by jlowe** [comment]
@wjxiz1992 I'm not sure how ExecutionPlanCaptureCallback is tied into the problem if we are just running test_explode_array_data.  That test does not perform plan capturing, nor does it call the methods in asserts.py that leverage ExecutionPlanCaptureCallback (it's just calling assert_gpu_and_cpu_are_equal_collect, not one of the assert forms with plan capture).  Therefore ExecutionPlanCaptureCallback's methods should not be getting called with the exception of `captureIfNeeded` since it is an installed Spark plan listener, but `shouldCapture` should always be false since nothing should be asking to capture plans.

Indeed I ran test_explode_array_data with a debugger attached to the JVM and breakpoints set on every ExecutionPlanCaptureCallback method, but only `captureIfNeeded` is getting called in practice and `shouldCapture` is always false, therefore it's not capturing any plans.  I'm not sure how this is supposed to be contributing a ton of space to the heap, nor do I see how commenting out the ExecutionPlanCaptureCallback.assert... code in asserts.py would affect how test_explode_array_data executes.  Any insight here?

**Comment by winningsix** [comment]
I am still investigating on it with no further conclusion yet. But It's leaked in ```execPlans``` from ```ShimmedExecutionPlanCaptureCallbackImpl``` (see below).  And OOM is fixed after I clear ```execPlans``` within ```assertContains``` method. I am still very confusing because ```shouldCaptured``` works in pair ```getResultsWithTimeout``` and ```startCapture```. It seems correct in ```asserts.py``` file.
 

![image](https://github.com/NVIDIA/spark-rapids/assets/2278268/f31e6343-588d-4042-9bdf-cf1a7c8ec0db)

**Comment by jlowe** [comment]
Yes, I totally agree that the OOM is due to leaked plans in ExecutionPlanCaptureCallback.  What's likely is that there's a test that needs a plan capture, it calls `startCapture` which triggers the plan listener to capture _everything_ until told otherwise, and then that test throws an exception and the listener is never told to stop capturing.  It then proceeds to capture for subsequent tests that don't actually interact with the listener capturing, but the previous test that threw an exception and didn't cleanup properly left the listener in a bad state.

That all makes sense, but what I don't get is how to reproduce it _solely_ with test_explode_array_data.  That test doesn't trigger capturing in any way that I can see (and debugger breakpoints prove it, at least for my environment).  In order for EsecutionPlanCaptureCallback to start leaking plans, it needs to start capturing first, and I don't see how test_explode_array_data will do that on its own.

**Comment by winningsix** [comment]
> Yes, I totally agree that the OOM is due to leaked plans in ExecutionPlanCaptureCallback. What's likely is that there's a test that needs a plan capture, it calls `startCapture` which triggers the plan listener to capture _everything_ until told otherwise, and then that test throws an exception and the listener is never told to stop capturing. It then proceeds to capture for subsequent tests that don't actually interact with the listener capturing, but the previous test that threw an exception and didn't cleanup properly left the listener in a bad state.
> 
> That all makes sense, but what I don't get is how to reproduce it _solely_ with test_explode_array_data. That test doesn't trigger capturing in any way that I can see (and debugger breakpoints prove it, at least for my environment). In order for EsecutionPlanCaptureCallback to start leaking plans, it needs to start capturing first, and I don't see how test_explode_array_data will do that on its own.

Yes, your guess is correct. The ```shouldCapture``` failed to be reset after an exception thrown in ```test_csv_save_as_table_fallback```.

```
Encountered an exception applying GPU overrides java.lang.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.CoalesceExec
Coalesce 1
```

**Comment by wjxiz1992** [comment]
> but what I don't get is how to reproduce it solely with test_explode_array_data

Sorry, I missed some important things. 

I also did test, that I only this `test_explode_array_data` and dump, no any  memory object leading to `ExecutionPlanCaptureCallback`.

I don't think it's related to `test_explode_array_data`. it is just at that place where its previous tests have already leak a lot and when it is his order to perform the run, his little extra memory requests break the whole JVM.
