### ISSUE TITLE
[BUG] missing metric `dataSize`

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#985]
Just noticed this one after a rebase. I think there were some recent changes to shuffle metrics that may affect this, will spend time on this today.
```
 java.util.NoSuchElementException: key not found: dataSize
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:101)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:99)
	at org.apache.spark.sql.rapids.RapidsCachingWriter.<init>(RapidsShuffleInternalManager.scala:88)
	at org.apache.spark.sql.rapids.RapidsShuffleInternalManagerBase.getWriter(RapidsShuffleInternalManager.scala:301)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jlowe** [comment]
I verified that it is fixed by reverting #973.

**Comment by revans2** [comment]
I see these types of issue every time I run the integration tests.  I think that there is an underlying issue that we need to look into.

**Comment by revans2** [comment]
This was before any of the changes mentioned here.

**Comment by jlowe** [comment]
I've got a fix, will post PR soon.
