### ISSUE TITLE
[BUG] pinned blocking alloc with spill test timeout

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9924]
```
[2023-11-30T23:08:18.310Z] - pinned blocking alloc with spill *** FAILED ***
[2023-11-30T23:08:18.310Z]   java.util.concurrent.TimeoutException:
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.HostAllocSuite$TaskThread$TaskThreadTrackingOp.get(HostAllocSuite.scala:107)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.HostAllocSuite$AllocOnAnotherThread.waitForAlloc(HostAllocSuite.scala:218)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$41(HostAllocSuite.scala:628)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$41$adapted(HostAllocSuite.scala:626)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$40(HostAllocSuite.scala:626)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$40$adapted(HostAllocSuite.scala:618)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
[2023-11-30T23:08:18.310Z]   at com.nvidia.spark.rapids.HostAllocSuite.$anonfun$new$39(HostAllocSuite.scala:618)
[2023-11-30T23:08:18.310Z]   at org.scalatest.enablers.Timed$$anon$1.timeoutAfter(Timed.scala:127)
[2023-11-30T23:08:18.310Z]   ...
[2023-11-30T23:08:19.674Z] *** RUN ABORTED ***
[2023-11-30T23:08:19.674Z]   java.lang.AssertionError: Leaked 1 pinned allocations
[2023-11-30T23:08:19.674Z]   at ai.rapids.cudf.PinnedMemoryPool.close(PinnedMemoryPool.java:317)
[2023-11-30T23:08:19.674Z]   at ai.rapids.cudf.PinnedMemoryPool.shutdown(PinnedMemoryPool.java:217)
[2023-11-30T23:08:19.674Z]   at com.nvidia.spark.rapids.HostAllocSuite.beforeEach(HostAllocSuite.scala:382)
[2023-11-30T23:08:19.674Z]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:233)
[2023-11-30T23:08:19.674Z]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
[2023-11-30T23:08:19.674Z]   at com.nvidia.spark.rapids.HostAllocSuite.runTest(HostAllocSuite.scala:34)
[2023-11-30T23:08:19.674Z]   at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:269)
[2023-11-30T23:08:19.674Z]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[2023-11-30T23:08:19.674Z]   at scala.collection.immutable.List.foreach(List.scala:431)
[2023-11-30T23:08:19.674Z]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[2023-11-30T23:08:19.675Z]   ...
```

**Comment by abellina** [comment]
I think you filed this already https://github.com/NVIDIA/spark-rapids/issues/9671
