### ISSUE TITLE
[BUG] Metrics Error shows up in some TPCH queries

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#993]
**Describe the bug**
When running our integration tests I will sometimes see exception stack traces like.

```
java.util.NoSuchElementException: key not found: 1136
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:63)
	at org.apache.spark.sql.execution.ui.SQLAppStatusListener.$anonfun$aggregateMetrics$11(SQLAppStatusListener.scala:257)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.execution.ui.SQLAppStatusListener.aggregateMetrics(SQLAppStatusListener.scala:256)
	at org.apache.spark.sql.execution.ui.SQLAppStatusListener.$anonfun$onExecutionEnd$2(SQLAppStatusListener.scala:365)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.tryLog(Utils.scala:1945)
	at org.apache.spark.status.ElementTrackingStore$$anon$1.run(ElementTrackingStore.scala:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

They do not fail the test, but indicate that something bad is happening.

**Steps/Code to reproduce bug**
```
$ mvn clean install -DskipTests
$ cd integration_tests
$ ./run_pyspark_from_build.sh -k test_tpch_q22
```

I see the issue with `test_tpch_q22` (both configs), `test_tpch_q11[conf1]`.  I do not see it for q11 conf0 though.

**Expected behavior**
No exception that might scare a user.

**Comment by sameerz** [comment]
Marking as P1 because it requires investigation.  If this turns out to be benign we will lower the priority.

**Comment by revans2** [comment]
So this looks like it is a bug in spark and not a bug in our code.  For `test_tpch_q11[conf1]` I added in some logging in spark and the metric that is causing the issue is the `number of output rows` metric in a Filter that is a part of the CPU run.

For `test_tpch_q22[conf1]` I see two exceptions one is for `number of output rows` for a `HashAggregateExec` and the other is `avg hash probe bucket list iters` for another `HashAggregateExec`.


`test_tpch_q22[conf0]` is not actually showing any issues.  It looks like conf1 is with AQE enabled.

After reading the code where the error is happening it looks like there is a mismatch between two different places that metrics show up. So my guess is that there is something happening with AQE in 3.0 where there is a race condition between metrics showing up as registered in one place and the metrics actually being used in another place.  Either way it is not a P1 for us.  We should test it again with spark 3.1 and see if the issue is still there, and if it is we should file something in spark.

**Comment by revans2** [comment]
I marked this as a P2 so we still take the time to try and file something in spark itself.
